### ISSUE TITLE
Hi Guys， RT1050+env添加cjson+sqlite3， IAR8.11.1 编译出错

### ISSUE THREAD

**Issue by DomainPon** [RT-Thread/rt-thread#1031]
Changed settings forces a full rebuild... 
Building configuration: project - Debug 
Updating build tree... 
 
3  file(s) deleted. 
Updating build tree... 
context_iar.S 
startup_MIMXRT1052.s 
api_lib.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
autoip.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
api_msg.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
backtrace.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
block_dev.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
board.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
cJSON_port.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
cJSON_util.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
clock.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
clock_time.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
cJSON.c  
cmd.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
completion.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
components.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
cpuport.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
dataqueue.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
def.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
devfs.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
device.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
device_test.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
dfs_elm.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
dfs.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
dfs_file.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
dfs_fs.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
dfs_posix.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
dhcp.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
div0.c  
dns.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
drv_eth.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
drv_sdio.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
environ.c  
err.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
ethernetif.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
ff.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
etharp.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
finsh_compiler.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
finsh_error.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
finsh_heap.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
finsh_init.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
finsh_node.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
finsh_ops.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
finsh_parser.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
finsh_var.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
finsh_token.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
finsh_vm.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
fsl_adc.c  
fsl_aipstz.c  
fsl_adc_etc.c  
fsl_aoi.c  
fsl_bee.c  
fsl_cache.c  
fsl_cmp.c  
fsl_clock.c  
fsl_common.c  
fsl_csi.c  
fsl_dcdc.c  
fsl_dcp.c  
fsl_dmamux.c  
fsl_elcdif.c  
fsl_enc.c  
fsl_edma.c  
fsl_enet.c  
fsl_ewm.c  
fsl_flexio.c  
fsl_flexcan.c  
fsl_flexio_i2c_master.c  
fsl_flexio_i2s.c  
fsl_flexio_i2s_edma.c  
fsl_flexio_spi.c  
fsl_flexio_spi_edma.c  
fsl_flexio_uart.c  
fsl_flexio_uart_edma.c  
fsl_flexram.c  
fsl_gpc.c  
fsl_flexspi.c  
fsl_gpio.c  
fsl_gpt.c  
fsl_kpp.c  
fsl_lpi2c_edma.c  
fsl_lpi2c.c  
fsl_lpspi.c  
fsl_lpspi_edma.c  
fsl_lpuart_edma.c  
fsl_lpuart.c  
fsl_phy.c  
fsl_pit.c  
fsl_pmu.c  
fsl_pwm.c  
fsl_pxp.c  
fsl_qtmr.c  
fsl_rtwdog.c  
fsl_sai.c  
fsl_sai_edma.c  
fsl_snvs_hp.c  
fsl_semc.c  
fsl_snvs_lp.c  
fsl_spdif.c  
fsl_src.c  
fsl_spdif_edma.c  
fsl_trng.c  
fsl_tsc.c  
fsl_wdog.c  
fsl_xbara.c  
icmp.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
fsl_usdhc.c  
idle.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
fsl_xbarb.c  
igmp.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
inet.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
inet_chksum.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
init.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
ip.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
ip_addr.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
ip_frag.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
ipc.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
irq.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
kservice.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
libc.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
main.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
mem.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
mem_test.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
memp.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
mmc.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
mmcsd_core.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
mqueue.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
msh.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
msh_cmd.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
msh_file.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
netbuf.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
netdb.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
netifapi.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
netif.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
object.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
pbuf.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
pipe.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
poll.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
pthread.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
pthread_attr.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
pthread_barrier.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
pthread_mutex.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
pthread_cond.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
pthread_rwlock.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
pthread_spin.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
pthread_tls.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
raw.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
ringbuffer.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
sched.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
rmtx.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
scheduler.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
sd.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
sdio.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
sdio_test.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
select.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
semaphore.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
serial.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
shell.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
showmem.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
signal.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
slipif.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
stats.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
stdio.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
sqlite3.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
sockets.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
symbol.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
sys.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
sys_arch.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
syscall_close.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
syscall_lseek.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
syscall_mem.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
syscall_open.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
syscall_read.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
syscall_remove.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
syscall_write.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
tcp.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
tcp_in.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
tcp_out.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
system_MIMXRT1052.c  
tcpip.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
thread.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
timer.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
timers.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
usart.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
udp.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
waitqueue.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
workqueue.c  
Fatal Error[Pe035]: #error directive: "POSIX poll/select, stdin need file BSD socket API(RT_USING_DFS_NET)" D:\rt-thread-master\include\rtdebug.h 33 
Error while running C/C++ Compiler 
 
Total number of errors: 121 
Total number of warnings: 2

**Comment by uestczyh222** [comment]
蛤？

**Comment by liu2guang** [comment]
:-D

**Comment by DomainPon** [comment]
![image]("C:\Users\Domain\Pictures\RT1050 BSP +CJSON+ SQLITE3 IAR 8.11.1.png")

**Comment by DomainPon** [comment]
["C:\Users\Domain\Pictures\RT1050 BSP +CJSON+ SQLITE3 IAR 8.11.1.png"](url)

**Comment by TanekLiang** [comment]
需要开(RT_USING_DFS_NET)
