### ISSUE TITLE
rt-thread 对Python3的支持

### ISSUE THREAD

**Issue by linhuikui** [RT-Thread/rt-thread#1033]
目前scons已经支持Python3了，是否考虑把rt-thread中的编译文件修改为支持Python3呢？

**Comment by BernardXiong** [comment]
scons 3.0好像已经支持Python 3.x了，这个后面验证下，如果可以就可以考虑迁移了

**Comment by itfanr** [comment]
www.xmake.io   建议用这个编译器吧  跨平台，无依赖

**Comment by ArdaFu** [comment]
@BernardXiong  RTT自己的某些脚本在 py2.7 和 py3.5+不兼容
