### ISSUE TITLE
USB问题

### ISSUE THREAD

**Issue by HubertXie** [RT-Thread/rt-thread#1041]
STM32F103
使用USB驱动框架，想将板载SpiFlash挂载为U盘。
电脑能识别到U盘，但是无法读写U盘内的文件

**Comment by uestczyh222** [comment]
是这样的，msc的class有问题。这个是已知问题正在处理中 不是103的问题也不是USB框架问题。

**Comment by HubertXie** [comment]
好的，那我还是继续用ST的USB库吧。
本来想切到rtt自带的USB库来。
希望早日完善这部分，ST的库只能当设备，不是很方便。

**Comment by HubertXie** [comment]
今天发现USB MSC可以用了，特来点赞！
