### ISSUE TITLE
rt-thread支持6lowpan吗？

### ISSUE THREAD

**Issue by xiaolongba** [RT-Thread/rt-thread#1058]
我看rtt里的组件中有支持lwip，其是支持IPv6的，不知道是否后续有支持6lowpan的计划吗？

**Comment by BernardXiong** [comment]
armink大神好像正在推进中

**Comment by xiaolongba** [comment]
@BernardXiong 牛批，期待+等待+急待！

**Comment by armink** [comment]
@xiaolongba 最近就在 ART-6LoWPAN 项目，到时候还会有配套的开发板，基于 RT-Thread 3.0，还支持 MicroPython ，目前测试阶段马上结束了。

**Comment by xiaolongba** [comment]
@armink 大神能透漏配置的开发板是啥不？因为不太想被绑在一棵树上（就是说不希望基于RTT3.0的6lowpan只能用于配套的开发板而不能用在非醒套的开发板上），希望只要一用RT-Thread 3.0，以后就一直用下去（不管是我换了RTT支持的哪个芯片或者内核，我都能用RTT及其支持的组件）

**Comment by armink** [comment]
先来一张靓照看一下，最终的外观会是红色。

![art-6lowpan](https://user-images.githubusercontent.com/1734686/33417544-eae79420-d5dc-11e7-837b-b39ac14aac84.jpg)

- 主控：STM32F405RG
- RFIC：SI4463

先透露这些。放心，6LoWPAN 不会仅限制于当前的开发板的。

**Comment by xiaolongba** [comment]
@armink 666,买买买，到时上市了通知一下呗，如果能出个基于BLE的就更合我意了。

**Comment by policeman0077** [comment]
现在支持lowpan了吗？
