### ISSUE TITLE
用scons 生成的keil5工程，部分include path不完整

### ISSUE THREAD

**Issue by z14git** [RT-Thread/rt-thread#1068]
如图：
![jtda33_zrz0odd kgxu8 a](https://user-images.githubusercontent.com/31793423/33512775-a734f11a-d770-11e7-8d68-ea3a1e66bf39.png)
有几条路径重复了，其中两条应该是 ..\rt-thread\components\drivers\include\drivers 和 ..\rt-thread\components\drivers\include\ipc

**Comment by BernardXiong** [comment]
"其中两条" 是指这两天漏掉了吗？你上面说的这两条应该不需要，也不应该加入到搜索路径的。

重复的问题，需要修下tools下的脚本了。

**Comment by z14git** [comment]
如果不加 ..\rt-thread\components\drivers\include\ipc的话，当我需要用到ringbuffer.h的时候，keil就会提示找不到ringbuffer.h

**Comment by BernardXiong** [comment]
这个不是这么用的，需要包含
rtdevice.h
这个头文件。
