### ISSUE TITLE
dfs中rt_malloc分配，但未用rt_free释放

### ISSUE THREAD

**Issue by zhanggy** [RT-Thread/rt-thread#1097]
函数fd_is_open中，在调用dfs_normalize_path失败后，释放fullpath时应使用rt_free，而不是直接用free

**Comment by BernardXiong** [comment]
谢谢指出。你这边是使用了多种内存方式吗？如果统一使用RTT的，free和rt_free会统一起来，所以这样的bug在完全RTT的环境中还真有些难发现。
