### ISSUE TITLE
EVN0.63 Bug: 提示找不到Python.dll

### ISSUE THREAD

**Issue by sczh01** [RT-Thread/rt-thread#1132]
复现路径：
刚装的系统，没有安装过任何的工具
然后按照env的文档来运行 提示找不到Python27.dll

找到同版本的python27.dll放到 root\env\tools\Python27_32 或者python27下即可。
这样才是真的绿色开发环境 
还请更新到相同的python27.dll到下一版中

**Comment by armink** [comment]
你的系统是什么版本？我的电脑也没装 Python 可以点开直接用的。

**Comment by BernardXiong** [comment]
可能是不是这个python27.dll，不是在安装的Python目录中，而是在Windows系统目录中

**Comment by sczh01** [comment]
Armink and Bernard,

是的 如果是官网下载的 安装版 的话是考到 windows\system32或64里的

绿色版的话一般是放在python.exe同一个目录下或者DLL下

**Comment by BernardXiong** [comment]
原来果真是这样，谢谢提供这个信息。

**Comment by SummerGGift** [comment]
0.6.4版本的env已经更新了这个问题。
