### ISSUE TITLE
关于优化 rt_object_get_information

### ISSUE THREAD

**Issue by xfan1024** [RT-Thread/rt-thread#1142]
该函数被频繁使用，目前使用的逐个比较的方法搜索rt_object_container。
使用二分查找或利用switch语法(#1141)能提升该函数性能。

**Comment by BernardXiong** [comment]
这个仅仅几个项，不会慢的。使用switch模式和循环模式几乎差不多（如果不考虑index增加的部分指令）。

主要是数目小，所以这个时候没必要去考虑复杂的方法来进行。
