### ISSUE TITLE
qemu-vexpress-a9编译，仿真运行时gui界面空白

### ISSUE THREAD

**Issue by zg-diligence** [RT-Thread/rt-thread#1145]
ubuntu 16.04 + RT-Thread 3.0.0
交叉编译器 arm-none-eabi-gcc
编译命令　scons
运行命令　qemu-system-arm -M vexpress-a9 -kernel rtthread.elf -show-cursor -serial telnet:127.0.0.1:1200,server -serial file:virtualkbd

**Comment by BernardXiong** [comment]
可以按个：Ctrl+Alt+3/4等来切换VC。

另外，也可以在menuconfig中选择GUI engine以及GUI example试试
