### ISSUE TITLE
大概试编译了一下，打开Gagent选项，把PKG_PAHOMQTT_SUBSCRIBE_HANDLERS设成3还是提示错误

### ISSUE THREAD

**Issue by charliexp** [RT-Thread/rt-thread#1174]
![image](https://user-images.githubusercontent.com/12693198/35020668-23749440-fb68-11e7-920d-63de8424dbb7.png)

![image](https://user-images.githubusercontent.com/12693198/35020709-5e9c13ae-fb68-11e7-8516-faa18207a716.png)

**Comment by charliexp** [comment]
env问题还是比较多的

**Comment by BernardXiong** [comment]
@flyingcys GAgent代码有问题哦，瞅瞅

**Comment by BernardXiong** [comment]
十三好像已经更新package了，可以用latest的版本再试试。
