### ISSUE TITLE
有没有对Linux下的支持？

### ISSUE THREAD

**Issue by jiapei100** [RT-Thread/rt-thread#1181]
Hi，

尝试在Linux下做，但是看到
**scons --target=mdk/mdk4/mdk5/iar/cb -s** 
貌似只能target为Windows下的Keil uVision。

SW4STM32 Linux很好用，不知道这个rt-thread是不是可以support SW4STM32 Linux？
Cheers

**Comment by BernardXiong** [comment]
linux？直接scons编译就可以了
