### ISSUE TITLE
STM32f10x hal版本gcc编译问题

### ISSUE THREAD

**Issue by xeonxu** [RT-Thread/rt-thread#1187]
STM32f10x hal使用ide编译可以正常运行，但是使用scons用gcc编译时，虽然可以正常编译，但是无法运行。

**Comment by uestczyh222** [comment]
这个问题应该是由于开启了main模式 然后程序入口应该变成entry gcc对应.s的启动代码中的入口不对造成的。我有时间fix

**Comment by uestczyh222** [comment]
第一个问题貌似没有很好的解决方法。。因为一旦不使用main模式那么又不对了 第二个问题好像不会造成什么奇奇怪怪的问题。你看要不要pr上来

**Comment by uestczyh222** [comment]
可以的话把所有芯片的.s都修改一下。

**Comment by xeonxu** [comment]
@uestczyh222 __libc_init_array的问题在3.0.1某个版本存在，应该是kconfig依赖导致的 Enable libc APIs from toolchain开关打开后无法正确编译。3.0.2版本无此问题。

**Comment by xeonxu** [comment]
#1226 使用新方案解决
