### ISSUE TITLE
低功耗如何使用？

### ISSUE THREAD

**Issue by mmyer** [RT-Thread/rt-thread#1206]
RT-Thread支持低功耗模式了，请问要怎么使用?

**Comment by uestczyh222** [comment]
向芯片厂商索取

**Comment by mmyer** [comment]
请问EFM32的单片机已经支持了吗？

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/tree/master/components/drivers/pm
https://docs.rt-thread.org/#/rt-thread-version/rt-thread-standard/programming-manual/pm/pm
