### ISSUE TITLE
stm32f10x-HAL的__libc_init_array问题

### ISSUE THREAD

**Issue by xeonxu** [RT-Thread/rt-thread#1227]
目前，stm32f10x-HAL中如果不开启Enable libc APIs from toolchain开关，gcc编译出来的目标程序会造成CPU死机，无法正常进入系统。
查了一圈，好多人都有遇到调用该函数时导致CPU异常的问题。网上给出的解释是工具链中的库函数编译成了arm32目标码，而非我们需要的thumb目标码。但是给出的解决方案中，无非是在编译时添加架构声明，我查了我们的编译参数，该有的参数都已经添加。
考虑到stm32f10x工程中使用的汇编启动文件中，程序在初始化完成后，调用main之前并没有调用该函数的操作。因此考虑，可否将HAL工程启动文件中的该语句删除？自测下来没有什么问题。
不过对于该调用死机的问题，还是希望能搞明白。不知大佬们有什么意见？
具体参考：
https://stackoverflow.com/questions/26585656/hardfault-on-stm32f030-startup-libc-init-array
https://electronics.stackexchange.com/questions/344625/why-does-libc-init-array-cause-an-exception

**Comment by uestczyh222** [comment]
加Q群155786310，讨论一下
