### ISSUE TITLE
PVS-Studio

### ISSUE THREAD

**Issue by AndreyKarpov** [RT-Thread/rt-thread#1247]
Article "[Static Code Analyzer PVS-Studio 6.22 Now Supports ARM Compilers (Keil, IAR)](https://www.viva64.com/en/b/0561/)".
....
I glanced through the analysis report by PVS-Studio and picked 95 warnings that I thought to be the most interesting ones. Too see all those messages for yourself, download the [rt-thread-html-log.zip](http://cppfiles.com/rt-thread-html-log.zip) archive with the full HTML report.
....

**Comment by BernardXiong** [comment]
Thanks , I will check them carefully.
