### ISSUE TITLE
stm32f429-apollo在env默认配置生成keil工程后无法编译通过

### ISSUE THREAD

**Issue by skawu** [RT-Thread/rt-thread#1271]
报错内容：
..\..\components\net\lwip-2.0.2\src\include\lwip/sockets.h(430): error:  #35: #error directive: "external FD_SETSIZE too small for number of sockets"
解决办法是将the number of struct netconns由默认的8改为4，不知这样修改是否会对工程其它功能造成影响，因此未提交PR。

**Comment by TanekLiang** [comment]
能问一下，你的具体步骤吗？
我拉取最新的源码， 重新生成mdk4和mdk5工程，都是可以编译通过的。

**Comment by skawu** [comment]
下载源码，env工具进入，menuconfig一下，不做更改保存退出，然后用scons命令生成mdk5的工程，编译就报错了

**Comment by TanekLiang** [comment]
OK，问题复现了。我看看怎么修复。

**Comment by TanekLiang** [comment]
最新版本应该修复了这个问题了。

**Comment by skawu** [comment]
我今天试一下看看

**Comment by TanekLiang** [comment]
有结果了吗？ @skawu

**Comment by skawu** [comment]
验证过了，可以，不报错了，我又试了一遍截图把结果发出来了

**Comment by kelebujiabing** [comment]
stm32f40x 问题还在，能说下改了哪吗

**Comment by TanekLiang** [comment]
@kelebujiabing f40x是另外一个bsp，请提新的issue，并贴出错误信息。
