### ISSUE TITLE
IAR 8.22.1版本中宏_DLIB_THREAD_SUPPORT被移除

### ISSUE THREAD

**Issue by Y-JESSE** [RT-Thread/rt-thread#1295]
在IAR8.22.1版本的DLib_Defaults.h文件中_DLIB_THREAD_SUPPORT被移除，并且会抛出一个错误
```
#ifdef _DLIB_THREAD_SUPPORT
  #error "Option has been removed"
#endif
```
在RT-Thread工程路径下rt-thread-master\components\libc\compilers\dlib，SConscript脚本如果检测到RT_USING_DFS宏被打开，会在IAR环境中添加宏_DLIB_THREAD_SUPPORT，最终导致编译出错

**Comment by TanekLiang** [comment]
是的。IAR升级之后，这个宏被废弃了。但是旧的IAR还是依赖这个宏。
临时的解决版本是，每次生成工程后，在新版IAR里手动在选项里移除相关的宏。

后续会考虑如何合适的支持不同IAR版本。

**Comment by BernardXiong** [comment]
看来有必要在scons中去检测各种已知编译器版本啊

**Comment by TanekLiang** [comment]
这个问题在之前的pr已经修复了。
需要在rtconfig.py里面正确指定IAR路径，就可以在生成工程的时候，自动判断IAR路径并做处理了。

@Y-JESSE

**Comment by skllii** [comment]
rtconfig.py已经指定IAR8.4的路径，这个编译报错还是会有
<img width="935" alt="lx_clip1675992957040" src="https://user-images.githubusercontent.com/48580851/217978447-84cfd634-a143-481b-aeac-c71c0878b561.png">

**Comment by aprilhome** [comment]
这个最后怎么解决的呀，我修改了py文件，也还是不行。
![图片](https://user-images.githubusercontent.com/41656067/232355858-52337d0e-5338-4795-b594-5e1df324d8fb.png)
