### ISSUE TITLE
关于USB 消息队列长度问题

### ISSUE THREAD

**Issue by s05427226** [RT-Thread/rt-thread#1297]
在调试STM32F407 host 的时候，发现USBD_MQ_MSG_SZ 定义为16，在实际调试中发现由于该参数过小，导致usb协议初始化不稳定，修改为32后，初始化正常，请跟踪解决一下

**Comment by uestczyh222** [comment]
好的，我跟踪处理一下

**Comment by s05427226** [comment]
使用案例是：我用RT-thread的STM32F407 的host 去连接STM32F407的device。

**Comment by uestczyh222** [comment]
我的意思是你发现的这个问题是位于主机驱动还是从机class上

**Comment by s05427226** [comment]
这个问题是主机

**Comment by s05427226** [comment]
这个是从机

**Comment by s05427226** [comment]
发现的两个问题，都是在从机上

**Comment by uestczyh222** [comment]
OK 我跟踪解决一下

**Comment by s05427226** [comment]
说错了，不是USBD_MQ_MSG_SZ，而是 这个#define USBD_MQ_MAX_MSG 16

**Comment by uestczyh222** [comment]
好的。

**Comment by uestczyh222** [comment]
我这边暂时比较忙 你改了的话可以看看提交PR 我来做测试。不然修复问题可能要几天

**Comment by s05427226** [comment]
好的
