### ISSUE TITLE
mstorage bug

### ISSUE THREAD

**Issue by s05427226** [RT-Thread/rt-thread#1298]
在_cbw_verify 这个函数中，发现有一段代码为 cmd->cmd_len = cbw->cb_len;该地方是不是应该改为 cbw->cb_len =  cmd->cmd_len；请确认一下。

**Comment by uestczyh222** [comment]
请问是主机还是从机

**Comment by s05427226** [comment]
是从机

**Comment by BernardXiong** [comment]
请问，这个还是存在问题吗？
