### ISSUE TITLE
dfs_elm_unmount 函数的bug

### ISSUE THREAD

**Issue by s05427226** [RT-Thread/rt-thread#1308]
在dfs_elm_unmount 函数中 有一段这样的代码result = f_mount(RT_NULL, "", (BYTE)index);，第二个参数感觉不对劲，如果超过两个设备被挂载，就不对了，我自己修改成了char logic_nbr[2] = {'0',':'};这种方式

**Comment by armink** [comment]
https://github.com/RT-Thread/rt-thread/blob/d5d07b761fd99e428af3e0ae57e494e45339ff43/components/dfs/filesystems/elmfat/dfs_elm.c#L196

最新版本代码好像已经修复了

**Comment by s05427226** [comment]
好的
