### ISSUE TITLE
I.mx rt bug list

### ISSUE THREAD

**Issue by uestczyh222** [RT-Thread/rt-thread#1354]
- [ ] Driver 目录下错误的依赖关系导致不打开iic宏时引入iic.c导致编译错误
- [ ] LPI2C_CLOCK_SOURCE_DIVIDER 宏应对RT_USING_I2C存在依赖关系
@TanekLiang

**Comment by uestczyh222** [comment]
@balanceTWK

**Comment by uestczyh222** [comment]
GUI对IIC的依赖关系应该使用反向依赖 而且用GUI应该也不是一定要触摸屏吧。人家用鼠标不行吗

**Comment by TanekLiang** [comment]
嗯，修。
