### ISSUE TITLE
3.03用scons生成后的工程编译提示奇怪的问题

### ISSUE THREAD

**Issue by sijinxiaotongxue** [RT-Thread/rt-thread#1356]
applications\canapp.c(142): error:  #55-D: too many arguments in invocation of macro "RT_CAN_FILTER_STD_INIT"
applications\canapp.c(143): error:  #55-D: too many arguments in invocation of macro "RT_CAN_FILTER_STD_INIT"
applications\canapp.c(144): error:  #55-D: too many arguments in invocation of macro "RT_CAN_STD_RMT_FILTER_INIT"
applications\canapp.c(145): error:  #55-D: too many arguments in invocation of macro "RT_CAN_STD_RMT_DATA_FILTER_INIT"
applications\canapp.c(149): error:  #55-D: too many arguments in invocation of macro "RT_CAN_FILTER_STD_INIT"
applications\canapp.c(150): error:  #55-D: too many arguments in invocation of macro "RT_CAN_FILTER_STD_INIT"
applications\canapp.c(151): error:  #55-D: too many arguments in invocation of macro "RT_CAN_STD_RMT_FILTER_INIT"
applications\canapp.c(152): error:  #55-D: too many arguments in invocation of macro "RT_CAN_STD_RMT_DATA_FILTER_INIT"

**Comment by BernardXiong** [comment]
这个估计是c99的问题，需要打开c99的编译选项
