### ISSUE TITLE
consider add void * priv_data field to struct rt_device

### ISSUE THREAD

**Issue by xfan1024** [RT-Thread/rt-thread#1364]
struct rt_device have a user_data field, but which is used for device driver. It is seem that application developors can't attach thire private data to device object, it's not convenient.

Especially in rx_indicate callback, I need get my private data pointer from the device object.

**Comment by BernardXiong** [comment]
Yes, I have the same issue. Or the device driver shall not use this field.

**Comment by xfan1024** [comment]
@BernardXiong Argee, device driver can place the struct rt_device in their private struct. Using container_of to get thire private data pointer to avoid use user_data. 
But too many driver have already used the user_data filed, modify thire implementation may be very difficult.

**Comment by xfan1024** [comment]
Thanks you fix it.  @armink
