### ISSUE TITLE
bsp/stm32f7-disco gcc 编译无法正常运行

### ISSUE THREAD

**Issue by bestw** [RT-Thread/rt-thread#1385]
gcc: gcc-arm-none-eabi-5_4
bsp: stm32f7-disco
config: default

使用env环境，scons默认编译后程序不能正常运行点灯

默认入口 -eentry，但在gcc/startup_stm32f746xx.s中Reset_Handler: line 115行直接进入了main()

**Comment by BernardXiong** [comment]
可能是入口位置不正确，可以参考下其他的stm32 bsp情况。

或者， @uestczyh222 来处理下
