### ISSUE TITLE
usbhost udisk rt_udisk_run函数信号量创建问题

### ISSUE THREAD

**Issue by s05427226** [RT-Thread/rt-thread#1388]
data->part.lock = rt_sem_create(sname, 1, RT_IPC_FLAG_FIFO);
 rt_snprintf(dname, 6, "ud%d-%d", data->udisk_id, i);
 rt_snprintf(sname, 8, "sem_ud%d", i);

**Comment by BernardXiong** [comment]
具体什么问题？越界了？

@uestczyh222 来看看这个问题。

**Comment by s05427226** [comment]
data->part.lock = rt_sem_create(sname, 1, RT_IPC_FLAG_FIFO); 与 rt_snprintf(sname, 8, "sem_ud%d", i); 应该写反了
