### ISSUE TITLE
Add README.md/Kconfig for some bsp.

### ISSUE THREAD

**Issue by BernardXiong** [RT-Thread/rt-thread#1389]
在v3.0.4版本中，一些描述需要做得更完善，需要添加一些常用bsp的描述文件，Kconfig配置文件。

**Comment by BernardXiong** [comment]
@uestczyh222 负责来处理stm32相关的bsp，或者 @liu2guang 是否也可以一起来帮忙？

* [ ] stm32f10x/stm32f10x-HAL
* [ ] stm32f40x/stm32f4xx-HAL
* [ ] stm32f7-disco
* [ ] stm32l476-nucleo

**Comment by BernardXiong** [comment]
@TanekLiang 负责来处理NXP相关的bsp：

* [ ] lpc54608-LPCXpresso
* [ ] lpc408x
* [ ] gd32450z-eval
* [ ] imxrt1052-evk

**Comment by BernardXiong** [comment]
bernard来处理其他的一些bsp：

* [ ] qemu-vexpress-a9
* [ ] x1000

**Comment by TanekLiang** [comment]
剩余那些bsp需要补充kconfig文件吗？

**Comment by BernardXiong** [comment]
@TanekLiang 我们目前只针对上面提及到的bsp进行完善，先立足于做好简单的事情。

**Comment by TanekLiang** [comment]
好的。

**Comment by uestczyh222** [comment]
@liu2guang 要跳坑吗

**Comment by BernardXiong** [comment]
@TanekLiang 请准备对应的一些README；

@uestczyh222 你这边的stm32，有更多的README说明需要提交；
