### ISSUE TITLE
heap Size在哪里改，gcc stm32

### ISSUE THREAD

**Issue by dangyanglim** [RT-Thread/rt-thread#1399]
我用scons编译的stm32f107，但是不知道heap_size在哪里改

keil版本的知道在哪里改startup_stm32f10x_md.s Heap_Size   EQU   0x00000200
但是gcc的不知道
谢谢

**Comment by aozima** [comment]
keil中并不使用 Heap_Size EQU 0x00000200
设置为0即可，不然浪费。

RT-Thread中的heap使用rt_system_heap_init
把所有末使用的内存作为heap供rt_malloc使用。

可以先阅读一下文档 https://www.rt-thread.org/document/site/
问题发到论坛 https://www.rt-thread.org/qa
