### ISSUE TITLE
关于对c-sky芯片架构BSP包支持的问题

### ISSUE THREAD

**Issue by Prismatic07** [RT-Thread/rt-thread#1433]
在readme中有提到支持csky的芯片架构，英文版的说明好像是有BSP包
可是我好像没有在bsp文件夹里找到。。请问是那个文件夹？

**Comment by BernardXiong** [comment]
我和维护人员check下，可能还在本地

**Comment by Prismatic07** [comment]
请问有进展了吗？

**Comment by TanekLiang** [comment]
我会尽快提交上来。

**Comment by Prismatic07** [comment]
好的，感谢：）

**Comment by linux-hacker** [comment]
请问对C-SKY的支持的代码路径在哪儿？支持哪几种SoC？谢谢！

**Comment by TanekLiang** [comment]
我尽快推出来，现在只支持CK802

**Comment by linux-hacker** [comment]
好的，多谢了！

**Comment by TanekLiang** [comment]
@Prismatic07 @linux-hacker 
CK802的BSP已经合并上去了。https://github.com/RT-Thread/rt-thread/pull/1515

**Comment by Prismatic07** [comment]
OK~收到
