### ISSUE TITLE
rt_list_for_each_entry is not supported by Keil/MDK toolchain

### ISSUE THREAD

**Issue by pansila** [RT-Thread/rt-thread#1459]
Keil/MDK工具链不支持typeof操作符，为什么不提供rt_list_for_each接口，这样至少可以搭配rt_list_entry来用？

**Comment by TanekLiang** [comment]
mdk里加入--gun选项就可以编译了

**Comment by pansila** [comment]
@TanekLiang 多谢
Thanks. It works like a charm, just add the option "--gnu" in the Misc Controls field of C/C++ configuration tab in the project configuration dialog.
