### ISSUE TITLE
JFFS2文件系统显示文件长度总是为0

### ISSUE THREAD

**Issue by mojingxian** [RT-Thread/rt-thread#148]
JFFS2文件系统显示文件长度总是为0，类型定义 typedef short dev_t应该为typedef unsigned int dev_t;

**Comment by mysterywolf** [comment]
目前已经调整为long了 https://github.com/RT-Thread/rt-thread/blob/9bc3896e41716f6415e948ffea153a5453fe4b34/components/libc/compilers/armlibc/sys/types.h#L28
