### ISSUE TITLE
SrcRemove不能很好的解决路径问题

### ISSUE THREAD

**Issue by geniusgogo** [RT-Thread/rt-thread#1505]
('sam0\\drivers\\sercom\\i2c\\i2c_samd20\\i2c_master.c', 'sam0/drivers/sercom/i2c/i2c_samd20/i2c_slave_interrupt.c')
('sam0\\drivers\\sercom\\i2c\\i2c_samd20\\i2c_master_interrupt.c', 'sam0/drivers/sercom/i2c/i2c_samd20/i2c_slave_interrupt.c')
('sam0\\drivers\\sercom\\i2c\\i2c_samd20\\i2c_slave.c', 'sam0/drivers/sercom/i2c/i2c_samd20/i2c_slave_interrupt.c')
('sam0\\drivers\\sercom\\i2c\\i2c_samd20\\i2c_slave_interrupt.c', 'sam0/drivers/sercom/i2c/i2c_samd20/i2c_slave_interrupt.c')
el\Intel(R) Management Engine Compo4\lib\gcc\x86_6
可以看到我在SrcRemove函数里加打印发现内部两种路径str不一样。导致没法正确删除文件。

比如我在lib下有个SConscript文件，添加了sam0/drivers/....下路的子路径文件，那么我的SrcRemove可能是下面这两种写法：
src += Glob('./sam0/drivers/sercom/i2c/i2c_samd20/*.c')
1.
SrcRemove(src, cwd + '/sam0/drivers/sercom/i2c/i2c_samd20/i2c_master_interrupt.c')
SrcRemove(src, cwd + '/sam0/drivers/sercom/i2c/i2c_samd20/i2c_slave_interrupt.c')
2.
SrcRemove(src, './sam0/drivers/sercom/i2c/i2c_samd20/i2c_master_interrupt.c')
SrcRemove(src, './sam0/drivers/sercom/i2c/i2c_samd20/i2c_slave_interrupt.c')
而这两种写法都没法和Src里面的路径一致

**Comment by aozima** [comment]
为嘛我们在win下出来也是 `/`

**Comment by BernardXiong** [comment]
用代码处理下，保证文件是对应的

**Comment by geniusgogo** [comment]
二十多个工程，N个SConscript文件，更新之后就这样了。从SConscript上解决肯定没有从tools里解决好啊。这个更新兼容性没考虑好。

**Comment by BernardXiong** [comment]
那你更改下，提交份PR吧

**Comment by geniusgogo** [comment]
待会儿pr

**Comment by aozima** [comment]
期待PR

**Comment by aozima** [comment]
整理一下各种case，然后独立测试好，争取一版终结。

```
src = ['client.c']
src += ['/test/client.c']
src += ['/test/t1_client.c']
src += ['/test/t2_client.c']
SrcRemove(src, 'client.c')
```

**Comment by geniusgogo** [comment]
case 1:
    src[] 具有重复项
    
case 2:
    remove是一个/风格的路径且是单个str
case 3:
    remove是一个/风格的路径且是list
case 4:
    remove是一个\风格的路径且是单个str
case 5:
    remove是一个\风格的路径且是list
case6:
    路径/\混用
    
case 7：
    src是一个\风格的路径且是单个str
    
case 8:
    src是一个\风格的路径且是list
    
case 9：
    src是一个/风格的路径且是单个str
    
case 10:
    src是一个/风格的路径且是list
