### ISSUE TITLE
使用scons添加SystemView组件，rtconfig.h文件中PKG_SYSVIEW_SYSDESC0 部分信息丢失

### ISSUE THREAD

**Issue by fanwenl** [RT-Thread/rt-thread#1532]
#define PKG_SYSVIEW_EVENTID_OFFSET 32
#define PKG_SYSVIEW_USE_CYCCNT_TIMESTAMP
#define PKG_SYSVIEW_SYSDESC0 "I#15
#define PKG_SYSVIEW_SYSDESC1 ""
#define PKG_SYSVIEW_SYSDESC2 ""

正确：
#define PKG_SYSVIEW_SYSDESC0 "I#15=SysTick"

**Comment by armink** [comment]
在 env 中输入 `pkgs --upgrade` 升级下 env

**Comment by fanwenl** [comment]
@armink 执行了还是一样的，需要手动修改。

**Comment by armink** [comment]
升级完，要记得先 SystemView 关闭，保存，再打开，保存才能重新生成配置文件。
