### ISSUE TITLE
君正x1000平台挂载TF卡写入问题

### ISSUE THREAD

**Issue by sirius65535** [RT-Thread/rt-thread#1541]
内存卡可以正常挂载并读取里面的文件，但是写入有问题，有时候可以正常写（几率小），并且可以写完马上读出来，但大多时候，执行写入操作后tf卡里面被写入的文件丢失或者整个内存卡损坏需要格式化，想问问熊大这大概是什么问题 谢谢了！

**Comment by BernardXiong** [comment]
看看那份驱动，是否其中buffer处理得有问题
