### ISSUE TITLE
信号量删除

### ISSUE THREAD

**Issue by weiye-lu** [RT-Thread/rt-thread#1550]
当我调用了信号量删除API后，再一次发送以及接受信号量的时候API返回RT_EOK。请问什么问题？？互斥信号量、邮箱、事件都是一样，删除后依旧返回RT_EOK。
我使用的是RT-Thread3.0.3

**Comment by geniusgogo** [comment]
因为你delete之后你的这些ipc句柄在堆内存上没有被分配，所以一些原来状态还在内存上，这时候你继续操作是一个野指针。情况就看随机了。当你有内存分配的动作就可能出现fault了

**Comment by aozima** [comment]
应用程序上应该杜绝这种错误操作，不然如果每个API都检查一遍，那性能影响就太大了。

**Comment by BernardXiong** [comment]
要解决这个，不仅是性能上还要包括资源占用上都需要付出代价
