### ISSUE TITLE
tshell是否（除了uart）跟drivers下有很强的耦合和关联

### ISSUE THREAD

**Issue by flightxgf** [RT-Thread/rt-thread#1557]
https://github.com/RT-Thread/rt-thread/blob/ff9162a9945267c9d2fa1166d889c694f51efa2c/bsp/stm32f429-apollo/drivers/drv_i2c.c#L113
比如当我不想使用i2C时，我不想把i2C挂载在总线上，我注释掉/*INIT_DEVICE_EXPORT(stm32f4_i2c_init);*/发现tshell启动不起来，放开就会起来，

**Comment by BernardXiong** [comment]
不会的，你是否是哪里卡住了
