### ISSUE TITLE
添加CmBacktrace组件使用gcc编译出现_sstack未定义

### ISSUE THREAD

**Issue by fanwenl** [RT-Thread/rt-thread#1568]
bsp/stm32f10x软件包，不知道在stm32_rom.ld文件中如何定义。
`
    .stack : 
    {
        . = . + _system_stack_size;
        . = ALIGN(4);
        _estack = .;
    } >DATA

`

**Comment by fanwenl** [comment]
`
    .stack : 
    {
        _sstack = .;
        . = . + _system_stack_size;
        . = ALIGN(4);
        _estack = .;
    } >DATA
`
这样修改可以吗？谢谢！

**Comment by armink** [comment]
可以的，我的也是这样

**Comment by 15298060982** [comment]
我也遇到这个问题，你能分享一下stm32_rom.ld文件吗？

**Comment by 15298060982** [comment]
我也遇到这个问题，你能分享一下stm32_rom.ld文件吗？谢谢

**Comment by fanwenl** [comment]
> 我也遇到这个问题，你能分享一下stm32_rom.ld文件吗？谢谢

你看上面的评论，增加那一行就可以了。

**Comment by 15298060982** [comment]
我现在的.ld 没有DATA，MEMORY不一样

**Comment by fanwenl** [comment]
> 我现在的.ld 没有DATA，MEMORY不一样

[stm32_rom.ld](https://github.com/fanwenl/iBoxClient/blob/master/Drivers/LinkerScript_gcc/stm32_rom.ld)

**Comment by 15298060982** [comment]
非常感谢
