### ISSUE TITLE
dfs_elm_mkfs logic_nbr处理不完整

### ISSUE THREAD

**Issue by s05427226** [RT-Thread/rt-thread#1600]
dfs_elm.c 中的dfs_elm_mkfs函数中， 该段代码
result = f_mkfs(logic_nbr, FM_ANY, 0, work, _MAX_SS);
    rt_free(work); work = RT_NULL;存在问题，修改如下：
logic_nbr[0] = '0' + index;
    result = f_mkfs(logic_nbr, FM_ANY, 0, work, _MAX_SS);
    rt_free(work); work = RT_NULL;

**Comment by BernardXiong** [comment]
为什么有问题呢？

在前面（268行），如果index != -1的时候，会进行处理：
```c
logic_nbr[0] = '0' + index;
```

如果index == -1，则按照`0:`的盘符进行处理。

**Comment by s05427226** [comment]
如果index 不等于 -1呢？

**Comment by BernardXiong** [comment]
是的，index != -1时（说明这个设备已有，并被装载），还不能用`0:`来做盘符进行处理，谢谢！
