### ISSUE TITLE
[components][usb][rndis] rndis单网卡，开启dhcp server，没有成功给客户端分配IP地址

### ISSUE THREAD

**Issue by cris8259** [RT-Thread/rt-thread#1606]
问题如标题。环境：stm32f407，HAL库，win10专业版，如果用407内置网卡开启dhcp server，pc端可分配到ip地址

**Comment by aozima** [comment]
是使用 /components/net/wip_dhcpd/dhcp_server_raw.c 这个DHCP服务器吗？
可以把 DHCP_DEBUG 打开一下看看日志。

同时也可以在RNDIS的驱动里面对数据包进行DUMP。

或者不使用DHCP，板子和电脑都使用固定IP。

先定位到问题点。

**Comment by cris8259** [comment]
用的dhcp_server_raw.c，lwip202

**Comment by aozima** [comment]
时隔多年，我这2天也遇到同样的问题。
最后定位到原因: 使用RNDIS时，都引用了同一个mac，导致设备端和PC端的MAC地址完全一样导致。

调整一下，让两边有所差异即可，比如最后1字节取反一下。
而用以太网时，两边的MAC是不同的。

```c
mac[5] = ~mac[5]
```
