### ISSUE TITLE
有计划把RT-Thread移植到ESP8266、ESP32上吗？或者有移植到其他芯片的教程吗？

### ISSUE THREAD

**Issue by Afantor** [RT-Thread/rt-thread#1610]
我想让ESP8266和ESP32支持RT-Thread，有计划加入这个芯片的计划吗？或者有没有关于把RT-Thread移植到其他芯片上的指导说明？

**Comment by BernardXiong** [comment]
在我自己的github仓库上有过一份ESP32的移植，但也是拼凑的方式的移植，你可以参考下，也许可以更新到最新版本。

**Comment by BernardXiong** [comment]
https://github.com/BernardXiong/rtthread-esp-idf

**Comment by flyingcys** [comment]
https://github.com/flyingcys/RT-Thread-ESP8266这里有1个基于ESP8266_RTOS_SDK_V1.4.x移植的工程，可以运行起来。使用的是lwip是SDK自带的lwip.a
最近有计划移植ESP8266_RTOS_SDK_V3.0版本，有兴趣一起参与下！

**Comment by hyt-klc** [comment]
Hello dear.
Rt-Thread and Rt-Thread Studio now supports RISC-V processors.
Are there any plans to add support for ESP32 processors and dev boards?
