### ISSUE TITLE
bsp\stm32f4xx-HAL\drivers\drv_gpio.c(1583): warning:  #815-D: type qualifier on return type is meaningless

### ISSUE THREAD

**Issue by xwiron** [RT-Thread/rt-thread#1633]
MDK/IAR 编译警告：
drivers\drv_gpio.c(1583): warning:  #815-D: type qualifier on return type is meaningless
  const  rt_uint16_t get_pin(uint8_t pin)

**Comment by BernardXiong** [comment]
@uestczyh222 大法师修修哦！

**Comment by uestczyh222** [comment]
修了
