### ISSUE TITLE
HardFault_Handler汇编处理栈指针的时候是否错了？

### ISSUE THREAD

**Issue by geniusgogo** [RT-Thread/rt-thread#1646]
```
HardFault_Handler    PROC

    ; get current context
    TST     lr, #0x04               ; if(!EXC_RETURN[2])
    MRSNE   r0, msp                 ; get fault context from handler.
    MRSEQ   r0, psp                 ; get fault context from thread.`
```

当LR值BIT2为1的时候代表触发异常时使用的PSP栈，为0使用的是MSP。
而NE条件后缀当xPSR寄存器Z位为0时有效，EQ条件当Z位为1时有效。
TST指令测试LR的BIT2,当BIT2为1的时候XPSR寄存器的Z位将为0代表NE，反之为1代表EQ.
所以
MRSNE R0,MSP
MRSEQ R0,PSP
应该改为
MRSEQ R0, MSP
MRSNE R0,PSP

================================
大佬们对不对？

**Comment by liangyongxiang** [comment]
我比较了两种的指令：
![image](https://user-images.githubusercontent.com/8002634/42934999-1f3a5e98-8b7b-11e8-8460-b63261a09716.png)

![image](https://user-images.githubusercontent.com/8002634/42935113-66a34e16-8b7b-11e8-9a36-5ff64ea0ca3b.png)

以及对比了Cortex-M3和M4权威指南书里的示例：
![image](https://user-images.githubusercontent.com/8002634/42935740-069f3488-8b7d-11e8-85a4-230e22fd6a89.png)

以及在stm32f103里测试了。

所以我觉得是对的。牛头哥威武霸气。
