### ISSUE TITLE
Very bad design to use TCB user_data to determine the thead is LWP 

### ISSUE THREAD

**Issue by parai** [RT-Thread/rt-thread#1661]
This logic will result that the pthreads can't be used along with LWP, or that the user should taken care not to use the user_date of the TCB.

510#ifdef RT_USING_LWP
511    struct rt_lwp *lwp;
512
513    lwp = (struct rt_lwp *)rt_thread_self()->user_data;
514    if (lwp)
515        fdt = &lwp->fdt;
516    else
517        fdt = &_fdtab;
518#else
519    fdt = &_fdtab;
520#endif

**Comment by BernardXiong** [comment]
Agree
