### ISSUE TITLE
RT1052bsp+野火mini+LWIP+8g SD/TF卡 操作SD错误

### ISSUE THREAD

**Issue by Dmy847239981** [RT-Thread/rt-thread#1688]
问题如下：
       使用野火的RT1052mini开发板，同时使用LWIP和8g SD卡时出现卡死现象。 使用LWIP和1g SD卡时正常工作。 使用LWIP和256m SD卡时正常工作。 关掉LWIP单独使用8G的卡时，可以正常工作。
猜测：
       使能了LWIP导致不能读取大容量的卡。

**Comment by BernardXiong** [comment]
是i.mx rt1052上的SD卡驱动还有问题，不稳定
