### ISSUE TITLE
有没有尝试过用C++开发RTThread？如果尝试过是什么原因导致了放弃C++而用C？

### ISSUE THREAD

**Issue by alexyuoouy** [RT-Thread/rt-thread#1701]

**Comment by liangyongxiang** [comment]
我觉得一个很重要的理由里，很多人不会C++。 
RTOS是给大家使用的。所以C就是首选。

**Comment by alexyuoouy** [comment]
我觉得可以为C写个API提供给不会C++的人。
用C++写的话结构应该会简单明了许多，只是不知道效率会怎样。

**Comment by liangyongxiang** [comment]
如果用C++。像我这种不会C++只会C的，就没法给RTT提PR了。
当然C++也是很有必要去学习的。

C++的问题，我是觉得有些地方会不好控制难度会有增加，例如启动代码相关（heap初始化之前，new关键字不能用。）

**Comment by alexyuoouy** [comment]
原来有这么多的问题，是我想的太简单了哈哈
