### ISSUE TITLE
RT_USING_DEVICE_OPS [=y]，引起rt_hw_rtc_init（）报错

### ISSUE THREAD

**Issue by MarcusXing** [RT-Thread/rt-thread#1726]
现象：
compiling drv_rtc.c...
drivers\drv_rtc.c(173): error:  #136: struct "rt_device"  has no field "init"
      rtc_device.init        = stm32_rtc_init;
drivers\drv_rtc.c(174): error:  #136: struct "rt_device"  has no field "open"
      rtc_device.open        = stm32_rtc_open;
drivers\drv_rtc.c(175): error:  #136: struct "rt_device"  has no field "close"
      rtc_device.close       = stm32_rtc_close;
drivers\drv_rtc.c(176): error:  #136: struct "rt_device"  has no field "read"
      rtc_device.read        = stm32_rtc_read;
drivers\drv_rtc.c(177): error:  #136: struct "rt_device"  has no field "write"
      rtc_device.write       = stm32_rtc_write;

可能的原因：
rt-thread/bsp/stm32f4xx-HAL/drivers/drv_rtc.c未按照ops方式适配

**Comment by BernardXiong** [comment]
现在除了qemu-vexpress-a9以外，挺多都没安装ops方式来编写驱动的。
