### ISSUE TITLE
UART3 issue

### ISSUE THREAD

**Issue by MarcusXing** [RT-Thread/rt-thread#1768]
在menuconfig中选择不支持UART3的mcu，例如STM32F401xx，会编译错误：
drivers\drv_usart.c(302): error:  #20: identifier "USART3" is undefined
      else if (uartHandle->Instance == USART3)
drivers\drv_usart.c(305): warning:  #223-D: function "__HAL_RCC_USART3_CLK_ENABLE" declared implicitly
          __HAL_RCC_USART3_CLK_ENABLE();
drivers\drv_usart.c(315): error:  #20: identifier "GPIO_AF7_USART3" is undefined
          GPIO_InitStruct.Alternate = GPIO_AF7_USART3;

建议在rt-thread\bsp\stm32f4xx-HAL\drivers\drv_usart.c的Line286和Line342增加
#if defined(RT_USING_UART3)

**Comment by uestczyh222** [comment]
于是用户就会很奇怪 为了开了uart3 却没有设备出来。这个后面做一个依赖分析吧 把没有uart3的设备从Kconfig种移除掉
