### ISSUE TITLE
关于"[Kernel] Add ARMCC 6.x support. #1835"更改的问题及建议

### ISSUE THREAD

**Issue by liruncong** [RT-Thread/rt-thread#1840]
1. 问题: libcpu\arm\cortex-m*\cpuport.c更改错误. 下面摘出错误位置.
__________________________________________________________________________________________
#if               /* ARMCC */ (  (defined ( __CC_ARM ) && defined ( __TARGET_FPU_VFP ))    \
                  /* Clang */ || (defined ( __CLANG_ARM ) && defined ( __TARGET_FPU_VFP )) \
                  /* IAR */   || (defined ( __ICCARM__ ) && defined ( __ARMVFP__ ))        \
                  /* GNU */   || (defined ( __GNUC__ ) && defined ( __VFP_FP__ ) && !defined(__SOFTFP__)) )
______________________________________________________________________________________________________
这里armclang使用了__TARGET_FPU_VFP,这个并不会定义,只会定义__VFP_FP__. 应删除.
当使用硬件浮点时, armclang定义了__VFP_FP__,没有定义__SOFTFP__. 
下面摘录部分定义,并说明
________________________________________________________________________________________________________
#define __llvm__ 1
#define __clang__ 1
#define __clang_major__ 7
#define __clang_minor__ 0
#define __clang_patchlevel__ 0
#define __clang_version__ "7.0.0 "                                               // 基于LLVM clang7.0.0
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 1
#define __GNUC__ 4                                                                     // 兼容GNU4.2
.....
#define __VFP_FP__ 1                                                                   // VFP
#define __ARM_VFPV3__ 1
#define __ARM_NEON 1
#define __ARM_NEON__ 1
#define __ARM_NEON_FP 0x4
....
注: 将我之前PR中的armclang.py中第70行"#print(stdout)"的"#"去掉,编译时会打印上面定义
________________________________________________________________________________________________________
因此,删除/* clang */行即可.
2. 建议: armclang和armcc差别较大, 在c/c++上跟gcc更接近(使用clang7.0语法格式,对gcc兼容性更好, 包括嵌入汇编).  差别只在于汇编文件格式不同, scatter和*.lds格式不同. 有关c/c++文件的修改应首选往gcc上靠,而不是往armcc靠. 
3. 这次更改并不完整, 没有任何一个bsp可以进行clang编译. 是不是后续还要分别提交其它内容?这种不完整的提交是怎么进行测试的?

**Comment by BernardXiong** [comment]
arm clang不是gcc，差别还是有些，各种的，还包括libc。所以arm clang肯定是独立的，想统一到一个编译器上，这个可能性非常非常低，另外也还有IAR呢；

所以对于arm clang的支持，可能会暂时这样，Keil MDK中默认的编译器还是armcc。

**Comment by liruncong** [comment]
好的
