### ISSUE TITLE
struct dfs_fd结构中的pos、size字段具体有什么意义价值没？

### ISSUE THREAD

**Issue by geniusgogo** [RT-Thread/rt-thread#1847]
我再适配littlefs，重构一下我之前的适配代码，发现会在read、write操作后会对dfs的pos和size进行更新，而我的理解是dfs作为文件系统的抽象层为什么需要跟踪文件的pos和size？如果我适配时忽略这两个字段会有影响吗？

**Comment by BernardXiong** [comment]
文件读写位置，和文件大小

**Comment by BernardXiong** [comment]
pos = position = 读写时的position。读和写是一体化的，不是分别的读、写

**Comment by HubertXie** [comment]
littlefs已经适配好了，上次提交了，熊大说要做成package
