### ISSUE TITLE
cplusplus中的thread 类可以直接 Thread t1(xxx)直接调用（实例化）吗？

### ISSUE THREAD

**Issue by beikeln** [RT-Thread/rt-thread#1851]
rt-thread/components/cplusplus/Thread.cpp中实现了Thread类
class Thread
{
public:
    typedef void (*thread_func_t) (void *param);
     .....
    Thread(rt_uint32_t stack_size = 2048,
           rt_uint8_t  priority = (RT_THREAD_PRIORITY_MAX * 2)/3,
           rt_uint32_t tick = 20,
           const char *name = "th");
   ......
}
可以直接调用 Thread t1(xxx) 创建一个任务吗？
发现使用arm-none-eabi-g++ 编译会有报错  
谢谢

**Comment by BernardXiong** [comment]
具体可以调试下，用静态对象是需要比较注意下的，看看它是在哪里进行构造对象的
