### ISSUE TITLE
使用 GCC 编译 DFS 时出现错误

### ISSUE THREAD

**Issue by xuzhuoyi** [RT-Thread/rt-thread#1862]
打开 RT_USING_DFS 后 GCC 出现编译错误：
...\rt-thread\components\libc\compilers\minilibc/errno.h:6:21: fatal error: dfs_def.h: No such file or directory

errno.h:
```
#ifndef __ERRNO_H__
#define __ERRNO_H__

#ifdef RT_USING_DFS

#include <dfs_def.h>

/* using device error codes */
#define ENOENT		DFS_STATUS_ENOENT
#define EIO		 	DFS_STATUS_EIO
#define ENXIO		DFS_STATUS_ENXIO
#define EBADF		DFS_STATUS_EBADF
#define EAGAIN		DFS_STATUS_EAGAIN
#define ENOMEM		DFS_STATUS_ENOMEM
#define EBUSY		DFS_STATUS_EBUSY
......
```
但是我在整个源代码树里也找不到 dfs_def.h 这个头文件，是哪里的配置有问题吗？

**Comment by BernardXiong** [comment]
dfs_def.h这个文件应该是移除了。应该是当时重构dfs，没有验证到minilibc，因为一般的，当使用DFS时，基本上会考虑全的newlib了。

**Comment by xuzhuoyi** [comment]
那这里的#include <dfs_def.h>可以直接移除了？

**Comment by BernardXiong** [comment]
dfs_def.h是不需要的，可以移除。

你参照下其他的修改下，这些error number应该也不需要定义了
