### ISSUE TITLE
在math.c文件中提示m_pi未定义

### ISSUE THREAD

**Issue by whj4674672** [RT-Thread/rt-thread#1863]
修改文件第一行#include <math.h>为#include "math.h" 可以修正此问题

**Comment by BernardXiong** [comment]
请给出更多详细信息

**Comment by whj4674672** [comment]
在math.c文件中 #include <math.h>，这样会导致在math.h定义的#define M_PI 会显示未定义。
所以修改math.c文件中的#include <math.h>为#include ”math.h”，可以修正此问题。
