### ISSUE TITLE
RTT 3.10 GCC LIBC compilation Error

### ISSUE THREAD

**Issue by WGR7** [RT-Thread/rt-thread#1883]
Hi,

I'm trying to compile RTT v3.10 with STM32 AC6 GCC Eclipse IDE, but I'm getting an error when the libc is compilled. The error is:

/components/lib/compillers/armlibc/stubs.c   rt_sys.h No such file or directory

Whats wrong? As I could see, keil has this file inside its diretories, but GCC don't have it. 

Best Regards

**Comment by BernardXiong** [comment]
The "armlibc" is used for Keil MDK, armcc. If you use GCC, please use libc/compilers/newlib.
