### ISSUE TITLE
有关RTT的编程风格

### ISSUE THREAD

**Issue by LittleFatHero** [RT-Thread/rt-thread#1913]
首先，感觉"!"、 "~"、 "++"、 "--"、 "&"（地址操作符）等单目操作符前后不应该加空格
其次，switch语句和case语句位于同一列，没有缩进让我很难受

**Comment by BernardXiong** [comment]
嗯，可以看看tools下的astyle脚本。

**Comment by ShareCat** [comment]
astyle脚本找到了：as.sh

建议所有大括号换行，除了函数的大括号外

**Comment by liruncong** [comment]
我倒是认为, 应该除函数的大括号外,都不换行. 这样一个文件可以少很多行, 比较简洁.

**Comment by BernardXiong** [comment]
RTT的风格是相互之间错开，清晰些

**Comment by gbcwbz** [comment]
zephyr 在根目录包括了一个 [.clang-format](https://github.com/zephyrproject-rtos/zephyr/blob/master/.clang-format) 文件， rtt 也可以加个 astylerc
