### ISSUE TITLE
compile error found since there is typeto issue

### ISSUE THREAD

**Issue by smartInstrument** [RT-Thread/rt-thread#1926]
On the latest change:
        d3764db892e4e97b6d599bda867eaa49b0ad4786
bellow “#ifndf” should be fix to "#ifndef"
+#ifndf USB_DEBOUNCE_TIME
+#define USB_DEBOUNCE_TIME               (RT_TICK_PER_SECOND / 5)    /* 0.2s */

address file:
       components/drivers/include/drivers/usb_common.h

**Comment by BernardXiong** [comment]
@uestczyh222 
Please take a look and fix it.

**Comment by uestczyh222** [comment]
#1929
