### ISSUE TITLE
bsp\stm32f40x MDK5.24编译失败

### ISSUE THREAD

**Issue by yangang123** [RT-Thread/rt-thread#1948]
**为什么编译失败？ 这个bsp下的工程是怎么回事？**
1. 切换到tag v3.1.0 
git checkout v3.1.0 

**2. 打开bsp/stm32f40x 下的MDK5的工程**

**3. 编译出现下面**
![default](https://user-images.githubusercontent.com/26058337/47995550-a2c06e00-e130-11e8-8dff-a0801bd0bbba.png)

**Comment by Lawlieta** [comment]
可能是代码改动没有重新生成工程，你这边手动生成新工程试试
