### ISSUE TITLE
关于测试框架

### ISSUE THREAD

**Issue by XXXXzzzz000** [RT-Thread/rt-thread#1974]
我在example中找到了TC框架,但是在menuconfig里没有搜到有关RT_USING_TC相关的配置,在手册里也基本上找不到相关的说明,只有过一篇CSDN的blog和论坛里讲过一点.
所以关于测试框架这部分是什么情况呢?

**Comment by BernardXiong** [comment]
因为tc会被取消掉，然后换新的，这个可能是和BSP整合同步推出吧，还不确定

**Comment by XXXXzzzz000** [comment]
移植现有的测试库是不是一个比较好的方式呢?https://github.com/ThrowTheSwitch/Unity/
bsp的整理哪里有什么详细的信息吗? @BernardXiong

**Comment by BernardXiong** [comment]
这个需要 @armink 来说明下了

**Comment by armink** [comment]
开发类似 Unity 这样的单元测试库的工作已经在进行了，这个只是整个测试框架中的一部分，还有一个目标是要实现 BSP 层面上的系统集成测试，所以对部分 BSP 的框架要做些调整。

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/5387

**Comment by jiuxiaxixi** [comment]
> ，这个只是整个测试框架中的一部分，还有一个目标是要实现 BSP 层面上的系统集成测试，所以对部分 BSP 的框架要做些调整。

新的测试框架有什么想法呀

**Comment by XXXXzzzz000** [comment]
您的邮件我已收到。                                                             宣泽
