### ISSUE TITLE
stm32f107 串口驱动 串口3 存在BUG

### ISSUE THREAD

**Issue by yuanxiaobai** [RT-Thread/rt-thread#1982]
`#if defined(RT_USING_UART3)
    uart = &uart3;

    config.baud_rate = BAUD_RATE_115200;
  ###   serial2.ops    = &stm32_uart_ops;         //应该是serial3
  ### serial2.config = config;                         //应该是serial3

    NVIC_Configuration(&uart3);

    /* register UART3 device */
    rt_hw_serial_register(&serial3, "uart3",
                          RT_DEVICE_FLAG_RDWR | RT_DEVICE_FLAG_INT_RX,
                          uart);
#endif /* RT_USING_UART3 */`

**Comment by BernardXiong** [comment]
Thank you for your feed back, which is fixed by #1983 .
