### ISSUE TITLE
rt-thread\components\cplusplus组件scons构建失败?

### ISSUE THREAD

**Issue by yangang123** [RT-Thread/rt-thread#1990]
1. 在menuconfig中，使能cplusplus功能
2. 命令:scons -s 
**构建失败**

`g++ -o "build\kernel\components\cplusplus\crt.o" -c -mcpu=cortex-m3 -mthumb -ffunction-sections -fdata-sections -O0 -gdwarf-2 -DHAVE_CCONFIG_H -DUSE_STDPERIPH_DRIVER -DSTM32F10X_HD -DRT_USING_NEWLIB -I. -Iapplications -Idrivers -ILibraries\STM32F10x_StdPeriph_Driver\inc -ILibraries\CMSIS\CM3\DeviceSupport\ST\STM32F10x -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\components\CMSIS\Include -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\include -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\libcpu\arm\cortex-m3 -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\libcpu\arm\common -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\components\cplusplus -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\components\dfs\include -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\components\dfs\filesystems\devfs -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\components\dfs\filesystems\elmfat -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\components\drivers\include -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\components\drivers\include -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\components\drivers\include -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\components\drivers\include -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\components\finsh -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\components\libc\compilers\newlib -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\components\libc\pthreads -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\components\libc\termios -IE:\yangang\Software\rtthread\firmware\platforms\rt-thread\components\libc\time "E:\yangang\Software\rtthread\firmware\platforms\rt-thread\components\cplusplus\crt.cpp"
Exception: [Error 2] : No such file or directory
scons: *** [build\kernel\components\cplusplus\crt.o] Error 2`

**Comment by BernardXiong** [comment]
为什么是使用g++，而不是arm-none-eabi-g++ ？
