### ISSUE TITLE
文件系统返回后errno为负

### ISSUE THREAD

**Issue by heyuanjie87** [RT-Thread/rt-thread#2002]
在移植linux代码的时候errno为正数,目前文件系统出错后errno为负数。
不确定以后rtt是否会向其他系统靠齐，我只好写成这样了：
    if (fd < 0) 
    {
        int eno = rt_get_errno();
        if (eno == ENOENT || eno == -ENOENT)
        {
            if (!secure_mkdirs(path)) 
            {
                goto fail;
            }           
        }
    }

**Comment by BernardXiong** [comment]
多找几个系统看看，这个修改影响很大呢

**Comment by BernardXiong** [comment]
linux，freebsd，然后其他的，例如vxworks，rtems等

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/issues/4791
