### ISSUE TITLE
mtd驱动不支持device框架操作？

### ISSUE THREAD

**Issue by geniusgogo** [RT-Thread/rt-thread#2010]
今天准备适配nor设备的文件系统，发现目前mtd设备的操作是通过具体的接口驱动ops适配到具体的mtd设备的ops上，而mtd设备register到rt_device上去的时候提供open/close这一套接口和ops接口都是制空的。
也就是说目前nor、nand驱动很奇葩。
当想使用rt_device_write这种抽象接口适配mtd设备时无法做到。
眼下还需要修改nor、nand等设备驱动才行。

**Comment by BernardXiong** [comment]
是的，很奇葩，而且还有两套，都不清楚杀猪的 @heyuanjie87 怎么想的

**Comment by heyuanjie87** [comment]
我只负责制造统一的mtd接口，埋葬旧的交给你，毕竟它已经猥琐的存在好多年了，我实在是下不去手。
牛头哥 mtd一般不是直接提供device接口给上层用，除非你给它写了ftl或nftl
