### ISSUE TITLE
[bsp][stm32f4xx]在stm32f4xx.c中assert_param的无效性

### ISSUE THREAD

**Issue by whj4674672** [RT-Thread/rt-thread#2026]
在3.1.0以前的版本中这个是有效的，因为在stm32f4xx_conf.h里面开启了USE_FULL_ASSERT，从而使assert_param有效，并在startup.c里面实现了函数assert_failed。
在3.1.1以后的版本中，stm32f4xx进行了更新，删除了startup.c和appliance.c，这样assert_failed就没有了，assert_param就变的无效了，RTT自己也有自己的RT_ASSERT，这样的话是否要用RT_ASSERT取代assert_param？

**Comment by BernardXiong** [comment]
这个是的，得要对接下
