### ISSUE TITLE
[bsp][stm32][stm32f429-atk-apollo]缺少"pcf8574.h"文件

### ISSUE THREAD

**Issue by fsyxhua** [RT-Thread/rt-thread#2138]
[bsp][stm32][stm32f429-atk-apollo]缺少"pcf8574.h"文件

**Comment by balanceTWK** [comment]
![image](https://user-images.githubusercontent.com/30776697/50540462-0dd86f00-0bcd-11e9-87b5-e965a8a2154a.png)

没有复现你的问题，你是不是在输入命令 scons --target=xxx 前 没有输入命令 pkgs --update ？

**Comment by fsyxhua** [comment]
pkgs --update 肯定输入了，而且我都设置是自动update的，手动输入也试了，能帮我看看pcf8574.c和pcf8574.h的文件路径吗？我的直接搜索都搜索不到的

**Comment by fsyxhua** [comment]
谢谢balanceTWK的回答，问题找到了，从gitee上clone下来的代码没有drivers文件夹，刚才去gitee站点看了一下，目录里确实没有drivers文件夹
<img width="800" alt="_20181230090141" src="https://user-images.githubusercontent.com/8734240/50543364-9d077600-0c11-11e9-965f-6d0c3612ec5b.png">
<img width="770" alt="_20181230090244" src="https://user-images.githubusercontent.com/8734240/50543367-b3153680-0c11-11e9-932a-1088db94a1f0.png">

**Comment by fsyxhua** [comment]
menuconfig 配置里面没有，pcf8574的选项，需要手动拷贝进去，你那个是不是手动添加的？

**Comment by balanceTWK** [comment]
@fsyxhua  没有手动加。代码是 GitHub 最新的， 选中 以太网 选项，按照正常流程打开 就能用了。
