### ISSUE TITLE
msh自带命令是否可以去掉list进行精简 感觉输起来好麻烦啊

### ISSUE THREAD

**Issue by Darabar** [RT-Thread/rt-thread#2155]
![image](https://user-images.githubusercontent.com/46389244/50718950-39c58a00-10d0-11e9-8ad8-2d048f733437.png)

**Comment by greedyhao** [comment]
个人感觉问题不大，毕竟可以使用tab自动补全

**Comment by zhaojuntao** [comment]
影响不大吧，这样看过去一目了然，精简之后，可能还需要看释义

**Comment by majianjia** [comment]
表示支持，问题虽不大但是跟后面的指令风格并不匹配。希望能统一一下或者缩写一下。毕竟每个指令后面已经有了注释说明，多一个list_前缀并不是必须的。

**Comment by BernardXiong** [comment]
主要是这个已经有一定历史了，另外是，如果输入一个sem，然后就list_sem好像也挺怪的。

**Comment by gbcwbz** [comment]
msh 使用 `list sem`这种风格更统一，可以再加一个`list`命令，然后有多个子命令

**Comment by majianjia** [comment]
然而你们的list_mem 都已经改成了free
list_thread 跟ps也是差不多的

**Comment by BernardXiong** [comment]
加个list sem/thread/mutex这样的也挺好，谁可以提个PR上来
