### ISSUE TITLE
lwip2.1.0的移植问题

### ISSUE THREAD

**Issue by qiaoqidui** [RT-Thread/rt-thread#2194]
测试发现初始化eth和lwip协议栈的顺序会影响网络接口添加后的状态，分析的情况应该是需要把netif->linkoutput放到线程启动判断的外面，比如放到netif->hwaddr_len   = 6;这一句的后面。然后在eth_netif_device_init和netif_device_init里面都需要设置netif->mtu          = ETHERNET_MTU;netif->output = etharp_output;以适应两种不同的初始化顺序。

**Comment by BernardXiong** [comment]
欢迎发出PR出来，谢谢！

**Comment by zhaojuntao** [comment]
该问题确实存在，PR #2282 中的修改是合理的。

原因：

LWIP210 相比 LWIP202 在 netif.c 的 `netif_add` 函数中增加了 `netif->output = netif_null_output_ip4;`，导致覆盖了 ethernetif.c 文件 `eth_device_init_with_flag` 函数中初始化的 `netif->output = etharp_output`。
