### ISSUE TITLE
使用mipsel-none-elf-win编译器编译龙芯1C工程时会出错，提示此应用无法在你的电脑上运行，电脑也重装过一次

### ISSUE THREAD

**Issue by DQHD** [RT-Thread/rt-thread#2211]
![1](https://user-images.githubusercontent.com/46662809/51094967-2ad78980-17ec-11e9-8904-6d1778dda6ba.png)

**Comment by DQHD** [comment]
![qri3q s_9 i 6 gwm8nx](https://user-images.githubusercontent.com/46662809/51095114-4ee79a80-17ed-11e9-9179-2f8334dce48c.png)

**Comment by DQHD** [comment]
![tim 20190114111233](https://user-images.githubusercontent.com/46662809/51095123-64f55b00-17ed-11e9-9676-d32ea869b6ab.png)

**Comment by BernardXiong** [comment]
这个好像没有好的办法，还是得自己找找编译器，工具链了。MIPS相关的，原来使用的主要是code sourcery的工具链。

**Comment by XBurst** [comment]
可以考虑自己做一个mingw的工具链，用newlib2.2
