### ISSUE TITLE
FINSH UART NO DMA

### ISSUE THREAD

**Issue by WGR7** [RT-Thread/rt-thread#2239]
Hi,

I've compiled sucessfully RTT 3.1 LTS for STM32F103RC, but I want to use the finsh terminal without DMA. When I try this, seems that putc works nice, but getc did not work. I can get text on terminal, but I can not write commands. The cursor blinks only, I can not enter text commands.

Regards,

**Comment by BernardXiong** [comment]
Normally, uart->getc is work with INT RX for UART.
