### ISSUE TITLE
sal框架，使用at设备，closesocket 有时候无法delete it from file system fd 

### ISSUE THREAD

**Issue by seblee** [RT-Thread/rt-thread#2242]
net_sockets.c 文件
line 252 
如果 在执行 sal_closesocket(socket) 的时候，socket被server关闭，可能会返回-1；然后就无法删除文件，内存可能会丢失

**Comment by seblee** [comment]
> net_sockets.c 文件
> line 252
> 如果 在执行 sal_closesocket(socket) 的时候，socket被server关闭，可能会返回-1；然后就无法删除文，内存可能会丢失

次数超过 
#define DFS_FD_MAX 4 
后 socket()函数 直接返回-1

**Comment by Lawlieta** [comment]
DFS_FD_MAX 值为最大支持的 Socket 使用数量，超过之后创建 socket 失败，返回 -1 正常

**Comment by Lawlieta** [comment]
确定一下 sal_closesocket 什么情况下出现的返回 -1，正常 sockt 被 server 关闭，客户端 recv 或 send 函数返回0之后，需要调用 closesocket 正常关闭当前 socket；
