### ISSUE TITLE
关于新的stm32 bsp的GPIO驱动

### ISSUE THREAD

**Issue by z14git** [RT-Thread/rt-thread#2258]
新的GPIO驱动相比于以前确实是好用，但现在所有 ```rt_pin_xxx()``` 函数里的 ```rt_base_t pin``` 参数的意义与以前的完全不一样了。这么大的改变，bsp里的文档都不提一下吗？

**Comment by SummerGGift** [comment]
每个驱动使用方法的文档，确实有待完善。
