### ISSUE TITLE
[sfud]flash reset

### ISSUE THREAD

**Issue by PiscesLyn** [RT-Thread/rt-thread#2271]
sfud hardware_init中会对flash device进行软件reset，但AT45DBxx系列不支持软件reset，而是硬件io reset，
这边的reset是否做一下判断差分？

**Comment by armink** [comment]
> 这边的reset是否做一下判断差分

具体指的什么呢

**Comment by PiscesLyn** [comment]
`    /* reset flash device */`
`    result = reset(flash);`
`    if (result != SFUD_SUCCESS) {`
`        return result;`
`    }`

hardware_init中这段reset，是通过发送0x00,0x66,0x99给flash进行复位，但AT45DBXX不支持该命令，导致超时等待，而超时等待有因为另一个问题会等很久[https://github.com/RT-Thread/rt-thread/issues/2272](url)，结果就是程序一直在reset中循环。

**Comment by armink** [comment]
AT45DBXX 目前基本废弃了对它的支持，如果你还在使用，期待去做下改进，然后 pr 上来

**Comment by PiscesLyn** [comment]
我看了下AT45DBXX的读写状态等寄存器地址也和sfud现有的不一样, 改了塞进sfud反而会造成臃肿, 还不如裸跑了.
