### ISSUE TITLE
gnu gcc 编译时出现与newlib类型重定义

### ISSUE THREAD

**Issue by aichiriemo** [RT-Thread/rt-thread#2279]
rt-thread 版本：3.1.1
系统版本：ubuntu18.10
目标平台：stm32F40x

gcc版本： arm-none-eabi-gcc（ 20170620）
 
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build
AS build/Libraries/CMSIS/ST/STM32F4xx/Source/Templates/gcc_ride7/startup_stm32f4xx.o
CC build/applications/main.o
In file included from /home/zhukaiyi/rt-thread/rt-thread/include/libc/libc_signal.h:67:0,
                 from /home/zhukaiyi/rt-thread/rt-thread/include/rtlibc.h:21,
                 from /home/zhukaiyi/rt-thread/rt-thread/include/rtdef.h:1071,
                 from /home/zhukaiyi/rt-thread/rt-thread/include/rtthread.h:24,
                 from /home/zhukaiyi/rt-thread/rt-thread/include/rthw.h:20,
                 from applications/main.c:12:
/usr/include/newlib/sys/signal.h:42:7: error: redefinition of 'union sigval'
 union sigval {
       ^~~~~~
In file included from /home/zhukaiyi/rt-thread/rt-thread/include/rtlibc.h:21:0,
                 from /home/zhukaiyi/rt-thread/rt-thread/include/rtdef.h:1071,
                 from /home/zhukaiyi/rt-thread/rt-thread/include/rtthread.h:24,
                 from /home/zhukaiyi/rt-thread/rt-thread/include/rthw.h:20,
                 from applications/main.c:12:
/home/zhukaiyi/rt-thread/rt-thread/include/libc/libc_signal.h:27:7: note: originally defined here
 union sigval

**Comment by BernardXiong** [comment]
请使用ARM GNU GCC，6或以前的版本。更改工具链重新编译，请先执行`scons -c`
