### ISSUE TITLE
stm32 新 bsp 中 LWIP 和 ETH 编译依赖问题

### ISSUE THREAD

**Issue by shaoguoji** [RT-Thread/rt-thread#2392]
使用新 bsp 时发现， 在 `\bsp\stm32\libraries\HAL_Drivers\SConscript`  文件中，把 lwip 和 eth 模块关联了起来：

```
if GetDepend('RT_USING_LWIP'):
    src += ['drv_eth.c']
```

导致只用 lwip 而不需要 eth（或者不支持 eth）的情况下，也会编译 drv_eth.c，在不支持 eth 的工程中会报 `undefined` 错误，能否考虑用其他方式处理两者的关系。

**Comment by SummerGGift** [comment]
关于该问题，在如下 PR 中去除了依赖。

https://github.com/RT-Thread/rt-thread/pull/2664
