### ISSUE TITLE
bug反馈。signal.c

### ISSUE THREAD

**Issue by Dutongxue** [RT-Thread/rt-thread#2398]
`src/signal.c: 421`行：`node = (struct rt_slist_node *)tid->si_list;`
应该是 `node = &((struct siginfo_node *)tid->si_list)->list;`

按道理tid->si_list指向的是`struct siginfo_node`类型

**Comment by BernardXiong** [comment]
请先使用lts-v3.1.x的分支；master, v4.0.x的分支，还存在SMP signal的问题，在修正中。

**Comment by mysterywolf** [comment]
麻烦确认一下现在的master还存在这个bug吗
