### ISSUE TITLE
关于rt_thread_idle_excute detach thread object操作的问题!

### ISSUE THREAD

**Issue by 13824125580** [RT-Thread/rt-thread#2465]
Hi　各位:
　　关于rt_thread_idle_excute中在不判断rt_object_is_systemobject是否是系统thead后面，rtt 4.0中加入了rt_thread_objec detach操作，但是在之前已经发布的rtthread 3.0中是没有这个操作的，现在项目遇到一个问题感觉和object释放有关系，所以这里想请教一下各位大佬，这个改动是否可以添加到3.0中确认问题？
127     ¦   ¦   /* if it's a system object, not delete it */                                                                                          |~                                       
128     ¦   ¦   if (rt_object_is_systemobject((rt_object_t)thread) == RT_TRUE)                                                                        |~                                       
129     ¦   ¦   {                                                                                                                                     |~                                       
130     ¦   ¦   ¦   /* unlock scheduler */                                                                                                            |~                                       
131     ¦   ¦   ¦   rt_exit_critical();                                                                                                               |~                                       
132                                                                                                                                                   |~                                       
133     ¦   ¦   ¦   /* enable interrupt */                                                                                                            |~                                       
134     ¦   ¦   ¦   rt_hw_interrupt_enable(lock);                                                                                                     |~                                       
135                                                                                                                                                   |~                                       
136     ¦   ¦   ¦   return;                                                                                                                           |~                                       
137     ¦   ¦   }

**Comment by BernardXiong** [comment]
请根据目前最新版本的master、lts-v3.1.x分支对比下看看。
