### ISSUE TITLE
case sensitive folder name in DFS/elmfat parition

### ISSUE THREAD

**Issue by grissiom** [RT-Thread/rt-thread#248]
Step to reproduce:
1. On RealBoard4088, create a "SD" folder and mount TF card to it.

```
msh /SD>ls /
Directory /:
bin                 <DIR>                    
resource            <DIR>                    
upgrade.rb4         478096                   
SD                  <DIR>                    
prog                <DIR>                    
```
1. reboot and `cd sd` in msh(note the lower case name).
2. `ls` will show an empty folder:

```
msh /sd>ls
Directory /sd:
```

However, the files in `SD/` is OK.

**Comment by Guozhanxin** [comment]
Isn't this a bug? FAT is indeed case insensitive
