### ISSUE TITLE
RTThread cmb组件中cmb_set_psp调用问题

### ISSUE THREAD

**Issue by yxcbreeze** [RT-Thread/rt-thread#2528]
在使用cm_backtrace V1.2.2版本时，会出现cmb_set_psp函数调用返回失败问题。示例为(__CC_ARM)中的代码。
原函数：
static __inline __asm void cmb_set_psp(uint32_t psp) {
        msr psp, r0
    }
这样调用之后，会出现函数不会返回，需要添加 bx lr返回；

修改之后代码：
static __inline __asm void cmb_set_psp(uint32_t psp) {
        msr psp, r0
        bx lr
    }

**Comment by armink** [comment]
欢迎提交 pr

**Comment by mysterywolf** [comment]
确认问题已经得到解决https://github.com/armink/CmBacktrace/blob/f1244876cd5aecdd371c3c535552ebb75b295ea7/demos/os/ucosii/stm32f10x/Libraries/CMSIS_RVMDK/CM3/CoreSupport/core_cm3.c#L280
