### ISSUE TITLE
#2511 的 pr 会导致 stm32 的 bsp 不能正常运行

### ISSUE THREAD

**Issue by Guozhanxin** [RT-Thread/rt-thread#2542]
#2511 的 pr 会导致 stm32 的 bsp 不能正常运行，平台 stm32-f411-nucleo。

![image](https://user-images.githubusercontent.com/25633294/55526636-676aa100-56c8-11e9-8c4b-2188fb300ce4.png)

**Comment by BernardXiong** [comment]
使用 #2541 更新代码后，再试试

**Comment by Guozhanxin** [comment]
没问题了
