### ISSUE TITLE
STM32F407内存使用情况 栈大小，为什么F407只有2W多，而F103有5W多？

### ISSUE THREAD

**Issue by zengwangfa** [RT-Thread/rt-thread#2547]
**STM32F4内存 使用情况**

![image](https://user-images.githubusercontent.com/40621296/55607444-c9053b00-57ae-11e9-86ad-60f713963c5b.png)

**STM32F1内存 使用情况**
![395P)%)2A A$6431UW$ZFCA](https://user-images.githubusercontent.com/40621296/55607501-efc37180-57ae-11e9-8caa-049cbbc4f479.png)

STM32F407内存大小，为什么F407只有2W多，而F103有5W多？

**Comment by BernardXiong** [comment]
22kB, 59kB?

这个是和你代码相关，静态变量用得多了，占用空间大了，总的堆空间自然少了。

**Comment by zengwangfa** [comment]
> 22kB, 59kB?
> 
> 这个是和你代码相关，静态变量用得多了，占用空间大了，总的堆空间自然少了。

嗯 好的谢谢。
