### ISSUE TITLE
Missing yfuns.h

### ISSUE THREAD

**Issue by dosadi** [RT-Thread/rt-thread#2579]
Hi,

In the latest pull (Monday April 15), the file:

yfuns.h

...is #included from:

src/rt-thread/components/libc/compilers/dlib/syscall_read.c

...and is missing from the repository.

**Comment by BernardXiong** [comment]
Please provide your IAR version information.

**Comment by dosadi** [comment]
What is IAR version information?  I couldn't find anything on a Google
search....

**Comment by BernardXiong** [comment]
It's IAR compiler.

These files under dlib folder, are the libc porting for IAR/libc.

**Comment by dosadi** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} Ok.  I use my own custom build system based on simple makefiles.                                                                                                                                                                        Sent via BlackBerry Hub+ Inbox for Android                                                                                                                                                                           From: notifications@github.comSent: April 18, 2019 11:40 AMTo: rt-thread@noreply.github.comReply-to: reply@reply.github.comCc: dosadi82@gmail.com; author@noreply.github.comSubject: Re: [RT-Thread/rt-thread] Missing yfuns.h (#2579)  It's IAR compiler.
These files under dlib folder, are the libc porting for IAR/libc.
