### ISSUE TITLE
建议规范代码的提交日志

### ISSUE THREAD

**Issue by Zero-Free** [RT-Thread/rt-thread#2583]
一些开发者在提交代码时，日志写的比较随意，也有一些跟描述不相干的修改，建议官方制定一些规范，提交也尽量使用英文，如：

- 描述尽量简洁，突出重点。让人一看知道做什么。
- 提交原子性，不要提交跟当前不相干的内容。
- 格式必须和团队保持统一。
- 增加前缀，如[bsp][components]

不规范的日志不仅影响代码review，也产生不严谨的错觉，如

![image](https://user-images.githubusercontent.com/17811346/56222357-75dc9380-609e-11e9-868a-588f23b9f763.png)

**Comment by BernardXiong** [comment]
@jhbdream 需要多多注意。

🦀 后续PR审核需要更严格才行

**Comment by XBurst** [comment]
很有必要，如果改动量比较大时最好按步骤分成多个commit，这样便于后来者追踪改动。

**Comment by a1012112796** [comment]
建议引入一个机器人，自动对issue和pr格式做审查，并自动添加标签。github好像有现成的。
