### ISSUE TITLE
[bsp][nordic]nordic如何提交新的SDK

### ISSUE THREAD

**Issue by sunshine0824** [RT-Thread/rt-thread#2618]
最近看了一下nordic的最新版本SDK，与目前rtt上面bsp下的sdk差异比较大，自己想更新一下，考虑到已经有人基于目前的bsp在开发自己的项目，如果直接提交的覆盖现有bsp不太合适。想重新添加又不知道如何入手。

**Comment by BernardXiong** [comment]
以软件包的方式提交吧，可以提交份新的BSP，这样对于整个发布包的体积也不会增加太多
