### ISSUE TITLE
mm32分支需要加入gcc编译功能，同时加入到ci持续集成中

### ISSUE THREAD

**Issue by BernardXiong** [RT-Thread/rt-thread#2639]
@ZhuGangfei 请在MM32相关分支中添加GCC编译功能支持：

* 添加GCC支持后，用户可以根据自身的需求来选择不同的工具链；GNU GCC工具链效率并不见得比Keil MDK/IAR差，同时不需要购买昂贵的Keil MDK/IAR软件；
* 添加GCC支持后，可以加入到travis-ci持续集成中，对应的每个PR都可以在MM32的BSP中得到编译方面的验证；

**Comment by ZhuGangfei** [comment]
Hi, Bernard Xiong,,

 

      感谢您对MM32的支持！

     我们会尽快在MM32相关分支中添加GCC编译功能。

   谢谢！

 

Best Regards

Gangfei zhu 朱刚飞

Field Application Engineer 现场应用工程师

Shanghai MindMotion Microelectronics Co., Ltd.

2/F, Building 10, 350 Niudun Road, Zhangjiang Hi-tech Park, Pudong New District, Shanghai, P.R.China

Office Phone: +86 21 2022 2002 ext. 814

Cell Phone: +86 18501746207

E-Mail: zhugangfei@mindmotion.com.cn <mailto:zhugangfei@mindmotion.com.cn> 

-- IMPORTANT NOTICE: The contents of this email and any attachments are confidential and may also be privileged. If you are not the intended recipient, please notify the sender immediately and do not disclose the contents to any other person, use it for any purpose, or store or copy the information in any medium. Thank you.

Shanghai MindMotion Microelectronics Co., Ltd.

 

 

发件人: Bernard Xiong <notifications@github.com> 
发送时间: 2019年4月30日 8:48
收件人: RT-Thread/rt-thread <rt-thread@noreply.github.com>
抄送: ZhuGangfei <zhugangfei@mindmotion.com.cn>; Mention <mention@noreply.github.com>
主题: [RT-Thread/rt-thread] mm32分支需要加入gcc编译功能，同时加入到ci持续集成中 (#2639)

 

@ZhuGangfei <https://github.com/ZhuGangfei>  请在MM32相关分支中添加GCC编译功能支持：

*	添加GCC支持后，用户可以根据自身的需求来选择不同的工具链；GNU GCC工具链效率并不见得比Keil MDK/IAR差，同时不需要购买昂贵的Keil MDK/IAR软件；
*	添加GCC支持后，可以加入到travis-ci持续集成中，对应的每个PR都可以在MM32的BSP中得到编译方面的验证；
