### ISSUE TITLE
rt_kprintf函数，格式化模板中存在冒号，无法打印

### ISSUE THREAD

**Issue by newflydd** [RT-Thread/rt-thread#2640]
如题，测试版本3.1.2nano（就是Keil内置包管理器下载的组件）
试过若干次了，各种平台都试过。
凡是rt_kprintf函数格式化模板中带有半角冒号`:`，就没法输出，比如：
```
rt_kprintf("event recved:%d\n", recved);
```
以上代码没法输出，但换成下面这句，就能正常输出：
```
rt_kprintf("event recved-%d\n", recved);
```
recved是一个u32变量。

==============补充=============
```
rt_kprintf("event recved:A%d", recved);
```
以上代码也无法正常输出。

```
rt_kprintf("event recved:ABC");
```
以上代码可以正常输出。

阅读rt_vsnprintf函数代码，似乎没有发现针对半角冒号':'的特殊逻辑块，求大神帮我理解一下。

**Comment by diverger** [comment]
%u试试

**Comment by newflydd** [comment]
sorry, The COM Helper Programe's problem.
对不起，是我使用的串口助手的问题，我用的是知乎上推荐的那个什么伏特加串口助手，what a fuck day.
