### ISSUE TITLE
New Kconfiglib GUI menuconfig

### ISSUE THREAD

**Issue by ulfalizer** [RT-Thread/rt-thread#2647]
Hello,

Just as an FYI, there's now a new GUI menuconfig interface for Kconfiglib.

See `guiconfig.py` in [this section of the README](https://github.com/ulfalizer/Kconfiglib#menuconfig-interfaces) for a screenshot.

Cheers,
Kconfiglib guy

**Comment by BernardXiong** [comment]
Thank you very much for your information. We are preparing an Eclipse Kconfig plugin for RT-Thread Studio IDE.

**Comment by ulfalizer** [comment]
No problem.

Tell me if you run into any issues or have any interface complaints.
