### ISSUE TITLE
[bsp][stm32f4xx-HAL][drivers][drv_rtc.c]

### ISSUE THREAD

**Issue by jnrg6** [RT-Thread/rt-thread#2683]
Uninitialized structure variables in function stm32_rtc_control.

In case RT_DEVICE_CTRL_RTC_GET_TIME:
now.tm_wday = sDate.WeekDay; is missing
*((time_t *)args) = mktime(&now); returns an invalid value.

In case RT_DEVICE_CTRL_RTC_SET_TIME:
sDate.WeekDay = now.tm_wday; is missing
The function HAL_RTC_SetDate(&hrtc, &sDate, RTC_FORMAT_BIN); gets ivalid date via &sDate.

**Comment by BernardXiong** [comment]
Thank you for your feed back. Could you please provide your BSP name?

**Comment by jnrg6** [comment]
stm32f4xx-HAL

**Comment by BernardXiong** [comment]
Please refer this URL:
https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drv_rtc.c

**Comment by jnrg6** [comment]
Ok, thank you.
