### ISSUE TITLE
宏定义 RT_NAME_MAX 定义不当会产生bug 建议添加处理机制

### ISSUE THREAD

**Issue by jhbdream** [RT-Thread/rt-thread#2716]
https://github.com/RT-Thread/rt-thread/blob/b013a4baa77ab4bf7dcde6c35817bd38223b8aa8/src/device.c#L130
在这里查找设备时比较的长度为 RT_NAME_MAX。
如果当宏定义 `RT_NAME_MAX =4` 比如定义的串口设备为 uart1 uart2 时，始终只会判断前四个字符。
假设我们调用函数 `rt_device_find("uart2")`,如果系统中同时存在 uart1 和 uart2 设备时 ，会返回uart1设备。导致无法找到正确的设备。

**Comment by BernardXiong** [comment]
这个是必然的，所以也可以通过list_device自行查看下，然后把NAME_MAX加大下

**Comment by jhbdream** [comment]
在准备换另一个串口作为控制台是发现了这个问题 
不知是否可以在程序中加一些判断处理 因为这样的问题需要多次调试才发现了原因
确实是按道理设备名称应该小于 RT_NAME_MAX 这个应该是用户负责
但是有一些设备的名称是官方驱动提供的  此时用户在为了裁剪代码修改此宏定义时 可能没有注意到这个问题
