### ISSUE TITLE
请问何时加入对德仪tms570系列的支持？

### ISSUE THREAD

**Issue by TaoistMo** [RT-Thread/rt-thread#2746]
发现BSP目录里只有一个tms320的bsp

**Comment by BernardXiong** [comment]
RT-Thread是一个开源，社区化的操作系统，所以也欢迎大家一起来完成。

tms320是由社区开发者 xuzuoyi 加入的，所以有能力、有条件的，可以尝试移植，并提交到github主干中来。移植过程中有什么问题，也可以到 [论坛](https://www.rt-thread.org/qa/portal.php) 中进行沟通，讨论。

**Comment by xuzhuoyi** [comment]
TMS570的CPU是Cortex-R4F的，RT-Thread已经有Cortex-R4的移植，只需要写一些外设的驱动就可以。可以参照bsp目录下rm48x50修改，这个和TMS570一样都属于TI Hercules MCU系列的

**Comment by romix5417** [comment]
> TMS570的CPU是Cortex-R4F的，RT-Thread已经有Cortex-R4的移植，只需要写一些外设的驱动就可以。可以参照bsp目录下rm48x50修改，这个和TMS570一样都属于TI Hercules MCU系列的

大佬，我在移植TMS570的时候遇到了一些问题，我是基于rm48x50的bsp移植的，libcpu里面才用cortex-R4，运行的时候如果不开启中断能够切换上下文进入app线程，电亮一次led，但是如果打开中断，直接就进入undef中断向量。
