### ISSUE TITLE
NRF52832的协议栈hex文件

### ISSUE THREAD

**Issue by Ghazigq** [RT-Thread/rt-thread#2748]
NRF52832的协议栈hex文件在哪里，我没有找到对应nRF5_SDK_13.0.0_04a0bfd的协议栈

**Comment by BernardXiong** [comment]
这个应该是在nRF的SDK里吧

**Comment by Ghazigq** [comment]
> 
> 
> 这个应该是在nRF的SDK里吧
没有找到

**Comment by Zero-Free** [comment]
> > 这个应该是在nRF的SDK里吧
> > 没有找到

可以去官网下载一个，hex文件被git脚本忽略了，没传上去
