### ISSUE TITLE
Bug in rt-thread/bsp/stm32/libraries/HAL_Drivers/drv_eth.c LN 482

### ISSUE THREAD

**Issue by jnrg6** [RT-Thread/rt-thread#2756]
LN 482 
SR = HAL_ETH_ReadPHYRegister(&EthHandle, PHY_Status_REG, (uint32_t *)&SR);

SR gets the return value from HAL_ETH_ReadPHYRegister, and not the PHY_Status_REG value.

**Comment by BernardXiong** [comment]
@SummerGGift Please check it.

**Comment by SummerGGift** [comment]
Thank you for your help，we are working to fix this issue.
