### ISSUE TITLE
STM32F407 是否支持 硬件i2c？

### ISSUE THREAD

**Issue by zengwangfa** [RT-Thread/rt-thread#2759]
STM32F407 是否支持 硬件i2c？

**Comment by zhangjun1996** [comment]
目前不支持的

**Comment by willianchanlovegithub** [comment]
目前stm32的BSP都是软件I2C，没有对硬件I2C做支持

**Comment by balanceTWK** [comment]
硬件 I2C 的实现可以参考一下这个。 [drv_i2c.zip](https://github.com/RT-Thread/rt-thread/files/3275547/drv_i2c.zip)

PS：这个驱动可能有坑。

**Comment by zengwangfa** [comment]
> 硬件 I2C 的实现可以参考一下这个。 [drv_i2c.zip](https://github.com/RT-Thread/rt-thread/files/3275547/drv_i2c.zip)
> 
> PS：这个驱动可能有坑。

好的谢谢
