### ISSUE TITLE
rtt 4.x的smp机制是否已经完善？

### ISSUE THREAD

**Issue by 13824125580** [RT-Thread/rt-thread#2773]
看到smp目前的内核已经添加了SMP支持宏，但细读了ipc部分的代码有些疑惑，感觉在smp情况下会有问题。
比如 rt_mutex_take的实现
 653 rt_err_t rt_mutex_take(rt_mutex_t mutex, rt_int32_t time)                                                                                        
 654 {                                                                                                                                                
 655     register rt_base_t temp;                                                                                                                     
 656     struct rt_thread *thread;                                                                                                                    
 657                                                                                                                                                  
 658     /* this function must not be used in interrupt even if time = 0 */                                                                           
 659     RT_DEBUG_IN_THREAD_CONTEXT;                                                                                                                  
 660                                                                                                                                                  
 661     /* parameter check */                                                                                                                        
 662     RT_ASSERT(mutex != RT_NULL);                                                                                                                 
 663     RT_ASSERT(rt_object_get_type(&mutex->parent.parent) == RT_Object_Class_Mutex);                                                               
 664                                                                                                                                                  
 665     /* get current thread */                                                                                                                                                              
 666     thread = rt_thread_self();
 667                                                               
 668     /* disable interrupt */
 669     temp = rt_hw_interrupt_disable();

669行的 rt_hw_interrupt_disable实现，在cortex-a目录下依然是关闭本地cpu中断处理，而不是全局中断，这种情况下:
1.只关闭本身处理器的中段而不关闭其它处理器中断处理，会不会导致当前处理器上的任务和其它核心上的中断处理出现竞争？
２．如果有一个驱动包含两个线程，task1, task2,分别在两个core上跑，core1,core2.　如果core1的线程和core2的线程同时操作同属这个驱动的一个mutex，按照目前的流程，rt_mutex_take内部的临界区是可以并行执行的（因为关闭core1或者core2的中断并不影响另一个核的任务抢占，仍然可以执行另一个task并且执行到rt_interrupt_disable后面，操作同一个共享资源).rt_mutex_take又属于一级函数，不能依赖外部操作保证互斥。
根据之前的一些了解，　linux内核内有关闭全局中断的接口来保证这种情况的安全，,不知道rtt是如何保证上面场景的互斥的？　rtt的smp的smp会制定一些强制规则要求驱动和应用开发者去follow吗？

**Comment by BernardXiong** [comment]
SMP是一个相对复杂的，并且在RT-Thread这边也是相对新的特性。这部分依然是在推进过程中，包括BSP底层的接口规范，整体的执行效率等等。

前期阶段，建议联系我们核心团队来共同往前推进。

**Comment by 13824125580** [comment]
thank you.
