### ISSUE TITLE
nRF2832的SDK版本

### ISSUE THREAD

**Issue by Ghazigq** [RT-Thread/rt-thread#2806]
SDK版本什么时候能换成最新的15.3.0版本呀

**Comment by BernardXiong** [comment]
欢迎提交更新版本的PR

**Comment by Afantor** [comment]
SDK版本要更新到15.3.0的话是不是对nRF52832的移植有很大的修改？我发现15.0.0版本以后SDK发生了很多改动，我现在也想做这个SDK的升级移植

**Comment by Ghazigq** [comment]
> SDK版本要更新到15.3.0的话是不是对nRF52832的移植有很大的修改？我发现15.0.0版本以后SDK发生了很多改动，我现在也想做这个SDK的升级移植

比较麻烦的 ，文件都要重新添加

**Comment by BernardXiong** [comment]
> SDK版本要更新到15.3.0的话是不是对nRF52832的移植有很大的修改？我发现15.0.0版本以后SDK发生了很多改动，我现在也想做这个SDK的升级移植

可以根据原来的情况来调整下SConscript文件，熟悉nRF的会相对容易
