### ISSUE TITLE
我在stm32h743这个工程中，只要用env打开编译一下，在没有改任何设置的情况下，编译完成之后，下载到开发板都会出现，没有办法下载进去到芯片

### ISSUE THREAD

**Issue by yizhitiantian** [RT-Thread/rt-thread#2810]
我在stm32h743这个工程中，只要用env打开编译一下，在没有改任何设置的情况下，编译完成之后，下载到开发板都会出现，没有办法下载进去到芯片
Load "D:\\download\\Newton\\newton\\Newton0.05\\bsp\\stm32\\stm32h743-atk-apollo\\build\\keil\\Obj\\rt-thread.axf" 
No Algorithm found for: 08000000H - 0800DAB7H
Erase skipped!
Error: Flash Download failed  -  "Cortex-M7"
Flash Load finished at 09:27:25

**Comment by zhangjun1996** [comment]
这个问题可以关闭了，[楼主在论坛回帖已经解决了](https://www.rt-thread.org/qa/thread-11880-1-1.html)
