### ISSUE TITLE
中文帖可以发到Gitee或RT-Thread中文论坛。Here you can place issue in English.

### ISSUE THREAD

**Issue by BernardXiong** [RT-Thread/rt-thread#2817]
中文贴可以发到[gitee](https://gitee.com/rtthread/rt-thread/issues)或[官网论坛](https://www.rt-thread.org/qa/portal.php)

It's better to submit issue in English here.

**Comment by ZeroLeo-GitHub** [comment]
你对中文也许应该更自信点。 @BernardXiong
