### ISSUE TITLE
K210 compile error: undefined reference to `current_coreid'

### ISSUE THREAD

**Issue by wuhanstudio** [RT-Thread/rt-thread#2824]
K210 编译会发现找不到 current_coreid 的定义，而这个定义在 encoding.h 里面第212-214行有：

`bsp\k210\packages\kendryte-sdk-v0.5.5\kendryte-standalone-sdk\lib\bsp\include\encoding.h`

但是 bsp\k210\driver 下面的 encoding.h  没有相应的定义。

把 SDK 里 encoding.h 的 current_coreid 定义复制到 bsp\k210\driver\encoding.h 就可以了，是不是 kendryte-standalone-sdk 更新了，但是 bsp 没有更新？

**Comment by BernardXiong** [comment]
@lymzzyh please check it.

**Comment by wuhanstudio** [comment]
回来对着板子又试了一下，又正常了，可能是公司 bsp 更新后旧的文件没有删除 ;)
