### ISSUE TITLE
希望AT Device少一点BUG

### ISSUE THREAD

**Issue by bevis-wong** [RT-Thread/rt-thread#2832]
1.6版本说删除了at_ping等指令，其实还有很多款模块都还是可以用，标准ping指令还有一些模块用不了报错，还有一些网络指令也是用不了。希望2.0能注意品控

**Comment by Guozhanxin** [comment]
- 对于AT netdev 来说，ping命令底层调用的其实也是at_ping命令，
- 有bug的话，是指什么bug呢？

**Comment by bevis-wong** [comment]
希望可以重视
https://www.rt-thread.org/qa/forum.php?mod=viewthread&tid=11931&page=1#pid51047






------------------
Tel: 16620801134
Email: bevis@uliansz.com
Company: 深圳市优联物联网有限公司
Add: 深圳市南山区海天一路软件产业基地5栋B座303室

 
正在努力加载...






 
 
 
------------------ Original ------------------

**Comment by Lawlieta** [comment]
ping 功能最终调用的是 at_device 中的实现，如果你模块支持就实现，如果不支持可以留空，并不影响

**Comment by Lawlieta** [comment]
已经说了sim7600 开发者还没来得及同步，sim7600 问题处理已经在计划内，近期会修复，请耐心等待

**Comment by armink** [comment]
如果 sim7600 的维护者还没时间维护这个设备，干脆删除对应配置好了，免得大家选上了，只是个半成品，大家好抱怨多
