### ISSUE TITLE
There are two warnings  when compiling a rt-thread c++ project with armcc:

### ISSUE THREAD

**Issue by alexyuoouy** [RT-Thread/rt-thread#2834]
Dear madam/sir,

I want to build a c/c++ mixed project on STM32, I checked the ”Support C++ features” using the ENV tool, and added “RT_USING_LIBC” to the rtconfig.h.

![support_cpp](https://user-images.githubusercontent.com/26848154/60698746-70674a80-9f23-11e9-9267-957c669e5d08.png)

 I changed main.c to main.cpp. Its contents are as follows：

```
#include <rtthread.h>
#include "Semaphore.h"
using namespace rtthread;
int main(void)
{
     /* user app entry */
    Semaphore semaphore;
    return 0;
}
```

Then I use armcc to compile the project via scons : No errors or Warnings in the compilation process.

![捕获4](https://user-images.githubusercontent.com/26848154/60698637-eb7c3100-9f22-11e9-94f6-284a83ade881.PNG)

Warning occurs in the link process : 

![捕获1](https://user-images.githubusercontent.com/26848154/60698701-431a9c80-9f23-11e9-9224-53c0a9940792.PNG)

This is my scatter file:

```
LR_IROM1 0x08000000 0x00040000  {    ; load region size_region
  ER_IROM1 0x08000000 0x00040000  {  ; load address = execution address
   *.o (RESET, +First)
   *(InRoot$$Sections)
   .ANY (+RO)
   .ANY (+XO)
  }
  RW_IRAM1 0x20000000 0x0000C000  {  ; RW data
   .ANY (+RW +ZI)
  }
}
```

Then I found this in the ARM official documentation:

![捕获](https://user-images.githubusercontent.com/26848154/60698892-2468d580-9f24-11e9-9e7f-dfa8b0ffa9b3.PNG)

I don't know how to change this file : I added two lines in the file.

```
LR_IROM1 0x08000000 0x00040000  {    ; load region size_region
  ER_IROM1 0x08000000 0x00040000  {  ; load address = execution address
   init_aeabi.o(+RO)
   * (.init_array)
   *.o (RESET, +First)
   *(InRoot$$Sections)
   .ANY (+RO)
   .ANY (+XO)
  }
  RW_IRAM1 0x20000000 0x0000C000  {  ; RW data
   .ANY (+RW +ZI)
  }
}
```

And Two more warnings now appear : 

![捕获3](https://user-images.githubusercontent.com/26848154/60699153-4e6ec780-9f25-11e9-9f62-cdc2f5f159dc.PNG)
  
What should I do to eliminate these two warnings and call the constructor correctly when stm32 starts?

Thanks in advance for your help.

Kind regards,

WangYu

**Comment by BernardXiong** [comment]
Yes, its related with object construction. You can take a try with adding a global static object.

**Comment by alexyuoouy** [comment]
Thank you very much. It works.

**Comment by Yoke365** [comment]
> Dear madam/sir,
> 
> I want to build a c/c++ mixed project on STM32, I checked the ”Support C++ features” using the ENV tool, and added “RT_USING_LIBC” to the rtconfig.h.
> 
> ![support_cpp](https://user-images.githubusercontent.com/26848154/60698746-70674a80-9f23-11e9-9267-957c669e5d08.png)
> 
> I changed main.c to main.cpp. Its contents are as follows：
> 
> ```
> #include <rtthread.h>
> #include "Semaphore.h"
> using namespace rtthread;
> int main(void)
> {
>      /* user app entry */
>     Semaphore semaphore;
>     return 0;
> }
> ```
> 
> Then I use armcc to compile the project via scons : No errors or Warnings in the compilation process.
> 
> ![捕获4](https://user-images.githubusercontent.com/26848154/60698637-eb7c3100-9f22-11e9-94f6-284a83ade881.PNG)
> 
> Warning occurs in the link process :
> 
> ![捕获1](https://user-images.githubusercontent.com/26848154/60698701-431a9c80-9f23-11e9-9224-53c0a9940792.PNG)
> 
> This is my scatter file:
> 
> ```
> LR_IROM1 0x08000000 0x00040000  {    ; load region size_region
>   ER_IROM1 0x08000000 0x00040000  {  ; load address = execution address
>    *.o (RESET, +First)
>    *(InRoot$$Sections)
>    .ANY (+RO)
>    .ANY (+XO)
>   }
>   RW_IRAM1 0x20000000 0x0000C000  {  ; RW data
>    .ANY (+RW +ZI)
>   }
> }
> ```
> 
> Then I found this in the ARM official documentation:
> 
> ![捕获](https://user-images.githubusercontent.com/26848154/60698892-2468d580-9f24-11e9-9e7f-dfa8b0ffa9b3.PNG)
> 
> I don't know how to change this file : I added two lines in the file.
> 
> ```
> LR_IROM1 0x08000000 0x00040000  {    ; load region size_region
>   ER_IROM1 0x08000000 0x00040000  {  ; load address = execution address
>    init_aeabi.o(+RO)
>    * (.init_array)
>    *.o (RESET, +First)
>    *(InRoot$$Sections)
>    .ANY (+RO)
>    .ANY (+XO)
>   }
>   RW_IRAM1 0x20000000 0x0000C000  {  ; RW data
>    .ANY (+RW +ZI)
>   }
> }
> ```
> 
> And Two more warnings now appear :
> 
> ![捕获3](https://user-images.githubusercontent.com/26848154/60699153-4e6ec780-9f25-11e9-9f62-cdc2f5f159dc.PNG)
> 
> What should I do to eliminate these two warnings and call the constructor correctly when stm32 starts?
> 
> Thanks in advance for your help.
> 
> Kind regards,
> 
> WangYu

请问警告怎么消除的
