### ISSUE TITLE
About The Hardware I2C

### ISSUE THREAD

**Issue by arikadogenya** [RT-Thread/rt-thread#2839]
Is it possible to add the Hardware I2C to the RTT？ Or do you have the plan to make it？
Thank you！

**Comment by BernardXiong** [comment]
Hi, 
Which IC do you use? It's OK for hardware I2C driver in RT-Thread.

**Comment by arikadogenya** [comment]
@BernardXiong, I am sorry that i forgot to refer to the IC.
That is STM32F4xx, there used to be something wrong with the hardware I2C CubeMx HAL driver, however I think ST have already fixed it and I tried it several times in CubeMX.

**Comment by BernardXiong** [comment]
There is some hardware issues in I2C peripheral. You can validate them. If this issue was fixed in new chip-set, you can submit a new I2C driver with hardware peripheral.

**Comment by arikadogenya** [comment]
Thank you.
