### ISSUE TITLE
rndis有内存泄漏可能

### ISSUE THREAD

**Issue by cris8259** [RT-Thread/rt-thread#2856]
rndis长时间运行后，没有内存了
<7>June  2 01:17:21 RNDIS usbd: REMOTE_NDIS_KEEPALIVE_MSG
<7>June  2 01:17:24 RNDIS usbd: REMOTE_NDIS_KEEPALIVE_MSG
<7>June  2 01:17:26 RNDIS usbd: REMOTE_NDIS_KEEPALIVE_MSG
<7>June  2 01:17:29 RNDIS usbd: REMOTE_NDIS_KEEPALIVE_MSG
<3>June  2 01:17:29 RNDIS usbd: _rndis_keepalive_response,675: no memory!
<7>June  2 01:17:31 RNDIS usbd: REMOTE_NDIS_KEEPALIVE_MSG
<3>June  2 01:17:31 RNDIS usbd: _rndis_keepalive_response,675: no memory!
<7>June  2 01:17:34 RNDIS usbd: REMOTE_NDIS_KEEPALIVE_MSG

total memory: 68584
used memory : 68600
maximum allocated memory: 68600

内存全部占用，重新插拔usb，response list释放内存恢复正常
<6>June  2 03:26:17 RNDIS usbd: plugged out
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<7>June  2 03:26:17 RNDIS usbd: remove resp chain list!
<6>June  2 03:26:22 RNDIS usbd: plugged in
<7>June  2 03:26:22 RNDIS usbd: REMOTE_NDIS_INITIALIZE_MSG
<7>June  2 03:26:22 RNDIS usbd: REMOTE_NDIS_QUERY_MSG
<7>June  2 03:26:22 RNDIS usbd: REMOTE_NDIS_QUERY_MSG
<7>June  2 03:26:22 RNDIS usbd: REMOTE_NDIS_QUERY_MSG
<7>June  2 03:26:22 RNDIS usbd: REMOTE_NDIS_QUERY_MSG
<7>June  2 03:26:22 RNDIS usbd: REMOTE_NDIS_QUERY_MSG
<7>June  2 03:26:22 RNDIS usbd: REMOTE_NDIS_QUERY_MSG
<7>June  2 03:26:22 RNDIS usbd: REMOTE_NDIS_QUERY_MSG
<7>June  2 03:26:22 RNDIS usbd: REMOTE_NDIS_QUERY_MSG
<7>June  2 03:26:22 RNDIS usbd: REMOTE_NDIS_SET_MSG
<7>June  2 03:26:22 RNDIS usbd: OID_GEN_CURRENT_PACKET_FILTER
<7>June  2 03:26:22 RNDIS usbd: REMOTE_NDIS_SET_MSG
<7>June  2 03:26:22 RNDIS usbd: REMOTE_NDIS_SET_MSG
<7>June  2 03:26:22 RNDIS usbd: OID_GEN_CURRENT_PACKET_FILTER
<7>June  2 03:26:22 RNDIS usbd: REMOTE_NDIS_SET_MSG
<7>June  2 03:26:22 RNDIS usbd: OID_GEN_CURRENT_PACKET_FILTER
<7>June  2 03:26:23 RNDIS usbd: REMOTE_NDIS_QUERY_MSG

total memory: 68584
used memory : 57424
maximum allocated memory: 68600

**Comment by BernardXiong** [comment]
可以打开memtrace，尝试跟踪修复这个问题。
