### ISSUE TITLE
imxrt1052 add openmv libs,build error in keil uv5.

### ISSUE THREAD

**Issue by Afantor** [RT-Thread/rt-thread#2912]
我在menuconfig上增加microPython和openmv的支持，都是选择最新版本，然后使用Keil uv5编译，编译出现71个错误和134个警告：
`Warning: C3910W: Old syntax, please use '-I'.
Error: C4065E: type of input file 'port/mpy_project_cfg.h' unknown`
如果只增加microPython库，编译时没有问题的
当前是openmv版本与microPython不兼容吗？

**Comment by BernardXiong** [comment]
目前主要维护micropython，openmv上没太多精力顾及吧。

**Comment by QinZihang2136** [comment]
我遇到了相同的问题，请问你解决了吗？
i meet the same problem，do you have finished it？thanks.

**Comment by mysterywolf** [comment]
请到openmv软件包提issue
