### ISSUE TITLE
7.31更新后的RTT,移植lwip到f103上面初始化时产生断言

### ISSUE THREAD

**Issue by jianggogogo** [RT-Thread/rt-thread#2913]
这是出现的警告。：(tid != RT_NULL) assertion failed at function:rt_application_init, line number:199

这是我用7.15之前的版本产生的结果： lwIP-2.0.2 initialized!

代码是一样的。

想知道7.15到7.30之间是否修改了LWIP协议栈的初始化过程？
或者有没有同志遇到了相同的问题？

**Comment by BernardXiong** [comment]
请给出具体的BSP，另外，这个assert很类似没内存了，线程创建不出来。

**Comment by jianggogogo** [comment]
是的，我用的stm32F103NONO的BSP做的F103RC系列的BSP，然后今天在调试中发现RC的48k内存似乎是不足以支持LWIP，我采用ZE系列的板子之后，lWIP和UDP初始化成功。所以我猜想LWIP需要大概64k的内存才能够初始化？能给一点参考吗？谢谢

**Comment by BernardXiong** [comment]
小内存也可以用起来，不过这样就需要做裁剪、优化了，不是那么一两句话说得清楚。在可能的情况下，还是建议用资源足够的芯片
