### ISSUE TITLE
程序运行时，出现 “to free a bad data block”是什么问题？

### ISSUE THREAD

**Issue by as564335sa** [RT-Thread/rt-thread#2917]
你好，
我用STM32F103C8T6，使用动态内存方式，现在程序运行时，打开console，偶尔串口输出这个提示：
“to free a bad data block:
mem: 0x20003920, used flag: 0, magic code: 0x1ea0”

看了下是rt_free的问题，请问什么情况下会出现这个问题？

**Comment by gengyiping** [comment]
> 你好，
> 我用STM32F103C8T6，使用动态内存方式，现在程序运行时，打开console，偶尔串口输出这个提示：
> “to free a bad data block:
> mem: 0x20003920, used flag: 0, magic code: 0x1ea0”
> 
> 看了下是rt_free的问题，请问什么情况下会出现这个问题？

你好，这个问题是怎么解决的？
