### ISSUE TITLE
Suggestions of building the Kconfig

### ISSUE THREAD

**Issue by Tonny-Y** [RT-Thread/rt-thread#2924]
Since there is no better way to let green hands to fully understand the meaning and the function of every macro definition temporarily, such as SBP_USING_GPIO, and we surely have limited modules and equipments even though RTT has adapted so many ones, why can't we enumerate all the macro combinations so that what the green hands need to do is to confirm what is the module used and to copy the right macro combinations.

**Comment by BernardXiong** [comment]
It's surely there are many options and they also grew rapidly over time.
