### ISSUE TITLE
scons --menuconfig  in  bsp/imxrt

### ISSUE THREAD

**Issue by youngday** [RT-Thread/rt-thread#2941]
in /bsp/imxrt/imxrt1052-atk-commander
run `scons --menuconfig`  
error ../Libraries/Kconfig not find.
issues change Libraies to libraries in /rt-thread/bsp/imxrt

**Comment by yqiu2018** [comment]
@tyustli please look at it.

**Comment by tyustli** [comment]
env no this command : `scons --menuconfig`
1.if your platform is gcc:you can use command:`scons`
2.if your platform is mdk:you can use command`scons --target=mdk5`
2.if your platform is iar:you can use command:`scons --target=iar`

**Comment by youngday** [comment]
env in ubuntu 

in /bsp/imxrt/imxrt1052-atk-commander
run scons --menuconfig

Libraries  need changed in to libraries

**Comment by tyustli** [comment]
> in /bsp/imxrt/imxrt1052-atk-commander
> run `scons --menuconfig`
> error ../Libraries/Kconfig not find.
> issues change Libraies to libraries in /rt-thread/bsp/imxrt

when your system is linux, L and l is distinguish,to solve this error you can change L to l.
this pull request will fix this
[https://github.com/RT-Thread/rt-thread/pull/2945](url)

**Comment by youngday** [comment]
Thank you!
