### ISSUE TITLE
Compile Error: Missing file "stm32f1xx_hal_exti.h" generated by CubeMX HAL v1.8.0

### ISSUE THREAD

**Issue by wuhanstudio** [RT-Thread/rt-thread#2955]
![image](https://user-images.githubusercontent.com/15157070/63075353-fbe0ec00-bf63-11e9-8ccf-5ee141659d0b.png)

CubeMX with HAL v1.8.0 will generate a new header file "stm32f1xx_hal_exti.h" which is not included in rt-thread, thus causing compile error,

Add this new file will solve this issue.

---------------------------
(看到置顶的 issue 说明于是改成了双语版 ....)

新的 CubeMX 使用 v1.8.0 的 HAL 库会生成 stm32f1xx_hal_exti.h 文件，但是在 rt-thread 
 的 \bsp\stm32\libraries 里没有这个头文件，编译会直接报错。

如果手动复制过去就可以了，是不是需要在 rt-thread 仓库里添加这个文件呢？

**Comment by BernardXiong** [comment]
We need to update the HAL library.
