### ISSUE TITLE
[K210] UART issue with SMP

### ISSUE THREAD

**Issue by sai-fpp** [RT-Thread/rt-thread#2969]
K210 BSP下使能SMP、AT ESP8266串口中断接收和轮训发送，经常发现会让wifi模组进入待收数据的状态，分析得知没能正确收到“>”回复；把SMP功能关掉后，就能正常接收。因此怀疑是否是SMP调度影响到了串口中断接收？

**Comment by BernardXiong** [comment]
有更多的一些log吗？

**Comment by sai-fpp** [comment]
> 有更多的一些log吗？

需要哪些log？分析此问题的时候增加了一些，发现通讯异常的时候，进入at client 敲at指令，esp8266模组不响应，必须重新上电，试着修改波特率，发现115200的要比921600的稳定一些

**Comment by BernardXiong** [comment]
921600，这么高的波特率本身就需要对驱动做更细致的设计、实现了。当使用115200，是否基本上就没问题了？

**Comment by sai-fpp** [comment]
115200基本上可以，高的波特率下那驱动更细致化的设计，从哪些方面考虑呢？

**Comment by jesven** [comment]
不知能否给个简化的项目代码我们这边复现一下，以便能迅速定位问题
