### ISSUE TITLE
cJSON.c

### ISSUE THREAD

**Issue by Tonny-Y** [RT-Thread/rt-thread#2970]
char *cJSON_PrintBuffered函数里面连续的两个return语句，有问题。

**Comment by balanceTWK** [comment]
cJSON 软件包是 rt-thread 移植的一个软件包。

楼主可以到下面链接里提 issues ，提 PR。

https://github.com/RT-Thread-packages/cJSON

**Comment by balanceTWK** [comment]
看了下，cJSON_PrintBuffered 好像是有问题。

楼主可以参考 https://gitee.com/jialelu/cJSON/blob/master/cJSON.c 里 cJSON_PrintBuffered 的实现。
