### ISSUE TITLE
Bug: Could not find the off_t in dfs component.

### ISSUE THREAD

**Issue by Linjieqiang** [RT-Thread/rt-thread#2974]
![image](https://user-images.githubusercontent.com/10217966/63325332-7a6ecc80-c35c-11e9-9a1d-d04cc24e3669.png)

**Comment by Linjieqiang** [comment]
![image](https://user-images.githubusercontent.com/10217966/63325459-bb66e100-c35c-11e9-941a-74d6b8d2aacc.png)
在Keil或者IAR这类的IDE中，倒是有这样的宏定义。但是对于Segger的Embedded Studio 貌似缺少了这个类型的数据定义

**Comment by BernardXiong** [comment]
不建议使用Segger Embedded Studio。它是自己独立的一套libc，会有很多兼容性问题

**Comment by Linjieqiang** [comment]
@BernardXiong 嗯嗯 我也发现了这个问题 基本上和rt-thread的网络组件与虚拟文件组件格格不入 无法移植过去 但是SES的编译速度和调试速度很快 

熊大 有无一些解决方案？

**Comment by BernardXiong** [comment]
关闭掉LIBC的功能，其他目前还没有好的办法
