### ISSUE TITLE
jffs2 bug

### ISSUE THREAD

**Issue by feiliuzhixia1000m** [RT-Thread/rt-thread#2976]
In components/dfs/filesystems/jffs2/include/port/sys/stat.h 
the first 9 lines:
#ifndef CYGONCE_ISO_SYS_TYPES_H
#define CYGONCE_ISO_SYS_TYPES_H
/*========================================================================
//
//      sys/types.h
//
//      POSIX types
//
//========================================================================

is from the types.h ， the first 2 lines may conflict with types.h
Or there is a porting trick?

thank you

**Comment by BernardXiong** [comment]
This component will be removed later, because littlefs is a better choice.
