### ISSUE TITLE
stm32f107在开启增加Enable libc APIs from toolchain,编译错误

### ISSUE THREAD

**Issue by tuopu** [RT-Thread/rt-thread#2992]
stm32f107在开启增加Enable libc APIs from toolchain 定义后，time.c文件IAR编译时有__localtime32定义冲突。

**Comment by BernardXiong** [comment]
是最近的版本吗？

**Comment by zhangjun1996** [comment]
iar是哪个版本? @tuopu

**Comment by tuopu** [comment]
都是最新的，操作系统是23号下载的。


------------------ 原始邮件 ------------------
发件人: "_--___"<notifications@github.com>;
发送时间: 2019年8月24日(星期六) 上午9:44
收件人: "RT-Thread/rt-thread"<rt-thread@noreply.github.com>;
抄送: "冷月无声"<68061664@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [RT-Thread/rt-thread] stm32f107在开启增加Enable libc APIs from toolchain,编译错误 (#2992)




iar是哪个版本? @tuopu

**Comment by zhangjun1996** [comment]
IAR是哪个版本呢?7.3版本的iar测试没有问题的

**Comment by tuopu** [comment]
8.10版本以上，对数据定义有了变化，所以有些不兼容了。

**Comment by zhangjun1996** [comment]
@tuopu 修过了，你下载最新的系统试试看看

**Comment by tuopu** [comment]
没有问题了。
