### ISSUE TITLE
修改mdk配置中的芯片类型，pin管脚编号不会改变

### ISSUE THREAD

**Issue by zhjc2014** [RT-Thread/rt-thread#2994]
在device中配置芯片类型stm32f103zf->stm32f103ve，管脚数量应该从144变为100，但是程序实际还是按照144的配置去初始化管脚。需要显式地在c/c++中配置宏定义STM32F103VE才能使得管脚数量变为100

**Comment by BernardXiong** [comment]
那是呀，mdk中重选设备，宏定义并不会跟着变
