### ISSUE TITLE
Scons compiled with keil5 to generate bin problem?

### ISSUE THREAD

**Issue by liliangego** [RT-Thread/rt-thread#3007]
![图片](https://user-images.githubusercontent.com/20839391/63682039-9e815080-c829-11e9-8f7c-531da7b4f3ee.png)

POST_ACTION = 'fromelf --bin $TARGET --output SGW_STD.bin \nfromelf -z $TARGET'

Only the project project is generated, can't generate bin file?

**Comment by BernardXiong** [comment]
Do you use `scons --target=xxx`? It only generates a project or other target. It does not compile anything.
