### ISSUE TITLE
scons 编译额外库 Fatal error: L3900U:

### ISSUE THREAD

**Issue by liliangego** [RT-Thread/rt-thread#3014]
添加库如下：
![图片](https://user-images.githubusercontent.com/20839391/63757095-1c0d9500-c8ec-11e9-805f-7c5ce6c26083.png)

lib库(keil_lib_power_cm33_core0.lib)放在目录：libraries\LPCXpresso55S69\devices\LPC55S69\arm\libs

用scons编译是报错：
Fatal error: L3900U: Unrecognized option '-Llibraries\LPCXpresso55S69\devices\LPC55S69\arm\libs'.

![图片](https://user-images.githubusercontent.com/20839391/63757183-39dafa00-c8ec-11e9-800a-1133177a1826.png)

**Comment by BernardXiong** [comment]
Keil支持得可能有些问题，Keil的模式应该不是`-L`参数

**Comment by liliangego** [comment]
> 
> 
> Keil支持得可能有些问题，Keil的模式应该不是`-L`参数

我看到building.py中使用的 armcc，我用的是armclang，这里需要适配下？

**Comment by liliangego** [comment]
> 
> 
> Keil支持得可能有些问题，Keil的模式应该不是`-L`参数

在building.py中适配了armclang后，这步可以通过了，
![图片](https://user-images.githubusercontent.com/20839391/63818594-43a84000-c974-11e9-850c-57fbca2cfb76.png)
但是有报错了？
Error: L6242E: Cannot link object fsl_power_lib.o as its attributes are incompatible with the image attributes.

在生产的KEIL工程中编译能通过呀？？？

**Comment by liliangego** [comment]
> 
> 
> > Keil支持得可能有些问题，Keil的模式应该不是`-L`参数
> 
> 在building.py中适配了armclang后，这步可以通过了，
> ![图片](https://user-images.githubusercontent.com/20839391/63818594-43a84000-c974-11e9-850c-57fbca2cfb76.png)
> 但是有报错了？
> Error: L6242E: Cannot link object fsl_power_lib.o as its attributes are incompatible with the image attributes.
> 
> 在生产的KEIL工程中编译能通过呀？？？

![图片](https://user-images.githubusercontent.com/20839391/63820059-748b7380-c97a-11e9-8c45-ea99ff2d5bb8.png)
应该是这个原因引起的。
