### ISSUE TITLE
目前LWIP已经更新到2.1.2，并说明2.1.0用户强烈建议更新到新版本

### ISSUE THREAD

**Issue by tuopu** [RT-Thread/rt-thread#3017]
目前LWIP已经更新到2.1.2，并说明2.1.0用户强烈建议更新到新版本，RT有计划更新版本吗？

**Comment by BernardXiong** [comment]
有。只是RTT对lwIP已经进行了一些更改，调整了，更新到2.1.2需要一定时间，后续可以做起来

**Comment by tuopu** [comment]
我用2.1.2直接替代了2.1.0，把你们增加的文件也放到2.1.2里了，会不会有问题啊这么更新。编译没问题了，功能还没看。

**Comment by armink** [comment]
不能直接替换的，一些细节上要做些定制化修改，晚些时候我们来同步吧

**Comment by tuopu** [comment]
有计划吗，预计什么时间。

**Comment by tuopu** [comment]
能否在升级时顺便写一下变更了那些内容。

**Comment by murphyzhao** [comment]
@tuopu 我提了个 PR  #3026 更新了 lwip 到 2.1.2 版本，在 407 上测试通过，如果你在用，可以尝试下，谢谢。

**Comment by wendal** [comment]
那2.0.2需要更新吗?
