### ISSUE TITLE
LPC176x bsp配置RT_USING_SPI选项，scons编译提示rt_error_t、RT_EOK等无定义

### ISSUE THREAD

**Issue by hotfire123** [RT-Thread/rt-thread#3020]
目前我的开发环境：
操作系统：**lubuntu 16.04**
编译器：**arm-none-eabi-gcc 7.2.1**
编辑器：**vs code**
代码版本：**3.1.3**
在配置选项中开启**RT_USING_SPI**，在编译`rt-thread/components/drivers/spi/spi_core.c`文件时，提示`rt_error_t`、`RT_EOK`等未定义。通过跟踪头文件，`spi_core.c` 包含头文件`<drivers/spi.h>`，而在整个项目文件中，有两个重名的头文件，一个文件位于`rt-thread/bsp/lpc176x/drivers`，另一个文件位于`rt_thread/components/drivers/include/drivers`中，这两个文件冲突导致`spi_core.c`不能找到正确头文件`rtdef.h`，出现上述错误。通过修改`rt-thread/bsp/lpc176x/drivers`文件夹下的文件名称和头文件定义，能够编译通过。目前还不清楚能否可通过scons脚本来解决这个问题

**Comment by BernardXiong** [comment]
是的，需要改名来解决这个问题。

lpc176x有些年头了，没怎么跟上目前的更新。欢迎在处理好后，反馈回RTT社区
