### ISSUE TITLE
最新clone的版本PWM不能使用

### ISSUE THREAD

**Issue by shao7936626** [RT-Thread/rt-thread#3021]
使用STM32F103RET6和STM32F103RFT6都测试了一下，用了5月份的版本是可以的，但是最新的不行。

**Comment by BernardXiong** [comment]
有更具体的信息吗？或什么log

BSP具体是哪个？bsp/stm32目录下的一个？

**Comment by ranbochen** [comment]
驱动没有问题，需要把CUBE的TIM配置成使用Internel Clock才能对应上PWM驱动的代码
否则TIMER不会起振
