### ISSUE TITLE
希望增加对CMake的支持，以支持Clion开发

### ISSUE THREAD

**Issue by zhaojh329** [RT-Thread/rt-thread#3069]
Clion的代码提示真的是太强大了。

**Comment by ziyouchutuwenwu** [comment]
特意去看了下，clion貌似没有scons的插件，之前就很期望有支持cmakefile的版本，clion支持cmakefile，可惜没有，后来我转vscode了，论代码提示，jetbrains家的确实最好

**Comment by lygstate** [comment]
cmake

**Comment by Siqiu** [comment]
希望支持clion   +1
