### ISSUE TITLE
在debug版本，rt_completion_wait 为什么只能阻塞一个线程？

### ISSUE THREAD

**Issue by qinpan1003** [RT-Thread/rt-thread#3079]
rt_completion_wait
--> RT_ASSERT(rt_list_isempty(&(completion->suspended_list)));

RT_ASSERT 这个宏在debug版本会判断 suspended_list 是否为空，如果不为空就会报错。

**Comment by BernardXiong** [comment]
设计就是这样的，希望它是一个轻型，简单的机制。

**Comment by qinpan1003** [comment]
_serial_int_tx --> putc 如果返回 -1 --> rt_completion_wait

这个流程，可能涉及多个线程同时调用 _serial_int_tx ，最终触发多个 rt_completion_wait。
debug版本会 assert 报错死机，release 版本就不会。
这种情况该怎么处理呢？

其实我觉得那个判断可以放开，如果不限制 waiter数量，和其他 OS 的 wait 概念也可以保持一致。
