### ISSUE TITLE
关于ipc.c 消息队列rt_mq_recv

### ISSUE THREAD

**Issue by HouqiLi** [RT-Thread/rt-thread#3084]
在ipc.c里面的rt_mq_recv发现了个问题：
【问题】
当rt_mq_recv接收不定长数据时会出现，rt_mq_recv每次从mq队列里取数据后没有清除原来的数据，这样会导致下一次接收到的实际消息长度小于本次长度时，下次消息队列接收到的数据是夹杂着上一次数据的尾巴。

【重现】
譬如，接收buffer大小大于7，小于消息队列单个消息长度，第一次发送消息"123456"，第一次调用rt_mq_recv没有问题，第二次发送消息"111"时，第二次调用rt_mq_recv接收到的数据会变成"111456"。

【解决办法】
基于这个问题，在rt_mq_recv里copy message后添加一句rt_memset(msg + 1, 0, size > mq->msg_size ? mq->msg_size : size);可解决。
  
请大佬确认下这个问题

**Comment by BernardXiong** [comment]
这个不是问题，设计就是这样的。

建议在mq中传递结构化的消息，即：
```c
struct msg_item
{
  int type;
  int size;
  uint8_t data[];
};
```

这样当接收端收到这个消息时，它就知道这个消息类型是什么，长度是多少。

**Comment by HouqiLi** [comment]
谢谢！！
