### ISSUE TITLE
rt_strncpy api 在u8g2_UserInterfaceMessage函数库中多复制一个字符

### ISSUE THREAD

**Issue by cyclonev** [RT-Thread/rt-thread#3099]
rt_strncpy api 在u8g2_UserInterfaceMessage函数库中多复制一个字符。
我最近在调试u8g2库，在button 定义了8个字符，发现第8个字符后显示多了一个字符，通过调试发现在rt_strncpy后，不知道什么原因多复制一个字符。
我用strcpy后，这个问题解决。
![image](https://user-images.githubusercontent.com/20747662/65474522-b8589680-deae-11e9-9da1-ee053cb3e4c4.png)

**Comment by BernardXiong** [comment]
please submit your issue in u8g2 package.
