### ISSUE TITLE
RTC时钟源导致时间设置失败和停止走动BUG

### ISSUE THREAD

**Issue by HelloByeAll** [RT-Thread/rt-thread#3106]
![QQ截图20190926173928](https://user-images.githubusercontent.com/53550140/65677703-aa5c6e80-e084-11e9-916e-1bb2632f1961.png)
![QQ截图20190926173950](https://user-images.githubusercontent.com/53550140/65677707-acbec880-e084-11e9-84eb-26f85100f445.png)
通过修改此处代码可解决此问题

**Comment by BernardXiong** [comment]
@SummerGGift Please fix it.

**Comment by mysterywolf** [comment]
#3938

**Comment by mysterywolf** [comment]
2021..2.8 今天查看 该问题已经得到解决
