### ISSUE TITLE
V4.0.0新建工程env开启sensor框架，没有sensor文件夹添加进工程

### ISSUE THREAD

**Issue by Tonny-Y** [RT-Thread/rt-thread#3107]
RTT源码下载后git checkout v4.0.0，重新制作BSP，在env中RT-Thread online packages->peripheral libraries and drivers->sensors drivers打开sensor驱动框架后，对应的sensor驱动文件夹并没有出现在项目文件中，是4.0.0和master不一样吗？

**Comment by Tonny-Y** [comment]
是stm32f1的模板

**Comment by BernardXiong** [comment]
对，这个需要4.0.1版本。
