### ISSUE TITLE
Sconscript添加.lib库文件生成keil工程

### ISSUE THREAD

**Issue by k0becheng** [RT-Thread/rt-thread#311]
有库文件‘a.lib’，在Sconscript文件中采用如下形式添加库文件到工程：
==代码==============
LIBS    = ['a']
DefineGroup('A', src, CPPPATH = CPPPATH, LIBS = LIBS, LIBPATH=LIBPATH)
==代码==============
这样生成的keil工程目录下会有两个同名的‘A’目录，一个里面放的是'.c'等源代码文件，另一个里面则单独放置一个'.lib'文件，同时尝试了添加两个‘.lib’文件，果然keil下又多了个同名目录单独放置新添加的库文件，不知能否改善下。

**Comment by BernardXiong** [comment]
I have fixed this bug in my local branch. I will submit it later.
