### ISSUE TITLE
关于调用关闭调度“rt_enter_critical"后在再次调用 yield　之类操作出让处理器的问题？

### ISSUE THREAD

**Issue by 13824125580** [RT-Thread/rt-thread#3135]
在rtt当前的实现里面，rt_enter_critical是通过设置CPU全局锁的方式关闭调度，所有线程共享一个调度器状态，造成的结果就是不允许在在前者调用之后马上调用sleep. yield之类导致线程休眠等待的接口，因为调了也没有用，调度器直接返回了。
但是对于有些系统，例如linux, zephyr之类的，scheduer lock会关闭抢占，线程会变为corouine性质，所以是允许在scheduler lock之后进入休眠的。
两种实现方式虽然没有优劣之分，但到具体实现选择上，有什么考量么？

**Comment by BernardXiong** [comment]
因为RTT不支持协程，所以这块没有具体的选择啊
