### ISSUE TITLE
stm32f103-atk-warshipv3 bsp中project.uvoptx直接打开编译会出错

### ISSUE THREAD

**Issue by ShineRoyal** [RT-Thread/rt-thread#3138]
在mdk5工程中，finish文件夹下有msh_cmd.c文件，而rtt版本中无此文件。
需要通过scons --target=mdk5重新生成工程解决。

**Comment by BernardXiong** [comment]
谢谢反馈，后面也会一起更新工程文件。

**Comment by mysterywolf** [comment]
2021-2-6 直接编译无错误 问题已经得到解决
