### ISSUE TITLE
drv_pwm.c and drv_hwtimer.c build error: use of empty enum

### ISSUE THREAD

**Issue by LUAN-Z** [RT-Thread/rt-thread#3141]
..\libraries\HAL_Drivers\drv_hwtimer.c(73): error:  #40: expected an identifier
  };
..\libraries\HAL_Drivers\drv_hwtimer.c(152): error:  #29: expected an expression
  };
..\libraries\HAL_Drivers\drv_hwtimer.c(83): error:  #1514: an empty initializer is invalid for an array with unspecified bound
  static struct stm32_hwtimer stm32_hwtimer_obj[] =
..\libraries\HAL_Drivers\drv_hwtimer.c: 0 warnings, 3 errors
compiling drv_gpio.c...
compiling drv_pwm.c...
..\libraries\HAL_Drivers\drv_pwm.c(78): error:  #40: expected an identifier
  };
..\libraries\HAL_Drivers\drv_pwm.c(157): error:  #29: expected an expression
  };
..\libraries\HAL_Drivers\drv_pwm.c(88): error:  #1514: an empty initializer is invalid for an array with unspecified bound
  static struct stm32_pwm stm32_pwm_obj[] =
..\libraries\HAL_Drivers\drv_pwm.c: 0 warnings, 3 errors

**Comment by BernardXiong** [comment]
Please provide more information. Which case will cause this issue?

**Comment by xuzheng821** [comment]
I found the same problem，when develop base the BSP of stm32f413-st-nucleo，is there any update?

**Comment by xuzheng821** [comment]
> Please provide more information. Which case will cause this issue?

I found the same problem，when develop base the BSP of stm32f413-st-nucleo，is there any update? thanks!

**Comment by mysterywolf** [comment]
![image](https://user-images.githubusercontent.com/34888354/174124903-fecd7f45-f934-4056-99a3-fb9f40ae7cab.png)
你要在这里去打开对应的宏，想用PWM几，什么宏都不打开，只开启了PWM，肯定会报错的
