### ISSUE TITLE
 Will  Nuvoton_M497 bsp support the Keil 5.28 version?

### ISSUE THREAD

**Issue by Sam-Wang** [RT-Thread/rt-thread#3144]
Hi :
 Will  Nuvoton_M487 bsp support above the Keil 5.28 version ?
BRS

**Comment by BernardXiong** [comment]
You can try it. If you not, you can use `scons --target=mdk5` to re-generate MDK project.

**Comment by Sam-Wang** [comment]
The M487 bsp was base keil 4.74, No template.uvprojx to re-generate !
.... \rt-thread\bsp\nuvoton_m487\SConstruct", line 27, in <module>
IOError: [Errno 2] No such file or directory: 'template.uvprojx':

**Comment by Sam-Wang** [comment]
Rename the template.uvproj  to template.uvprojx .
scons --target=mdk5  will generate a project.uvprojx file. 

".\build\template.axf" - 0 Error(s), 2 Warning(s).

Thanks !

**Comment by BernardXiong** [comment]
Yes. The template project file is just an empty project file. Therefore, you can use Keil MDK to genernate a new and empty project file with correct device settings.
