### ISSUE TITLE
新增更新使用LWIP时，增加了很多ssize_t未定义错误

### ISSUE THREAD

**Issue by tuopu** [RT-Thread/rt-thread#3156]
测试了一下9月份更新版本，无ssize_t未定义问题，10月26日下载了一次，更新了系统，发现了这个问题，27日更新版本也存在。

**Comment by BernardXiong** [comment]
具体指的是？lwIP用的是什么样的版本

**Comment by tuopu** [comment]
用的2.10，编译的时候出现的。

**Comment by BernardXiong** [comment]
还请提供更多的信息，menuconfig中是如何选择的，编译器？libc是？

**Comment by tuopu** [comment]
menuconfig 使能了 Enable libc APIs from toolchain、开启RT_USING_DFS、Enable network interface device、Enable Ethernet。编译器iar和mdk问题一致，都会出现ssize_t未定义问题。9月14日版本无此问题。
