### ISSUE TITLE
Rt-Thread Modbus Config port

### ISSUE THREAD

**Issue by yasinsoltani** [RT-Thread/rt-thread#3165]
Hi everybody
I want to have a Modbus RTU Slave communication on UART1 ( eMBInit(MB_RTU, 2, 1, 9600,  MB_PAR_NONE);
But unfortunately the connection doesn't work. When I change come port to UART2 ( eMBInit(MB_RTU, 2, 2, 9600,  MB_PAR_NONE); it works correct.  
I thought maybe uart1 defined as master and needs to change the default setting for salve but I couldn't find any relevant default to change. Please help me what shall I do? 
Thank you for your kindness
yasin.soltani1@gmail.com

**Comment by BernardXiong** [comment]
It seems there is no setting for master or slave in RT-Thread UART device. Maybe you can check more about in Modbus.
