### ISSUE TITLE
Suggestion: Add string information for error

### ISSUE THREAD

**Issue by a1012112796** [RT-Thread/rt-thread#3173]
hello everyone. I have found a little trouble that there is no standard error message output function in RTT. In case of an error, only one number can be print, and the meaning of this number can only be found by looking up the code or the document.Therefore,I think it is recommended to add strerror function to increase the readability of error message output.
I have try to realise it,and here is my work:
[add_strerror_patch.zip](https://github.com/RT-Thread/rt-thread/files/3800059/add_strerror_patch.zip)
here is the result:
test by stm32f427-robomaster-a and building with MDK5. 
![图片](https://user-images.githubusercontent.com/25342410/68064747-6d0d8f80-fd5a-11e9-970c-b3d4b958d6d9.png)
I think it can be realise by a more perfect way, so I put it on issues to find more good ways.
A bit individual opinion, if  it have error, hope your forgive, thanks.

**Comment by BernardXiong** [comment]
谢谢。

请问有github repo可以看看是什么样实现的吗？另外，关于errno标准错误的部分，应该是可以用strerror函数的。

**Comment by a1012112796** [comment]
@BernardXiong 
您好，我尝试做的改动在附件add_strerror_patch.zip中以patch补丁的形式给出，用的是最简单的数组的方式实现的并且复制了%s的很多内容，我觉得应该有更好的办法，所以没发，仅放在这供各位大什佬参考。

**Comment by a1012112796** [comment]
![图片](https://user-images.githubusercontent.com/25342410/68122807-28464c00-ff46-11e9-89de-afa6ed12a69b.png)
还有请问现在是不是发ISSUE必须用英文了？！:cry:

**Comment by BernardXiong** [comment]
> ![图片](https://user-images.githubusercontent.com/25342410/68122807-28464c00-ff46-11e9-89de-afa6ed12a69b.png)
> 还有请问现在是不是发ISSUE必须用英文了？！😢

Yes, If you use Chinese, suggest to submit in [Chinese Forum](https://www.rt-thread.org/qa/portal.php) or [Gitee](https://gitee.com/rtthread/rt-thread).

**Comment by a1012112796** [comment]
OK,I see. I have change it.
