### ISSUE TITLE
bsp/hifive目录的Makefile，使用的scon.py位置在哪里？

### ISSUE THREAD

**Issue by 245950258** [RT-Thread/rt-thread#3187]
请问bsp/hifive目录的Makefile，使用的scon.py位置在哪里？按照readme步骤走不通。

**Comment by BernardXiong** [comment]
@Guozhanxin Please take a look.

**Comment by tyustli** [comment]
scons.py 是 env 工具里面的脚本文件，路径在：env\tools\Python27\Scripts，按照 readme 操作哪里有问题可以把问题贴出来看一下

**Comment by 245950258** [comment]
好的，谢谢回复。
