### ISSUE TITLE
Any planning modify current workqueue to support CMWQ like linux?

### ISSUE THREAD

**Issue by zwxf** [RT-Thread/rt-thread#3192]
Hi:
     Any planning modify current workqueue to support CMWQ like linux?
     I read workqueue source code currently,  I have found that current workqueue only support single thread, If i create work which sleep some time that will block all last works, so Do we any plan to modify current mechanism to CMWQ mode like linux? hope to reply.
    best regards : ).

**Comment by BernardXiong** [comment]
So, what's the mean of CMWQ?
