### ISSUE TITLE
question: some code in sd.c is surrounded with #if 0

### ISSUE THREAD

**Issue by a1012112796** [RT-Thread/rt-thread#3211]
https://github.com/RT-Thread/rt-thread/blob/c7681600831ee7d5cf5f57466187750f50d65ed9/components/drivers/sdio/sd.c#L96
https://github.com/RT-Thread/rt-thread/blob/c7681600831ee7d5cf5f57466187750f50d65ed9/components/drivers/sdio/sd.c#L145

Hello, I don't understand why these codes are surrounded by #if 0, if there is no special reason, I suggest deleting them, thanks.

**Comment by BernardXiong** [comment]
Thank you. We will check it.

**Comment by a1012112796** [comment]
This issue has been solved in a646b9275de2c4b38acc00116c393551d3f6e1a6,Thanks
