### ISSUE TITLE
stm32f429-fire-challenger  添加usb ecm功能 编译没用device设备

### ISSUE THREAD

**Issue by hacklinshell** [RT-Thread/rt-thread#3288]
![image](https://user-images.githubusercontent.com/9523270/71361514-27d54380-25ce-11ea-85dd-b40d418dc038.png)

这是为什么呀，我使用stm32cubemx重新配置开启了usb fs功能和时钟，最后还有这个错误

**Comment by hacklinshell** [comment]
![image](https://user-images.githubusercontent.com/9523270/71366599-67eff280-25dd-11ea-8a7d-4afeb8afcea1.png)

是否是这个参数用错了，device应该是ecm_eth_dev  请检查下

**Comment by lymzzyh** [comment]
#3292

**Comment by hacklinshell** [comment]
已经合并master了
