### ISSUE TITLE
【探讨】msh ps命令中的线程 <错误码> 是否可以修改成 <状态码>，这样不容易误导人

### ISSUE THREAD

**Issue by liu2guang** [RT-Thread/rt-thread#3320]
![状态码](https://user-images.githubusercontent.com/24929334/71958837-33f70d00-322c-11ea-893c-db573378718b.png)

**Comment by armink** [comment]
之前有个 pr 提到这个功能

https://github.com/RT-Thread/rt-thread/pull/3186

**Comment by BernardXiong** [comment]
是字符串吗？

**Comment by liu2guang** [comment]
![image](https://user-images.githubusercontent.com/24929334/71971687-12a31a80-3246-11ea-89c9-d20bf278d3e5.png)

**Comment by BernardXiong** [comment]
state是什么？还是说error string？

**Comment by a1012112796** [comment]
您好，这位大兄弟的意思是把表头的“error”改成 "state"，估计他觉得意思不合适。

**Comment by QQWE1345** [comment]
他的意思是 error这个说法 改成state更准确 最后一列不是反馈的错误代码 而是线程的状态

**Comment by mysterywolf** [comment]
这个errno指的是每个thread的errno成员变量的值

**Comment by mysterywolf** [comment]
应该把error改成errno更准确一点
