### ISSUE TITLE
imxrt1052-fire-pro drv_eth.c ENET_Deinit 系统跑飞

### ISSUE THREAD

**Issue by scJingP** [RT-Thread/rt-thread#3321]
野火RT1052网卡功能移植已完成, 但有问题还请官方注意, 在实际运行中会卡死在 drv_eth.c 文件中 _enet_config 函数下 "ENET_Deinit(imxrt_eth_device.enet_base);" 代码处. 注释后程序正常运行, ping正常.

**Comment by liliangego** [comment]
在RT-Thread4.0.2中屏幕了也不行呀？在野火开发板上也是无法自动获取IP，原因是 数据没有发送出去，发送数据的时候没有进入中断回调函数，怎么解决的呀？

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/issues/3315
