### ISSUE TITLE
这个获取PHY状态的返回值和参数冲突，应该去掉返回值左值SR

### ISSUE THREAD

**Issue by geniusgogo** [RT-Thread/rt-thread#3332]
https://github.com/RT-Thread/rt-thread/blob/cad32a326ce5774044837197fe566f0d5bd69ca9/bsp/stm32/libraries/HAL_Drivers/drv_eth.c#L418

**Comment by BernardXiong** [comment]
Please submit PR, thanks.

**Comment by geniusgogo** [comment]
fixed pr:https://github.com/RT-Thread/rt-thread/pull/3336#issue-362952997
