### ISSUE TITLE
stm32/drv_pwm.c的初始化BUG

### ISSUE THREAD

**Issue by geniusgogo** [RT-Thread/rt-thread#3333]
https://github.com/RT-Thread/rt-thread/blob/cad32a326ce5774044837197fe566f0d5bd69ca9/bsp/stm32/libraries/HAL_Drivers/drv_pwm.c#L326

描述：https://github.com/RT-Thread/rt-thread/commit/d3f8b9b9c14b0c4b79bc67efb8d4ff65f9552f50#commitcomment-36788100

**Comment by geniusgogo** [comment]
正确的处理是只需要保留HAL_TIM_PWM_Init即可。

**Comment by BernardXiong** [comment]
@SummerLife Please take a look. 

Or, @geniusgogo sir, please submit PR, thanks.

**Comment by geniusgogo** [comment]
fixed PR:https://github.com/RT-Thread/rt-thread/pull/3337#issue-362967962
