### ISSUE TITLE
rt-thread + lwip; The delay from the ENET_RXD0 signal to the "recvfrom" function reaches milliseconds. Real time?

### ISSUE THREAD

**Issue by scJingP** [RT-Thread/rt-thread#3342]
Development environment:
RT-Thread: v4.0.2 (master)
SOC: i.MX RT1050
Board: Wildfire RT1052

System environment:
lwip (2.0.2) + test program ("recvfrom" function outputs IO signal immediately after receiving data)

Test Methods:
Probe 1: ENET_RXD0 pin
Probe 2: IO signal pin
Test the delay of these two signals

Purpose: The network card performs business processing immediately after receiving the data. The delay in this process is maintained at the microsecond level and the jitter is controlled within 100 microseconds

Phenomenon: After testing, it is found that the delay is up to 9ms, and the minimum delay is 97us

Question: How to make "Maximum Delay-Minimum Delay <= 100us"

**Comment by qz721** [comment]
As far as I know, when net data arrives, the interrupt handler sends a message to the mailbox, which in turn wakes up the RX thread to read the data. So, improving the priority of the RX thread might help shorten the latency time.

Perfect format!
Wish this could help you.
