### ISSUE TITLE
ipc completion的疑问

### ISSUE THREAD

**Issue by mttbx** [RT-Thread/rt-thread#3347]
你好，在驱动运行过程中，如果中断在等待之前先释放了completion，会不会导致永久的等待？
比如说在serial.c中的_serial_int_tx函数里，如果在rt_completion_wait之前触发了rt_hw_serial_isr（当然可能性很小，比如正好发生了被另一个线程抢占运行了）。

**Comment by mttbx** [comment]
也就是提前被释放掉了。

**Comment by BernardXiong** [comment]
有这个可能的，所以一些顺序是需要自己控制好的

**Comment by mttbx** [comment]
好的。
