### ISSUE TITLE
请求添加INIT_XXX_EXPORT 顺序支持

### ISSUE THREAD

**Issue by mttbx** [RT-Thread/rt-thread#3351]
你好，我发现INIT_XXX_EXPORT尽管有APP、ENV、COMPONENT等等不同的类型，但是还是不够用，是否可以考虑增加一些INIT_XXX_EXPORT的类型，或者提供类型支持？因为有些库占用了INIT_APP_EXPORT导致很多时候会担心出现初始化顺序的问题。

**Comment by BernardXiong** [comment]
这些定义也是定义成另外的等级，例如

```C
#define INIT_APP_EXPORT(fn)             INIT_EXPORT(fn, "6")
```

所以，你也可以直接用INIT_EXPORT来控制等级，包括后面的"6.1", "6.2"等等

**Comment by BernardXiong** [comment]
再然后，INIT_EXPORT仅仅是提供了一份懒人机制，在一些复杂产品场合，其实是推荐你直接自行来初始化，以严格保证你的产品初始化顺序。

**Comment by mttbx** [comment]
nice!
