### ISSUE TITLE
移植到gd32vf103，gcc编译优化掉sections片段钦，导致自动初始化失效

### ISSUE THREAD

**Issue by WenliBest** [RT-Thread/rt-thread#3354]
使用芯来的IDE，gcc编译环境，在使用INIT_BOARD_EXPORT() 宏导出自动初始化函数，通过map文件lst文件查看gcc会删除导出的sections片段，导致无法实现自动初始化。RTT版本3.1.3。

**Comment by WenliBest** [comment]
已经使能#define RT_USING_COMPONENTS_INIT，但是使用INIT_BOARD_EXPORT(usart_init);添加的函数无法自动调用。请问怎么解决？

**Comment by BernardXiong** [comment]
You can use JTAG to debug it one by one.

**Comment by WenliBest** [comment]
通过板载GD调试器跟踪，分析生成的.map 和.lst文件，原来编译器吧未使用的section优化掉了，所以通过attirbute属性添加的自动执行函数不会运行，在去掉编译器相应优化之后编译程序体积暴增5倍，查看map文件和lst终于有自定义的section地址了，但是下载elf文件到目标板程序依然不执行自定义函数。另外通过板载调试器跟踪到的函数地址和lst给出的LMA和VMA居然不一样。各种分析不得要领，不知道那块儿出问题了。
