### ISSUE TITLE
BSP for AT91SAM9G25

### ISSUE THREAD

**Issue by JPB1JPB1** [RT-Thread/rt-thread#3361]
Dear RT Thread Team

Please, can you add the BSP for anay AT91SAM9g25 and other parts too ..
Thanks
Br
Jp

**Comment by BernardXiong** [comment]
You can refer bsp/at91sam9g45 for AT91SAM9G25.

**Comment by JPB1JPB1** [comment]
ok thanks
Another question :
How can we run in underclock mode to run at 100Mhz, 200Mhz, instead of 400Mhz in order to reduce the power consumption but having everything ok ?
and Is it possible ?

Br
Jp

**Comment by BernardXiong** [comment]
Yes, it's possible. You can change the clock tree setting.
