### ISSUE TITLE
typo in bsp/stm32/stm32f769-st-disco/.config - CONFIG_RT_IDEL_HOOK_LIST_SIZE=4

### ISSUE THREAD

**Issue by gdamjan** [RT-Thread/rt-thread#3366]
`CONFIG_RT_IDEL_HOOK_LIST_SIZE=4` should be `CONFIG_RT_IDLE_HOOK_LIST_SIZE=4`

ie. `IDEL` vs `IDLE`

**Comment by BernardXiong** [comment]
You can use menuconfig to fix it since we update the Kconfig file.
