### ISSUE TITLE
USB HOST support for Wifi, Bluetooth uSD, pendrive

### ISSUE THREAD

**Issue by JPB1JPB1** [RT-Thread/rt-thread#3368]
DEAR RT Thread team

what about the USB Host support for Wireless and Pendrive ? Is it also HIGH speed to support 480Mbps and hub features with power optimisation ....

Which board are suggested for this ? 

Best Regards
Jp

**Comment by BernardXiong** [comment]
Hello, 
There is no USB wifi, bt yet in USB host. USB Host stack support mass storage class at present.

**Comment by JPB1JPB1** [comment]
Please, if USB mass storage IS supported, mamy ne other device Can be added in a close futur ?
Any plan to get any USB host wireless connections only for few  limited device (not all ) for each case ( wifi, bluetooth, lora, thread) ...
Best regards
Jp
