### ISSUE TITLE
[Feature][stm32] add STM32 LL Library suport for stm32 device drive

### ISSUE THREAD

**Issue by a1012112796** [RT-Thread/rt-thread#3386]
Dear RT-Thread team:
      I suggest to add support for STM32 Low Level Library in stm32 device drive , Maybe it will be usefull for  Small memory chips.  thanks!

some usefull links:
http://www.handsonembedded.com/stm32f103-ll-tutorial-1/
https://community.st.com/s/question/0D50X00009XkhQSSAZ/hal-vs-ll

**Comment by BernardXiong** [comment]
Welcome to submit your device driver PR with STM32 low level... 👍
