### ISSUE TITLE
Does rt-thread have any API for timed lock of mutex?

### ISSUE THREAD

**Issue by djndl1** [RT-Thread/rt-thread#3388]
Currently I am trying to implement C++11 threading support based on rt-thread's POSIX interface. I've finished `<thread>` part and most of `<mutex>` but I just found out it's got no timed mutex support. Normally on POSIX-conformant systems, `try_lock_for` and `try_lock_until` are implemented by wrapping around `pthread_mutex_timedlock` but it's not available on rt-thread and I've found no other functions for this. Therefore, `timed_mutex` and `recursive_timed_mutex` are currently not implemented. Is there any plan to implement this function?

**Comment by BernardXiong** [comment]
👍 You can PR a draft firstly, thank you.

**Comment by djndl1** [comment]
Currently, some of the code is borrowed from libstdc++ and libc++ and there are some bugs already found during unit test. I might have to rewrite some to avoid legal issues. Also, I'm not sure if implementing C++ threads using pthread is really suitable for rt-thread as I'm not familiar with real-time OS. PR won't be made within the near two months.

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/tree/master/components/cplusplus/cpp11
