### ISSUE TITLE
file 线程是在哪建的，怎么调这个线程栈的大小？

### ISSUE THREAD

**Issue by SuWeipeng** [RT-Thread/rt-thread#3409]
没找到 file 线程创建的地方，求助。
---
![Selection_003](https://user-images.githubusercontent.com/24380862/75311611-599aad00-5892-11ea-8f22-0532c6198339.png)

**Comment by SuWeipeng** [comment]
我有用文件系统在 SD 卡上记日志，但我没有建过叫“file”的线程。
---
<img width="481" alt="Snipaste_2020-02-26_12-58-49" src="https://user-images.githubusercontent.com/24380862/75313462-d11f0b00-5897-11ea-8c72-5b1ac245c2d9.png">

**Comment by shao7936626** [comment]
什么叫file的线程？   你哪个线程去用file去读文件，就是file线程啊，那个线程就要弄大一点，不然读的文件大了，就溢出了

**Comment by SuWeipeng** [comment]
> 什么叫file的线程？ 你哪个线程去用file去读文件，就是file线程啊，那个线程就要弄大一点，不然读的文件大了，就溢出了

怎么调这个线程的大小呢？我没找到创建线程的地方，所以不知道在哪调。

**Comment by SuWeipeng** [comment]
> > 什么叫file的线程？ 你哪个线程去用file去读文件，就是file线程啊，那个线程就要弄大一点，不然读的文件大了，就溢出了
> 
> 怎么调这个线程的大小呢？我没找到创建线程的地方，所以不知道在哪调。

找到了，在我写文件的地方。
