### ISSUE TITLE
Common typo errors in bsp/stm32/xxx/board/ports/fal_cfg.h

### ISSUE THREAD

**Issue by DavidLin1577** [RT-Thread/rt-thread#3414]
Hi, there is a file which named fal_cfg.h, which no one use it,
may be a file of some internal build tools.

Typo error:
FAL_PART_MAGIC_WROD -> FAL_PART_MAGIC_WORD

It is a common typo error in these stm32 files, not nxp or others :

bsp/stm32/stm32f469-st-disco/board/ports/fal_cfg.h 
bsp/stm32/stm32f429-st-disco/board/ports/fal_cfg.h 
bsp/stm32/stm32l475-atk-pandora/board/ports/fal_cfg.h 
bsp/stm32/stm32f407-atk-explorer/board/ports/fal_cfg.h 
bsp/stm32/stm32f429-atk-apollo/board/ports/fal_cfg.h 
bsp/stm32/stm32f429-armfly-v6/board/ports/fal_cfg.h 
bsp/stm32/stm32f429-fire-challenger/board/ports/fal_cfg.h 
bsp/stm32/stm32f767-atk-apollo/board/ports/fal_cfg.h 
bsp/stm32/stm32f767-fire-challenger/board/ports/fal_cfg.h 
bsp/stm32/stm32f746-st-disco/board/ports/fal_cfg.h 
bsp/stm32/stm32g071-st-nucleo/board/ports/fal_cfg.h 
bsp/stm32/stm32f103-dofly-M3S/board/ports/fal_cfg.h 
bsp/stm32/stm32l496-ali-developer/board/ports/fal_cfg.h 
bsp/stm32/stm32f103-atk-nano/board/ports/fal_cfg.h 
bsp/stm32/stm32f103-fire-arbitrary/board/ports/fal_cfg.h 
bsp/stm32/stm32f091-st-nucleo/board/ports/fal_cfg.h 
bsp/stm32/stm32f103-hw100k-ibox/board/ports/fal_cfg.h 
bsp/stm32/stm32l452-st-nucleo/board/ports/fal_cfg.h

**Comment by armink** [comment]
The fal_cfg.h file will be used when FAL package is enabled. It's the flash partition config file.
