### ISSUE TITLE
tag 4.02, v4.0.2/bsp/stm32/libraries/HAL_Drivers/drv_comm.c, Missing implementation for HAL_Delay

### ISSUE THREAD

**Issue by liulee** [RT-Thread/rt-thread#3426]
v4.0.2/bsp/stm32/libraries/HAL_Drivers/drv_comm.c , no implementation for HAL_Delay
That's awsome. cause overwrited system default impl.
should change like this:
```
void HAL_Delay(__IO uint32_t Delay)
{
	rt_thread_mdelay(Delay);
}
```

**Comment by BernardXiong** [comment]
Thank you for you feedback. You can check the master branch. If there is no implementation, you can submit a PR. Thank you.

**Comment by SummerLife** [comment]
I think the function you said has been implemented on the master branch, thank you :), you can check it.

https://github.com/RT-Thread/rt-thread/blob/a7bcf90d78970f9a5e221133653331df158e9548/bsp/stm32/libraries/HAL_Drivers/drv_common.c#L68
