### ISSUE TITLE
写文件的问题

### ISSUE THREAD

**Issue by SmallSmartMouse** [RT-Thread/rt-thread#3428]
使用的4.0.2的系统，在main进来后读写文件，发现不能发现文件，后来加了500ms的延时就可以了，看代码发现mout的用了一个线程，这个没办法保证时序啊，认为是一个bug，另外，写文件的时候，不调用fsync方法，文件数据不会写进去，也认为是一个bug

**Comment by BernardXiong** [comment]
这些相关的，请根据你使用的场合自行进行处理。开发主干上游，不可能考虑到更多具体的场合，所以一些使用方式上尽可能考虑宽松的模式。
