### ISSUE TITLE
rt_err_t 回傳值有規範嗎?

### ISSUE THREAD

**Issue by wosayttn** [RT-Thread/rt-thread#3440]
請問回傳值 是 RT_ENOSYS 正數，還是 -(RT_ENOSYS) 負數?

rt_err_t rt_pin_irq_enable(rt_base_t pin, rt_uint32_t enabled)
{
    RT_ASSERT(_hw_pin.ops != RT_NULL);
    if(_hw_pin.ops->pin_irq_enable)
    {
        return _hw_pin.ops->pin_irq_enable(&_hw_pin.parent, pin, enabled);
    }
    return RT_ENOSYS;
}

**Comment by BernardXiong** [comment]
RTT自己定义的一般都是负数，POSIX的是正数。

后续逐步过渡到，返回值都是负数，errno是正数，向POSIX靠拢

**Comment by mysterywolf** [comment]
谢谢你的issue 已经提pr解决
