### ISSUE TITLE
Where is freetype? 在哪里可以找到 freetype 这个中间件？

### ISSUE THREAD

**Issue by imgtec** [RT-Thread/rt-thread#3469]
Hi, I am new to rt-thread,  I want to display some glyph on lcd,
I grep(ed) keyword freetype in the source tree, 

```
./ChangeLog.md:* Update freetype to 2.5.4 version.
```
but I can't find the freetype option in menuconfig.

I have some experence with freetype, I have port it on a baremetal mcu with 64KiB flash,
and also have port it to some other realtime kernel...(e.g. t-kernel)

where to start to enalble freetype support?

thanks.

**Comment by BernardXiong** [comment]
You can use menuconfig to enable GUI Engine menu, and then enable the FreeType feature.
