### ISSUE TITLE
4.0的系统程序运行起始地址怎么配置

### ISSUE THREAD

**Issue by SmallSmartMouse** [RT-Thread/rt-thread#3476]
我使用scons进行编译，打算用自己写的bootloader，但是程序运行的起始地址不知道怎么配置，我的芯片是stm32f427

**Comment by Guozhanxin** [comment]
修改链接脚本 xxx.ld/lds 里面的flash起始地址就好了

**Comment by SmallSmartMouse** [comment]
rtconfig.py里面是这样
`    LFLAGS = DEVICE + ' -Wl,--gc-sections,-Map=rt-thread.map,-cref,-u,Reset_Handler -T board/linker_scripts/link.lds'
`
link.lds文件里面我已经修改了，但是编译通过bootloader烧录的还是不能运行 
```
/* Program Entry, set to mark it as "used" and avoid gc */
MEMORY
{
    ROM (rx) : ORIGIN = 0x08004000, LENGTH = 2032k /* 2048KB flash */
    RAM1 (rw) : ORIGIN = 0x20000000, LENGTH =  192k /* 192K sram */
    RAM2 (rw) : ORIGIN = 0x10000000, LENGTH =   64k /* 64K sram */
}
```

**Comment by SmallSmartMouse** [comment]
有了解的吗
