### ISSUE TITLE
Is there a bug here?

### ISSUE THREAD

**Issue by fuluwwa** [RT-Thread/rt-thread#3481]
In kernel file mem.c，function rt_realloc:
471     if (newsize + SIZEOF_STRUCT_MEM + MIN_SIZE < size)
472     {
473         /* split memory block */
The conditions to determine if memory should be split or not is right? Maybe,
471     if (newsize + 2*SIZEOF_STRUCT_MEM + MIN_SIZE < size)

Because functin rt_malloc that is,
316             if (mem->next - (ptr + SIZEOF_STRUCT_MEM) >=
317                 (size + SIZEOF_STRUCT_MEM + MIN_SIZE_ALIGNED))
318             {

**Comment by qz721** [comment]
No, this is not a bug. The actual size of the memory to be allocated is `newsize + SIZEOF_STRUCT_MEM + MIN_SIZE`.

And some characters in MarkDown have special meanings, to improve the readability, C code should listed like this:

```c
316 if (mem->next - (ptr + SIZEOF_STRUCT_MEM) >=
317 (size + SIZEOF_STRUCT_MEM + MIN_SIZE_ALIGNED))
318 {
```

Thanks for your efforts!
