### ISSUE TITLE
'NoneType' object has no attribute 'groups' when switching python2 to python3

### ISSUE THREAD

**Issue by imxood** [RT-Thread/rt-thread#3485]
if I use python3,  scons --menuconfig, or scons --target=eclipse, all is wrong, and the wrong is the same.
![image](https://user-images.githubusercontent.com/14890680/77650523-97c8e080-6fa6-11ea-8e48-b577d77cd579.png)

however, using python2, it is OK.
![image](https://user-images.githubusercontent.com/14890680/77650877-f2623c80-6fa6-11ea-8b3e-924a0872ad89.png)

**Comment by SummerLife** [comment]
也许你手动升级一下 env 的脚本就没这样的问题了

**Comment by imxood** [comment]
> 也许你手动升级一下 env 的脚本就没这样的问题了

**Comment by imxood** [comment]
> 也许你手动升级一下 env 的脚本就没这样的问题了

我是ubuntu系统
你说的是这样的吗:
```
source ~/.env/env.sh
pkgs --update
```
又试了一遍, 也是不行, 一样的结果.

**Comment by SummerLife** [comment]
不是这个意思，我的意思是 pkgs --upgrade 更新 env 功能脚本到最新版，

或者你切换到 env 的功能脚本目录，使用 git pull 命令来更更新

**Comment by imxood** [comment]
现在可以了, 或许 apt install scons 默认安装的是python2版本的, 需要卸载scons, apt autoremove scons, 安装py3的, pip3 install scons, 就可以使用scons编译了

**Comment by mkx171217** [comment]
> 现在可以了, 或许 apt install scons 默认安装的是python2版本的, 需要卸载scons, apt autoremove scons, 安装py3的, pip3 install scons, 就可以使用scons编译了

感谢，我也是apt安装的scons不行。按你的方法，用pip3安装scons就可以了。
