### ISSUE TITLE
stall packet while receiving read_capacities command( USBmass storage)

### ISSUE THREAD

**Issue by egbert-h** [RT-Thread/rt-thread#3490]
HI 

I implemented usb mass storage device with a formatted medium and ran into trouble in windows 10.   
Command handling in the mstorage.c line 614 will stall the IN endpoint if data_reside is not zero.
a shown in below figure
![image](https://user-images.githubusercontent.com/39821023/77870376-d34bff00-7273-11ea-9503-9526ba3d8102.png)

Remove the line 614 and the mass storage seems okay! 
![image](https://user-images.githubusercontent.com/39821023/77871528-004de100-7277-11ea-8979-f872ba526776.png)

![image](https://user-images.githubusercontent.com/39821023/77898970-905b4d00-72ae-11ea-944a-cf8ac2843385.png)

anyidea? 

many thanks.

**Comment by qz721** [comment]
Thanks, your issue has been noticed, we're trying to figure out what is happening.

**Comment by balanceTWK** [comment]
https://github.com/RT-Thread/rt-thread/commit/0bfb881168c0c69d8d5903391c0a16d13e393ec8

This issue has been fixed by the commit above. If in doubt, you can open the issue again.
