### ISSUE TITLE
Bug in _read_capacity implementation

### ISSUE THREAD

**Issue by egbert-h** [RT-Thread/rt-thread#3493]
HI 

SFUD driver reads the address out of bound due to the wrong value sent by _read_capacity to host.
![image](https://user-images.githubusercontent.com/39821023/78006322-6f0e6580-736f-11ea-90a8-f9bbe50d030b.png)

test code & solution( mstorage.c)
![image](https://user-images.githubusercontent.com/39821023/78005393-14c0d500-736e-11ea-8d46-b61c28ccf396.png)

![image](https://user-images.githubusercontent.com/39821023/78005270-e80cbd80-736d-11ea-9d8c-6b57851ae67b.png)

**Comment by tyustli** [comment]
> HI
> 
> SFUD driver reads the address out of bound due to the wrong value sent by _read_capacity to host.
> ![image](https://user-images.githubusercontent.com/39821023/78006322-6f0e6580-736f-11ea-90a8-f9bbe50d030b.png)
> 
> test code & solution( mstorage.c)
> ![image](https://user-images.githubusercontent.com/39821023/78005393-14c0d500-736e-11ea-8d46-b61c28ccf396.png)
> 
> ![image](https://user-images.githubusercontent.com/39821023/78005270-e80cbd80-736d-11ea-9d8c-6b57851ae67b.png)

thanks for your feedback.
this is a bug.
capacity = (last logical block address + 1) * block_size.
so when usb device return sector count  must descend 1.if possible you can pull request to fix this bug.thank you again.

**Comment by BernardXiong** [comment]
Fix with #3569. Thank you for your contribution.
