### ISSUE TITLE
USB masstorage: error while receiving INQUERY command

### ISSUE THREAD

**Issue by egbert-h** [RT-Thread/rt-thread#3507]
HI,

I get an error message: "xfer_len > data size" like below figure.

![image](https://user-images.githubusercontent.com/39821023/78734157-1431cb00-797a-11ea-8277-be5e46b48703.png)

It seems that the function, _cb_len_calc() ,in mstorage.c  does not handle the command length "12".

USB device may stall the command while receiving the command  which the length is not "6" or "10".  
![image](https://user-images.githubusercontent.com/39821023/78734486-00d32f80-797b-11ea-8e35-5d25bb1bda98.png)

![image](https://user-images.githubusercontent.com/39821023/78734456-ebf69c00-797a-11ea-89fc-922473a90ebf.png)

By adding handling for command length 12 in function _cb_len_calc() can workaround this issue. 
![image](https://user-images.githubusercontent.com/39821023/78735017-50662b00-797c-11ea-9d0d-4be42ef1bcdb.png)

**Comment by tyustli** [comment]
Thanks for your feedback.

this is a bug.when the command length is 0x0c it doesn't handle

your code can fix this.but your code only handle the COUNT case.if possible you can complete your code and pull request to fix this bug.

thank you again.

**Comment by balanceTWK** [comment]
This problem has been repaired in 0bfb881168c0c69d8d5903391c0a16d13e393ec8 ， can now be closed.
