### ISSUE TITLE
发现STM32F2xx_HAL的构建脚本里文件名拼写错误

### ISSUE THREAD

**Issue by DeclanHuaChen** [RT-Thread/rt-thread#3517]
https://github.com/RT-Thread/rt-thread/blob/446091fc103d279ea6ffb835041d9660fb99a0db/bsp/stm32/libraries/STM32F2xx_HAL/SConscript#L32
其中stm32f2xx_hal_pccd.c应该改为stm32f2xx_hal_pccard.c吧？

**Comment by BernardXiong** [comment]
@SummerLife Please check it, thank you.

**Comment by SummerLife** [comment]
这里确实是写错了，并没有 stm32f2xx_hal_pccd.c 这个文件

**Comment by SummerLife** [comment]
@DeclanHuaChen  方便提交一个 PR 来修复这个问题吗？

**Comment by DeclanHuaChen** [comment]
@SummerLife 好的，我试试

**Comment by DeclanHuaChen** [comment]
@SummerLife PR已经提交了，顺便改了一个头文件宏的拼写错误

**Comment by SummerLife** [comment]
好的看到了 感谢贡献 😄
