### ISSUE TITLE
stm32 keil一用pow就死机

### ISSUE THREAD

**Issue by Simon-Leung** [RT-Thread/rt-thread#3537]
同时不用系统的libc时，GCC编译出错。
还有cos、sqrt等，keil都有有问题

**Comment by BernardXiong** [comment]
前面一句话没看懂

**Comment by Simon-Leung** [comment]
就是GCC用minilibc时缺少了pow函数，用newlib就没问题

**Comment by BernardXiong** [comment]
> 就是GCC用minilibc时缺少了pow函数，用newlib就没问题

这个很正常，因为minilibc就是一个小型版本，裁剪版本的libc，有了的话才不正常。

**Comment by Simon-Leung** [comment]
但是keil的库也不行

**Comment by Simon-Leung** [comment]
哎，keil库没问题，是我自己把参数写到程序区去了
