### ISSUE TITLE
ImportError: No module named building

### ISSUE THREAD

**Issue by xubaoqiang** [RT-Thread/rt-thread#3551]
scons: Reading SConscript files ...                                                                              
ImportError: No module named building:                                                                           
  File "D:\Cygwin_Eclipse_IDE\AITHINKER-ESP8266-SDK\cygwin\home\allwinner_tina_prj_v1\SConstruct", line 8:       
    from building import *

**Comment by BernardXiong** [comment]
Please use scons or env tool to build it.
