### ISSUE TITLE
Get stuck issue after open-close-open CAN device

### ISSUE THREAD

**Issue by wosayttn** [RT-Thread/rt-thread#3560]
Report a bug.
The tx_fifo->sem is inited in open, but not detach in close. It will halted after doing open-close-open can device.

rt_sem_init:
https://github.com/RT-Thread/rt-thread/blob/master/components/drivers/can/can.c#L329

Forget rt_sem_detach(&(tx_fifo->sem)) in here.
https://github.com/RT-Thread/rt-thread/blob/master/components/drivers/can/can.c#L424

**Comment by BernardXiong** [comment]
Thank you for your feedback, and welcome to submit a PR.

**Comment by wosayttn** [comment]
PR　#3565
