### ISSUE TITLE
STM32F429  armflyv6开发板fread读取SD卡文件出现未对齐访问!必现问题

### ISSUE THREAD

**Issue by hacklinshell** [RT-Thread/rt-thread#3583]
读取固定长度没问题，分别读取不同长度数据，必然出现问题

 #进行SD卡文件读取操作，

具体详细描述  
https://www.rt-thread.org/qa/forum.php?mod=viewthread&tid=424409&page=1&extra=#pid477974

**Comment by su5176** [comment]
drv_sdio.c   把所有memcpy换成rt_memcpy试试

**Comment by hacklinshell** [comment]
> drv_sdio.c 把所有memcpy换成rt_memcpy试试

有可能真是这个问题，我暂时没用那个板子，用的spi接口的sd卡了，发现没用出现问题，等我有空后面测试下

**Comment by zhangjun1996** [comment]
1,这个应该是跟stm32库有关，[stmcu论坛有人提出过了](http://www.stmcu.org.cn/module/forum/thread-617579-1-1.html)
2,建议你的buf对齐一下看看

> > drv_sdio.c 把所有memcpy换成rt_memcpy试试
> 
> 有可能真是这个问题，我暂时没用那个板子，用的spi接口的sd卡了，发现没用出现问题，等我有空后面测试下
