### ISSUE TITLE
Missing _sbrk function for STM32 when compile it with AT device support

### ISSUE THREAD

**Issue by tekkamanninja** [RT-Thread/rt-thread#3595]
when compile stm32f407-st-discovery with AT device support, you may get:
    /usr/lib/gcc/arm-none-eabi/9.2.0/../../../../arm-none-eabi/bin/ld:    /usr/lib/gcc/arm-none-eabi/9.2.0/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libc.a(lib_a-sbrkr.o):    in function `_sbrk_r':
    /builddir/build/BUILD/newlib-3.1.0/build-newlib/arm-none-eabi/thumb/v7e-m+fp/hard/newlib/libc/reent/../../../../../../../../newlib/libc/reent/sbrkr.c:51:    undefined reference to `_sbrk'
    collect2: error: ld returned 1 exit status
    scons: *** [rtthread.elf] Error 1
    scons: building terminated because of errors.

GCC: 
Fedora : sudo yum install arm-none-eabi-*
OR
ARM : https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

**Comment by Lawlieta** [comment]
开启 LIBC 支持可解决问题
