### ISSUE TITLE
SFUD框架不能直接支持在兼容列表中的AT45DB161E芯片

### ISSUE THREAD

**Issue by mukuss** [RT-Thread/rt-thread#3597]
从芯片文档和代码判断，AT45DB161E的大多数操作与SFUD不同，如读状态和软件复位等，导致该硬件无法直接使用。
是否考虑进行补充支持或直接在兼容列表中去除该芯片？

**Comment by armink** [comment]
之前有测试过 AT45DB161D ，简单的读写是没问题的。

后面这颗 Flash 不会再维护了，以后会移除。
