### ISSUE TITLE
When enable audio and usb at the same time. The warning <"MIN" redefined> is shown. 

### ISSUE THREAD

**Issue by liuduanfei** [RT-Thread/rt-thread#3621]
audio.c:22:0: warning: "MIN" redefined
 #define MIN(a, b)         ((a) < (b) ? (a) : (b))
 ^
usb_common.h:497:0: note: this is the location of the previous definition
 #define MIN(a, b) (a < b ? a : b)
 ^

**Comment by BernardXiong** [comment]
Welcome to PR for audio.c, to judge this `MINI` firstly.

**Comment by Guozhanxin** [comment]
已修复：https://github.com/RT-Thread/rt-thread/pull/4033
