### ISSUE TITLE
[F1C100S] USH HS HOST integration for Allwinner F1C100S

### ISSUE THREAD

**Issue by Hoel** [RT-Thread/rt-thread#3648]
Hello,
Is there any direction on how to add the USB HOST support for F1C100S? I have the Sunxi low level drivers working in bare metal (usbc_dev.c, usbc_dma.c, usbc_host.c, usbc_i.h, usbc_phy.c, usbc_resource.c, usbc.h, usbc.c) but i dont clearly see what has to be done to use the RTTHread USB HS HOST core.
Thank you.

**Comment by BernardXiong** [comment]
USB Host or USB Device? Mostly, your bare metal code are USB device.

**Comment by Hoel** [comment]
Hello, we want to implement USB HOST. The bare metal code i have is extracted from u-boot, it is the official USB stack from sunxi, and it does cover both HOST and DEVICE mode (as well as DMA) but at low level only. To implement device from this code is simple, and there is no need for a higher level stack, however that is not the case for HOST mode.

**Comment by Hoel** [comment]
[F1C100S_USB_Driver_V1_1 2.zip](https://github.com/RT-Thread/rt-thread/files/4730121/F1C100S_USB_Driver_V1_1.2.zip)

This is the bare metal Eclipse project containing the files for low level driver files from Sunxi USB.

**Comment by Guozhanxin** [comment]
You can refer to the STM32 USB host driver https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drv_usbh.c

**Comment by thinpv** [comment]
> [F1C100S_USB_Driver_V1_1 2.zip](https://github.com/RT-Thread/rt-thread/files/4730121/F1C100S_USB_Driver_V1_1.2.zip)
> 
> This is the bare metal Eclipse project containing the low level driver files from USB Sunxi.
I am investigating this matter. Have you tried the usb host feature yet?
