### ISSUE TITLE
imx .rt系列bsp制作

### ISSUE THREAD

**Issue by ccx-lan** [RT-Thread/rt-thread#3657]
1、/docs文件夹上的Ii.MX RT 系列 BSP 制作教程 文档里中修改链接脚本sct文件时，m_text_size 计算的大小应该算错了；
2、/templates 文件夹里 board/imxrt1050xxx/board/Kconfig 里少了
select  RT_USING_COMPONENTS_INIT
select  RT_USING_USER_MAIN

**Comment by BernardXiong** [comment]
缺少的宏，欢迎PR上来

**Comment by tyustli** [comment]
this pull request have fix this bug https://github.com/RT-Thread/rt-thread/pull/3660
