### ISSUE TITLE
Xen

### ISSUE THREAD

**Issue by jwinarske** [RT-Thread/rt-thread#3671]
Greetings.

I am interested in running RT-Thread as a Xen Guest OS.  It looks like there has been some related work in this area (VBUS/VMM).  Is there a recommended configuration to start with?

Regards,
Joel Winarske

**Comment by BernardXiong** [comment]
Hello,
The vmm is rarely used. You may need to try it yourself first. For the AMP with vbus, you can do it with qemu-vexpress-gemini BSP.

**Comment by jwinarske** [comment]
Thanks I'll take a look.
