### ISSUE TITLE
Python2 specifics

### ISSUE THREAD

**Issue by mubes** [RT-Thread/rt-thread#3676]
In ba32394a00fee9b749ae0a7c690828bb38b028a7 the cmp operator has been added in tools/building.py.  This is obsolete from Python2. It would be better to `import operator` and use the methods defined there.

**Comment by BernardXiong** [comment]
@geniusgogo please fix this issue, thanks.

**Comment by geniusgogo** [comment]
@BernardXiong @mubes #3677

**Comment by BernardXiong** [comment]
@mubes Please check it. Thanks.

**Comment by mubes** [comment]
this is working great again now. Thanks.
