### ISSUE TITLE
K210 port 的ＦＰＵ设置问题

### ISSUE THREAD

**Issue by 13824125580** [RT-Thread/rt-thread#3726]
HI folks:
 K210的 port中将FS定义为如下的值，也即是0b11,有没有问题？，根据RV Spec和Linux内核的实现，FS为0b11表示的是dirty, 而非init, initial状态应该为0b10.
  #define MSTATUS_FS      0x00006000U /* initial state of FPU     */

**Comment by balanceTWK** [comment]
https://github.com/RT-Thread/rt-thread/pull/4046

已提交相关 PR：增加对 FPU 的支持。
