### ISSUE TITLE
at server parser error

### ISSUE THREAD

**Issue by ganhx** [RT-Thread/rt-thread#3751]
AT Server, 解析 =%s,%s,%s  格式失败， =%d,%d,%d 可以

**Comment by Lawlieta** [comment]
假设你现在需要解析的数据时 “=1,2,3\r\n”

%s 会解析到当前字符串 \0 结尾的数据，所以第一个 %s 就把该字符串所有数据都解析完了，造成你所述错误，可以由两种处理方式
1. 使用 "=%d,%d,%d” 方式解析
2. 如果 %d 方式解析有限制，比如非常大的一个数据，可以换种处理方式 “%*[^=]=%[^,],%[^,],%[^,]” 应该也是可以解析的

**Comment by ganhx** [comment]
是的，可以用这种方式解析 %s, %s, %s 问题。万分感谢！
