### ISSUE TITLE
同一个timer下多channel生成不同频率的pwm支持?

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [RT-Thread/rt-thread#3771]
如题, 能否增加对于同一个timer, 多channel, 生成不同频率的pwm的支持? 相对比较节约定时器.
stm32的裸机下, 看很多人是用输出比较来实现的, 不知道能不能将这个列入支持的计划

**Comment by BernardXiong** [comment]
欢迎PR

**Comment by jinbangju** [comment]
估计做不到 按照这个说法需要4个CNT 4个ARR 4个CCR寄存器 可以定时器的输出捕获来反转 可以参考一个定时器控制4轴电机

**Comment by BernardXiong** [comment]
也许。实际上这块还是得看大家的，或许这个中间也会有些独门绝技，我这边更多关注OS本身

**Comment by mysterywolf** [comment]
这个是做不到的，这个是芯片硬件设计需要实现的。芯片定时器内部依靠一个统一的时钟源为4个通道提供时基信号。程序上唯一能实现的就是每几次时钟就中断一次，通过软件进行降频，这将会导致软件反复、高频次进入中断，得不偿失。
