### ISSUE TITLE
Hard fault occurred with tag 4.0.2 on frdmk64f armgcc build

### ISSUE THREAD

**Issue by willisyi** [RT-Thread/rt-thread#3778]
Logs as below:
 \ | /
- RT -     Thread Operating System
 / | \     4.0.2 build Jul 27 2020
 2006 - 2019 Copyright by rt-thread team
psr: 0x00000000
r00: 0x20030000
r01: 0x10000000
r02: 0xf0000000
r03: 0x20003a9c
r04: 0x000000f4
r05: 0x00000000
r06: 0x00000000
r07: 0x00011ea0
r08: 0x00000000
r09: 0x00000000
r10: 0x00000000
r11: 0x00000000
r12: 0x00000000
 lr: 0x000066ef
 pc: 0x0002c580
hard fault on handler

usage fault:
SCB_CFSR_UFSR:0x02 INVSTATE

**Comment by willisyi** [comment]
After power on reset it works now. Previously I performed reset using J-Link.

**Comment by BernardXiong** [comment]
🆗 That's fine.
