### ISSUE TITLE
关于FATFS文件系统命名的问题

### ISSUE THREAD

**Issue by mysterywolf** [RT-Thread/rt-thread#3805]
我注意到在RT-Thread中所有涉及到FatFs文件系统的env配置、文档说明、以及挂载文件系统时的命名(fs_name)都是用的"ELM FatFs"或者直接称之为"elm"。
    这个文件系统名字叫做FatFs
    作者叫ChaN 是个日本人
    elm是The Electronic Lives Manufacturing的缩写，是作者的座右铭或者口号一类的东西。详见作者主页的标题：http://elm-chan.org/
    所以，为什么要用人家的座右铭来命名文件系统啊，是将elm理解错为这个作者的名了吗？而且单说elm会让人误解为其他什么新的文件系统
   建议命名为'fatfs' 或者'fat'

**Comment by BernardXiong** [comment]
There are certain historical reasons for this one.
