### ISSUE TITLE
UDP 接收丢包采用IPOP软件无延时发送

### ISSUE THREAD

**Issue by cychen88** [RT-Thread/rt-thread#3809]
利用UDP对RTT系统洪水测试，接收数据会丢包。IPOP软件采用无延时发送 单片机收到后用sendto会给IPOP软件发现都会丢数据 发100包 没试过一次全收完。芯片是LPC54608和STM32F764 都不能接收完整。利用LPC54608 采用FreeRtos 使用同样发包及回数据方式 FreeRtos能够完整接收并回复。感觉采用Rx线程导致

**Comment by BernardXiong** [comment]
逻辑能整理下吗。文本几乎用空格来代替标点了
