### ISSUE TITLE
GD32E230 使用Keil报错

### ISSUE THREAD

**Issue by HoGC** [RT-Thread/rt-thread#3813]
clone后直接使用keil编译GD32E230，报错
ArmClang: error: unsupported option '--c99'

**Comment by BernardXiong** [comment]
可以使用AC5，或者在工程选项中把这个`--c99`拿掉

**Comment by HoGC** [comment]
如何删去c99，再哪里配置

**Comment by HoGC** [comment]
AC5是ARM Compiler选择V5.06吗，编译报错
Fatal error: C3903U: Argument 'NOT_SUPPORTED' not permitted for option 'cpu'.

**Comment by HoGC** [comment]
我修改了Project.uvprojx(687)
```
//<MiscControls> --c99</MiscControls>
<MiscControls> </MiscControls>
```
已经可以编译了，这个操作是正确的吧
