### ISSUE TITLE
mem.c文件应该用互斥量代替信号量以规避潜在的优先级翻转的问题，如果您认可的话 我就提pr了

### ISSUE THREAD

**Issue by mysterywolf** [RT-Thread/rt-thread#3816]
https://github.com/RT-Thread/rt-thread/blob/d463a5a0bad360c0ba17bf60356683317f1e20ae/src/mem.c#L133

**Comment by geniusgogo** [comment]
优先级翻转的问题根源自于IPC支持了fifo队列。:)

**Comment by mysterywolf** [comment]
> 优先级翻转的问题根源自于IPC支持了fifo队列。:)

我理解你的意思，但是我说的优先级翻转是传统RTOS概念上的优先级翻转。而且你说的也是个问题，本文件中采用的是FIFO，而非PRIO。

**Comment by geniusgogo** [comment]
嗯，官方目前对此类问题视而不见。不过你可以提pr，会不会被merge就不知道了。

**Comment by BernardXiong** [comment]
对于mem管理这块的，当时是感觉mem allocate的过程应该可以很短暂，所以用的semaphore。如果是使用mutex的话，那么系统就一定需要mutex才能干活了。所以考虑点是，semaphore更轻量级些。

**Comment by mysterywolf** [comment]
那根据现在rtt的发展战略 您认为还需要改吗？要是需要我就提pr了。

**Comment by mysterywolf** [comment]
可不可以这样 通过宏定义判断用户是否启用mutex 如果启用mutex就优先使用mutex 如果没有启用则选择sem @BernardXiong
