### ISSUE TITLE
softtimer BUG记录

### ISSUE THREAD

**Issue by geniusgogo** [RT-Thread/rt-thread#3817]
https://github.com/RT-Thread/rt-thread/blob/d463a5a0bad360c0ba17bf60356683317f1e20ae/src/timer.c#L609-L628

由于这里的list遍历会出现严重的迭代失效问题，导致softtimer任务死循环。
正确的处理方式应该和系统timerlist一致。

**Comment by BernardXiong** [comment]
迭代失效是啥情况

**Comment by geniusgogo** [comment]
> 迭代失效是啥情况

n->next有可能被stop了。
