### ISSUE TITLE
pthread_cond_destroy问题

### ISSUE THREAD

**Issue by zmj64351508** [RT-Thread/rt-thread#3870]
int ret;
pthread_cond_t hdl;
pthread_cond_init(&hdl, NULL);
ret = pthread_cond_destroy(&hdl);

问题：运行以上代码ret最终是EBUSY。看了下代码，rt_sem_trytake在计数为0的情况下会返回-RT_ETIMEOUT，pthread_cond_destroy会判断rt_sem_trytake的返回值，一旦不是RT_OK就返回EBUSY。

希望的结果：上述代码运行后ret应该是0。

**Comment by BernardXiong** [comment]
多谢反馈，后面修正下

**Comment by KyleChenjh** [comment]
@zmj64351508  rt_sem_trytake在计数为0，并且time为0条件下，返回应该就是-RT_ETIMEOUT，然后pthread_cond_destroy去判断这个返回值时候，就应该是EBUSY状态的。因为它没成功获取到信号量，所以也不能clean condition。

**Comment by Guozhanxin** [comment]
楼主确认下问题吧，如果没问题，这个issue就关闭吧
