### ISSUE TITLE
DFS fgets

### ISSUE THREAD

**Issue by WGR7** [RT-Thread/rt-thread#3889]
Hi,

Is there support for fgets using DFS(elmfat)?

Regards

**Comment by BernardXiong** [comment]
what's that? fgets is the POSIX API. If you use libc, this API should be 🆗.

**Comment by mysterywolf** [comment]
Hi, 
you can use this macro `RT_USING_LIBC` to enable this function and all of the standard C functions. If you want to use some functions which are regarding the file systems, you should also enable `RT_USING_DFS` and `RT_USING_POSIX`
Regards
