### ISSUE TITLE
IDE支持

### ISSUE THREAD

**Issue by git-binbin** [RT-Thread/rt-thread#3892]
我觉得除了keil、IAR、RT-Thread Studio等，
还需要支持一个IDE，
它是VisualGDB，其实是Visual Studio的一款插件。
它的官网是
( https://visualgdb.com/ )
同样支持创建嵌入式工程、STM32工程(Embedded Project Wizard 选项)等

**Comment by mysterywolf** [comment]
这个东西的本质就是gcc编译链吗？

**Comment by GIT111222** [comment]
是的，主要是内核层(开关中断、上下文切换等)，有移植好的代码嘛？

**Comment by mysterywolf** [comment]
这个和编译器/工具链有啥关系吗？ 这个不应该是cpu平台的问题吗

**Comment by BernardXiong** [comment]
欢迎PR

**Comment by GIT111222** [comment]
那意思是说，内核移植的部分得我们用户按照在mdk或IAR的写法自己去写咯

**Comment by GIT111222** [comment]
好的，那内核移植部分，我自己写一下，最近也看到了一些例子，区别不大，同样的汇编指令只是语法写法与MDK等软件不一样

**Comment by GIT111222** [comment]
我试试看吧
