### ISSUE TITLE
STM32F429 u盘重新插拔时，U盘无法再次写入数据

### ISSUE THREAD

**Issue by circlegan** [RT-Thread/rt-thread#3894]
我的RT-Thread版本为v4.0.2，单片机启动后，插入U盘，可正常识别和读写。但重新插拔后，可以识别U盘，却无法“写打开”U盘文件。调试发现第一次插入U盘时，其挂载格式为elm，再次插入时，就挂载成了rom，所以无法“写打开”成功，请问这个问题有谁遇到过没？

**Comment by BernardXiong** [comment]
需要有更多的信息的。

热拔插应该是有个自动重新装载的过程，可以看看装载部分逻辑是否一致

**Comment by Guozhanxin** [comment]
你用最新的代码再试一次，我们这边测试是没问题的

**Comment by balanceTWK** [comment]
我这边使用最新的 stm32f429-atk-apollo BSP 测试 U 盘，没有复现上诉问题。

建议使用最新的代码重新测试下！如果还没有解决，可以再打开这个 issue 。
