### ISSUE TITLE
MDK ARMCLANG build error

### ISSUE THREAD

**Issue by geniusgogo** [RT-Thread/rt-thread#3902]
../middleware/rt-thread/include\rtthread.h(24): warning: In file included from...
../middleware/rt-thread/include\rtdef.h(1094): warning: In file included from...
../middleware/rt-thread/include/rtlibc.h(15): warning: In file included from...
../middleware/rt-thread/include/libc/libc_stat.h(14): error: 'sys/stat.h' file not found

**Comment by BernardXiong** [comment]
@mysterywolf  Please check them carefully.

**Comment by mysterywolf** [comment]
got it 麻烦标个bug label

**Comment by mysterywolf** [comment]
bug已排除 @BernardXiong  @geniusgogo

**Comment by geniusgogo** [comment]
你提交在哪里了？

**Comment by geniusgogo** [comment]
@mysterywolf 单独发我一份patch，我先测试一下

**Comment by mysterywolf** [comment]
@geniusgogo  https://github.com/mysterywolf/rt-thread 你可以fork一份

**Comment by geniusgogo** [comment]
> @geniusgogo https://github.com/mysterywolf/rt-thread 你可以fork一份

可以了，我这里编译通过

**Comment by mysterywolf** [comment]
> > @geniusgogo https://github.com/mysterywolf/rt-thread 你可以fork一份
> 
> 可以了，我这里编译通过

@BernardXiong  OK了

**Comment by BernardXiong** [comment]
PR呢？合并在哪？

**Comment by mysterywolf** [comment]
> PR呢？合并在哪？

https://github.com/RT-Thread/rt-thread/pull/3898 这里

**Comment by mysterywolf** [comment]
这个issue可以关了 @geniusgogo
