### ISSUE TITLE
[bsp/nordic] bsp_nordic bsp清理

### ISSUE THREAD

**Issue by supperthomas** [RT-Thread/rt-thread#3908]
![image](https://user-images.githubusercontent.com/60349489/93019560-66060d80-f60a-11ea-84e8-8dd3cec5e3e7.png)

master上面的bsp有两个文件夹，看上去似乎有些编译不过或者没法使用，这边我也没摸清楚具体如何使用。还有个文件夹还有nordic的sdk。
目前bsp/nrf5x的bsp不知道是否已经覆盖这两个文件夹功能了，是否需要考虑删掉这两个文件夹？因为里面的文件还挺多的。

**Comment by BernardXiong** [comment]
如果覆盖，可以考虑移除
