### ISSUE TITLE
rtc中time函数在vs，编译时和已有函数冲突

### ISSUE THREAD

**Issue by www220** [RT-Thread/rt-thread#392]
#if defined (__IAR_SYSTEMS_ICC__) &&  (__VER__) >= 6020000
#pragma module_name = "?time"
time_t (__time32)(time_t *t) /* Only supports 32-bit timestamp */
#elif defined (_MSC_VER)
time_t _time32(time_t *t)
#else
time_t time(time_t *t)
#endif

**Comment by BernardXiong** [comment]
Hi @prife, 
Any update about this issue?

**Comment by BernardXiong** [comment]
@www220 
Do you have patch about this issue? If you have, please pull a merge quest. Thank you.
