### ISSUE TITLE
提PR防入坑指南 | Please look at this issue before you want to pull request(s)

### ISSUE THREAD

**Issue by mysterywolf** [RT-Thread/rt-thread#3922]
### 1.判断GCC编译环境
不要这么写
```c
#if defined ( __GNUC__)
。。。
#endif
```
要这么写
```c
#if (defined( __GNUC__ ) && !defined(__CLANG_ARM))
。。。
#endif

```
因为在AC6（即ARM CLANG）环境下，也会定义__GNUC__这个标志，但是不提供实质的<sys/xxxx.h>头文件，因此在clang环境下编译会出现这些头文件以及相关的数据类型找不到的错误。

**Comment by Guozhanxin** [comment]
不光 AC6，5的版本也提供 GNU 扩展，当开启扩展后也会定义 __GNUC__ 这个宏。。。

![image](https://user-images.githubusercontent.com/25633294/93431412-af01de80-f8f6-11ea-8f79-59c5d5cf2878.png)

**Comment by BernardXiong** [comment]
@mysterywolf 原来都是依靠次序来区分的，即：

先是否是ARMCC，是否是ARMCLANG，然后才是，是否是GCC
