### ISSUE TITLE
clock.c第91行获得线程句柄有可能会失败，应该判断非RT_NULL再进行下面的操作

### ISSUE THREAD

**Issue by homolumo** [RT-Thread/rt-thread#393]
thread = rt_thread_self();
if (thread) {...}

出现thread为空，导致进入FaultISR。
使用tm4c129x时修改rtconfig.h
#define RT_TICK_PER_SECOND 1000
则系统在1ms内无法进入init线程，仍然在打印版本信息show_version()，导致thread获取为空。

**Comment by ArdaFu** [comment]
Fix at #431
