### ISSUE TITLE
[roadmap] common/time.c & common/sys/time.h

### ISSUE THREAD

**Issue by mysterywolf** [RT-Thread/rt-thread#3938]
目前已经发现的问题：
该sys/time.h文件缺少struct timespec结构体定义
```c
/*
 * Structure defined by POSIX.1b to be like a timeval.
 */
struct timespec {
	time_t	tv_sec;		/* seconds */
	long	tv_nsec;	/* and nanoseconds */
};
```

------------------------------
**该问题已经修复 2021.1.1**

**Comment by BernardXiong** [comment]
当加入musl后，这块又出问题了

**Comment by mysterywolf** [comment]
TODO:时区、夏令时问题将留到下个版本进行修改

**Comment by mysterywolf** [comment]
DWORD get_fattime(void) 函数 RT_USING_LIBC宏使用有些问题，即便没有定义libc也可以使用time函数的。后续需要修改。

**Comment by mysterywolf** [comment]
RTC驱动框架需要增加一种方案：用线程维持 硬件定期校准。防止频繁访问芯片时间等待过长。

**Comment by mysterywolf** [comment]
> 当加入musl后，这块又出问题了

我将会接手这个问题

**Comment by mysterywolf** [comment]
联动&相关：#4337

**Comment by mysterywolf** [comment]
需要排查底层驱动在获取时间是调用非线程安全是否加调度锁的问题

**Comment by mysterywolf** [comment]
此issue计划完成，时区问题过于复杂，推迟到下个大版本中完成。
