### ISSUE TITLE
能否支持tricore系列芯片？

### ISSUE THREAD

**Issue by snikeguo** [RT-Thread/rt-thread#3941]
目前tricore体系结构用的是tricore1.6版本的ip核；
代表芯片有tc275，三个核，对称smp；
开发环境是aurix development studio；
有类似于stm32标准库的外设库源码，叫做illd库；
用在汽车ecu上，目前threadx也支持这个芯片。问下rtt官方能否支持一下此cpu体系结构，我代表汽车行业先谢谢rtt官方

**Comment by BernardXiong** [comment]
不太了解这块，或者可以邮件联系我，一起来进行沟通吗？ 
![image](https://user-images.githubusercontent.com/1241087/94783476-50148d00-03ff-11eb-826a-a802f970037b.png)

**Comment by BernardXiong** [comment]
这个架构芯片的支持已经在推进中了，后续会逐步有相关的信息出来。

**Comment by snikeguo** [comment]
厉害了RTT~

**Comment by snikeguo** [comment]
@BernardXiong 我这有一份FreeRTOS单核的移植，在我项目上一直在用。
https://gitee.com/snikeguo/tc275_illd_freertos_led_demo/blob/master/FreeRTOS/portable/port.c
