### ISSUE TITLE
[question] IWDG not work under RT-Thread Studio.

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [RT-Thread/rt-thread#3980]
参考问题的详细，有劳大神了
https://club.rt-thread.org/ask/question/428787.html

**Comment by BernardXiong** [comment]
Please check your low level driver or debug it step by step under RT-Thread Studio.

**Comment by TRSK-CONMI** [comment]
> Please check your low level driver or debug it step by step under RT-Thread Studio.

Hello,Mr.BernardXiong.They are all up to date

**Comment by TRSK-CONMI** [comment]
It entered “rt_wdt_init()” and “return RT_EOK”, 
but I later saw in the main function that “rt_device_find("wdt")” returned null

**Comment by TRSK-CONMI** [comment]
The development board selected for project creation is STM32F103C8T6

**Comment by balanceTWK** [comment]
https://www.rt-thread.org/document/site/programming-manual/device/watchdog/watchdog/

这里有详细的看门狗使用方法。
