### ISSUE TITLE
/bsp/allwinner_tina/driver/spi/drv_spi.c  486行，判断有问题。

### ISSUE THREAD

**Issue by YellowTre** [RT-Thread/rt-thread#3993]
switch (configuration->mode)这一行。如果设置的 cfg.mode = RT_SPI_MASTER | RT_SPI_MODE_1 | RT_SPI_MSB; 
则 RT_SPI_MODE_1 ！= RT_SPI_MASTER | RT_SPI_MODE_1 | RT_SPI_MSB； 无法成功设置。

**Comment by BernardXiong** [comment]
Welcome submit a PR.

**Comment by mysterywolf** [comment]
如何给rtthread提pr参见：https://www.bilibili.com/video/BV1gr4y1w7yX

**Comment by eYoung8475** [comment]
pr #4017已经解决，可以关闭
