### ISSUE TITLE
调用set_if6函数设置静态ipv6地址，导致线程tcpip的hard fault

### ISSUE THREAD

**Issue by Hotwill** [RT-Thread/rt-thread#400]
![image](https://cloud.githubusercontent.com/assets/7548705/5557833/c2a2fc40-8d49-11e4-8cf8-fa2a0b625f40.png)
图片中的SetIf6就是set_if6.

finsh输出的错误信息：
![image](https://cloud.githubusercontent.com/assets/7548705/5557839/f762bc7c-8d49-11e4-80a9-b8a9fdbe1740.png)

**Comment by BernardXiong** [comment]
@hduffddybz please check it.

**Comment by hduffddybz** [comment]
Any information can provide that how to reproduce this issue?
