### ISSUE TITLE
关于stm32F429st的官方bsp的内存问题

### ISSUE THREAD

**Issue by chunyexixiaoyu** [RT-Thread/rt-thread#4048]
1. 在使用过程中，本来ram为192+64kb大小，但是发现map文件中ram最大限制为128kn也就是0x20000，后
来经过QQ群李子木哥哥的帮助，是link.sct 里面写错的问题。

2.另外master分支无法编译必须把相关的库去掉才行（pthread）

**Comment by BernardXiong** [comment]
您好，可以给个具体的bsp名字吗？

**Comment by chunyexixiaoyu** [comment]
> 您好，可以给个具体的bsp名字吗？

https://github.com/RT-Thread/rt-thread/tree/master/bsp/stm32/stm32f429-st-disco
另外这个master的bsp是拿出来无法编译的

**Comment by mysterywolf** [comment]
你好这个bsp是由社区小伙伴维护的 如果知道怎么修改欢迎直接提PR 如果不知道怎么修改可以在对应BSP路径下找到README文档，在文档的最后有维护人的联系方式

**Comment by chunyexixiaoyu** [comment]
好的



---原始邮件---
发件人: "Meco Man"<notifications@github.com&gt;
发送时间: 2020年11月22日(周日) 晚上8:02
收件人: "RT-Thread/rt-thread"<rt-thread@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"chunyexixiaoyu"<834670833@qq.com&gt;;
主题: Re: [RT-Thread/rt-thread] 关于stm32F429st的官方bsp的内存问题 (#4048)




 
你好这个bsp是由社区小伙伴维护的 如果知道怎么修改欢迎直接提PR 如果不知道怎么修改可以在对应BSP路径下找到README文档，在文档的最后有维护人的联系方式

**Comment by xuzhuoyi** [comment]
我是这个bsp的维护人，这个问题我处理一下吧。

**Comment by chunyexixiaoyu** [comment]
> 我是这个bsp的维护人，这个问题我处理一下吧。

两个问题，1个是不能编译应该是menuconfig配置的 问题，另外一个是连接文件ram尺寸不对，linux底下的和keil用的都不对。linux写的是320kb 应该是192

**Comment by xuzhuoyi** [comment]
好的，我看一下

**Comment by mysterywolf** [comment]
#4077
