### ISSUE TITLE
软件包与rtconfig.h的关联问题

### ISSUE THREAD

**Issue by geniusgogo** [RT-Thread/rt-thread#4093]
现在在env下运行menuconfig不进行任何配置就退出后，也会因为软件包的更新影响到rtconfig.h里面的内容修改。
这个反馈很多次类似的问题，一直没有得到解决。
希望重视起来！

**Comment by BernardXiong** [comment]
有办法可以解决吗？或者有份总的选项，RT_USING_PKGS，然后开始打开一些online的packages，否则都是关闭的。

**Comment by geniusgogo** [comment]
这份总的选项貌似一直会根据上游更新。
而我反馈的这个问题貌似与这个不直接相关。
我这里是不进行任何的更改，启动~退出，即发生变化（rtconfig.h产生了差异）！

**Comment by BernardXiong** [comment]
如果没有使用在线软件包，也就是这个RT_USING_PKGS不定义，则online packages一切更改都和这个无关。
