### ISSUE TITLE
[TO DO] RISC-V 浮点上下文切换优化。

### ISSUE THREAD

**Issue by balanceTWK** [RT-Thread/rt-thread#4120]
RISC-V mstatus 寄存器中的 SD 位域用于记录浮点寄存器中是否有脏数据。

rt-thread 上下文切换可以利用这个位域来判断浮点相关上下文是否需要保存。这样可以提高上下文切换的效率。

**Comment by BernardXiong** [comment]
请更新状态，处理好了，这个issue就关闭吧

**Comment by mysterywolf** [comment]
糖爷 这个issue是否关闭 还是保持开启
