### ISSUE TITLE
ESP32 Support

### ISSUE THREAD

**Issue by WGR7** [RT-Thread/rt-thread#4121]
Hi
Is there any plan to add support to ESP32 boards?

**Comment by BernardXiong** [comment]
There are some unofficial porting for ESP32. And it's interesting that the ESP32-C3 is a WiFi SoC with RISC-V core. There may be an BSP in RT-Thread later.

**Comment by WGR7** [comment]
Thanks

**Comment by hyt-klc** [comment]
Hello dear.
Now rt-thread supports RISC-V processors.
Are there any plans to add support for ESP32 processors and dev boards?
