### ISSUE TITLE
这里头文件包含还有问题。

### ISSUE THREAD

**Issue by liuduanfei** [RT-Thread/rt-thread#4140]
https://github.com/RT-Thread/rt-thread/blob/4f7cff88d08f0a2de87573a577dcd25b6e7f5544/components/drivers/include/drivers/audio.h#L16

audio.h包含了audio_pipe.h，audio_pipe.h里面包含了rtdevice.h，rtdevice.h又包含了audio.h，导致编译得时候出现：

audio.h:150:26: error: field 'pipe' has incomplete type struct rt_audio_pipe pipe;

**Comment by thread-liu** [comment]
根据 PR ：https://github.com/RT-Thread/rt-thread/pull/4055  的修改， IAR 和 Studio 编译都会出问题：  
IAR:  
![image](https://user-images.githubusercontent.com/44889940/101726434-7b95b100-3aed-11eb-8c45-48bb9fb9909e.png)
Studio:  
![image](https://user-images.githubusercontent.com/44889940/101726578-c57e9700-3aed-11eb-8ec0-a48fa34a52c8.png)

**Comment by liuduanfei** [comment]
> 根据 PR ：#4055 的修改， IAR 和 Studio 编译都会出问题：
> IAR:
> ![image](https://user-images.githubusercontent.com/44889940/101726434-7b95b100-3aed-11eb-8c45-48bb9fb9909e.png)
> Studio:
> ![image](https://user-images.githubusercontent.com/44889940/101726578-c57e9700-3aed-11eb-8ec0-a48fa34a52c8.png)

是的，在audio_pipe.c中加上 #include<rtdevice.h>能解决编译错误的问题，但是这里头文本包含还是别扭着。

**Comment by thread-liu** [comment]
在 PR ： https://github.com/RT-Thread/rt-thread/pull/4055/files 的基础上修改 audio_pipe.h :
#include <rtdevice.h> -> #include "ipc/ringbuffer.h"

**Comment by liuduanfei** [comment]
> 在 PR ： https://github.com/RT-Thread/rt-thread/pull/4055/files 的基础上修改 audio_pipe.h :
> #include <rtdevice.h> -> #include "ipc/ringbuffer.h"
> 这样 audio_pipe.h 就不会包含 audio.h, 编译也可以通过

嗯嗯，这样也可以。
