### ISSUE TITLE
k210 使用rw007 lwip协议使用2.1.2版本导致出问题

### ISSUE THREAD

**Issue by chunyexixiaoyu** [RT-Thread/rt-thread#4176]
heap: [0x8005f058 - 0x80600000]
initialize rti_board_start:0 done
initialize io_config_init:0 done
initialize rt_hw_pin_init:0 done

 \ | /
- RT -     Thread Operating System
 / | \     4.0.3 build Dec 18 2020
 2006 - 2020 Copyright by rt-thread team
do components initialization.
initialize rti_board_end:0 done
initialize dfs_init:0 done
initialize lwip_system_init
Exception:
Store address misaligned
x1 (ra   : Return address                ) ==> 0x00000000800109c4
x2 (sp   : Stack pointer                 ) ==> 0x8000000000007880
x3 (gp   : Global pointer                ) ==> 0x2323232323232323
x4 (tp   : Thread pointer                ) ==> 0x00000000deadbeef
x5 (t0   : Temporary                     ) ==> 0x000000008000036c
x6 (t1   : Temporary                     ) ==> 0x000000000000000f
x7 (t2   : Temporary                     ) ==> 0xffffffffffffffff
x8 (s0/fp: Save register,frame pointer   ) ==> 0x0000000080050b2c
x9 (s1   : Save register                 ) ==> 0x000000008003e490
x10(a0   : Function argument,return value) ==> 0x0000000080050b54
x11(a1   : Function argument,return value) ==> 0x0000000000000604
x12(a2   : Function argument             ) ==> 0x000000000000000c
x13(a3   : Function argument             ) ==> 0x0000000080000378
x14(a4   : Function argument             ) ==> 0x00000000800504f0
x15(a5   : Function argument             ) ==> 0x000000008004b0f0
x16(a6   : Function argument             ) ==> 0x0000000000000010
x17(a7   : Function argument             ) ==> 0x0000000000000000
x18(s2   : Save register                 ) ==> 0x0000000000000002
x19(s3   : Save register                 ) ==> 0x000000008003a2b8
x20(s4   : Save register                 ) ==> 0x00000000deadbeef
x21(s5   : Save register                 ) ==> 0x00000000deadbeef
x22(s6   : Save register                 ) ==> 0x00000000deadbeef
x23(s7   : Save register                 ) ==> 0x00000000deadbeef
x24(s8   : Save register                 ) ==> 0x00000000deadbeef
x25(s9   : Save register                 ) ==> 0x00000000deadbeef
x26(s10  : Save register                 ) ==> 0x00000000deadbeef
x27(s11  : Save register                 ) ==> 0x00000000deadbeef
x28(t3   : Temporary                     ) ==> 0x0000000000000020
x29(t4   : Temporary                     ) ==> 0x0000000000000000
x30(t5   : Temporary                     ) ==> 0x0000000000000001
x31(t6   : Temporary                     ) ==> 0x0000000000000020
exception pc => 0x800109bc

8位对其，在2.0.2 版本是可以的，在2.1.2版本是不行的。应该是2.1.2兼容性的问题

**Comment by chunyexixiaoyu** [comment]
![F3PJ5U$ PA`8(3B$2YLNL0O](https://user-images.githubusercontent.com/24492495/102595796-298b0600-4153-11eb-93bb-7fe4b7175798.png)

**Comment by BernardXiong** [comment]
这个是初始化就错误了？

**Comment by chunyexixiaoyu** [comment]
> 这个是初始化就错误了？
是的，我移植的rw007包现在是可以用了，但是我menuconfig 选择lwip协议版本的时候选择最新的会报上面的错误，然后在设置里面都写了8字节对齐 存储

**Comment by BernardXiong** [comment]
> > 这个是初始化就错误了？
> > 是的，我移植的rw007包现在是可以用了，但是我menuconfig 选择lwip协议版本的时候选择最新的会报上面的错误，然后在设置里面都写了8字节对齐 存储

还请给个清晰的说明，

1. 选择了v2.1.2版本lwIP？
2. 然后默认4字节对齐初始化报错？
3. 还是说，设置8字节对齐也报错？

**Comment by chunyexixiaoyu** [comment]
> > > 这个是初始化就错误了？
> > > 是的，我移植的rw007包现在是可以用了，但是我menuconfig 选择lwip协议版本的时候选择最新的会报上面的错误，然后在设置里面都写了8字节对齐 存储
> 
> 还请给个清晰的说明，
> 
> 1. 选择了v2.1.2版本lwIP？
> 2. 然后默认4字节对齐初始化报错？
> 3. 还是说，设置8字节对齐也报错？

选择了2.12lwip 然后设置8字节对齐就是上面的现象。选择2.12上一个版本选择8字节对齐没错。k210 64位单片机应该是要选择8字节对齐的吧？

**Comment by heyuanjie87** [comment]
2.0.2的lwipopts.h是这样写的
#ifdef RT_LWIP_MEM_ALIGNMENT
#define MEM_ALIGNMENT RT_LWIP_MEM_ALIGNMENT
#else
#define MEM_ALIGNMENT               4
#endif

你复制到2.1.2试试，里面是写死的4

**Comment by chunyexixiaoyu** [comment]
> 2.0.2的lwipopts.h是这样写的
> #ifdef RT_LWIP_MEM_ALIGNMENT
> #define MEM_ALIGNMENT RT_LWIP_MEM_ALIGNMENT
> #else
> #define MEM_ALIGNMENT 4
> #endif
> 
> 你复制到2.1.2试试，里面是写死的4

是这个问题，那就是2.1.2代码的bug了 里面没有进行if else 的判断 。我直接把2.1.2里面的宏定义写成8是可以运行的
