### ISSUE TITLE
K210 使用RW007 Lwip 版本导致的问题 2.0.2可以使用 2.1.2不可以使用

### ISSUE THREAD

**Issue by chunyexixiaoyu** [RT-Thread/rt-thread#4183]
![1GGLNJTYK$6DNYEG` %9DMX](https://user-images.githubusercontent.com/24492495/102735300-017eeb00-437d-11eb-855c-ca1ae0a89948.png)
![4ZUH18YW}ZKZ F0LSBBN 2](https://user-images.githubusercontent.com/24492495/102735304-0348ae80-437d-11eb-9bb6-453fedad4387.jpg)

**Comment by chunyexixiaoyu** [comment]
上次是K210 使用rw007 lwip2.1.2内存对齐的事情已经解决

**Comment by BernardXiong** [comment]
目前是好还是不好？如果解决了，可以把这个issue给close了

**Comment by chunyexixiaoyu** [comment]
> 目前是好还是不好？如果解决了，可以把这个issue给close了

老师，目前是k210+rw007 在使用lwip协议时，会发现2.1.2版本的lwip无法使用在连接wifi的过程会出现上述图片的问题。之前的问题是由于2.1.2版本里面字节对齐写死4 导致的然后改成8好了。之前的问题已经close，现在的问题还没有解决。

**Comment by BernardXiong** [comment]
可以考虑把etx、erx的任务栈加大，因为K210是64位的，它的栈占用会更大了
