### ISSUE TITLE
NXP i.MXRT1050/1060  GPIO Interrupt bug in drv_gpio.c driver file

### ISSUE THREAD

**Issue by jicheng0622** [RT-Thread/rt-thread#4184]
In drv_gpio.c, The pin_start input of imxrt_isr API in GPIOx_Combined_16_31_IRQHandler should be changed to 16 instead of 15. The GPIO(x, 31) interrupt flag can not be cleared with the original 15, which results into CPU dead in ISR if GPIO(x,31) interrupt is enabled and its event is detected.

![drv_gpio](https://user-images.githubusercontent.com/3296827/102745904-10bf6200-4398-11eb-8175-5e5919a270db.JPG)

**Comment by BernardXiong** [comment]
@Guozhanxin Please take a look.

**Comment by jicheng0622** [comment]
hi @willianchanlovegithub，

Have you verify this issue and do we have plan to fix this issue? THanks.

**Comment by willianchanlovegithub** [comment]
@jicheng0622 Sure, We will fix it. Thanks for you proposal.

**Comment by Guozhanxin** [comment]
@jicheng0622 If you have confirmed and fixed this problem, you can mention PR to fix it.

**Comment by mysterywolf** [comment]
@Guozhanxin  I think we should add a bug label to this issue.

**Comment by mysterywolf** [comment]
在此处修复：https://github.com/RT-Thread/rt-thread/pull/6220
