### ISSUE TITLE
STM32F746G-Discovery 在RT-thread下进行浮点运算会报错

### ISSUE THREAD

**Issue by DUXin-ece** [RT-Thread/rt-thread#4186]
具体错误：fault: SCB_CFSR_UFSR:0x01 UNDEFINSTR

**Comment by DUXin-ece** [comment]
测试代码如下：
![image](https://user-images.githubusercontent.com/68297313/102860802-7f202500-4469-11eb-8609-75777bfd82ef.png)

烧录后运行程序结果如下：
![Uploading image.png…]()

**Comment by DUXin-ece** [comment]
测试代码如下：
![image](https://user-images.githubusercontent.com/68297313/102860869-9fe87a80-4469-11eb-9658-27dcd48ae849.png)
烧录后运行结果如下：
![image](https://user-images.githubusercontent.com/68297313/102860896-b098f080-4469-11eb-94ff-642419800f81.png)

**Comment by chunyexixiaoyu** [comment]
楼上是我们实验室的小伙厉害了

**Comment by BernardXiong** [comment]
> 楼上是我们实验室的小伙厉害了

😄 为什么厉害了？别人天生厉害吧。这个问题可以看看栈的情况，或者一些编译器的选项配置。

**Comment by DUXin-ece** [comment]
> > 楼上是我们实验室的小伙厉害了
> 
>  为什么厉害了？别人天生厉害吧。这个问题可以看看栈的情况，或者一些编译器的选项配置。

老师您好，目前该问题已解决。该问题是由于rtthread在gcc编译平台下和FPU相关的flag设置错误引起的。STM32F74X系列只支持单精度浮点运算，因此`-mfpu`应该设置为`fpv5-sp-d16`。已经提交了Pull Request。

**Comment by BernardXiong** [comment]
> > > 楼上是我们实验室的小伙厉害了
> > 
> > 
> > 为什么厉害了？别人天生厉害吧。这个问题可以看看栈的情况，或者一些编译器的选项配置。
> 
> 老师您好，目前该问题已解决。该问题是由于rtthread在gcc编译平台下和FPU相关的flag设置错误引起的。STM32F74X系列只支持单精度浮点运算，因此`-mfpu`应该设置为`fpv5-sp-d16`。已经提交了Pull Request。

Thank you so much. You are the best one! 👍
