### ISSUE TITLE
[BUG] SystemClock_Config is missing

### ISSUE THREAD

**Issue by M0n7y5** [RT-Thread/rt-thread#4229]
Hi,
i am trying to follow these steps in `board.h`, but it looks like `SystemClock_Config` from `board.c` is missing... 
I am using rt-thread v4.0.2 Standard

## `board.h`
![obrazek](https://user-images.githubusercontent.com/17201053/103878693-0fe83900-50d7-11eb-9b71-d91bdf12d3c1.png)

## `board.c`
![obrazek](https://user-images.githubusercontent.com/17201053/103878950-766d5700-50d7-11eb-9491-5976febf3abd.png)

**Comment by BernardXiong** [comment]
What's the BSP of this board.c?

**Comment by M0n7y5** [comment]
I am using bluepill board with STM32F103CB

**Comment by M0n7y5** [comment]
Also i am using rt-thread IDE

**Comment by BernardXiong** [comment]
@mysterywolf Do you have some comments?

**Comment by M0n7y5** [comment]
I found that method in `Project -> drivers -> drv_clk.c` and i replaced that with my code. Now USB CDC will show up in Device Manager, but still not printing anything. I am using code from here #4227.

**Comment by M0n7y5** [comment]
Ok so i managed to get it CDC working ...
![obrazek](https://user-images.githubusercontent.com/17201053/104043330-eebd4080-51db-11eb-959d-4a718b45fb01.png)

But there is a new problem here. finsh shell is not working anymore for some reason.

**Comment by margguo** [comment]
It looks like a prtoject generated from RT-Thread Studio  by chip, not from bsp， replace code in drv_clk.c --system_clock_config with code  from CubeMX fucntion ”SystemClock_Config“ , and pay attention to update the Marco value of HSE_VALUE in stm32fxxx_hal_conf.h

**Comment by mysterywolf** [comment]
Hi, today, just now,  we released bluepill board bsp. You can re-create a project by using "Base on board".
![微信截图_20210110143523](https://user-images.githubusercontent.com/34888354/104116181-40d3a280-5351-11eb-8142-90b6f5ee1b4b.png)

**Comment by M0n7y5** [comment]
Oh nice! I am gonna try it  ASAP! If thats gonna work i will close this issue.

**Comment by M0n7y5** [comment]
Ok, so i am unable to get USB CDC workign with provided BSP. I checked configuration of clocks and rt-thread settings, but for some reason i get Unrecognized Device every time i plug it into PC. However i was able to get USB working using Chip based configuration instead (look above). 

So this is my configuration in STM32Cube:
![obrazek](https://user-images.githubusercontent.com/17201053/104301905-76e76280-54c8-11eb-92a4-88140e369707.png)

![obrazek](https://user-images.githubusercontent.com/17201053/104301919-7cdd4380-54c8-11eb-9944-a5b46972c20b.png)

**Comment by M0n7y5** [comment]
So i am finally able to use USB CDC and finsh via UART. But only if i use project based on CHIP configuration. I had no luck with released BluePill BSP. 

![obrazek](https://user-images.githubusercontent.com/17201053/104307101-1d366680-54cf-11eb-905b-91158385839e.png)

**Comment by M0n7y5** [comment]
@mysterywolf Can u test USB CDC on your side?

**Comment by mysterywolf** [comment]
Hi, Today, @balanceTWK  has added the USB CDC function for your need. But please wait for a moment, I need some time to carry this function into RT-Studio version. And I will release a tutorial to help you how to create a bluepill project with USB CDC. And, please tell you about your next purpose, we could help you to develop because bluepill board is a very popular board.

**Comment by mysterywolf** [comment]
And I will translate the vconsole to English for you.

**Comment by mysterywolf** [comment]
vconsole English version https://github.com/enkiller/vconsole/pull/3

**Comment by mysterywolf** [comment]
Hi, today, we release the bluepill rt-studio project that allows you can use USB CDC as a console device. I shot a video for you to teach you how to create a USB CDC project by using rt-studio.
[Uploading 20210118_183810.zip…]()

**Comment by mysterywolf** [comment]
Hi, today, we release the bluepill rt-studio project that allows you can use USB CDC as a console device. I shot a video for you to teach you how to create a USB CDC project by using rt-studio.
[20210118_183810.zip](https://github.com/RT-Thread/rt-thread/files/5829692/20210118_183810.zip)

**Comment by M0n7y5** [comment]
Nice! I am gonna try it asap.

**Comment by M0n7y5** [comment]
Also it would be really good to upload that video on official RT-Thread Youtube channel :)

**Comment by mysterywolf** [comment]
Yes, This video will upload on youtube and Twitter. Be advised, please pay attention to the ROM and RAM. I think there no extra space(ROM) to create a new thread if you add the function of USB-CDC virtual com.

**Comment by M0n7y5** [comment]
@mysterywolf Oh i forgot to mention... I am using BluePill with 128KB Flash memory. So don't worry about that :)

**Comment by mysterywolf** [comment]
`list_thread` and `free`. These two commands are very useful to reduce RAM.
