### ISSUE TITLE
关于用TCP连接方式做为finish的输入/输出调用list_if()的时候出现网络直接挂掉。

### ISSUE THREAD

**Issue by batbob** [RT-Thread/rt-thread#423]
1、在用TCP连接方式做为finish的输入/输出方式list_if()的时候，导致网络直接挂了，ping不同。后面发现是在list_if()里面有rt_enter_critical();，导致被锁死。以至于网路无法正常使用。经过测试把rt_enter_critical();屏蔽掉，telent方式就可以正常使用。
在tcp连接实现shell【例程地址：http://www.rt-thread.org/phpBB3/topic3823.html】
2、但是这个会导致另外一个问题发生，就是没有这个锁”rt_enter_critical();“可能会导致netif这个链表可能在这个过程中加入新的，或者某个netif被删除了。
注意：在使用telent方式【例程地址：http://www.rt-thread.org/phpBB3/viewtopic.php?p=10467】的时候，在打开rt_enter_critical();的时候list_if()不会出现网络死掉的情况，希望你们注意，希望得到你们的帮助解决，谢谢。

**Comment by BernardXiong** [comment]
这个问题在于，
1. 你的程序中，当进行device_write时，直接调用了lwip_write函数，它是一个完全基于事件机制并会等待发送确认的函数，会导致当前任务挂起。但这个时候确处于调度器挂起状态；
2. 论坛中的telnet程序，是使用ring buffer先缓存write的数据，当当前线程解锁调度器时，才会真正开始数据发送动作，所以不会有问题。

类似程序，请使用telnet例子提供的方式来编写代码。
