### ISSUE TITLE
USB MASS storage in STM32F746-disco

### ISSUE THREAD

**Issue by updesh31** [RT-Thread/rt-thread#4230]
How can I use only MASS storage host class for USB FS?

**Comment by balanceTWK** [comment]
![image](https://user-images.githubusercontent.com/30776697/103971273-0f1dd880-51a5-11eb-9c3d-6c986b8d9a9f.png)

STM32F746-DISCO is not supported yet, but it is almost the same as STM32F767-ATK-Apollo.You can refer to the STM32F767-ATK-Apollo implementation.
