### ISSUE TITLE
stm32f072-st-nucleo配置ROSSERIAL包，发现串口输出的波特率没有按照程序配置的115200

### ISSUE THREAD

**Issue by conscience-still** [RT-Thread/rt-thread#4240]
最近按照rtt教程配置rosserial的包，增加我的一部分代码，发现串口配置的115200，但是实际输出的波特率经过检测是68823，而配置的过程是按照rtt官网env 指导配置的，出现这个问题所以感到很奇怪，希望有配置的朋友答疑一下。

![image](https://user-images.githubusercontent.com/37905983/104815572-57499480-5850-11eb-91df-ee503a997ed7.png)

![image](https://user-images.githubusercontent.com/37905983/104815586-6a5c6480-5850-11eb-8212-b7085f3a5eaf.png)

**Comment by BernardXiong** [comment]
可以关注下板载晶振的情况，可能BSP里晶振频率和你板子上的晶振不一样。也可以使用cubemx重新配置

**Comment by mysterywolf** [comment]
你好如果还有问题可以继续提问，没有问题的话可以关闭此issue
