### ISSUE TITLE
[Question] Possible support for Raspberry Pi Pico? 

### ISSUE THREAD

**Issue by M0n7y5** [RT-Thread/rt-thread#4262]
Hi,
is it possible to add support for upcoming new cheap board from Raspberry Pi?

More info:
- https://www.raspberrypi.org/blog/raspberry-pi-silicon-pico-now-on-sale/
- https://www.raspberrypi.org/products/raspberry-pi-pico/
- https://github.com/raspberrypi/pico-sdk

**Comment by mysterywolf** [comment]
Yes, we have noticed that news, and we will plan to work on it.

**Comment by mysterywolf** [comment]
I have a question: where can you buy bluepill board and Raspberry Pi Pico in your country? Can you give me a shopping web site link?

**Comment by M0n7y5** [comment]
Oh yeah no problem ...
For specifically RPi stuff, there is this store:
- https://rpishop.cz/pico/3352-raspberry-pi-pico-0617588405587.html

For other stuff (where you can also buy RPi stuff) there is 
- https://www.laskarduino.cz/bluepill-arm-stm32-stm32f103c8-vyvojova-deska/
- https://pajenicko.cz/vyvojova-deska-stm32-bluepill-s-stm32f103c8t6
- http://www.automatizace.kvalitne.cz/vyvojove-desky/105-stm32f103c8t6-arm-stm32-vyvojova-deska-pouzitelna-s-arduino-pcb-typ-b.html
 
Also, good amount of people here are also buying from stores like Amazon, Aliexpress or Banggood ...

**Comment by liu2guang** [comment]
https://github.com/Guozhanxin/rt-thread/tree/raspberry-pico/bsp/raspberry-pico

![image](https://user-images.githubusercontent.com/24929334/106098835-ace93f80-6174-11eb-8e3e-94b04eee2dec.png)

**Comment by yoyojacky** [comment]
![image](https://user-images.githubusercontent.com/6893075/106119410-24789800-6190-11eb-8599-31c32ba7ab1b.png)
RT-Thread single kernel running is good.

**Comment by BernardXiong** [comment]
Merged with #4275 !

Who can provide the mpy with RT-Thread? Welcome!

**Comment by mysterywolf** [comment]
https://twitter.com/rt_thread/status/1354730387155480578

**Comment by mysterywolf** [comment]
https://rt-thread.medium.com/getting-started-with-raspberry-pi-pico-in-rt-thread-studio-ide-5bb08c01363f

**Comment by mysterywolf** [comment]
https://club.rt-thread.org/ask/article/2539.html
