### ISSUE TITLE
RTT能否兼容Makefile和menuconfig

### ISSUE THREAD

**Issue by baidxi** [RT-Thread/rt-thread#4312]
本人多数时候使用的是LINUX命令行,和MAC OS, 发现很多使用上的不方便.比如配置和移植的时候.很多需要SCONS

**Comment by mysterywolf** [comment]
RTT的env可以在linux下使用: https://supperthomas-wiki.readthedocs.io/en/latest/04_dozingfiretruck/06/Linux.html
你也可以通过scons --target=eclipse 生成eclipse工程 或者通过 scons --target=makefile生成makefile工程。

**Comment by BernardXiong** [comment]
scons比较弱的就是慢，怎一个慢字了得！
