### ISSUE TITLE
Google Summer of Code(GSoC) Ideas List

### ISSUE THREAD

**Issue by Cathy-lulu** [RT-Thread/rt-thread#4354]
### Idea 1: Micro-ROS on RT-Thread

**Project Description:**

This project aims to integrate RT-Thread into the micro-ROS build system.

To date, micro-ROS is supported by FreeRTOS, Zephyr, NuttX, in addition to Linux and Windows. All three RTOSes are downloaded natively with the micro-ROS build system, and can be chosen when creating a new firmware workspace. Dedicated tutorials for running the first micro-ROS application on each of these Operating Systems is also available here.

RT-Thread, on the other hand, provides a software package Micro-XRCE-DDS-Client that achieves communication with ROS2 node through TCP/UDP/Serial connection.

A successful completion of the project would include a demo on RT-Thread supported hardware or QEMU simulator that demonstrates a successful integration with micro-ROS API.

[**Find More Details**](https://docs.google.com/document/d/1xtWzgDYmUck478ofllIRr-xu6diCIPxYZdTdk5iOUXc/edit?usp=sharing)

### Idea 2: Implement a lightweight Hypervisor on the RISC-V processor

**Project Description:**

This project is looking to implement a light hypervisor on RISC-V.
Due to the fact that the standard of RISC-V virtualization has not been completed yet, the emulator QEMU RV64 is chosen as the development platform. We run a light hypervisor in the M mode of RISC-V, which supports one or more guest operating systems, such as RT-Thread Smart, Linux.

- Implement Hypervisor basic functionality on qemu
- Implement Hypervisor console on qemu
- Add SMP environment for Hypervisor

**[Find More Details](https://docs.google.com/document/d/1ME4i4lbmt6vXMXyM4Zk9ndq6ZGLqQoYc1SbfzIztXfo/edit?usp=sharing)**

### Idea 3: Support user-mode applications written in Rust running on RT-Thread Smart

**Project Description:**

RT-Thread Smart(Short for RT-Smart) is a real-time microkernel operating system for embedded platforms.
Currently, RT-Thread Smart user-state application only supports C/C++ that uses musl libc. As the development of embedded ecology fastly grows, running the Rust application on rt-smart is necessary. The purpose of this project is to support user-mode applications written in Rust running on RT-Thread Smart.

- Support Rust Library
- Compile the code written in Rust to generate an executable that runs on RT-Smart
- Add RT-Smart to Rust ecology

**[Find More Details](https://docs.google.com/document/d/1MgtJdEZWr371ZGqVyWBDpZqVAh-tgrpQ9spL16e98nE/edit?usp=sharing)**

### Idea 4: RT-Thread Application Development with Rust

**Project Description:**

Rust — A Green Language for the 21st Century. We generally consider Rust as the ideal language for developing applications on embedded systems. Rust supports a large number of embedded operating systems in the form of compilation targets, this project is looking to have Rust support for RT-Thread.

Project requires using Rust, selecting an architecture that encapsulates the compilation target for writing RT-Thread applications. You can choose from architectures that Rust already supports, such as "riscv64imac-rt-thread" or "aarch64-rt-thread". Also you can choose the architecture that has not yet been supported, such as "xtensa", off course, it requires more effort on the back end of the compiler.

**[Find More Details](https://docs.google.com/document/d/1nEtMbBv5BUukX0g2--YV0Xg9rSfBPfeTZViK-F7rZUs/edit?usp=sharing)**

**Comment by wuhanstudio** [comment]
Hi,

It turns out additional permissions are required for [more details](https://docs.google.com/document/d/1MgtJdEZWr371ZGqVyWBDpZqVAh-tgrpQ9spL16e98nE/edit?usp=sharing) of idea 3.
