### ISSUE TITLE
drv_qspi.c文件有错误

### ISSUE THREAD

**Issue by jch12138** [RT-Thread/rt-thread#4374]
![image](https://user-images.githubusercontent.com/30290347/108802970-6e5c6e80-75d4-11eb-9389-dba65b961f87.png)
在344行,cs_pin->Pin有问题,
在cs_pin的定义中,发现只有x小写的pin,是不是拼写有问题
![image](https://user-images.githubusercontent.com/30290347/108803061-b54a6400-75d4-11eb-8f2d-0e8800783618.png)

**Comment by mysterywolf** [comment]
感谢反馈 已经提交pr修复
