### ISSUE TITLE
Env显示问题

### ISSUE THREAD

**Issue by James1989Cn** [RT-Thread/rt-thread#4387]
3.1.4版本components下的Kconfig文件，缺少菜单信息
config RT_USING_COMPONENTS_INIT
    bool 
    default n
    
config RT_USING_USER_MAIN
    bool 
    default n
这样在menuconfig界面中无法正常显示出这两个选项

**Comment by BernardXiong** [comment]
这些应该是在bsp里主动select的，而不是交给用户来选择。因为这些选项是完全和bsp绑定的，选择或不选择，和BSP不对应，也会编译出错
