### ISSUE TITLE
[ymodem] warning,enumerated type mixed with another type

### ISSUE THREAD

**Issue by liuduanfei** [RT-Thread/rt-thread#4397]
https://github.com/RT-Thread/rt-thread/blob/2bf53d315d62bd199c01fd2d6a7f05d1a6712153/components/utilities/ymodem/ry_sy.c#L101

ry_sy.c(101): warning:  #188-D: enumerated type mixed with another type

**Comment by BernardXiong** [comment]
Welcome to submit a PR for this issue.
