### ISSUE TITLE
SCB_EnableDCache宏与函数名冲突，若定义该宏则编译报错

### ISSUE THREAD

**Issue by Jedcheen** [RT-Thread/rt-thread#4435]
https://github.com/RT-Thread/rt-thread/blob/4c399f88bb15416e833e9b86ad9de46807ca12e0/bsp/stm32/libraries/HAL_Drivers/drv_common.c#L138

RT

**Comment by Guozhanxin** [comment]
@whj4674672 Can you help me take a look

**Comment by Guozhanxin** [comment]
看起来原来的代码是想根据这个来检测函数是否有定义，但是 #ifdef 并没有这个功能。。。

**Comment by whj4674672** [comment]
因为宏和函数的名字一模一样导致的问题，修改宏的名字就可以了。
