### ISSUE TITLE
at_resp_set_info里一个realloc的使用问题

### ISSUE THREAD

**Issue by xf22001** [RT-Thread/rt-thread#4436]
components/net/at/src/at_client.c

at_response_t at_resp_set_info(at_response_t resp, rt_size_t buf_size, rt_size_t line_num, rt_int32_t timeout)
{
	...
        resp->buf = (char *) rt_realloc(resp->buf, buf_size);
        if (!resp->buf)
        {
            LOG_D("No memory for realloc response buffer size(%d).", buf_size);
            return RT_NULL;
        }
	...
}
这个realloc如果分配内存失败，返回了NULL,是不是会造成原本的resp->buf内存泄露呢？

**Comment by mysterywolf** [comment]
这个函数貌似已经解释了，如果返回NULL表示申请空间不够，用户可以继续沿用原来的空间，因此要检查一下返回参数，和realloc的使用方法一样。不过你提到的问题确实很值得人警醒

**Comment by xf22001** [comment]
嗯，resp->buf = (char *) rt_realloc(resp->buf, buf_size);
貌似这样操作把原来的空间指针抹掉了。

**Comment by mysterywolf** [comment]
有道理

**Comment by mysterywolf** [comment]
问题解决感谢反馈
