### ISSUE TITLE
[AB32VG1]  uart console复制粘贴无法正确接收到所有数据

### ISSUE THREAD

**Issue by supperthomas** [RT-Thread/rt-thread#4468]
在测试AB32VG1的 UART中，不管将console设为UART0还是UART1。 都无法在console中，粘贴复制的文字，比如复制文字  help  4个字节，也无法完全接收到正确的数据到console口，怀疑UART连续接收字节有问题。

**Comment by mysterywolf** [comment]
应该是那个上位机的问题吧

**Comment by supperthomas** [comment]
> 应该是那个上位机的问题吧

不是，putty在其他平台上没有问题，应该是驱动数据接收丢了

**Comment by greedyhao** [comment]
如果在 uart1 双线串口通信的情况下还有问题，那可能确实是驱动有问题

**Comment by supperthomas** [comment]
> 如果在 uart1 双线串口通信的情况下还有问题，那可能确实是驱动有问题

UART1已经试过，也是有问题的。详细见https://club.rt-thread.org/ask/article/2624.html
