### ISSUE TITLE
nrf5x 看门狗驱动有问题

### ISSUE THREAD

**Issue by Guozhanxin** [RT-Thread/rt-thread#4558]
这里的驱动有问题，参考文档中心的这个 PR:https://gitee.com/rtthread/docs-online/commit/64eeb2691a3cca7988af9a8d0b1c7542eacb3721

https://github.com/RT-Thread/rt-thread/blob/95c0569b332fe659269706625435c4f1f7001142/bsp/nrf5x/libraries/drivers/drv_wdt.c#L45

**Comment by Guozhanxin** [comment]
@supperthomas 你看下这个问题吧

**Comment by ylz0923** [comment]
[https://www.rt-thread.org/document/site/programming-manual/device/watchdog/watchdog/](url) 
![无标题](https://user-images.githubusercontent.com/32135954/113230753-44c9ed80-92cc-11eb-95b5-99c89ffb1fe2.png)
要改变使用方法了？@Guozhanxin

**Comment by Guozhanxin** [comment]
> [https://www.rt-thread.org/document/site/programming-manual/device/watchdog/watchdog/](url)
> ![无标题](https://user-images.githubusercontent.com/32135954/113230753-44c9ed80-92cc-11eb-95b5-99c89ffb1fe2.png)
> 要改变使用方法了？@Guozhanxin

不是，好像就是之前文档的问题，我搜索了仓库里的驱动实现，基本上都是按照指针的形式使用的。

**Comment by ylz0923** [comment]
那文档里面的时间单位：秒，有问题吗？

**Comment by Guozhanxin** [comment]
![image](https://user-images.githubusercontent.com/25633294/113236969-88c2ef80-92d8-11eb-8356-04d23c430b24.png)
没问题的

**Comment by chenyingchun0312** [comment]
如果按照当前看门狗驱动的写法，官方的sample，无法开箱即用， 大概总结一下几点原因：
- 一般传递一个整形数据的值，不是把这整形数据转为指针，而是取该整形数据的地址往下传，下面接收到这个地址后，再取出其中的值
- 官方sample如图所示，传递的是timeout的地址，而不是把timeout转为指针类型
![image](https://user-images.githubusercontent.com/44871523/129129226-6474f47d-d7d0-4e2f-903e-ab0f9ef4b86e.png)

**Comment by chenyingchun0312** [comment]
@Guozhanxin 该issue已提交PR，请求关闭该issue
PR: #https://github.com/RT-Thread/rt-thread/pull/4938
