### ISSUE TITLE
simulator不能使用外部字体文件。

### ISSUE THREAD

**Issue by hexlog** [RT-Thread/rt-thread#46]
环境：VS2012
BSP：simulator

描述：已经确定在finsh shell中可以访问字体文件，调试后发现GUI的字体系统比文件系统要更早初始化。

RTGUI: could not open the font file:/resource/hzk16.fnt
RTGUI: please mount the fs first and make sure the file is there
RTGUI: could not open the font file:/resource/hzk12.fnt
RTGUI: please mount the fs first and make sure the file is there
win32 share directory initialized!

**Comment by BernardXiong** [comment]
The components initialization is removed from simulator branch. Therefore, please manually initialize components one by one.

**Comment by alexwqr** [comment]
请问如何手动修改components的加载顺序啊
