### ISSUE TITLE
rt-thread/components/drivers/src/ringbuffer.c存在竞态，建议使用锁保护

### ISSUE THREAD

**Issue by yellowbeeHYF** [RT-Thread/rt-thread#4615]
rt-thread/components/drivers/src/ringbuffer.c中的rt_ringbuffer_put_force和rt_ringbuffer_putchar_force存在修改read_mirror和read_index，如果有线程同时在读数据时候就存在竞态，导致这个两个数值不一致的情况

**Comment by mysterywolf** [comment]
你好，这个ringbuffer设计之初就是故意不带锁的 用户需要自己保护，后续会在文档中标注出来以免误解
