### ISSUE TITLE
使用硬件RTC获取时间戳比实际时间戳多了8小时

### ISSUE THREAD

**Issue by OROKIN** [RT-Thread/rt-thread#4617]
使用硬件 RTC 获取时间戳比实际时间戳多了 8 小时，从 RTT 4.0.2 到 4.0.3 一直都有这个问题。

**Comment by mysterywolf** [comment]
请用最新版的master 最新版的master已经修复这个问题了 最好等https://github.com/RT-Thread/rt-thread/pull/4616 这个pr合并后再下载

**Comment by OROKIN** [comment]
> 请用最新版的master 最新版的master已经修复这个问题了 最好等#4616 这个pr合并后再下载

好的，谢谢！

**Comment by mysterywolf** [comment]
已经合并了 你可以用了
