### ISSUE TITLE
RT-Thread 开发/维护问题快查手册 | RT-Thread QRH

### ISSUE THREAD

**Issue by mysterywolf** [RT-Thread/rt-thread#4637]
本issue列举一些已经解决或者close但是非常典型，后续很有可能继续再犯的问题，作为开发的快查手册(QRH)。欢迎跟帖补充。

**Comment by mysterywolf** [comment]
## 双精度浮点问题
部分STM32高级芯片具备双精度浮点计算能力，设置方式有所区别
参见：
https://github.com/RT-Thread/rt-thread/issues/4186 ->  https://github.com/RT-Thread/rt-thread/pull/4188
https://github.com/RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi/issues/177 -> https://github.com/RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi/pull/195

**Comment by Guozhanxin** [comment]
这个和 https://github.com/RT-Thread/rt-thread/issues/3912 这个issue可以合并一个吗？
