### ISSUE TITLE
stm32 串口长时间int_tx/poll_tx 导致低优先级无法执行

### ISSUE THREAD

**Issue by cc-caixf** [RT-Thread/rt-thread#4646]
数据块是应用层传递过来,无法保证在dma_tx传输完成之前,数据块的内容不变.所以串口选择int_tx/poll_tx,

但是这两种选项的 源码实现 与 实际测试 都反应了一个问题:,串口不能长时间发送,长时间发送就会导致低优先级任务无法执行(例如idle的喂狗).

**Comment by heyuanjie87** [comment]
框架没给中断发送建缓冲区，当前线程会被频繁调度，你可以修改下框架给发送加上ringbuffer估计会改善

**Comment by KyleChenjh** [comment]
因为int_tx和poll_tx其实都是没有对cpu做让出的动作，因此发送数据较长时会出现低优先级任务无法执行甚至咬狗情况，不过该问题在  测试版本的串口驱动框架  上已经修复。
另外针对dma_tx，新版本的串口框架已经解决了数据块内容一致性的问题，对于大数据传输的场景，推荐使用dma_tx。

以h7为例，测试版本的串口框架仓库- [art-pi-lab-serial](https://github.com/RT-Thread-Studio/sdk-bsp-stm32h750-realthread-artpi/tree/lab_serial)
