### ISSUE TITLE
Which JavaScript engine does Persimmon UI use?

### ISSUE THREAD

**Issue by chengziorange** [RT-Thread/rt-thread#4652]
I want to import a cpp module in my APP, and considered using WASM, but I know nothing about the JS runtime of Persimmon UI, can't find anything related to it in the source code either.

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread-packages/jerryscript

**Comment by BernardXiong** [comment]
WASM and JavaScript? How to integrate them?

**Comment by chengziorange** [comment]
> WASM and JavaScript? How to integrate them?

I'm a new js learner, so I probably said something wrong about it. My intention is to import a c++ module in my app. I know that in web, c++ can be compiled into wasm and run in browser. So I wander whether I can do it in persimmon ui.
