### ISSUE TITLE
[ci测试例程] dist后无法进入menuconfig，example报错

### ISSUE THREAD

**Issue by mysterywolf** [RT-Thread/rt-thread#4685]
![image](https://user-images.githubusercontent.com/34888354/118147574-4bf32800-b442-11eb-9f0f-e818921d7096.png)
如果把整个仓库clone下来 进到某个bsp可以menuconfig； 但是如果dist下来的话就不行了
建议在根目录下新建一个bench文件夹，专门放ci自动测试程序，与example脱钩。
https://github.com/RT-Thread/rt-thread/pull/4678

**Comment by Guozhanxin** [comment]
已修复：https://github.com/RT-Thread/rt-thread/pull/4687

**Comment by Guozhanxin** [comment]
修复方式：dist之后的工程，删除了 Utestcast 选项菜单。
