### ISSUE TITLE
NUC980  ETH-PHY LAN8720A  无法 ping 通，无法通信，能否兼容一下

### ISSUE THREAD

**Issue by studyinhub** [RT-Thread/rt-thread#4692]
MUC980 默认设置是 IP101 ，但仔细对比过 IP101 和 LAN8720 ,发现其实对于 PHY 的设置基本没有区别，要实现对 LAN8720 的兼容应该不复杂，不知道谁可以帮忙测试一下，多谢。

**Comment by studyinhub** [comment]
实际测试发现 PHY 寄存器都正常，采用 Nuvoton_NonOS 包中的 sample code 中的 EMAC_LwIP_httpd 也正常，说明硬件没有问题。但用 RT-THREAD 就是无法 ping 通，感觉是中断那里设置有问题。

**Comment by BernardXiong** [comment]
Hello @wosayttn 

Could you please take a look this issue? Thanks.

**Comment by studyinhub** [comment]
It's OK now.
I repulled the code ,and just change the EMAC_PHY_ADDR 1UL to 0UL,It's OK now.

**Comment by wosayttn** [comment]
Noted. Thanks.
