### ISSUE TITLE
关于scons --dist-ide命令的建议

### ISSUE THREAD

**Issue by mysterywolf** [RT-Thread/rt-thread#4723]
1.该命令过于泛在，所有的编译环境比如keil iar都可以叫ide，究竟指的是哪个IDE？建议改成--dist-studio 更清晰明确这个命令是用于导出 rt-studio工程的。
2.该命令必须输入--project-name以及--project-path 这两个参数，输入路径比较麻烦，建议改成可选项，若用户没有输入这两个参数，可以和dist命令一样在bsp目录下创建一个dist-studio文件夹，把工程放在这个文件夹下。

这个命令非常有用，因为目前studio bsp软件包那边并不会及时同步更新master的源码，要想基于RT-Studio体验或测试最新版的bsp工程，必须通过该命令导出。

**Comment by mysterywolf** [comment]
@margguo

**Comment by margguo** [comment]
@armink

**Comment by armink** [comment]
建议保持兼容性，这里的 ide 是站在 RT-Thread 的角度，不是外部其他 IDE 角度

那两个默认参数，可以的

**Comment by mysterywolf** [comment]
@margguo 麻烦大佬第二个搞一下

**Comment by margguo** [comment]
已提交pr   https://github.com/RT-Thread/rt-thread/pull/4734    @mysterywolf  @armink

**Comment by armink** [comment]
👍 神速
