### ISSUE TITLE
.init_priority 这个成员变量是否可以移除？该变量在内核中并没有起到任何实际作用

### ISSUE THREAD

**Issue by mysterywolf** [RT-Thread/rt-thread#4761]

**Comment by BernardXiong** [comment]
Where is this variable?

**Comment by mysterywolf** [comment]
这里https://github.com/RT-Thread/rt-thread/blob/master/include/rtdef.h#L635

**Comment by Guozhanxin** [comment]
之前记得这个优先级变量是用于互斥量调整完优先级之后，用于还原优先级用的。不知道后面怎么就没用到了。反正就是为了临时调整完优先级之后还原用的。

**Comment by mysterywolf** [comment]
待会干掉

**Comment by Guozhanxin** [comment]
😂

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/4772
