### ISSUE TITLE
stm通用库drv_common.c中的rt_hw_us_delay延迟超过1000us有bug

### ISSUE THREAD

**Issue by taokingithub** [RT-Thread/rt-thread#4775]
其实现如下
void rt_hw_us_delay(rt_uint32_t us)
{
    rt_uint32_t start, now, delta, reload, us_tick;
    start = SysTick->VAL;
    reload = SysTick->LOAD;
    us_tick = SystemCoreClock / 1000000UL;
    do
    {
        now = SysTick->VAL;
        delta = start >= now ? start - now : reload + start - now;
    }
    while (delta < us_tick * us);
}
SysTick在RTThread中做系统时钟，一般是1ms，而如果参数us超过1000（即超过1ms），则delta < us_tick * us判断会永远成立，即跳不出while循环

**Comment by Guozhanxin** [comment]
https://gitee.com/rtthread/rt-thread/pulls/217/files 已经有人提pr了

**Comment by mysterywolf** [comment]
该问题的pr已经被合并
