### ISSUE TITLE
pthread信号量初始化错误

### ISSUE THREAD

**Issue by CornerOfSkyline** [RT-Thread/rt-thread#4784]
在使用pthread信号量时，信号量初始化过程中如果内存耗尽，无法为rt-thread信号量申请到内存，初始化进程存在bug未能报出该错误，导致在使用信号量时引发(sem != RT_NULL)断言错误，引发错误的代码为下列位置，该处应判定`if(sem->sem == RT_NULL)`.

https://github.com/RT-Thread/rt-thread/blob/ed402ec25c1a6ec486a9b5470728c00085acd6a5/components/libc/pthreads/semaphore.c#L189

**Comment by BernardXiong** [comment]
欢迎提交补丁的PR
