### ISSUE TITLE
BSP/stm32中的例程编译报错

### ISSUE THREAD

**Issue by shen2lan** [RT-Thread/rt-thread#4799]
..\..\..\components\drivers\src\pipe.c(14): error:  #5: cannot open source input file "sys/errno.h": No such file or directory

**Comment by mysterywolf** [comment]
这个是由于你没有刷新工程引起的，进入env命令行之后，敲menuconfig然后直接再退出来就好了

**Comment by shen2lan** [comment]
是的   已经好了 谢谢
