### ISSUE TITLE
(bug report）In the bsp of raspi-4-32, a network card driver problem will cause the network card to send repeated packets all the time。

### ISSUE THREAD

**Issue by huyu168** [RT-Thread/rt-thread#4818]
In the drv_eth.c file, the variable prod_index should be zeroed at 0xffff instead of 0xe000, otherwise it will cause the network card to repeatedly send data packets.
`if (prod_index == 0xe000)
    {
        write32(MAC_REG + TDMA_PROD_INDEX, 0);
        prod_index = 0;
    }`
should be changed to：
`prod_index &= 0xffff;`

**Comment by BernardXiong** [comment]
Yes, you are correct. 👍

**Comment by BernardXiong** [comment]
fixed with #4915
