### ISSUE TITLE
mailbox 引起hard fault

### ISSUE THREAD

**Issue by enjoydiy** [RT-Thread/rt-thread#486]
有人测试过mailbox吗？今天尝试用了一下mailbox，在接收的线程里面引起 hard fault，如果换成消息队列和事件做同步没有问题。

**Comment by pangweishen** [comment]
肯定是测试过的。

**Comment by grissiom** [comment]
没有代码，不知道你是怎么用的。无法判断情况。

在提供更多信息之后 reopen 吧～
