### ISSUE TITLE
BUG: bsp\simulator编译报错

### ISSUE THREAD

**Issue by BreederBai** [RT-Thread/rt-thread#4877]
执行scons --target=vs2012 -s命令，用vs2019打开，重定向项目后，编译报错
![image](https://user-images.githubusercontent.com/27894314/126143151-e5ab2bd0-1fda-41cc-b10c-6a2b4177d145.png)

**Comment by mysterywolf** [comment]
你先用4.0.3稳定版本的，或者master版本任意真实的bsp即可。我们现在对libc进行一次调整，还在进行中，win32平台的问题会留在最后处理。

**Comment by BreederBai** [comment]
@mysterywolf 好的。请问4.0.3版本是已经发布了吗？还是说正在进行的就是4.0.3，等bsp问题都解决了，正式发布

**Comment by mysterywolf** [comment]
4.0.3去年已经发布

**Comment by BreederBai** [comment]
@mysterywolf 好的，我看github的相关页面没有显示，代码库中也没有相关的分支。以为这个版本还在开发中
![image](https://user-images.githubusercontent.com/27894314/126582231-8e60132c-0a98-4206-a608-9b9912297eff.png)

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/releases
