### ISSUE TITLE
Support for Cortex-M33 nRF9160 from Nordic Semiconductor

### ISSUE THREAD

**Issue by rajeev1986** [RT-Thread/rt-thread#4895]
Does RT-Thread have any plan to support [nRF9160 ](https://www.nordicsemi.com/Products/nRF9160)SiP from Nordic Semiconductor that has cortex-M33 with built-in GPS and cellular modem?

Thanks

**Comment by BernardXiong** [comment]
Glad to see that nRF9160 can be supported, but we have no this board yet.

**Comment by lt6210925** [comment]
https://github.com/RT-Thread/rt-thread/blob/master/bsp/nrf5x/docs/nRF5x%E7%B3%BB%E5%88%97BSP%E5%88%B6%E4%BD%9C%E6%95%99%E7%A8%8B.md
@rajeev1986 if you have nrf9160 you can add bsp follow this document.
