### ISSUE TITLE
Pi Pico C++ Compilation Issue 

### ISSUE THREAD

**Issue by TechnoGangsta** [RT-Thread/rt-thread#4979]
I have been having issues getting a project compiled for the pi pico with the C++ features enabled. Build log below:

`19:21:15 **** Build of configuration Debug for project Pico_Learning ****
scons.bat -j6 
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...

scons: warning: you do not seem to have the pywin32 extensions installed;
	parallel (-j) builds may not work reliably with open Python files.
File "C:\RT-ThreadStudio\platform\env_released\env\tools\Python27\Scripts\scons.py", line 204, in <module>
scons: building associated VariantDir targets: build
CC build\applications\main.o
CC build\drivers\board.o
CC build\drivers\drv_gpio.o
CC build\drivers\drv_uart.o
CC build\kernel\components\cplusplus\crt_init.o
CXX build\kernel\components\cplusplus\cxx_crt.o
applications\main.c: In function 'change_brightness':
applications\main.c:183:26: warning: implicit declaration of function 'atoi' [-Wimplicit-function-declaration]
     int brightness_cmd = atoi(argv[1]);
                          ^~~~
CXX build\kernel\components\cplusplus\cxx_Mutex.o
CXX build\kernel\components\cplusplus\cxx_Semaphore.o
CXX build\kernel\components\cplusplus\cxx_Thread.o
CC build\kernel\components\drivers\misc\pin.o
CC build\kernel\components\drivers\serial\serial.o
CC build\kernel\components\drivers\src\completion.o
CC build\kernel\components\drivers\src\dataqueue.o
CC build\kernel\components\drivers\src\pipe.o
CC build\kernel\components\drivers\src\ringblk_buf.o
CC build\kernel\components\drivers\src\ringbuffer.o
CC build\kernel\components\drivers\src\waitqueue.o
CC build\kernel\components\drivers\src\workqueue.o
CC build\kernel\components\finsh\cmd.o
CC build\kernel\components\finsh\msh.o
CC build\kernel\components\finsh\shell.o
CC build\kernel\components\libc\compilers\common\stdlib.o
CC build\kernel\components\libc\compilers\common\time.o
CC build\kernel\components\libc\compilers\newlib\libc.o
CC build\kernel\components\libc\compilers\newlib\stdio.o
CC build\kernel\components\libc\compilers\newlib\syscalls.o
CC build\kernel\libcpu\arm\common\backtrace.o
CC build\kernel\libcpu\arm\common\div0.o
CC build\kernel\libcpu\arm\common\showmem.o
AS build\kernel\libcpu\arm\cortex-m0\context_gcc.o
CC build\kernel\libcpu\arm\cortex-m0\cpuport.o
CC build\kernel\src\clock.o
CC build\kernel\src\components.o
CC build\kernel\src\device.o
CC build\kernel\src\idle.o
CC build\kernel\src\ipc.o
CC build\kernel\src\irq.o
CC build\kernel\src\kservice.o
CC build\kernel\src\mem.o
CC build\kernel\src\mempool.o
CC build\kernel\src\object.o
CC build\kernel\src\scheduler.o
CC build\kernel\src\thread.o
CC build\kernel\src\timer.o
AS build\libraries\generated\bs2_default_padded_checksummed.o
CC build\libraries\pico-sdk\src\common\pico_sync\critical_section.o
CC build\libraries\pico-sdk\src\common\pico_sync\lock_core.o
CC build\libraries\pico-sdk\src\common\pico_sync\mutex.o
CC build\libraries\pico-sdk\src\common\pico_sync\sem.o
CC build\libraries\pico-sdk\src\common\pico_time\time.o
CC build\libraries\pico-sdk\src\common\pico_time\timeout_helper.o
CC build\libraries\pico-sdk\src\common\pico_util\datetime.o
CC build\libraries\pico-sdk\src\common\pico_util\pheap.o
CC build\libraries\pico-sdk\src\common\pico_util\queue.o
CC build\libraries\pico-sdk\src\rp2_common\hardware_claim\claim.o
CC build\libraries\pico-sdk\src\rp2_common\hardware_clocks\clocks.o
AS build\libraries\pico-sdk\src\rp2_common\hardware_divider\divider.o
CC build\libraries\pico-sdk\src\rp2_common\hardware_gpio\gpio.o
CC build\libraries\pico-sdk\src\rp2_common\hardware_irq\irq.o
AS build\libraries\pico-sdk\src\rp2_common\hardware_irq\irq_handler_chain.o
CC build\libraries\pico-sdk\src\rp2_common\hardware_pll\pll.o
CC build\libraries\pico-sdk\src\rp2_common\hardware_sync\sync.o
CC build\libraries\pico-sdk\src\rp2_common\hardware_timer\timer.o
CC build\libraries\pico-sdk\src\rp2_common\hardware_uart\uart.o
CC build\libraries\pico-sdk\src\rp2_common\hardware_vreg\vreg.o
CC build\libraries\pico-sdk\src\rp2_common\hardware_watchdog\watchdog.o
CC build\libraries\pico-sdk\src\rp2_common\hardware_xosc\xosc.o
AS build\libraries\pico-sdk\src\rp2_common\pico_bit_ops\bit_ops_aeabi.o
CC build\libraries\pico-sdk\src\rp2_common\pico_bootrom\bootrom.o
AS build\libraries\pico-sdk\src\rp2_common\pico_divider\divider.o
AS build\libraries\pico-sdk\src\rp2_common\pico_double\double_aeabi.o
CC build\libraries\pico-sdk\src\rp2_common\pico_double\double_init_rom.o
CC build\libraries\pico-sdk\src\rp2_common\pico_double\double_math.o
AS build\libraries\pico-sdk\src\rp2_common\pico_double\double_v1_rom_shim.o
AS build\libraries\pico-sdk\src\rp2_common\pico_float\float_aeabi.o
CC build\libraries\pico-sdk\src\rp2_common\pico_float\float_init_rom.o
CC build\libraries\pico-sdk\src\rp2_common\pico_float\float_math.o
AS build\libraries\pico-sdk\src\rp2_common\pico_float\float_v1_rom_shim.o
AS build\libraries\pico-sdk\src\rp2_common\pico_int64_ops\pico_int64_ops_aeabi.o
CC build\libraries\pico-sdk\src\rp2_common\pico_malloc\pico_malloc.o
AS build\libraries\pico-sdk\src\rp2_common\pico_mem_ops\mem_ops_aeabi.o
CC build\libraries\pico-sdk\src\rp2_common\pico_platform\platform.o
CC build\libraries\pico-sdk\src\rp2_common\pico_printf\printf.o
CC build\libraries\pico-sdk\src\rp2_common\pico_runtime\runtime.o
CC build\libraries\pico-sdk\src\rp2_common\pico_standard_link\binary_info.o
AS build\libraries\pico-sdk\src\rp2_common\pico_standard_link\crt0.o
CXX build\libraries\pico-sdk\src\rp2_common\pico_standard_link\new_delete.o
CC build\libraries\pico-sdk\src\rp2_common\pico_stdio\stdio.o
CC build\libraries\pico-sdk\src\rp2_common\pico_stdio_uart\stdio_uart.o
CC build\libraries\pico-sdk\src\rp2_common\pico_stdlib\stdlib.o
LINK rtthread-pico.elf
**build\kernel\components\cplusplus\cxx_crt.o: In function `operator new(unsigned int)':
C:\RT-ThreadStudio\workspace\Pico_Learning/rt-thread\components\cplusplus/cxx_crt.cpp:15: multiple definition of `operator new(unsigned int)'
build\libraries\pico-sdk\src\rp2_common\pico_standard_link\new_delete.o:C:\RT-ThreadStudio\workspace\Pico_Learning/libraries\pico-sdk\src\rp2_common\pico_standard_link/new_delete.cpp:12: first defined here
build\kernel\components\cplusplus\cxx_crt.o: In function `operator new[](unsigned int)':
C:\RT-ThreadStudio\workspace\Pico_Learning/rt-thread\components\cplusplus/cxx_crt.cpp:20: multiple definition of `operator new[](unsigned int)'
build\libraries\pico-sdk\src\rp2_common\pico_standard_link\new_delete.o:C:\RT-ThreadStudio\workspace\Pico_Learning/libraries\pico-sdk\src\rp2_common\pico_standard_link/new_delete.cpp:16: first defined here
build\kernel\components\cplusplus\cxx_crt.o: In function `operator delete(void*)':
C:\RT-ThreadStudio\workspace\Pico_Learning/rt-thread\components\cplusplus/cxx_crt.cpp:25: multiple definition of `operator delete(void*)'
build\libraries\pico-sdk\src\rp2_common\pico_standard_link\new_delete.o:C:\RT-ThreadStudio\workspace\Pico_Learning/libraries\pico-sdk\src\rp2_common\pico_standard_link/new_delete.cpp:20: first defined here
build\kernel\components\cplusplus\cxx_crt.o: In function `operator delete[](void*)':
C:\RT-ThreadStudio\workspace\Pico_Learning/rt-thread\components\cplusplus/cxx_crt.cpp:30: multiple definition of `operator delete[](void*)'
build\libraries\pico-sdk\src\rp2_common\pico_standard_link\new_delete.o:C:\RT-ThreadStudio\workspace\Pico_Learning/libraries\pico-sdk\src\rp2_common\pico_standard_link/new_delete.cpp:22: first defined here
build\kernel\components\cplusplus\crt_init.o: In function `cplusplus_system_init':
C:\RT-ThreadStudio\workspace\Pico_Learning/rt-thread\components\cplusplus/crt_init.c:67: undefined reference to `__ctors_start__'
C:\RT-ThreadStudio\workspace\Pico_Learning/rt-thread\components\cplusplus/crt_init.c:67: undefined reference to `__ctors_end__'**
collect2.exe: error: ld returned 1 exit status
scons: *** [rtthread-pico.elf] Error 1
scons: building terminated because of errors.
"scons.bat -j6" terminated with exit code 2. Build might be incomplete.

19:21:20 Build Failed. 10 errors, 1 warnings. (took 5s.287ms)`

**Comment by cndabai** [comment]
1. The multiple definition is caused by that rt-thread and raspberry both overwrite the standard allocators. Can this problem be solved by removing new_delete.c from Sconscript (bsp/raspberry-pico/libraries/Sconscript)? 
2. Undefined reference to ctors_start' may caused by the link script's problem. You can reference https://github.com/RT-Thread/rt-thread/blob/master/components/cplusplus/README.md to perfect link.ld
