### ISSUE TITLE
cmake+gnu gcc for arm不能生效INIT_EXPORT和FINSH_FUNCTION_EXPORT如何解决

### ISSUE THREAD

**Issue by desphunter** [RT-Thread/rt-thread#5104]
用的cmake3.20和arm-none-eabi-gcc，使用的stm32cubemx+rt-thread nano生成的project文件，配置控制台打印和finsh时发现INIT_EXPORT和FINSH_FUNCTION_EXPORT不能生效，只能显示调用，搜索解决方式在MD上在linker的misc control加入–keep .o(.rti_fn.)，这个通过cmake方式怎么添加？可以通过STM32XX_FLASH.ld文件添加吗？

**Comment by chenyingchun0312** [comment]
可以参考已有bsp目录下的lds文件，比如下面这个
https://github.com/RT-Thread/rt-thread/blob/master/bsp/nrf5x/nrf52832/board/linker_scripts/link.lds

![Screenshot_2021-09-28-00-12-57-83.jpg](https://user-images.githubusercontent.com/44871523/134946091-04f056f6-30a9-4057-9d99-b9b6d3c56159.jpg)

**Comment by SSSANTON** [comment]
发现同样的问题，终于找到答案了，太猥琐了。

**Comment by mysterywolf** [comment]
这个需要加入到文档中心
