### ISSUE TITLE
K210  bsp  RT_USING_PTHREADS 打开后 编译无法通过 重定义

### ISSUE THREAD

**Issue by fortunerains** [RT-Thread/rt-thread#5125]
d:/xpack-riscv-none-embed-gcc-8.3.0-2.3-win32-x64/bin/../lib/gcc/riscv-none-embed/8.3.0/../../../../riscv-none-embed/bin/ld.exe: build\packages\kendryte-sdk-latest\kendryte-standalone-sdk\lib\bsp\entry_user.o: in function `pthread_setcancelstate':
entry_user.c:(.text.pthread_setcancelstate+0x0): multiple definition of `pthread_setcancelstate'; build\kernel\components\libc\pthreads\pthread.o:pthread.c:(.text.pthread_setcancelstate+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
scons: *** [rtthread.elf] Error 1
![Uploading image.png…]()

**Comment by mysterywolf** [comment]
我查了一下k210那边这个函数没有任何意义，你把他注释掉用rtt的。
![image](https://user-images.githubusercontent.com/34888354/136645438-eb084c25-cd21-4149-83b1-dc5d0e5d16ea.png)
