### ISSUE TITLE
K210 bsp 最新需要选择C++ 导致包含 semaphore.h 报错

### ISSUE THREAD

**Issue by fortunerains** [RT-Thread/rt-thread#5155]
![image](https://user-images.githubusercontent.com/24492495/136941927-98b4fa65-b055-4fef-8322-743dd25aa565.png)

**Comment by mysterywolf** [comment]
@Guozhanxin 郭老师这个是不是C++的问题？

**Comment by chunyexixiaoyu** [comment]
最新版本的K210 堪智必须勾选C++ 才能编译通过这个时候引入这个头文件semaphore导致编译不过

**Comment by chunyexixiaoyu** [comment]
> > > K210 需要勾选C++ 才能编译通过
> > 
> > 
> > 就是因为勾选c++才报的错，这个应该是c++代码的问题 我在qemu上也报错了
> 
> c++ 跑测试用例没出现问题

得包含那个头文件

**Comment by Guozhanxin** [comment]
这个问题是 Pthread 和C++里的头文件冲突。

C++ 和 pthread 同时打开的时候，GCC 的这个编译器，分辨不出来 Semaphore.h 和 semaphore.h ；编译会出问题
