### ISSUE TITLE
master BSP K210版本中SPI 驱动有缺陷

### ISSUE THREAD

**Issue by chunyexixiaoyu** [RT-Thread/rt-thread#5170]
如果同时接rw007和LCD屏幕，rw007无法使用，还有KPU 感觉是堪智自己的硬件的坑，dma不同通道也会冲突
但是可以参考这个版本
https://github.com/kendryte/K210-Micropython-OpenMV

建议将这个版本的bsp的驱动合并到master

**Comment by mysterywolf** [comment]
可以提个pr吗 对k210不太了解

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/5181
