### ISSUE TITLE
newlib fopen "rb" mode pass the wrong arg 'flags" to _open_r with value 65536

### ISSUE THREAD

**Issue by rqbh** [RT-Thread/rt-thread#5186]
when call the fopen with mode "rb", _open_r get the wrong arg 'flags' with value 65536, replaced by "r+" , _open_r get the right args.

**Comment by mysterywolf** [comment]
Thank you for your report, and we also received a same problem from community.

社区报告：fopen 参数如果是rb+,会有问题

**Comment by mysterywolf** [comment]
I have confirmed that this problem caused by arm-gcc toolchain itself, not RT-Thread side. When arm-gcc's newlib is trying to convert from fopen to open, the parameter is given by mistake. rsicv-gcc toolchain and Keil IDE don't have this problem.

**Comment by mysterywolf** [comment]
Thanks for your report, we are going to fix this problem at https://github.com/RT-Thread/rt-thread/pull/5267. It will be merged in recent days. Thank you!
