### ISSUE TITLE
更新到4.0.4后，用gcc编译，gcc的fcntl.h里面的O_XX和rt-thread的不一致了

### ISSUE THREAD

**Issue by eddylin83** [RT-Thread/rt-thread#5265]
之前用master的时候（一段时间之前，大概4.0.2左右？），fopen打开文件没有问题，现在更新后，用"rb"选项打开出问题，查了一下，发现是因为使用b选项的时候，fopen传递给_open_r的flags是0x10000，即gcc的O_BINARY与rt-thread的O_DIRECTORY一致，导致以文件夹的方式打开文件。

**Comment by mysterywolf** [comment]
感谢定位问题点！

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/issues/5186

**Comment by mysterywolf** [comment]
感谢反馈，已经在https://github.com/RT-Thread/rt-thread/pull/5267 近日将合并
