### ISSUE TITLE
例程编译出错

### ISSUE THREAD

**Issue by i-wanglei** [RT-Thread/rt-thread#5269]
[例程编译出错] 编译stm32野火例程出错
克隆master分支`e6ae01e`，进入`G:\RT-Thread\rt-thread\bsp\stm32\stm32f103-fire-arbitrary` 路径，打开对应的Keil5工程，编译工程，提示`"no source": Error:  #5: cannot open source input file "..\..\..\components\libc\compilers\armlibc\libc.c": No such file or directory` ,查看`G:\RT-Thread\rt-thread\components\libc\compilers\armlibc`目录，确实没有libc库
查看gitee内`rt-thread\components\libc\compilers\armlibc` 此路径下存在libc.c和libc.h文件，但是gitee工程编译亦会报其他文件找不到错误

**Comment by mysterywolf** [comment]
请使用menuconfig重新生成一下keil工程，或者使用4.0.4发布版编译。master是开发版本，所以不能一直保证keil工程的结构是跟着最新的master来的，需要你手动刷新一下工程。发布版本会帮你刷新好工程。
