### ISSUE TITLE
[SDIO] Multi-host supporting

### ISSUE THREAD

**Issue by wosayttn** [RT-Thread/rt-thread#5307]
Hi,

最近在研究 RT_Device_Class_SDIO 的對接，這是個好物; 但在 Multi-host 下，似乎 auto-mounting 是不支持的?  它目前僅支持單張 SD 卡上的所有 FAT partition 掛載; 但似乎不支持 多張卡多區 的掛載?
EX: 
Now: sd0, sd1, ......., sdN.  
Wish: sda0, sda1, ......, sdaN; sdb0, sdb1, ....,sdbN.

[Mounting for Signle](https://github.com/RT-Thread/rt-thread/blob/master/components/drivers/sdio/block_dev.c#L402 )

是否可提供獲取來自 allocated host index 號，並加載這個資訊到各 block device name，讓多卡多區的掛載適配更加完善?

**Comment by BernardXiong** [comment]
欢迎提建议。

多SD/MMC，当前框架是支持的，不过好像是分区不支持？

**Comment by Guozhanxin** [comment]
这里有个pr，看看是不是相关的？https://github.com/RT-Thread/rt-thread/pull/5062

**Comment by wosayttn** [comment]
@BernardXiong 目前不支持的。
@Guozhanxin 不像我的wish。

我搞了 一版支持這個功能 且 提供一BUGFIX，請大師們 comment and approve to merge.
[Implemented](https://github.com/RT-Thread/rt-thread/pull/5312)
