### ISSUE TITLE
wait AT client connect timeout该如何分析

### ISSUE THREAD

**Issue by hessonsu** [RT-Thread/rt-thread#5337]
wait AT client(%s) connect timeout(%d tick).
开启ESP8266。
确实配置wifi ssid ，密码，uart3无错！改如何分析问题？

**Comment by xiangxistu** [comment]
AT Client 的 connect timeout ，这个情况是发生在 使用 AT 命令控制 ESP8266 的阶段。
这个和 wifi ssid, password 还没有直接关系。

排查问题应该从这个思路开始：

1. 模块是否能响应波特率 115200 的 AT 命令？
2. 前期的 AT -> AT OK，ATH -> OK 等命令是否正常响应？
3. 若前面的检查正常，则观察 wifi 连接的命令需要多久能返回结果，并且适当调整延时。

----

分析思路就是这样，不过，建议排查一下电路；接线与波特率这块要特别注意。

**Comment by hessonsu** [comment]
已解决！ #5346
