### ISSUE TITLE
4.0.5 计划发布/同步内容

### ISSUE THREAD

**Issue by mysterywolf** [RT-Thread/rt-thread#5356]
将自4.0.4发布后master发现的重要bug，向4.0.5同步更新
## 内核
- [ ] #5366 

## 组件
- [x] #5267
- [x] #5328 
- [ ] #5333
- [ ] #5335
- [ ] #5353

## BSP
- [ ] #5293
- [ ] #5251
- [ ] #5296

**Comment by xiangxistu** [comment]
https://github.com/RT-Thread/rt-thread/pull/5413

**Comment by Guozhanxin** [comment]
最后记得刷新工程

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/5417
