### ISSUE TITLE
BSP中的STM32F0工程编译失败

### ISSUE THREAD

**Issue by lishidetiankong** [RT-Thread/rt-thread#536]
是不是工程结构做了更改？git clone下来的代码直接编译失败，提示components/init/components.c找不到，仔细一看根本没有components/init/这个文件夹。。。

**Comment by wzyy2** [comment]
应该是要重新scons生成一下

**Comment by pangweishen** [comment]
components.c  移动到src目录下了

**Comment by lishidetiankong** [comment]
@pangweishen 的确移动到src目录下了，但是我把components.c文件定位到init文件夹下，仍然编译出错

**Comment by BernardXiong** [comment]
用scons从新生成下就好
