### ISSUE TITLE
为啥当时没把 device_find和device_open勾搭在一起呢，看着它们相离又相依的好伤心难过

### ISSUE THREAD

**Issue by heyuanjie87** [RT-Thread/rt-thread#538]

**Comment by BernardXiong** [comment]
我也有感觉，但是把device_find移除掉，只用device_open，这样会导致很多的代码修改。

**Comment by heyuanjie87** [comment]
在下个大版本变更的时候改吧，修改起来也不会太麻烦

**Comment by BernardXiong** [comment]
我看看是否可以考虑启用新的API，有什么推荐的吗？

**Comment by heyuanjie87** [comment]
那就只有用open read write这样的接口了

**Comment by BernardXiong** [comment]
或者，我们是否确实应该多探讨下基于文件接口open/read/write/close的设备操作方式？ @heyuanjie87 能否多提供些探索？

**Comment by Quintin-Z** [comment]
可以考虑直接使用posix接口，open/read/...，跟文件系统使用起来比较统一，移植类linux的程序也方便。不知道熊大有没看过nuttx的驱动框架

**Comment by BernardXiong** [comment]
具体没看过。open/read/write应该是趋势，但是合到device driver部分，可能还不仅仅需要这样，可能也需要底层感知到这样的接口。还在思考中...
