### ISSUE TITLE
\bsp\k210\driver\board.c:19:10: fatal error: encoding.h: No such file or directory

### ISSUE THREAD

**Issue by 30tobobroad** [RT-Thread/rt-thread#5450]
在\bsp\k210\driver\board.c:19:10，提交了不必要的头文件包含，导致编译失败：
 fatal error: encoding.h: No such file or directory

**Comment by Guozhanxin** [comment]
https://github.com/RT-Thread/rt-thread/pull/5445 已经修复了，可以测试下

**Comment by wineee** [comment]
我遇到了同样的问题，似乎没有修复，即使 git checkout 6b44585ade1b83e50c3b19f8c814efa3ee57ed88 到对应提交

CC build/applications/lcd_test.o
CC build/applications/main.o
CC build/applications/mnt.o
CC build/driver/board.o
driver/board.c:19:10: fatal error: encoding.h: No such file or directory
   19 | #include "encoding.h"
      |          ^~~~~~~~~~~~
compilation terminated.
