### ISSUE TITLE
请教关于NVIC_VTOR_MASK这个值是如何得到或计算的？

### ISSUE THREAD

**Issue by hessonsu** [RT-Thread/rt-thread#5457]
```c
/**
 * Function    ota_app_vtor_reconfig
 * Description Set Vector Table base location to the start addr of app(RT_APP_PART_ADDR).
*/
static int ota_app_vtor_reconfig(void)
{
    #define NVIC_VTOR_MASK   0x3FFFFF80
    /* Set the Vector Table base location by user application firmware definition */
    SCB->VTOR = RT_APP_PART_ADDR & NVIC_VTOR_MASK;

    return 0;
}
INIT_BOARD_EXPORT(ota_app_vtor_reconfig);
````
在[<STM32通过Bootloader>](https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/application-note/system/rtboot/an0028-rtboot?id=%E5%88%B6%E4%BD%9C-app-%E5%9B%BA%E4%BB%B6)一文中出现NVIC_VTOR_MASK   
请教关于NVIC_VTOR_MASK= 0x3FFFFF80这个值是如何得到或计算的？

**Comment by mysterywolf** [comment]
你好，请到社区论坛提问，issue用于汇报bug
https://club.rt-thread.org/index.html
