### ISSUE TITLE
通过scons生成CMake VSCode应使用相对路径

### ISSUE THREAD

**Issue by mysterywolf** [RT-Thread/rt-thread#5482]
目前通过scons生成Cmake vscode工程的头文件路径是绝对路径，应该和keil生成方法一样，使用相对路径，否则工程换个位置，就全报错了。
![image](https://user-images.githubusercontent.com/34888354/148421967-95aec337-a85e-43aa-b4f4-b25930efb629.png)
![image](https://user-images.githubusercontent.com/34888354/148422033-ba10d519-56a3-486a-93db-f1615629a194.png)

参见:
https://github.com/RT-Thread/rt-thread/blob/master/tools/keil.py#L383

**Comment by BernardXiong** [comment]
这个状态是？

**Comment by Guozhanxin** [comment]
为啥又关了？

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/5677
