### ISSUE TITLE
STM32F4 BSD的rtconfig问题

### ISSUE THREAD

**Issue by Jexbat** [RT-Thread/rt-thread#562]
在BSD为STM32F4的`rtconfig.h`文件中，未有定义`#define CHECKSUM_GEN_ICMP                 0`导致默认`CHECKSUM_GEN_ICMP`为**1**, 又lwip默认使用的硬件校验，所以导致ICMP校验总是出错，表现为ping响应超时，定义了`#define CHECKSUM_GEN_ICMP                0`之后问题解决。

**Comment by BernardXiong** [comment]
@aozima 确认下

**Comment by pangweishen** [comment]
应该是stm32f4xx_eth.c默认开启了CHECKSUM_BY_HARDWARE，而rtconfig.h中未定义CHECKSUM_GEN_ICMP，lwip默认使用软件校验和算法，而MAC采用硬件校验和，两者都生效了。

**Comment by xools** [comment]
#define CHECKSUM_CHECK_ICMP             0
#define CHECKSUM_GEN_ICMP                  0
需要在rtconfig.h里定义上面两个宏，否则会有问题。主要是Lwip生成了ICMP的校验和之后，发送时如果eth驱动也是默认全部生成校验和，则反而会清零校验和位置。
我发现好几个bsp都没有define上面两个宏，可能会有问题。但我也只在stm32f407平台上测试过。

**Comment by BernardXiong** [comment]
一般会考虑默认不开启硬件checksum的特性，由最终用户确定是否开启。

**Comment by mysterywolf** [comment]
issue关闭了，目前标准库已经淘汰掉了。
