### ISSUE TITLE
源码和脚本应该分隔开

### ISSUE THREAD

**Issue by Guozhanxin** [RT-Thread/rt-thread#5624]
目前，rt-thread 脚本和源码是绑定的，源码发布正式版本之后tools下的脚本就没办法更改了，就算是有bug需要修复也不能很方便的修改。。。
比如：4.0.5的tools目录下的脚步对python3的支持不好，有点问题。导致env升级python3之后，再想用4.0.5版本就比较费劲了。

**Comment by mysterywolf** [comment]
可否把tools的脚本都扔到env仓库去？

**Comment by aozima** [comment]
我觉得发布 4.0.5 的工具修正版本比较好！

**Comment by Guozhanxin** [comment]
也不光这一个，还有其他的问题，比如：生成eclipse工程这个脚本也不太对劲。旧版本的不支持这个命令，studio就用不了了。或者studio那边要重新写一套生成工程的逻辑出来，适配所有的rt-thread版本。维护起来也不怎么方便。

**Comment by BernardXiong** [comment]
这些都是跟着版本走的，有些bsp下的脚本可能都是和tools目录下的脚本相耦合。所以如果有这类的，还是升级版本吧
