### ISSUE TITLE
..\libraries\nuc980\rtt_port\drv_emac.c(458): error:  #20: identifier "old_level" is undefined

### ISSUE THREAD

**Issue by tylihongjie** [RT-Thread/rt-thread#5636]
# RT-Thread v4.1.0 Beta released

**..\libraries\nuc980\rtt_port\drv_emac.c(458): error:  #20: identifier "old_level" is undefined**

SYS_ARCH_DECL_PROTECT defined in \components\net\lwip\lwip-2.1.2\src\include\lwip\sys.h

in the head of  \bsp\nuvoton\libraries\nuc980\rtt_port\dev_emac.c must #include <lwip/sys.h>

**Comment by mysterywolf** [comment]
请确认该问题是否需要反馈，还是已经自己解决了？

**Comment by tylihongjie** [comment]
问题本地已解决,可以反馈开发人员修改库上代码。

**Comment by wosayttn** [comment]
Thanks. Updated in #5647.
