### ISSUE TITLE
cortex-m33 gcc支持

### ISSUE THREAD

**Issue by yanmowudi** [RT-Thread/rt-thread#5641]
使用env工具的gcc工具链编译cortex-m33内核芯片提示arm-none-eabi-gcc: error: unrecognized argument in option '-mcpu=cortex-m33'
是否是env的gcc版本不支持cortex-m33内核？
![微信截图_20220307105636](https://user-images.githubusercontent.com/11622534/156960823-c4616212-3369-4f01-b648-9f43776b3ca4.png)

**Comment by balanceTWK** [comment]
是的。

把 env 环境变量 RTT_EXEC_PATH  改成最新 gcc 工具链路径。 

或者 改 rtconfig.py 里的内容， gcc 工具链路径改下。

**Comment by balanceTWK** [comment]
另外问一句， m33 的 trustzone，咋用起来的？

**Comment by yanmowudi** [comment]
> 

env工具内置的gcc会更新吗？

**Comment by yanmowudi** [comment]
> 另外问一句， m33 的 trustzone，咋用的？

我是用的芯片没有TZ

**Comment by yanmowudi** [comment]
> 是的。
> 
> 把 env 环境变量 RTT_EXEC_PATH 改成最新 gcc 工具链路径。
> 
> 或者 改 rtconfig.py 里的内容， gcc 工具链路径改下。

env工具里的gcc后续会更新吗？

**Comment by yanmowudi** [comment]
> 另外问一句， m33 的 trustzone，咋用的？

我使用的芯片没有TZ.

**Comment by wendal** [comment]
默认的gcc的版本的确太低了, 现在看来

**Comment by BernardXiong** [comment]
好像后面是要发新的env版本了，发新版本可以考虑升级gcc工具链，或者可以把工具链配置成可选择/可安装的模式

**Comment by smarthobee612** [comment]
是否解决这个问题，我也遇到编译U5A5出现：
AR19DD~1.EXE: error: unrecognized argument in option '-mcpu=cortex-m33'

**Comment by suntong30** [comment]
> 是否解决这个问题，我也遇到编译U5A5出现： AR19DD~1.EXE: error: unrecognized argument in option '-mcpu=cortex-m33'

您好，请问rt-thread能支持UA5A使用tf-m吗？
