### ISSUE TITLE
\rt-thread\bsp\stm32\stm32h743-openmv-h7plus sdram test fail 

### ISSUE THREAD

**Issue by chunyexixiaoyu** [RT-Thread/rt-thread#5665]
![image](https://user-images.githubusercontent.com/24492495/157831314-53f584df-44a9-4fc6-9305-df074e21eb63.png)

@supperthomas 
谢谢老哥，麻烦老哥看下

**Comment by supperthomas** [comment]
@chunyexixiaoyu 建议看下https://club.rt-thread.org/ask/question/423914.html

**Comment by chunyexixiaoyu** [comment]
因为你写了sdram并在readme添加了，我以为你已经验证好了，所以我一开始以为我们自己的问题，事实你写的没问题，而你的bsp生成的时候pa7引脚没添加初始化，现在已经验证，后续我们团队会提交pr，完善该板子的bsp，谢谢。





------------------ Original ------------------
From: supperthomas ***@***.***&gt;
Date: Fri,Mar 11,2022 8:13 PM
To: RT-Thread/rt-thread ***@***.***&gt;
Cc: xiaoyu ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [RT-Thread/rt-thread]\rt-thread\bsp\stm32\stm32h743-openmv-h7plus sdram test fail  (Issue #5665)





 
@chunyexixiaoyu 建议看下https://club.rt-thread.org/ask/question/423914.html
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by supperthomas** [comment]
> 实你写的没问题，而你的bsp生成的时候pa7引脚没添加初始化，现在已经验证，后续我们团队会提交pr，完善该板子的bsp，谢谢。

欢迎PR。感谢。之前没调出来。

**Comment by chunyexixiaoyu** [comment]
后面提交pr先关闭
