### ISSUE TITLE
PHY_FULL_DUPLEX 标识符重复定义

### ISSUE THREAD

**Issue by skjsnb** [RT-Thread/rt-thread#5700]
\rt-thread-4.0.5\bsp\stm32\libraries\HAL_Drivers\drv_eth.c:407:5: error: redeclaration of enumerator 'PHY_FULL_DUPLEX'
     PHY_FULL_DUPLEX = (1 << 2),
     ^

\rt-thread-4.0.5\components\drivers\include/drivers/phy.h:32:5: note: previous definition of 'PHY_FULL_DUPLEX' was here
     PHY_FULL_DUPLEX       /* PHY full duplex. */
    ^

**Comment by xiangxistu** [comment]
F407 是自带 ETH 结构的，不需要启用 ```RT_USING_PHY``` 宏的吧；

就是添加多个网口的情况下，这两个宏定义也不应该出现在一个 C 文件里面；
