### ISSUE TITLE
rtthread.elf在龙芯派上启动异常。

### ISSUE THREAD

**Issue by allendai** [RT-Thread/rt-thread#5723]
![image](https://user-images.githubusercontent.com/3170020/160319381-aab65d08-2b8c-4f6e-9f73-2c8db84feaf3.png)

**Comment by allendai** [comment]
master 主干上编译的 rtthread.elf 在龙芯派上启动异常。

**Comment by thewon86** [comment]
https://club.rt-thread.org/ask/article/3186.html
