### ISSUE TITLE
生成 CMakeLists.txt 前对路径名和文件名按字母表重排序

### ISSUE THREAD

**Issue by QIANWC** [RT-Thread/rt-thread#5745]
![image](https://user-images.githubusercontent.com/25631947/160750905-1afe7c57-5c26-4249-b964-c8ae83faf0d2.png)
如图所示，scons每次生成的CMakeLists.txt里面的路径都是随机排列的，对于版本管理非常不利
cmake.py在写入之前sort一下就行
keil工程也是随机顺序，很久没用了，不知道改进了没
可能是个通病

**Comment by Guozhanxin** [comment]
没有改进，我刚试过了

**Comment by mysterywolf** [comment]
不光是Cmake，keil iar 的工程也有这个问题，完全是随机的

**Comment by armink** [comment]
是的，可以在 build.py 里统一处理一下

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/5783
