### ISSUE TITLE
开发者用户路径被写入测试用例

### ISSUE THREAD

**Issue by Rrooach** [RT-Thread/rt-thread#5752]
在rt-thread，提交编号201bd8871dff1efd1f48bdfd01a1938e4547ffd5中，rt-thread/bsp/qemu-riscv-virt64路径下，使用scons --target=makefile && make进行编译时，
'''
config.mk:4:CROSS_COMPILE ?=/home/lizhirui/workspace/riscv64-toolchains/bin/riscv64-unknown-elf-
rtconfig.py:18:    EXEC_PATH   = r'/home/lizhirui/workspace/riscv64-toolchains/bin'
'''
开发者写死的用户路径

**Comment by mysterywolf** [comment]
是的 这个路径是写死的，比较没有银杏，现在无法自动探测

**Comment by BernardXiong** [comment]
后续纠正过来，也欢迎发PR

**Comment by mysterywolf** [comment]
在env里敲入
set RTT_EXEC_PATH=D:\RT-ThreadStudio\repo\Extract\ToolChain_Support_Packages\WCH\RISC-V-GCC-WCH\8.2.0\bin
通过这个环境变量可以改变
