### ISSUE TITLE
GD32F4XX启动文件缺少82号中断向量

### ISSUE THREAD

**Issue by 909958846** [RT-Thread/rt-thread#5759]
bsp/gd32/libraries/GD32F4xx_Firmware_Library/CMSIS/GD/GD32F4xx/Source/GCC)/startup_gd32f4xx.s
中断向量表缺少82号.
word     CAN1_EWMC_IRQHandler              // 82:CAN1 EWMC
详细说明在https://club.rt-thread.org/ask/article/3148.html
https://github.com/RT-Thread/rt-thread/pull/5293/commits/4c42b5bd82420b1ef6089f9219d990d379b117e1

**Comment by aozima** [comment]
上面显示 #5293 已经修了吧？

**Comment by mysterywolf** [comment]
@909958846 如果没有什么问题的话可以关闭这个issue了
