### ISSUE TITLE
numaker-iot-m487音频播放问题

### ISSUE THREAD

**Issue by zhzsx** [RT-Thread/rt-thread#5822]
numaker-iot-m487上，使用wavplay对音频进行录音后播放测试，有一半概率播放声音是噪音，有些参数下甚至是变调；
参数 	       结果(测十次)	                                测试命令
1. 8000/1/16	3次有声音(环境噪明显), 7次全噪	wavrecord -s 8000_1.wav 8000 1; wavrecord -t; wavplay -s 8000_1.wav
2. 8000/2/16	6次正常，4次全是噪声	                wavrecord -s 8000_2.wav 8000 2; wavrecord -t; wavplay -s 8000_2.wav
3. 16000/1/16	5次正常，5次全是噪声	                wavrecord -s 16000_1.wav 16000 1; wavrecord -t; wavplay -s 16000_1.wav
4. 16000/2/16	5次正常，5次全是噪声	                wavrecord -s 16000_2.wav 16000 2; wavrecord -t; wavplay -s 16000_2.wav
5. 44100/1/16	5次变调加噪声，5次全是噪声	wavrecord -s 44100_1.wav 44100 1; wavrecord -t; wavplay -s 44100_1.wav
6. 44100/2/16	5次变调，5次全是噪声	                wavrecord -s 44100_2.wav 44100 2; wavrecord -t; wavplay -s 44100_2.wav
7. 48000/1/16	1次变调加噪声，9次全是噪声	wavrecord -s 48000_1.wav 48000 1; wavrecord -t; wavplay -s 48000_1.wav
8. 48000/2/16	1次变调加噪声，9次全是噪声	wavrecord -s 48000_2.wav 48000 2; wavrecord -t; wavplay -s 48000_2.wav

**Comment by wosayttn** [comment]
Hi,
How about use a SD card as recording/playback storage?
