### ISSUE TITLE
GD32 SPI驱动

### ISSUE THREAD

**Issue by evan-liyb** [RT-Thread/rt-thread#5843]
GD32的drv_spi.c里面，以下语句应该是写错了的吧？
    gpio_af_set(gd32_spi->spi_port, GPIO_AF_5,  gd32_spi->sck_pin | gd32_spi->mosi_pin | gd32_spi->miso_pin);

    gpio_mode_set(gd32_spi->spi_port, GPIO_MODE_AF, GPIO_PUPD_NONE, gd32_spi->miso_pin| gd32_spi->miso_pin);
    gpio_output_options_set(gd32_spi->spi_port, GPIO_OTYPE_PP, GPIO_OSPEED_200MHZ,gd32_spi->miso_pin| gd32_spi->miso_pin);

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/5729/

**Comment by evan-liyb** [comment]
好的，这个提交出太不小心了。
