### ISSUE TITLE
[新功能需求]关于finsh

### ISSUE THREAD

**Issue by pathletboy** [RT-Thread/rt-thread#586]
因为可能需要批量执行finsh命令，所以一般编写好命令例如：

```
set(1,1) //设置通道1为1
set(2,2) //设置通道2为2
...
```

将上述内容存至文档中，下次打开直接复制粘贴后执行。

现在问题是，finsh并不能处理好注释符，是否可以增加过滤注释的功能。

**Comment by BernardXiong** [comment]
我记得是支持的，你确定不支持吗？或者试试  /* your comments */

**Comment by pathletboy** [comment]
finsh>>list() /*123123*/
	Expect a operater
	finsh>>list() //123123   
	Invalid token

测试结果如上。

**Comment by pangweishen** [comment]
确实不支持
