### ISSUE TITLE
[bsp][qemu-vexpress-a9] 串口 CTS/RTS 硬件控制流支持

### ISSUE THREAD

**Issue by Jackistang** [RT-Thread/rt-thread#5950]
请问下 qemu-vexpress-a9 这个 bsp 里的串口 CTS/RTS 硬件控制流有计划支持么，我目前在基于 qemu 环境开发蓝牙应用，需要将蓝牙控制器以串口的形式接入 qemu，同时使能 CTS/RTS 硬件控制流，但该 bsp 目前不支持。

linux 环境借助 bluez 能够比较方便的使用 qemu 开发蓝牙应用。

若该 bsp 支持 CTS/RTS，在 windows 上基于 qemu 开发蓝牙应用也会很方便，希望官方能支持一下。

**Comment by supperthomas** [comment]
@Jackistang  Linux 下面没有问题，windows下面有问题，更新一下windows的qemu试试看。

**Comment by Jackistang** [comment]
我自己试过添加 cts/rts 驱动，但是在 windows 环境下还是不可以：https://github.com/Jackistang/rtthread-qemu-ble/commit/f20485adfed44b219f328e58d2ad6b1eb50dc9d1#diff-35e74e2c3ce0379ae398a70c885636d0d25a8ba236fdbd0d0bf0f53ce4895d8f

我更新下 windows 环境下的 qemu 再试试。

**Comment by supperthomas** [comment]
更新windows qemu 到7.0.0 不起作用。
