### ISSUE TITLE
qemu-riscv-virt64 smode 下无法启动

### ISSUE THREAD

**Issue by wineee** [RT-Thread/rt-thread#5979]
使用工具：
QEMU emulator version 7.0.0
opensbi v1.0

目前 m态 运行正常，但是 S态 无法启动：

./qemu-nographic-smode.sh 执行结果：
....(opensbi)
heap: [0x802323a1 - 0x866323a1]
 \ | /
- RT -     Thread Operating System
 / | \     4.1.0 build May 22 2022 01:38:06
 2006 - 2022 Copyright by RT-Thread team
xcause = 00000002,xtval = 80200112,xepc = 8025fdf8

Exception:
Illegal instruction
--------------Dump Registers-----------------
Function Registers:
xcause = 00000005,xtval = 802085a8,xepc = 80224b00

Exception:
Load access fault
--------------Dump Registers-----------------
Function Registers:
xcause = 00000005,xtval = 80208386,xepc = 80224d00

Exception:
Load access fault
--------------Dump Registers-----------------
Function Registers:
xcause = 00000005,xtval = 80208386,xepc = 80224d00

Exception:
Load access fault
--------------Dump Registers-----------------
Function Registers:
xcause = 00000005,xtval = 80208386,xepc = 80224d00

Exception:
Load access fault
--------------Dump Registers-----------------
Function Registers:
xcause = 00000005,xtval = 80208386,xepc = 80224d00
无限循环了

我是用 scons --pyconfig 配置的：
![image](https://user-images.githubusercontent.com/22803888/169642131-921ee8de-c1e6-4dfe-a341-6dd0a6030679.png)

大概测试了一下历史版本 https://github.com/RT-Thread/rt-thread/commit/cda8caeda0cf105dd660192e367017eea0d407ec 是可以用的， https://github.com/RT-Thread/rt-thread/commit/557821fd3dfb6e13fc26b65e199508ba09f49872 开始无法正常使用

**Comment by wineee** [comment]
(gdb) s
sbi_set_timer (val=6897667) at driver/sbi.c:125
125         if (has_time_extension)
=> 0x0000000080201dc4 <sbi_set_timer+12>:       97 77 02 00     auipc   a5,0x27
   0x0000000080201dc8 <sbi_set_timer+16>:       93 87 47 ec     addi    a5,a5,-316 # 0x80228c88 <has_time_extension>
   0x0000000080201dcc <sbi_set_timer+20>:       83 c7 07 00     lbu     a5,0(a5)
(gdb) s
132             (void)SBI_CALL1(SBI_SET_TIMER, 0, val);
=> 0x0000000080201e18 <sbi_set_timer+96>:       01 48   li      a6,0
   0x0000000080201e1a <sbi_set_timer+98>:       81 47   li      a5,0
   0x0000000080201e1c <sbi_set_timer+100>:      01 47   li      a4,0
   0x0000000080201e1e <sbi_set_timer+102>:      81 46   li      a3,0
   0x0000000080201e20 <sbi_set_timer+104>:      03 36 84 fd     ld      a2,-40(s0)
   0x0000000080201e24 <sbi_set_timer+108>:      81 45   li      a1,0
   0x0000000080201e26 <sbi_set_timer+110>:      01 45   li      a0,0
   0x0000000080201e28 <sbi_set_timer+112>:      ef f0 9f f1     jal     ra,0x80201d40 <sbi_call>
(gdb) s
sbi_call (arg7=arg7@entry=0, arg6=arg6@entry=0, arg0=arg0@entry=6897667, 
    arg1=arg1@entry=0, arg2=arg2@entry=0, arg3=arg3@entry=0, arg4=arg4@entry=0)
    at driver/sbi.h:150
150         register uintptr_t a0 __asm("a0") = (uintptr_t)(arg0);
=> 0x0000000080201d62 <sbi_call+34>:    03 35 84 fb     ld      a0,-72(s0)
(gdb) s
151         register uintptr_t a1 __asm("a1") = (uintptr_t)(arg1);
=> 0x0000000080201d66 <sbi_call+38>:    83 35 04 fb     ld      a1,-80(s0)
(gdb) s
152         register uintptr_t a2 __asm("a2") = (uintptr_t)(arg2);
=> 0x0000000080201d6a <sbi_call+42>:    03 36 84 fa     ld      a2,-88(s0)
(gdb) s
153         register uintptr_t a3 __asm("a3") = (uintptr_t)(arg3);
=> 0x0000000080201d6e <sbi_call+46>:    83 36 04 fa     ld      a3,-96(s0)
(gdb) s
154         register uintptr_t a4 __asm("a4") = (uintptr_t)(arg4);
=> 0x0000000080201d72 <sbi_call+50>:    03 37 84 f9     ld      a4,-104(s0)
(gdb) s
155         register uintptr_t a6 __asm("a6") = (uintptr_t)(arg6);
=> 0x0000000080201d76 <sbi_call+54>:    03 38 04 fc     ld      a6,-64(s0)
(gdb) s
156         register uintptr_t a7 __asm("a7") = (uintptr_t)(arg7);
=> 0x0000000080201d7a <sbi_call+58>:    83 38 84 fc     ld      a7,-56(s0)
(gdb) s
158         __asm __volatile(\
=> 0x0000000080201d7e <sbi_call+62>:    73 00 00 00     ecall
(gdb) s
0x0000000080000408 in ?? ()
=> 0x0000000080000408:  73 12 02 34     csrrw   tp,mscratch,tp
(gdb) s
Cannot find bounds of current function
(gdb) s
Cannot find bounds of current function

**Comment by wineee** [comment]
目前debug到这了，明天我再看看

**Comment by supperthomas** [comment]
欢迎尝试修正，PR。

**Comment by FatPigeorz** [comment]
在https://github.com/RT-Thread/rt-thread/commit/557821fd3dfb6e13fc26b65e199508ba09f49872 中和的最近的commit https://github.com/RT-Thread/rt-thread/commit/f57eb4feb5ee4856299058058eff15593ac0570d 下都没发现这种情况
![51](https://user-images.githubusercontent.com/79293503/201011571-bd45796e-861b-4b82-8bb1-1631d2185122.png)
![now](https://user-images.githubusercontent.com/79293503/201011586-5d05447e-971a-41c0-b138-29ac18bea500.png)

**Comment by mysterywolf** [comment]
solve in here: https://github.com/RT-Thread/rt-thread/pull/7040
