### ISSUE TITLE
关于 rt_container_of 代码注释的一点疑惑

### ISSUE THREAD

**Issue by wineee** [RT-Thread/rt-thread#5981]
https://github.com/RT-Thread/rt-thread/blob/master/include/rtservice.h

```c++
/**
 * rt_container_of - return the member address of ptr, if the type of ptr is the
 * struct type.
 */
#define rt_container_of(ptr, type, member) \
    ((type *)((char *)(ptr) - (unsigned long)(&((type *)0)->member)))
```

按照英文，应该是说如果 ptr 的类型是 struct 类型，返回ptr的成员（member）的地址

但实际上，ptr 应该是某个 struct （type）的一个成员（member），根据 ptr 的地址逆推出 struct 的首地址

不清楚我的理解对不对

**Comment by supperthomas** [comment]
欢迎PR，修正一下。
