### ISSUE TITLE
k210 bsp问题

### ISSUE THREAD

**Issue by catchPig51** [RT-Thread/rt-thread#5992]
在aa09f2b中的bsp里初始化到装载sd文件系统时出现：

> initialize mnt_initset spi freq 400198
Function[rt_mutex_take] shall not be used in ISR
(0) assertion failed at function:rt_mutex_take, line number:921 

将**drv_spi.c**、**drv_lcd.c**回滚到上一版本解决问题。

**Comment by chunyexixiaoyu** [comment]
目前仓内bsp中spi确实是我移植的，我是参考https://github.com/kendryte/K210-Micropython-OpenMV 进行移植的，然后K210 bsp库里面的勘智官方库和现在的spi可能适配有点出入，
https://github.com/kendryte/K210-Micropython-OpenMV  这个仓库据说是rt的人和勘智的人共同维护移植的，spi驱动比较稳定，我验证过RW007以及挂载相关的sd卡

如果要用现在的驱动版本最好适配以下仓库的勘智sdk
https://www.gitlink.org.cn/chunyexixiaoyu/kendryte-sdk-source  k210_bsp 分支
该分支参考的openmv将spi底层sdk稍微改写适配。
