### ISSUE TITLE
[bsp][qemu-vexpress-a9] 文件系统有问题

### ISSUE THREAD

**Issue by supperthomas** [RT-Thread/rt-thread#5999]
试了下qemu，文件系统有问题
![image](https://user-images.githubusercontent.com/60349489/170443539-b1996ddb-db92-480a-b0ca-12c03db1be48.png)

**Comment by BernardXiong** [comment]
啊，其他现象描述呢？fatfs？是否mount 上了？

**Comment by supperthomas** [comment]
> 

没有，sd0 没有mount上。

**Comment by supperthomas** [comment]
> 啊，其他现象描述呢？fatfs？是否mount 上了？

这个好像是时序的问题，等有空来解一下，或者其他小伙伴有兴趣解一下。应该很简单。

**Comment by supperthomas** [comment]
root cause: rt_hw_us_delay 这个函数没有实现，需要实现一下：
```
rt_hw_us_delay() doesn't support for this board.Please consider implementing rt_hw_us_delay() in another file.rt_hw_us_delay() doesn't support for this board.Please consider implementing rt_hw_us_delay() in another file.rt_hw_us_delay() doesn't support for this board.Please consider implementing rt_hw_us_delay() in another file.Hello RT-Thread!

```

**Comment by chenyingchun0312** [comment]
尝试再次mount，同样失败

![image](https://user-images.githubusercontent.com/44871523/171346291-bceb6cc8-152c-4ea6-8429-db9ae79fd843.png)

**Comment by supperthomas** [comment]
第一次使用，如果list_device中sd0没有mount上，就是文件系统不能用，进入rtthread执行如下命令

mkfs -t elm sd0

**Comment by mysterywolf** [comment]
如果文档中心有问题的话，可以直接改。
