### ISSUE TITLE
bsp/hc32/ev_hc32f4a0_lqfp176/board/config/uart_config.h uart10 定义错误.

### ISSUE THREAD

**Issue by liulee** [RT-Thread/rt-thread#6002]
#if defined(BSP_USING_UART10)
#ifndef UART10_CONFIG
#define UART10_CONFIG                                           \
    {                                                           \
        .name     = "uart10",                                   \
        .Instance = CM_USART10,                                 \
        .clock    = FCG3_PERIPH_USART10,                        \
        .rxerr_irq.irq_config =                                 \
        {                                                       \
            .irq_num    = BSP_UART10_RXERR_IRQ_NUM,             \
            .irq_prio   = BSP_UART10_RXERR_IRQ_PRIO,            \
            .int_src    = **INT_SRC_USART7_EI,**                    \
        },                                                      \
        .rx_irq.irq_config =                                    \
        {                                                       \
            .irq_num    = BSP_UART10_RX_IRQ_NUM,                \
            .irq_prio   = BSP_UART10_RX_IRQ_PRIO,               \
            .int_src    = **INT_SRC_USART7_RI**,                    \
        },                                                      \
        .tx_irq.irq_config =                                    \
        {                                                       \
            .irq_num    = BSP_UART10_TX_IRQ_NUM,                \
            .irq_prio   = BSP_UART10_TX_IRQ_PRIO,               \
            .int_src    = **INT_SRC_USART7_TI**,                    \
        },                                                      \
    }
#endif /* UART10_CONFIG */
#endif /* BSP_USING_UART10 */

/// bolded 部分.

**Comment by andychen329** [comment]
可以PR修复下
