### ISSUE TITLE
[Linux & English] Can IDE run natively on Linux?

### ISSUE THREAD

**Issue by rtek1000** [RT-Thread/rt-thread#6025]
Hello,

Can IDE run natively on Linux?

Because I tried some compilers for ARM and all of them compiled much faster when using Linux instead of Windows.

Post Script (P.S.): Preferably Linux Xubuntu (derived from Debian, easy to install and very light).

---

It would be nice for more people to read if people write the issues in English, translation to other languages ​​is better if it's from English.

---

I came here because I researched about RTOS compiler for Arm920T (S3C2440).

Thanks for sharing!

https://community.infineon.com/t5/Legacy-microcontrollers/What-RTOS-support-is-there-for-S6E2CC-Series/td-p/45504?start=0&tstart=0

**Comment by supperthomas** [comment]
Hi @rtek1000 :
you can follow this document to build the environment for linux. 

https://www.rt-thread.io/document/site/documentation/quick_start_qemu/quick_start_qemu_linux/


BYW, there's other document for you to know the RTOS for this link
https://www.rt-thread.io/document/site/introduction/introduction/

**Comment by rtek1000** [comment]
Thank you!

**Comment by mysterywolf** [comment]
Hi, Here is the latest version: https://github.com/RT-Thread/rt-thread/blob/master/documentation/quick-start/quick_start_qemu/quick_start_qemu_linux.md
If you would like to use MAC OS: here is the tutorial: https://github.com/RT-Thread/rt-thread/blob/master/documentation/quick-start/quick_start_qemu/quick_start_qemu_macos.md

Thank you for you suggestion. But we cannot force every community number to use English, which is a non-native language, to chat and discuss with others. Google translate may overcome this problem.

**Comment by BernardXiong** [comment]
Maybe we can open Pandora's box and use vscode + smart extension to develop RT-Thread under Linux.

**Comment by rtek1000** [comment]
ST and NPX manufacturers make use of Eclipse:

![NXP_MCUXpresso_IDE](https://user-images.githubusercontent.com/8660811/172045737-3ff6d6bb-13c5-4c98-b221-1af3f115a29e.png)


![ST_STM32CubeIDE](https://user-images.githubusercontent.com/8660811/172045724-a0bc931e-bdd4-47a5-8136-3c61477d6497.png)

**Comment by rtek1000** [comment]
There is also another IDE called ChibiStudio, which also has an Eclipse distribution:


> The best way to get started is to download ChibiStudio, an Eclipse-based environment with everything required in order to evaluate ChibiOS. 

https://osdn.net/projects/chibios/

![ChibiStudio](https://user-images.githubusercontent.com/8660811/172046135-ee2e26f7-37a5-4f34-b9ba-c85e4e7206d1.png)
