### ISSUE TITLE
🔨[bsp][RENESAS][driver][Improve the drivers within HAL_Driver]

### ISSUE THREAD

**Issue by supperthomas** [RT-Thread/rt-thread#6062]
可以做的PR:
- [x] 支持IAR  IDE
- [ ]  UART_V2 驱动支持 control 修改参数，如波特率
- [x] 硬件 IIC 驱动支持
- [x] 以太网 接口驱动
- [x] USB 接口驱动
- [x] 支持segger_rtt 软件包与console对接

**Comment by ShermanShao** [comment]
- [ ] UART_V2 驱动支持 control 修改参数，如波特率
- [ ] 硬件 IIC 驱动支持
- [ ] 以太网 接口驱动
- [ ] USB 接口驱动
