### ISSUE TITLE
USB CDC "CDC_SET_CONTROL_LINE_STATE"能否准确反映其连接状态？

### ISSUE THREAD

**Issue by balconyq** [RT-Thread/rt-thread#6099]
文件：components/drivers/usb/usbdevice/class/cdc_vcom.c
问题：虚拟串口的打开和关闭状态标识“connected”，与“SET_CONTROL_LINE_STATE”流控制操作绑定，是否合理？

**Comment by winfenggao** [comment]
不合理。不过好像没有更合适的办法。

**Comment by a5632645** [comment]
> 文件：components/drivers/usb/usbdevice/class/cdc_vcom.c 问题：虚拟串口的打开和关闭状态标识“connected”，与“SET_CONTROL_LINE_STATE”流控制操作绑定，是否合理？

合理的，如果DTR不为1你向主机发数据主机会拒绝并且重置端点
