### ISSUE TITLE
libcpu下的汇编文件为什么会用大写后缀呢, 这么奇怪

### ISSUE THREAD

**Issue by imxood** [RT-Thread/rt-thread#6111]
stm32cubemx rt-thread-nano, 生成Makefile项目, 由于汇编文件大小写的问题, 就要额外地处理一些新的路径匹配问题

**Comment by Guozhanxin** [comment]
你可以看看这个，大写的表示需要预处理

![image](https://user-images.githubusercontent.com/25633294/175871138-a88d8ffa-38d9-4186-b9d3-1081c92d79b9.png)
