### ISSUE TITLE
rt1170 bsp编译通不过

### ISSUE THREAD

**Issue by xjy198903** [RT-Thread/rt-thread#6173]
下载master源码，无论是使用keil arm还是使用env的scons指令，编译默认的imxrt1170 bsp均不能通过，请问如何解决

**Comment by supperthomas** [comment]
![图片](https://user-images.githubusercontent.com/60349489/180009459-863420d2-b4a5-4a0a-ba52-a6d233fb6687.png)

这里可以编译过，keil版本看看。我是5.36
