### ISSUE TITLE
[CPK-RA6M4] onenet上云报错<RT-Thread 的版本为 4.1.0 及以上>

### ISSUE THREAD

**Issue by kurisaW** [RT-Thread/rt-thread#6188]
问题描述：

​                 ![img](https://raw.githubusercontent.com/kurisaW/picbed/main/img/202207241346586.png)        

这里点击paho_mqtt_pipe.c中的#include <dfs_posix.h>跳转到该函数，然后将该函数封装的所有头文件声明复制到paho_mqtt_pipe.c中，并将`#include <dfs_posix.h>注释，另外还有一个函数报错同样如此。

此时编译发现仍会报错

​                 ![img](https://docimg2.docs.qq.com/image/BqvNBJF0wRwGXmMVp7P4Ew.png?w=1280&h=687.5247524752475)        

解决：

1. 我们需要修改刚刚复制的#include <pipe.h>为#include <ipc/pipe.h>
2. 使能 components -> c/C++ -> posix -> IPC -> pipe(进程间通信管道)
3. 查看paho_mqtt.h 内的  MQTTClient 结构体的代码，将94 行改为 #if defined(RT_USING_DFS_NET) || defined(SAL_USING_POSIX)；也就是去掉关于 RT_USING_POSIX 的内容。

此时再进行编译即可通过

​                 ![img](https://raw.githubusercontent.com/kurisaW/picbed/main/img/202207241346934.png)        

​                 ![img](https://raw.githubusercontent.com/kurisaW/picbed/main/img/202207241346979.png)        

​                 ![img](https://docimg2.docs.qq.com/image/wX6_XdFhiT1sWd75LAV2bQ.png?w=921&h=315)

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread-packages/onenet/pull/40
