### ISSUE TITLE
AT组件中的SIM7600在只有4G情况下无法连接的问题

### ISSUE THREAD

**Issue by weizhiX** [RT-Thread/rt-thread#6211]
问题描述：
在一个只有4g信号环境中，或者使用只开通4G的物联网卡的情况下，使用AT组件会初始化设备失败导致无法连接网络。
原因是AT组件中对AT+CREG和AT+CGRAG进行了判断。如果返回的不对就会直接退出初始化，CGREG是LTE这块业务的，CREG是2G这块业务的，如果遇到现场环境没有2G只有4G的实惠，CREG的返回就不会是0,1或者是0，5，程序会判断联网失败直接退出，所以后续即使有4G信号能通讯也是不行了。
如果直接屏蔽了CREG的判断和退出，那么就是可以正常是用4G的。
建议对AT+CREG和AT+CGRAG判断时，不要直接go exit

**Comment by xiangxistu** [comment]
应该是开发者在完善 AT_Device 时做了逻辑，可以按照自己的需求进行修改。
可以提交一个 PR，该 IUUSE 应该位于 https://github.com/RT-Thread-packages/at_device/issues

**Comment by xiangxistu** [comment]
已迁移
