### ISSUE TITLE
HID HOST issue with N9H30K41

### ISSUE THREAD

**Issue by updesh31** [RT-Thread/rt-thread#6216]
Currently I am using HMI-N9H30 dev board with N9H30K41 MPU with RT-Thread V4.1.0. All peripherals working ok. In USB HOST mode MSC is working Ok but when I am going to attach a keyboard always getting an error:
msh />EHCI port2 status change: 0x1403
EHCI port 2 - port reset failed!
OHCI port2 status change: 0x10301
OHCI connect device.
get full device descriptor failed

Can anybody help?

**Comment by andychen329** [comment]
@wosayttn please help

**Comment by wosayttn** [comment]
Hi, 
    We tested the UDISK function of rtthread on Nuvoton boards porting only, HID device not. Thanks.
