### ISSUE TITLE
[kernel memheap related] RT1170 SDRAM使能后，系统卡住

### ISSUE THREAD

**Issue by xjy198903** [RT-Thread/rt-thread#6243]
在4.1.1版本中，rt1170-evk使能SDRAM，在主函数中使用rt_malloc函数分配内存，系统卡住，代码如下：
/*
 * Copyright (c) 2006-2022, RT-Thread Development Team
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Change Logs:
 * Date           Author       Notes
 * 2019-05-06     tyustli      first version
 *
 */

#include <rtthread.h>
#include <rtdevice.h>
#include "drv_gpio.h"

char b_path[141072] = {1};

int main(void)
{
  while (1)
  {
    // rt_kprintf("test\r\n");
    char *full_path;
    full_path = (char *)rt_malloc(141072);
    rt_memcpy(full_path, b_path, 141072);
    rt_thread_mdelay(500);
  }
}

串口错误如下：
![image](https://user-images.githubusercontent.com/29084288/183541129-b83899fe-4b3d-4685-90c6-2d4d14eaa0ec.png)

**Comment by mysterywolf** [comment]
是否对full_path进行了检查? 是否为NULL？

**Comment by mysterywolf** [comment]
你这么写肯定要死机的，没有对pull_path进行参数检查，而且还放在了循环里，1秒钟就要执行两次，过不了一会就会内存消耗光，然后就memset直接就死机了。

顺便用free命令看一下当前有多少内存

**Comment by xjy198903** [comment]
注释掉申请内存的代码，可以看到：
![image](https://user-images.githubusercontent.com/29084288/183549637-d21e6d99-780d-41fb-b223-70d27dbf83d1.png)
，只要加了申请内存的代码：
#include <rtthread.h>
#include <rtdevice.h>
#include "drv_gpio.h"

char b_path[141072] = {1};

int main(void)
{
  // char *full_path;
  // full_path = (char *)rt_malloc(141072);
  // if (full_path != RT_NULL)
  // {
  //   rt_memcpy(full_path, b_path, 141072);
  // }

  while (1)
  {
    // rt_kprintf("test\r\n");

    rt_thread_mdelay(500);
  }
}
就是卡住，串口报错：
![image](https://user-images.githubusercontent.com/29084288/183549834-8dbd09e6-c816-4830-879d-7c2a69825a4a.png)

**Comment by mysterywolf** [comment]
你把memcpy注释掉还死机吗？

**Comment by xjy198903** [comment]
注释掉以后，不死机了，串口输出：
![image](https://user-images.githubusercontent.com/29084288/183552088-bcbf7c7a-b602-47c0-8f18-736c20e0f107.png)
能看到它从系统HEAP里面分配空间了

**Comment by mysterywolf** [comment]
![image](https://user-images.githubusercontent.com/34888354/183553320-98a5c6ed-2a40-4147-98d0-e9efb16bc732.png)
把这个勾选上，再打开rt_memcpy试试？

**Comment by xjy198903** [comment]
![image](https://user-images.githubusercontent.com/29084288/183556480-d2315c13-ca66-4844-bfa3-673859a5ee8b.png)
已加入选项，解除rt_memcpy后，仍还卡死

**Comment by xjy198903** [comment]
补充说明：开发环境为IAR 9.30.1

**Comment by mysterywolf** [comment]
昨天NXP官方已经帮你验证过了，我今天又确认了一次，他们那边可以正确运行，你的问题无法复现😂 1170支持IAR

**Comment by mysterywolf** [comment]
<img width="685" alt="576db44fa87cc5bb96aa1582ef74841" src="https://user-images.githubusercontent.com/34888354/183569195-8bf963e2-55b4-419f-9ba7-d343a5c1174e.png">

**Comment by mysterywolf** [comment]
![image](https://user-images.githubusercontent.com/34888354/183569216-24470ac4-ae97-4ef9-b1de-383cc5fe5a17.png)

**Comment by xjy198903** [comment]
版本不一样，我用的是最新的4.1.1，而且官方的没说SDRAM有没有扩大到64M，目前BSP（drv_sdram.c和sdram_port.h）支持的是32M的大小

**Comment by xjy198903** [comment]
切换到4.1.0版本，SDRAM一切正常，串口输出如下：
![image](https://user-images.githubusercontent.com/29084288/183575874-69be8438-f904-46fb-a61c-59dc15926754.png)
main函数操作如下：
#include <rtthread.h>
#include <rtdevice.h>
#include "drv_gpio.h"

int main(void)
{
    char *buf = (char*)rt_malloc(4*1024*1024);
    if(buf)
    {
      rt_memcpy(buf, "hello RT-Thread 4.1.0", 25);
      buf[26] = '\0';
    }
    rt_kprintf("buf: %s\r\n", buf);
    rt_free(buf);
    while (1)
    {
//      rt_kprintf("test\r\n");
      rt_thread_mdelay(500);
    }
}

**Comment by xjy198903** [comment]
中间的数字是4*1024*1024，没有显示全

**Comment by xjy198903** [comment]
信号显示不了，应该是`4*1024*1024`

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/tree/master/bsp/imxrt/imxrt1170-nxp-evk
这个BSP是今年五月份才提交上来的，为什么能切到4.1.0版本呢，4.1.0是今年三月发布的呀

**Comment by xjy198903** [comment]
我参照4.1.1，1170-nxp-evk文件夹拷贝过来，重复4.1.1版本的操作（引脚配置等等），重新编译烧录，就可以，可以肯定的是，4.1.1这部分有问题应该是kernel部分有待完善；上面的截图，NXP官方还玩的4.0.4，估计他们也是把现有代码拷贝去测试的

**Comment by mysterywolf** [comment]
好的&nbsp; 这回应该清楚了 不是nxp的问题&nbsp; 我反馈一下争取4.1.1发布的时候解决



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月9日(周二) 凌晨2:13
收件人: ***@***.***&gt;;
抄送: "Man, Jianting ***@***.******@***.***&gt;;
主题: Re: [RT-Thread/rt-thread] RT1170 SDRAM使能后，系统卡住 (Issue #6243)




 
我参照4.1.1，1170-nxp-evk文件夹拷贝过来，重复4.1.1版本的操作（引脚配置等等），重新编译烧录，就可以，可以肯定的是，4.1.1这部分有问题应该是kernel部分有待完善；上面的截图，NXP官方还玩的4.0.4，估计他们也是把现有代码拷贝去测试的

**Comment by xjy198903** [comment]
嗯嗯，我在4.1.0版本上，再测试下1170别的接口☺

**Comment by mysterywolf** [comment]
可否帮忙看一下Keil下是否也会发生同样的问题？ 4.1.1版本

**Comment by xjy198903** [comment]
测试情况：Keil 5.30，使能SDRAM后，串口输出：
![image](https://user-images.githubusercontent.com/29084288/183600130-f0d60f03-e45d-4129-a0af-59f6288f1cba.png)
系统卡住

**Comment by mysterywolf** [comment]
OK 感谢

**Comment by mysterywolf** [comment]
HI, 你用目前的最新的代码，把这个commit revert回来之后试试 看看还死机嘛？
https://github.com/RT-Thread/rt-thread/commit/4562ae12460c22617185dd66332c5b591f256e7b

**Comment by xjy198903** [comment]
你是说下载最新的代码，但是用原来的1170的bsp文件去验证吗？

**Comment by mysterywolf** [comment]
不是 我怀疑是 这个提交记录导致的问题，请帮忙验证一下  https://github.com/RT-Thread/rt-thread/commit/4562ae12460c22617185dd66332c5b591f256e7b
你把这个提交记录里的内容恢复回来，也就是revert翻转回来，应该只翻转memheap.c的就可以
![image](https://user-images.githubusercontent.com/34888354/184520597-70a6b537-752b-434d-a383-82699a942fab.png)
然后再测试一下rt_memcpy还死机否

记得用最新的代码

**Comment by xjy198903** [comment]
嗯。清楚了，不过得明天了，我现在手上没板子

**Comment by mysterywolf** [comment]
嗯嗯 谢谢

**Comment by mysterywolf** [comment]
我在QEMU上测了一下 可以正确分配和memcpy 不会死机
我在怀疑 是不是你分配的内存不允许4字节拷贝还是有什么奇奇怪怪的限制

![image](https://user-images.githubusercontent.com/34888354/184557734-8b82ba05-09f1-4e14-8631-797a4f28a6fe.png)

**Comment by mysterywolf** [comment]
> 我在怀疑 是不是你分配的内存不允许4字节拷贝还是有什么奇奇怪怪的限制

不过也不应该 如果物理内存有限制的话 4.1.0也应该会崩

**Comment by xjy198903** [comment]
那也应该是系统的问题，同样的代码，4.1.0自运行正确后，已连续运行1周无异常，同样的代码，在4.1.1立马死机

**Comment by mysterywolf** [comment]
是的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月14日(周日) 晚上6:54
收件人: ***@***.***&gt;;
抄送: "Man, Jianting ***@***.******@***.***&gt;;
主题: Re: [RT-Thread/rt-thread] [kernel memheap related] RT1170 SDRAM使能后，系统卡住 (Issue #6243)




 
那也应该是系统的问题，同样的代码，4.1.0自运行正确后，已连续运行1周无异常，同样的代码，在4.1.1立马死机

**Comment by xjy198903** [comment]
4.1.1如果直接用rt_memheap_alloc分配后，直接操作sdram可以随便操作，分配1兆没问题；4.1.0我现在用rt_malloc分配了4兆的空间，稳定运行

**Comment by mysterywolf** [comment]
嗯 这肯定是内核的问题了 有时间先帮忙revert一下看看&nbsp; 我这边死活复现不出来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月14日(周日) 晚上6:57
收件人: ***@***.***&gt;;
抄送: "Man, Jianting ***@***.******@***.***&gt;;
主题: Re: [RT-Thread/rt-thread] [kernel memheap related] RT1170 SDRAM使能后，系统卡住 (Issue #6243)




 
4.1.1如果直接用rt_memheap_alloc分配后，直接操作sdram可以随便操作，分配1兆没问题；4.1.0我现在用rt_malloc分配了4兆的空间，稳定运行

**Comment by xjy198903** [comment]
好的，我尽快测试

**Comment by xjy198903** [comment]
revert以后，注释掉ipc文件的RT_DEBUG_SCHEDULER_AVAILABLE(time != 0);增加SDRAM支持后，主函数如下：
/*
 * Copyright (c) 2006-2022, RT-Thread Development Team
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Change Logs:
 * Date           Author       Notes
 * 2019-05-06     tyustli      first version
 *
 */

#include <rtthread.h>
#include <rtdevice.h>
#include "drv_gpio.h"

int main(void)
{
    char *buf = (char*)rt_malloc(4*1024*1024);
    if(buf)
    {
      rt_memcpy(buf, "hello RT-Thread 4.1.0 for RT1176", 39);
      buf[40] = '\0';
    }
    rt_kprintf("buf: %s\r\n", buf);
    rt_free(buf);
    while (1)
    {
//      rt_kprintf("test\r\n");
      rt_thread_mdelay(500);
    }
}
系统运行如下：

![image](https://user-images.githubusercontent.com/29084288/184561900-7fc77242-3d6e-447a-8c49-937ae3ead452.png)

一切正常

**Comment by mysterywolf** [comment]
好的 感谢！我来考虑怎么处理一下

**Comment by xjy198903** [comment]
我要上传下SDRAM相关的配置，目前的BSP，SDRAM编译过不去，配置也不太对

**Comment by mysterywolf** [comment]
嗯嗯好的
我看了一下这个commit里边的内容，这里边主要是检查memheap是否在调度器启动之后调用，因为memheap用到了互斥量和信号量，因此需要确保调度器启动之后才能够初始化memheap。是不是在这个bsp里边，有在调度器启动之前就开始初始化memheap了？

**Comment by xjy198903** [comment]
rt_hw_board_init应该是在调度器起来之前就运行了，这里面有
#ifdef RT_USING_HEAP
    rt_system_heap_init((void *)HEAP_BEGIN, (void *)HEAP_END);
#endif

**Comment by mysterywolf** [comment]
好的 问题点找到了 这里初始化有问题...

**Comment by xjy198903** [comment]
我上传了sdram的修改，但是备注好像还是上一次的"RTL8211F驱动"相关的信息，merge的时候改下修改信息

**Comment by mysterywolf** [comment]
没关系 这个我来处理一下即可

**Comment by xjy198903** [comment]
SDRAM的修改还没有merge到master吧

**Comment by mysterywolf** [comment]
merge了呀 你提交的PR我都合并了 你看一下是不是你上个PR漏提交了，或者是fork下来的rt-thread仓库没有同步rt-thread最新？

**Comment by mysterywolf** [comment]
另外提交pr的时候建议基于你仓库的master新建一个分支来提交，不要直接往你仓库的master分支上提交。

**Comment by xjy198903** [comment]
提示这个：
![image](https://user-images.githubusercontent.com/29084288/184582915-f812c57a-01b3-477a-b221-9a94e3f6b88d.png)
文件格式不对吗，还是什么的，我现在在master里面没看到这部分修改的内容

**Comment by xjy198903** [comment]
> 另外提交pr的时候建议基于你仓库的master新建一个分支来提交，不要直接往你仓库的master分支上提交。

好的

**Comment by mysterywolf** [comment]
应该是你全往master合并然后覆盖掉了 你看看可否重新提交一下？ 点击每一个update xxxx 这种记录就能看见你的当次提交内容

**Comment by xjy198903** [comment]
好的，我fork后，新建分支再PR吧

**Comment by mysterywolf** [comment]
提PR一般是这样：
从rt-thread/rt-thread仓库fork下来一份到你自己用户名下的rt-thread的仓库，然后，你用户名下的rt-thread仓库应该始终和rt-thread官方仓库的master分支保持同步，每次提交PR都从你仓库的master创建一个新的分支，一个分支一个目标比如修改网络或者什么的，然后基于此分支创建PR。然后可以创建下一个分支，再提另外一个主题的PR。

**Comment by xjy198903** [comment]
正常开发来说是这样的，我这跨步骤了，为了省事

**Comment by xjy198903** [comment]
已重新提交

**Comment by mysterywolf** [comment]
请问你死机的时候第二个rt_memheap_init 是放在哪里初始化的？第一个rt_memheap_init就是你截图的位于hw_board_init函数里，第二个哩 您放在哪里了？

**Comment by xjy198903** [comment]
第二个在drv_sdram.c里面，作为board init一部分进行的，你看一下

**Comment by mysterywolf** [comment]
你把rt_hw_sdram_Init 塞到了 rt_hw_board_init里？

**Comment by xjy198903** [comment]
不是我塞的，是原来bsp这么安排的，作为BOARD_INIT的一部分，初始化流程我没动过

**Comment by mysterywolf** [comment]
噢噢 我知道问题在哪里了
我一会把你提交的那个PR改一下 然后你帮忙测试下
问题就出在这个BOARD_INIT上，我刚才以为你是直接塞到了rt_hw_board_init里，无论是那种方式，都会死机
第二个rt_memheap_init必须在调度器起来之后才能用

**Comment by xjy198903** [comment]
好的，修改好了我试一下

**Comment by mysterywolf** [comment]
合并进去了 你可以拉取一下最新的代码 试一试

**Comment by xjy198903** [comment]
拉取最新代码，测试没问题，不过多了个编译警告，我把drv_sdram.h中init函数的声明注释掉了

**Comment by mysterywolf** [comment]
ok 麻烦还得提个pr 我现在不在电脑旁 直接把.h的声明删了就可以了。 顺利解决！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月15日(周一) 凌晨3:50
收件人: ***@***.***&gt;;
抄送: "Man, Jianting ***@***.******@***.***&gt;;
主题: Re: [RT-Thread/rt-thread] [kernel memheap related] RT1170 SDRAM使能后，系统卡住 (Issue #6243)




 
拉取最新代码，测试没问题，不过多了个编译警告，我把drv_sdram.h中init函数的声明注释掉了

**Comment by xjy198903** [comment]
![image](https://user-images.githubusercontent.com/29084288/184597593-0ed7eb59-77f1-4500-af16-90c873d99e6a.png)
