### ISSUE TITLE
RT1170-EVK 千兆网卡rtl8211f驱动

### ISSUE THREAD

**Issue by xjy198903** [RT-Thread/rt-thread#6258]
在百兆网卡ksz8081测试通过的情况下，增加千兆网卡8211F的驱动支持，程序加载完成后，芯片CLK_OUT脚稳定输出125MHz，系统未卡住，只要在板卡执行ping执行，系统就会卡住，请问这种问题大概是由什么引起的，或者排查点有哪些？如果NXP官方能指点下就最好了，增加和修改的文件见附件；程序执行后，串口显示：
![image](https://user-images.githubusercontent.com/29084288/184329856-ee7bdf87-736b-4662-ba63-2c20b0cb5264.png)

[修改文件.zip](https://github.com/RT-Thread/rt-thread/files/9315419/default.zip)

**Comment by xjy198903** [comment]
仔细看了下nxp官方RT1170-EVK的SDK中网络驱动部分（fsl_enet.c）和现有rt-thread中的驱动文件差别太大，基本无法融合，建议rt-thread社区能跟随开发板SDK的发布，更新相应驱动文件，这样也能加快社区伙伴适配rt-thread的进度

**Comment by mysterywolf** [comment]
可以帮忙更新一下NXP SDK吗？欢迎提交PR

**Comment by xjy198903** [comment]
已按SDK2.12版本，更新所有文件 #6264
