### ISSUE TITLE
RT-Thread Studio update error

### ISSUE THREAD

**Issue by updesh31** [RT-Thread/rt-thread#6267]
I am getting this error :
scons: Reading SConscript files ...
Traceback (most recent call last):
    from cmds import *
    from .cmd_package_upgrade import package_upgrade
    from pip._internal.utils.misc import get_installed_distributions
ImportError: No module named _internal.utils.misc

**Comment by mysterywolf** [comment]
thanks for reporting. fix at here https://github.com/RT-Thread/env/pull/164

you can close the studio and reopen it. and wait for 10 seconds.

**Comment by mysterywolf** [comment]
Thank you!
