### ISSUE TITLE
fatal error: perf_counter.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by neuberfran** [RT-Thread/rt-thread#6273]
This issue insists on appearing in every project I start. In fact its does not appear right after the project is created, but after adding one or another package. LVGL type, etc.

Even if I remove the package, the error does not disappear and the project does not work again

![screen101](https://user-images.githubusercontent.com/38701397/184539810-48dbc79c-1758-4e2a-a796-d82037eaa098.png)
![screen102](https://user-images.githubusercontent.com/38701397/184539814-e4ac8e9c-c137-4830-9c70-1d0d6f050cd1.png)

**Comment by mysterywolf** [comment]
You may go to the project folder and use ENV to download the pakcages `pkgs --update`

**Comment by mysterywolf** [comment]
![屏幕截图 2022-08-14 164306](https://user-images.githubusercontent.com/34888354/184554221-800af0b7-2604-4cbf-9498-8d3c5ae6bd0f.png)

![image](https://user-images.githubusercontent.com/34888354/184554218-044e80a0-5676-4a78-95c3-5265e286b99e.png)

**Comment by neuberfran** [comment]
@mysterywolf  I stay trying pkgs --update But this issue back again
![image](https://user-images.githubusercontent.com/38701397/185724600-39983a8a-7904-4897-9d56-abe135e4992d.png)
