### ISSUE TITLE
Folder does not appear in packages: Permission issues or something wrong with RT-THREAD STUDIO IDE

### ISSUE THREAD

**Issue by neuberfran** [RT-Thread/rt-thread#6276]
As is clear from the photos below, the folder does not appear where it should in the RT-THREAD STUDIO IDE. I've already done packages update and sync sconscript to project in RTT Studio and pksgs --update using ENV. It didn't.
It's not permission issue on my PC. There must be something wrong in the RTT Studio IDE.

![screen120](https://user-images.githubusercontent.com/38701397/184559492-e3d30bb3-55bb-4747-875f-2e7cb5eb6f03.png)
![screen121](https://user-images.githubusercontent.com/38701397/184559500-623c2a97-020d-4f07-af28-c22b6caab1aa.png)

**Comment by mysterywolf** [comment]
This is not RT-Thread Studio problem.
ui folder is your application folder, you need to add it into your project by yourself. I suggest to move ui folder into application folder and modify the Sconscript file to add .c files and .h paths

**Comment by neuberfran** [comment]
@mysterywolf 
Where be ui folder? I put in applications folder too. But nothing
![image](https://user-images.githubusercontent.com/38701397/184651637-cb3f0566-2815-41d9-8395-ca180d3bf4d4.png)

**Comment by neuberfran** [comment]
@mysterywolf 

In w11 (My Works Machine) I can't use simulator yet with vs2022.
I can't see lvgl (And Screen Music Demo) results list_thread:

scons --target=vs2012
scons: Reading SConscript files ...

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\test\rt-thread\bsp\simulator\SConstruct", line 13, in <module>

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\test\rt-thread\bsp\simulator\SConstruct", line 15, in <module>
**No vc version!**
scons: done reading SConscript files.
![screen131](https://user-images.githubusercontent.com/38701397/184653113-063a8d58-ce1a-49be-bec3-874f367c43cc.png)
![screen132](https://user-images.githubusercontent.com/38701397/184653133-f9f0624e-1a43-42f7-bc40-74fb8db1b07c.png)

**Comment by mysterywolf** [comment]
> @mysterywolf
> 
> In w11 (My Works Machine) I can't use simulator yet with vs2022. I can't see lvgl (And Screen Music Demo) results list_thread:
> 
> scons --target=vs2012 scons: Reading SConscript files ...
> 
> scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly File "C:\test\rt-thread\bsp\simulator\SConstruct", line 13, in
> 
> scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly File "C:\test\rt-thread\bsp\simulator\SConstruct", line 15, in **No vc version!** scons: done reading SConscript files. ![screen131](https://user-images.githubusercontent.com/38701397/184653113-063a8d58-ce1a-49be-bec3-874f367c43cc.png) ![screen132](https://user-images.githubusercontent.com/38701397/184653133-f9f0624e-1a43-42f7-bc40-74fb8db1b07c.png)

You didn't enable LVGL, of course you cannot see LVGL demo

**Comment by neuberfran** [comment]
> > @mysterywolf
> > In w11 (My Works Machine) I can't use simulator yet with vs2022. I can't see lvgl (And Screen Music Demo) results list_thread:
> > scons --target=vs2012 scons: Reading SConscript files ...
> > scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly File "C:\test\rt-thread\bsp\simulator\SConstruct", line 13, in
> > scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly File "C:\test\rt-thread\bsp\simulator\SConstruct", line 15, in **No vc version!** scons: done reading SConscript files. ![screen131](https://user-images.githubusercontent.com/38701397/184653113-063a8d58-ce1a-49be-bec3-874f367c43cc.png) ![screen132](https://user-images.githubusercontent.com/38701397/184653133-f9f0624e-1a43-42f7-bc40-74fb8db1b07c.png)
> 
> You didn't enable LVGL, of course you cannot see LVGL demo


> > @mysterywolf Where be ui folder? I put in applications folder too. But nothing ![image](https://user-images.githubusercontent.com/38701397/184651637-cb3f0566-2815-41d9-8395-ca180d3bf4d4.png)
> 
> You can copy this Sconscript into your folder. Then modify it, based on your C file position.

Everytime I need to import my old project from another Pc(Backup) to backup My ui folder. It's not Cool. How to configure SConscript file? Where will be SConscript file  that I will have to reconfigure?

![image](https://user-images.githubusercontent.com/38701397/184668968-7c6ca03a-809a-4674-9209-f72a3161e587.png)

**Comment by neuberfran** [comment]
@mysterywolf 
Everytime I need to import my old project from another Pc(Backup) to backup My ui folder. It's not Cool. How to configure SConscript file? Where will be SConscript file that I will have to reconfigure?
![image](https://user-images.githubusercontent.com/38701397/184680753-b95cfecd-2fdc-4d0d-b3e2-3a98ee4fa93d.png)

**Comment by neuberfran** [comment]
@mysterywolf 
Same issue using Env/scons command:

Look to ls -lha in ui folder. Not is wrong. I think

![image](https://user-images.githubusercontent.com/38701397/184684821-8dfd1922-b7c9-4ff1-8989-4a9066fd327a.png)

**Comment by neuberfran** [comment]
> LVGL

I enable LVGL. But I can't see lvgl thread (and Music demo app screen). I think it's a windows 10 (and not windows 11) SDK

**Comment by mysterywolf** [comment]
I submit a PR, you may try this https://github.com/lvgl/lvgl/commit/704363c5bdd5b29b00bf51807720f86c8f79bb6b
