### ISSUE TITLE
RT1170网络问题

### ISSUE THREAD

**Issue by xjy198903** [RT-Thread/rt-thread#6282]
使用最新的RT1170-EVK板卡SDK2.12的网络驱动后，无论是rtl8211f还是ksz8081，均发送超时，请问有NXP官方人员根据最新SDK调整drc_eth.c文件吗？如果不做调整，最新SDK将无法满足网络使用的需求

**Comment by xjy198903** [comment]
没有其它小伙伴用rt1170吗

**Comment by supperthomas** [comment]
https://github.com/NXPmicro/mcux-sdk   这里找找看。 @xjy198903

**Comment by xjy198903** [comment]
> https://github.com/NXPmicro/mcux-sdk 这里找找看。 @xjy198903

NXP官方SDK的部分我已经同步到主线了，相关的驱动代码我已在freertos上测试过，没有问题，但用rt-thread的网络模型，通用驱动文件drv_eth.c后，百兆千兆通信都是超时；freertos上一切正常

**Comment by supperthomas** [comment]
> 到

可以把同步的先PR上来，大家帮你看看

**Comment by xjy198903** [comment]
已提交PR #6293

**Comment by xjy198903** [comment]
> > 到
> 
> 可以把同步的先PR上来，大家帮你看看

已同步最新的代码，麻烦看一下
