### ISSUE TITLE
网络指令ifconfig的问题

### ISSUE THREAD

**Issue by xjy198903** [RT-Thread/rt-thread#6322]
按照https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/programming-manual/net/net_introduce 里面的说明，ifconfig执行时，会有：
![image](https://user-images.githubusercontent.com/29084288/185850273-55f472c9-199f-41b8-b9f8-94c01868c843.png)

但在4.1.1版本的lwip2.0.3版本中，执行ifconfig的结果如下：
![image](https://user-images.githubusercontent.com/29084288/185850291-67740926-ac45-4a27-8b48-b34c441d503d.png)

没有**INTERNET_UP / INTERNET_DOWN**字段，是系统删除了还是网络设备配置有问题？
————————————————
版权声明：本文为RT-Thread论坛用户「linuxer」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://club.rt-thread.org/ask/question/9778633f1f97ff09.html

**Comment by mysterywolf** [comment]
https://club.rt-thread.org/ask/question/9778633f1f97ff09.html
