### ISSUE TITLE
是不是有计划让rt_kprintf支持2进制和8进制打印？

### ISSUE THREAD

**Issue by winfenggao** [RT-Thread/rt-thread#6332]
rt_kprintf 和 rt_sprintf 函数是不是后续支持2进制和8进制打印？
相关函数中添加了%o的选项，并做了base赋值，但没有%b

当前代码中虽然添加了%o选项，但在函数
rt_inline int divide(long *n, int base) 中没有做相应的进制处理，依然按照非10进制即16进制来处理的。

**Comment by mysterywolf** [comment]
欢迎提交pr实现

**Comment by winfenggao** [comment]
刚注意到，标准c库的printf不支持%b,我想当然的一直以为有。

**Comment by mysterywolf** [comment]
没关系，rt_kprintf是rt-thread内部自己用的，不必完全遵循C标准，%b这个功能挺常用的，可以考虑加上的 包括你提到的八进制打印
