### ISSUE TITLE
rt-thread/ch32v307 NOT have ethernet connection AND RT-Thread terminal NOT have ifconfig command

### ISSUE THREAD

**Issue by neuberfran** [RT-Thread/rt-thread#6368]
https://blog.csdn.net/bonson2004/article/details/122040352

I've been having success with the video tutorial above for two weeks now.

I enable UART1 to UART8. In ifconfig part I can see (using ifconfg e0 Not **ifconfig Only** egual tutorial) 192.168.1.30, etc, etc...But I can't ping to 192.168.1.2. I don't know why.

Evidently, I already tried with router, with switch And with crossover ethernet cable.

Why I don't have ifconfig command egual tutorial ?

How can i get ethernet/internet connection on ch32v307 board?

**Link about photos of this issue:**
https://drive.google.com/drive/folders/17KWvUCj2QosKkptQX4EfXS4R8O_JFvvH
```

ifconfig command Only Work's with all arguments:

msh />ifconfig e0
bad parameter! e.g: ifconfig e0 192.168.1.30 192.168.1.1 255.255.255.0

all arguments:
==============
msh />ifconfig e0 192.168.1.30 192.168.1.1 255.255.255.0
config : e0
IP addr: 192.168.1.30
Gateway: 192.168.1.1
netmask: 255.255.255.0
bad network interface device name(e0).
```
**My project with issue in GitHub:**
https://github.com/neuberfran/rtthread2/blob/main/applications/main.c

**Comment by muaxiaohei** [comment]
In my test， I've used the BSP of 1.0.8 version and connected my ch32v307-r1-1v0 board with a router by a Network cable.
![image](https://user-images.githubusercontent.com/45762837/188265347-bf8d132a-169d-4c72-af0e-ead6a6fca67e.png)
![aed2b49618e5d3cc3f99d73be08876e](https://user-images.githubusercontent.com/45762837/188265670-6235c68f-b32a-42e8-a8dc-c8411a498b2e.jpg)

I've opened the ETH drivers which depends on the lwip assembly.
![image](https://user-images.githubusercontent.com/45762837/188265507-41ea2705-e684-4c65-8f53-d9e1a7f7316f.png)
![image](https://user-images.githubusercontent.com/45762837/188265512-b4c78bbe-7356-4ec4-a938-6dd065eb5e31.png)
Here is my test result.
`msh >ping google.com`
`ping: from 172.217.160.110 icmp_seq=0 timeout`
`ping: from 172.217.160.110 icmp_seq=1 timeout`
`ping: from 172.217.160.110 icmp_seq=2 timeout`
`ping: from 172.217.160.110 icmp_seq=3 timeout`
![image](https://user-images.githubusercontent.com/45762837/188265693-9952cff5-f7d1-4c4d-965e-b2c6089a6d1b.png)

maybe you should check more variables?
haha, excuse my poor English.

**Comment by muaxiaohei** [comment]
I can't ping google.com success because I don't have a VPN.
I should paste the result of "ping baidu.com".

**Comment by muaxiaohei** [comment]
And here is my test of ping a ip of LAN.
![image](https://user-images.githubusercontent.com/45762837/188265866-48d49a2a-a055-4db3-a6ab-794b4fee4bcc.png)

**Comment by neuberfran** [comment]
@muaxiaohei Pls. Tell me ifconfig (Without Arguments) result. 

I'm learning to use this software:
https://www.big-meter.com/opensource/pt/6138a65ada0ebe0a421c38b3.html

![issueS017](https://user-images.githubusercontent.com/38701397/188291660-b5f72dfc-51e8-45d7-bb59-763f88eae504.png)

**Comment by muaxiaohei** [comment]
yep, here is the result.
![image](https://user-images.githubusercontent.com/45762837/188312498-36490928-8822-4da9-a5f3-72bde054f940.png)

**Comment by neuberfran** [comment]
@muaxiaohei  Can u help-me in this issue?
https://stackoverflow.com/questions/73451177/how-to-implement-interrupt-or-task-inside-while-loop-in-cpp-file-without-voi?fbclid=IwAR1VSFMJRzDgd6dvsA8CCv7nKSLE8o5VkeZZO6UulEaDix66BLue4Vv6ocg
Any help is welcome on RT-Thread/Task/Thread/Semaphore/LVGL_Arduino/LVGL_Thread

**Comment by muaxiaohei** [comment]
ooop, sorry, I am not familiar with LVGL, maybe later.



***@***.***
 
From: Neuber Sousa
Date: 2022-09-05 05:20
To: RT-Thread/rt-thread
CC: self-confident neko; Mention
Subject: Re: [RT-Thread/rt-thread] rt-thread/ch32v307 NOT have ethernet connection AND RT-Thread terminal NOT have ifconfig command (Issue #6368)
@muaxiaohei Can u help-me in this issue?
https://stackoverflow.com/questions/73451177/how-to-implement-interrupt-or-task-inside-while-loop-in-cpp-file-without-voi?fbclid=IwAR1VSFMJRzDgd6dvsA8CCv7nKSLE8o5VkeZZO6UulEaDix66BLue4Vv6ocg
Any help is welcome on RT-Thread/Task/Thread/Semaphore/LVGL_Arduino/LVGL_Thread

**Comment by neuberfran** [comment]
@muaxiaohei  Pls. Where I can find this software to download for W11 or W10 Or in last case for Ubuntu 20.04?

![image](https://user-images.githubusercontent.com/38701397/188341371-89f541b6-d1eb-40ee-9424-782c1592384e.png)

**Comment by muaxiaohei** [comment]
here is it.



***@***.***
 
From: Neuber Sousa
Date: 2022-09-05 09:02
To: RT-Thread/rt-thread
CC: self-confident neko; Mention
Subject: Re: [RT-Thread/rt-thread] rt-thread/ch32v307 NOT have ethernet connection AND RT-Thread terminal NOT have ifconfig command (Issue #6368)
@muaxiaohei Pls. Where I can find this software to download for W11 or W10 Or in last case for Ubuntu 20.04?

**Comment by neuberfran** [comment]
@muaxiaohei Why did you post this? I asked politely and seriously

**Comment by muaxiaohei** [comment]
> @muaxiaohei Why did you post this? I asked politely and seriously

I have added this software in my appendix， but it seems that github won't add this it. Here is my google driver sharing.

https://drive.google.com/file/d/14n0U9WYjKWwUXg0afXlzQUBmN44csFPZ/view?usp=sharing

**Comment by neuberfran** [comment]
@muaxiaohei Why my folder examples\arduino\LVGL_Arduino appear in VsCode and Not appear in rt-thread studio ide? It's because SConscript? If yes, how to solve? How to solve

https://github.com/neuberfran/discovery9

![inrt-threadideNotappear](https://user-images.githubusercontent.com/38701397/188345145-3b3a7a84-d0e6-4a14-9521-abee8560ea4a.png)
![invscodeappear](https://user-images.githubusercontent.com/38701397/188345147-f9ea411f-7393-434c-9568-6d2acdc8732b.png)

**Comment by muaxiaohei** [comment]
Maybe you should try to open the examples switch.



***@***.***
 
From: Neuber Sousa
Date: 2022-09-05 09:55
To: RT-Thread/rt-thread
CC: self-confident neko; Mention
Subject: Re: [RT-Thread/rt-thread] rt-thread/ch32v307 NOT have ethernet connection AND RT-Thread terminal NOT have ifconfig command (Issue #6368)
@muaxiaohei Why my folder examples\arduino\LVGL_Arduino appear in VsCode and Not appear in rt-thread studio ide? It's because SConscript? If yes, how to solve? How to solve
https://github.com/neuberfran/discovery9

**Comment by neuberfran** [comment]
@muaxiaohei No. it's SConscript issue:
https://github.com/lvgl/lvgl/commit/704363c5bdd5b29b00bf51807720f86c8f79bb6b#diff-88fd1fd72a3632b24dc12027eb8b6a68bd13903191a70120caf5e57f3b76c03d
Cheers
