### ISSUE TITLE
RTduino/Wire.h in RT-Thread IDE project to CH32V307 causing issue. Why ? How to solve?

### ISSUE THREAD

**Issue by neuberfran** [RT-Thread/rt-thread#6413]
![image](https://user-images.githubusercontent.com/38701397/189516636-5403a439-e991-4832-9861-3056ac64cdbf.png)

Why when I try enable RTduino and Wire.h in RTT ide project, I have issue described in the screen above

How to solve? 
Pls

Note.:
I stay using RTduino/Wire.h in rtt project using device stm32f469 disco kit without issues.

**Comment by mysterywolf** [comment]
RTduino have not support ch32 yet.

https://github.com/RTduino/RTduino

we are trying to pushing on it.
