### ISSUE TITLE
rt_ringbuffer_put_force函数是不是存在问题

### ISSUE THREAD

**Issue by dichi** [RT-Thread/rt-thread#642]
..\..\components\drivers\src\ringbuffer.c` 的109 和110行，直接将   length = rb->buffer_size;是不是会造成ptr【】的溢出风险 
代码函数如下：

rt_size_t rt_ringbuffer_put_force(struct rt_ringbuffer *rb,
                            const rt_uint8_t     *ptr,
                            rt_uint16_t           length)
{
    rt_uint16_t space_length;

    RT_ASSERT(rb != RT_NULL);

    space_length = rt_ringbuffer_space_len(rb);

    if (length > space_length)
        length = rb->buffer_size;

    if (rb->buffer_size - rb->write_index > length)
    {
        /* read_index - write_index = empty space */
        memcpy(&rb->buffer_ptr[rb->write_index], ptr, length);
        /* this should not cause overflow because there is enough space for
         * length of data in current mirror */
        rb->write_index += length;

        if (length > space_length)
            rb->read_index = rb->write_index;

        return length;
    }

    memcpy(&rb->buffer_ptr[rb->write_index],
           &ptr[0],
           rb->buffer_size - rb->write_index);
    memcpy(&rb->buffer_ptr[0],
           &ptr[rb->buffer_size - rb->write_index],
           length - (rb->buffer_size - rb->write_index));

    /* we are going into the other side of the mirror */
    rb->write_mirror = ~rb->write_mirror;
    rb->write_index = length - (rb->buffer_size - rb->write_index);

    if (length > space_length)
    {
        rb->read_mirror = ~rb->read_mirror;
        rb->read_index = rb->write_index;
    }

    return length;
}

**Comment by BernardXiong** [comment]
请多给些说明。

**Comment by dichi** [comment]
memcpy(&rb->buffer_ptr[rb->write_index],
       &ptr[0],
       rb->buffer_size - rb->write_index);
memcpy(&rb->buffer_ptr[0],
       &ptr[rb->buffer_size - rb->write_index],
       length - (rb->buffer_size - rb->write_index));
这段代码理论上是将数组ptr中的内容复制到环形缓冲中去，但是由于
if (length > space_length)
    length = rb->buffer_size; 可能导致length的大小直接等于环形缓冲的大小，从而大于数组ptr元素个数，在执行mencpy的时候导致溢出。
