### ISSUE TITLE
升级STM32底层库函数？

### ISSUE THREAD

**Issue by Linjieqiang** [RT-Thread/rt-thread#643]
感谢你们的付出，我用的是STM405进行项目的编写，我看目前底层库函数是1.0.0，而当前最新的1.7.0，我尝试更换，可惜失败……能否定期更新支持芯片的库函数？

**Comment by BernardXiong** [comment]
更新支持依赖的是大家对RT-Thread的支持，你可以尝试进行更新，如果遇到问题也可以发上来，大家会提供相应的一些建议。更新成功后，也欢迎把更新的版本提交到github上来

**Comment by Linjieqiang** [comment]
好吧 我是初学者 还在学习实时操作系统 我看看 主要是替换后冲突太多 或者报错太多 我得仔细看看如何构成

**Comment by Linjieqiang** [comment]
![image](https://cloud.githubusercontent.com/assets/10217966/16609098/a3143dac-4383-11e6-8efb-d246cc4465ab.png)
![image](https://cloud.githubusercontent.com/assets/10217966/16609112/bf1f3e2a-4383-11e6-9cd4-1afdb83c17ad.png)
我刚试了试，keil能编译成功，就是scons编译不过去。。。。

**Comment by BernardXiong** [comment]
f40x没有fmc吧，还是fsmc。

**Comment by Linjieqiang** [comment]
嗯嗯，是的，f40x没有fmc，然后我对scons不太熟悉，不知道宏定义在哪……后来我重新用keil做了个最小系统，搞好了，谢谢。删掉一些无用的资源文件，然后清爽了，然后打算用它来写飞控，感谢你们团队的系统，学习中，资料很不错~！
![image](https://cloud.githubusercontent.com/assets/10217966/16610448/dbf7d142-438d-11e6-8036-eb4ecfbd4de9.png)
