### ISSUE TITLE
STM32F4  MQTT代码sub功能 一直Fail，有人知道怎么解决吗 

### ISSUE THREAD

**Issue by zhangqiang0801** [RT-Thread/rt-thread#644]
有人用过官网例程的MQTT软件包吗，sub一直fail，pub没问题，查不出什么原因，有人知道的话给点提示，谢谢！

**Comment by BernardXiong** [comment]
@heyuanjie87 Please have a look. Thanks.

**Comment by heyuanjie87** [comment]
当时没板子是在Linux调试的。刚在f4测试，调用setsockopt后导致接收失败。看来是lwip得修理了？

**Comment by heyuanjie87** [comment]
@zhangqiang0801 你把setsockopt改成select试试（我没试过）。

**Comment by aozima** [comment]
mqttclient.c 中的 SO_RCVTIMEO 单位是秒
而LWIP的 
netconn_set_recvtimeout()
netconn_recv_data()
sys_arch_mbox_fetch()
都是毫秒，最后转为tick来执行的超时，
所以等待时间不够，直接关闭连接了。
