### ISSUE TITLE
arm926 __rt_ffs 在gcc编译时有bug

### ISSUE THREAD

**Issue by www220** [RT-Thread/rt-thread#648]
__rt_ffs中使用了x寄存器作为返回值，gcc编译时回选择为r0，输入参数的寄存器也是r0，导致算法失败，将参数valule复制到其他寄存器，可以避免此类问题

**Comment by BernardXiong** [comment]
这个貌似和gcc里的__builtin_ffs功能一样，或许可以处理下。
