### ISSUE TITLE
LWIP IPV6问题

### ISSUE THREAD

**Issue by chwncy** [RT-Thread/rt-thread#6542]
最新的LWIP 2.1.2里面，没有找到“set_if6”这个函数呢，是已经废弃了吗？
![1](https://user-images.githubusercontent.com/31879464/196644988-c464c3a9-0124-412a-9a44-27afd53b1f8c.png)

另外，如果已经不用了，那要怎么才能手动设置ipv6?

**Comment by aozima** [comment]
补回来试试？
v6一般都自动分配吧，dhcpv6都用得少，如果仅是局域网通信，自动生成的本地地址也够用了。
