### ISSUE TITLE
[BSP]CH32V307重载了memset却未实现？

### ISSUE THREAD

**Issue by kaidegit** [RT-Thread/rt-thread#6558]
在编译选项有-Wl,-wrap=memset，在board.c中似乎并没有实现此
https://github.com/RT-Thread/rt-thread/blob/fd6cfa3bbd57ce645eadd58dd1aad7f2b07e59ee/bsp/wch/risc-v/ch32v307v-r1/rtconfig.py#L50

在打开lwip后编译会导致找不到__wrap_memset之类的报错

```
bin/ld: build/kernel/components/net/lwip/lwip-2.0.3/src/api/sockets.o: in function `lwip_accept':
/Users/yekai/DevPkgs/rt-thread/components/net/lwip/lwip-2.0.3/src/api/sockets.c:557: undefined reference to `__wrap_memset'
```

**Comment by BernardXiong** [comment]
或者把这个编译选项拿掉，具体为什么还不清楚

**Comment by mysterywolf** [comment]
感谢反馈 会有PR跟进

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/6561
