### ISSUE TITLE
STM32F4 HAL库版本最新为V1.8.1，请更新

### ISSUE THREAD

**Issue by wdfk-prog** [RT-Thread/rt-thread#6559]
# RTT中STM32F4 hal版本为V1.7.13。最新版为V1.8.1
![image](https://user-images.githubusercontent.com/66928464/197510432-94dc151e-e64e-4fd1-88ce-7602b48dddc2.png)
![image](https://user-images.githubusercontent.com/66928464/197510955-7fed1017-3a61-40d9-8b53-43d6b519c3e7.png)

**Comment by BernardXiong** [comment]
欢迎提交更新的PR

**Comment by wdfk-prog** [comment]
> 欢迎提交更新的PR

emmm,我有一个pr还没结束，能同时传新的吗？

**Comment by mysterywolf** [comment]
我会让郭老师尽快review合并掉。 不过你pr的方式有些问题，建议目前的pr合并之后，删除你fork的仓库并重新fork。你仓库的master分支只负责同步rt-thread仓库，提交PR时基于master分支创建新的分支，一个PR一个分支。PR合并了，分支随即可以删除掉。

**Comment by wdfk-prog** [comment]
> 

OK，OK。
