### ISSUE TITLE
请教自动初始化问题

### ISSUE THREAD

**Issue by nstopb828** [RT-Thread/rt-thread#6582]
请问，使用自动初始化接口，比如INIT_APP_EXPORT配置了多个初始化函数，他们之间的顺序如何控制呢？

**Comment by aozima** [comment]
由链接器决定顺序，可以在链接时指定排序来确定。

相关讨论
- [关于组件自动初始化的顺序控制问题](https://club.rt-thread.org/ask/question/185dfa1471637c4f.html)
- [INIT_APP_EXPORT启动线程的顺序是随机的吗？](https://club.rt-thread.org/ask/question/b9b07bb8b0b9ec07.html)
