### ISSUE TITLE
F407 pwm1和pwm8配置问题

### ISSUE THREAD

**Issue by nstopb828** [RT-Thread/rt-thread#6584]
请教，使用rtt studio自动生成的驱动文件，pwm_config.h中没有pwm1和pwm8的配置定义。查了下芯片手册，这两个是高级定时器，寄存器定义和普通的不同，是因为这个原因吗？那是需要自己手动写bsp还是定义在了其他地方？

**Comment by mysterywolf** [comment]
只需要在pwm_config.h中补充上去即可。
