### ISSUE TITLE
cmd.c中list_thread等函数printf格式“%-*.s”是否有问题

### ISSUE THREAD

**Issue by wdfk-prog** [RT-Thread/rt-thread#6587]
### list_thread()函数中的printf有 .precision（精度）
```c
rt_kprintf("%-*.s pri  status      sp     stack size max used left tick  error\n", maxlen, item_title);
```
### C关于 .precision（精度）描述
- 对于 s: 要输出的最大字符数。默认情况下，所有字符都会被输出，直到遇到末尾的空字符。
![image](https://user-images.githubusercontent.com/66928464/199697986-0df57b59-02fa-4db6-91b6-0de679bfa6c6.png)
### 没有说明“.s”的情况，这种情况下，不同printf的处理结果不一样
- 用kservice.c的rt_vsnprintf可以输出thread"
![image](https://user-images.githubusercontent.com/66928464/199695088-bf70e849-7491-487a-afa5-4a1c9359c573.png)
- 用rt_vsnprintf_full软件包中的rt_vsnprintf输出不了“thread”
>https://github.com/mysterywolf/rt_vsnprintf_full
![image](https://user-images.githubusercontent.com/66928464/199695027-b44e8e03-4de2-46e5-9635-d894be8da6d5.png)
- 使用printf输出结果
![image](https://user-images.githubusercontent.com/66928464/199695180-dd4dabbf-fcaf-4391-896b-33af7601ade8.png)
### kservice.c中相关代码如下
```c
       while (1)
        {
            /* skips the first '%' also */
            ++ fmt;
            if (*fmt == '-') flags |= LEFT;
            else if (*fmt == '+') flags |= PLUS;
            else if (*fmt == ' .') flags |= SPACE;
            else if (*fmt == '#') flags |= SPECIAL;
            else if (*fmt == '0') flags |= ZEROPAD;
            else break;
        }

        /* get field width */
        field_width = -1;
        if (_ISDIGIT(*fmt)) field_width = skip_atoi(&fmt);
        else if (*fmt == '*')
        {
            ++ fmt;
            /* it's the next argument */
            field_width = va_arg(args, int);
            if (field_width < 0)
            {
                field_width = -field_width;
                flags |= LEFT;
            }
        }
```
### rt_vsnprintf_full中相关代码如下
```c
    // evaluate flags
    flags = 0U;
    do {
      switch (*format) {
        case '0': flags |= FLAGS_ZEROPAD; format++; n = 1U; break;
        case '-': flags |= FLAGS_LEFT;    format++; n = 1U; break;
        case '+': flags |= FLAGS_PLUS;    format++; n = 1U; break;
        case ' ': flags |= FLAGS_SPACE;   format++; n = 1U; break;
        case '#': flags |= FLAGS_HASH;    format++; n = 1U; break;
        default :                                   n = 0U; break;
      }
    } while (n);

    // evaluate width field
    width = 0U;
    if (is_digit_(*format)) {
      width = atoi_(&format);
    }
    else if (*format == '*') {
      const int w = va_arg(va, int);
      if (w < 0) {
        flags |= FLAGS_LEFT;    // reverse padding
        width = (unsigned int)-w;
      }
      else {
        width = (unsigned int)w;
      }
      format++;
    }

    // evaluate precision field
    precision = 0U;
    if (*format == '.') {
      flags |= FLAGS_PRECISION;
      format++;
      if (is_digit_(*format)) {
        precision = atoi_(&format);
      }
      else if (*format == '*') {
        const int precision_ = (int)va_arg(va, int);
        precision = precision_ > 0 ? (unsigned int)precision_ : 0U;
        format++;
      }
    }
```
### 是否应该规范格式使用“%-*.*s”
如下
```c
 rt_kprintf("%-*.*s pri  status      sp     stack size max used left tick  error\n", maxlen, maxlen,item_title);
```
- 用kservice.c的rt_vsnprintf可以输出thread"
![image](https://user-images.githubusercontent.com/66928464/199701456-842d2b2f-9179-4085-9cdd-c134c8790474.png)

- 用rt_vsnprintf_full软件包中的rt_vsnprintf输出结果
![image](https://user-images.githubusercontent.com/66928464/199701283-b895a383-888b-4b15-86b2-958a2ff3e8ca.png)

- printf输出结果
![image](https://user-images.githubusercontent.com/66928464/199701759-d3377511-3d0a-4369-9328-5d0ba78a8457.png)

**Comment by mysterywolf** [comment]
你好 麻烦随便往我邮箱里发点什么

**Comment by mysterywolf** [comment]
这个部分有时间可否把整个仓库扫描检查一下 有问题的提个PR改一下 按照标准的格式走~

**Comment by mysterywolf** [comment]
不用管原生rt_kprintf，只要开了rt_vsnprintf_full这个软件包能正确显示就可以
