### ISSUE TITLE
USB keybord problem with Nuvoton N9H30F61IEC

### ISSUE THREAD

**Issue by updesh31** [RT-Thread/rt-thread#6621]
I am working with RT-Thread Version: 2.2.1 and N9H30F61IEC. USB MSCHOST is working perfectly but in HID host mode getting given messages: 
EHCI port2 status change: 0x1403
EHCI port 2 - port reset failed!
OHCI port2 status change: 0x10301
OHCI connect device.
get full device descriptor failed
OHCI port2 status change: 0x10300
OHCI disconnect device.
Keyboard is ok and working with freertos.

**Comment by BernardXiong** [comment]
Maybe you need to consult the engineers of Nuvoton. The Nuvoton BSPs in RT Thread are maintained by the manufacturer.

**Comment by updesh31** [comment]
thanks
