### ISSUE TITLE
是否有安全编码规范-静态检测-代码覆盖率的公开资料

### ISSUE THREAD

**Issue by openluopworld** [RT-Thread/rt-thread#6622]
想问下是否有 RT-Thread 安全编码规范、静态检测、代码覆盖率等的公开资料和结果可以分享？谢谢

**Comment by BernardXiong** [comment]
这些安全相关的都很严格，如misra-c编码规范，这类可以找些商业工具来扫描测试下。开源的还是更多是社区层面的

**Comment by supperthomas** [comment]
如果有小伙伴对这方面感兴趣的，也可以尝试开源实现一下。开源的嘛，大家都贡献一点点，就会有结果。（RTTHREAD很多公开资料和结果都是社区小伙伴贡献的）

**Comment by mysterywolf** [comment]
非BUG问题请到论坛提问
