### ISSUE TITLE
ADC设备驱动 不支持DMA?

### ISSUE THREAD

**Issue by wdfk-prog** [RT-Thread/rt-thread#6628]
# ADC设备驱动 不支持DMA?
我看论坛好早都在反馈了，怎么还没有支持。
是不需要吗？

**Comment by ztlchina** [comment]
ADC 没用驱动。 用的HAL的代码。 比较好使。&nbsp;&nbsp;


mengzhilu_ztl
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月19日(星期六) 下午5:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [RT-Thread/rt-thread] ADC设备驱动 不支持DMA? (Issue #6628)





 
ADC设备驱动 不支持DMA?
 
我看论坛好早都在反馈了，怎么还没有支持。
 是不需要吗？

**Comment by wdfk-prog** [comment]
> ADC 没用驱动。 用的HAL的代码。 比较好使。&nbsp;&nbsp; mengzhilu_ztl ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年11月19日(星期六) 下午5:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [RT-Thread/rt-thread] ADC设备驱动 不支持DMA? (Issue #6628) ADC设备驱动 不支持DMA? 我看论坛好早都在反馈了，怎么还没有支持。 是不需要吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

啥意思?
不是不同bsp自己去实现的吗？
怎么就没用驱动了。

**Comment by wdfk-prog** [comment]
> ADC 没用驱动。 用的HAL的代码。 比较好使。&nbsp;&nbsp; mengzhilu_ztl ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年11月19日(星期六) 下午5:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [RT-Thread/rt-thread] ADC设备驱动 不支持DMA? (Issue #6628) ADC设备驱动 不支持DMA? 我看论坛好早都在反馈了，怎么还没有支持。 是不需要吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

- 如果说stm32的话，单独用hal库驱动adc+dma是可以。
- 不过为什么不整合到设备驱动呢

**Comment by mysterywolf** [comment]
是的 现在stm32 的ADC驱动以及ADC驱动框架本身都非常的简单到不行... 就是给一个命令读一下 根本没有fifo之类的东西。

**Comment by i-jaffer** [comment]
@mysterywolf 麻烦分享下加群方式 我这也有一套dma+adc驱动方案 很乐意探讨

**Comment by i-jaffer** [comment]
> 是的 现在stm32 的ADC驱动以及ADC驱动框架本身都非常的简单到不行... 就是给一个命令读一下 根本没有fifo之类的东西。楼主可否以stm32为基础实现一个完整版本的adc框架，最好先和群里讨论 然后再实现~

@mysterywolf 麻烦分享下加群方式 我这也有一套dma+adc驱动方案 很乐意探讨

**Comment by wdfk-prog** [comment]
- https://github.com/RT-Thread/rt-thread/pull/11440
