### ISSUE TITLE
RT-Thread所有工程的编译warnings等级应加上CFLAGS = -Wall，CI应加上-werror

### ISSUE THREAD

**Issue by childerxxx** [RT-Thread/rt-thread#6665]

**Comment by dongly** [comment]
最好是 -Wall -Wextra 都加上.不过开头会很痛苦
![image](https://user-images.githubusercontent.com/3203502/204414890-01f60333-365f-45c3-ad32-35b49af1da2f.png)

**Comment by mysterywolf** [comment]
这个我们在CI上加了 加了werror wall 没加wextra 后续也要加上wextra，

**Comment by dongly** [comment]
论坛上的大佬说的

**Comment by mysterywolf** [comment]
bsp是适合直接加这些标志，因为rt-thread有很多软件包，有些软件包如果稍微有点问题的话 就直接当错误assert掉是不合适的。主仓库有ci看守就可以了。
