### ISSUE TITLE
NUC980 编译错误，BSP下未修改直接按步骤操作

### ISSUE THREAD

**Issue by kylongmu** [RT-Thread/rt-thread#6680]
> menuconfig --generate

THINKPAD@NOTEBOOK-P52 D:\Develop\Git_Project\rt-thread\bsp\nuvoton\nk-980iot
> pkgs --update
[Use Gitee server]
==============================>  wavplayer update done

==============================>  uffs update done

==============================>  ramdisk update done

==============================>  optparse update done

Operation completed successfully.

THINKPAD@NOTEBOOK-P52 D:\Develop\Git_Project\rt-thread\bsp\nuvoton\nk-980iot
> scons
scons: Reading SConscript files ...
Newlib version: 4.1.0
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build
CC build\applications\main.o
CC build\applications\mnt.o
CC build\board\board_dev.o
CC build\board\nu_pin_init.o
CC build\kernel\components\dfs\filesystems\devfs\devfs.o
CC build\kernel\components\dfs\filesystems\elmfat\dfs_elm.o
CC build\kernel\components\dfs\filesystems\elmfat\ff.o
CC build\kernel\components\dfs\filesystems\elmfat\ffunicode.o
CC build\kernel\components\dfs\src\dfs.o
CC build\kernel\components\dfs\src\dfs_file.o
CC build\kernel\components\dfs\src\dfs_fs.o
CC build\kernel\components\dfs\src\dfs_posix.o
CC build\kernel\components\drivers\audio\audio.o
CC build\kernel\components\drivers\audio\audio_pipe.o
CC build\kernel\components\drivers\can\can.o
CC build\kernel\components\drivers\cputime\cputime.o
CC build\kernel\components\drivers\hwcrypto\hwcrypto.o
CC build\kernel\components\drivers\hwcrypto\hw_hash.o
CC build\kernel\components\drivers\hwcrypto\hw_rng.o
CC build\kernel\components\drivers\hwcrypto\hw_symmetric.o
CC build\kernel\components\drivers\hwtimer\hwtimer.o
CC build\kernel\components\drivers\i2c\i2c-bit-ops.o
CC build\kernel\components\drivers\i2c\i2c_core.o
CC build\kernel\components\drivers\i2c\i2c_dev.o
CC build\kernel\components\drivers\ipc\completion.o
CC build\kernel\components\drivers\ipc\dataqueue.o
CC build\kernel\components\drivers\ipc\pipe.o
CC build\kernel\components\drivers\ipc\ringblk_buf.o
CC build\kernel\components\drivers\ipc\ringbuffer.o
CC build\kernel\components\drivers\ipc\waitqueue.o
CC build\kernel\components\drivers\ipc\workqueue.o
CC build\kernel\components\drivers\misc\adc.o
CC build\kernel\components\drivers\misc\pin.o
CC build\kernel\components\drivers\misc\rt_drv_pwm.o
CC build\kernel\components\drivers\mtd\mtd_nand.o
CC build\kernel\components\drivers\rtc\alarm.o
CC build\kernel\components\drivers\rtc\rtc.o
CC build\kernel\components\drivers\serial\serial.o
CC build\kernel\components\drivers\spi\qspi_core.o
CC build\kernel\components\drivers\spi\spi_core.o
CC build\kernel\components\drivers\spi\spi_dev.o
CC build\kernel\components\drivers\usb\usbdevice\class\cdc_vcom.o
CC build\kernel\components\drivers\usb\usbdevice\class\mstorage.o
CC build\kernel\components\drivers\usb\usbdevice\core\usbdevice.o
CC build\kernel\components\drivers\usb\usbdevice\core\usbdevice_core.o
CC build\kernel\components\drivers\usb\usbhost\class\mass.o
CC build\kernel\components\drivers\usb\usbhost\class\udisk.o
CC build\kernel\components\drivers\usb\usbhost\core\driver.o
CC build\kernel\components\drivers\usb\usbhost\core\hub.o
CC build\kernel\components\drivers\usb\usbhost\core\usbhost.o
CC build\kernel\components\drivers\usb\usbhost\core\usbhost_core.o
CC build\kernel\components\drivers\watchdog\watchdog.o
CC build\kernel\components\finsh\cmd.o
CC build\kernel\components\finsh\msh.o
CC build\kernel\components\finsh\msh_file.o
CC build\kernel\components\finsh\msh_parse.o
CC build\kernel\components\finsh\shell.o
CC build\kernel\components\libc\compilers\common\cstdlib.o
CC build\kernel\components\libc\compilers\common\cstring.o
CC build\kernel\components\libc\compilers\common\ctime.o
CC build\kernel\components\libc\compilers\newlib\syscalls.o
CC build\kernel\components\libc\posix\io\poll\poll.o
CC build\kernel\components\libc\posix\io\poll\select.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\api\api_lib.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\api\api_msg.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\api\err.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\api\if_api.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\api\netbuf.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\api\netdb.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\api\netifapi.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\api\sockets.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\api\tcpip.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\apps\ping\ping.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\altcp.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\altcp_alloc.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\altcp_tcp.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\def.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\dns.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\inet_chksum.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\init.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\ip.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\ipv4\autoip.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\ipv4\dhcp.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\ipv4\etharp.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\ipv4\icmp.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\ipv4\igmp.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\ipv4\ip4.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\ipv4\ip4_addr.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\ipv4\ip4_frag.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\memp.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\netif.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\pbuf.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\raw.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\stats.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\sys.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\tcp.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\tcp_in.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\tcp_out.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\timeouts.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\core\udp.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\netif\ethernet.o
CC build\kernel\components\net\lwip\lwip-2.1.2\src\netif\lowpan6.o
CC build\kernel\components\net\lwip\port\ethernetif.o
CC build\kernel\components\net\lwip\port\sys_arch.o
CC build\kernel\components\net\netdev\src\netdev.o
CC build\kernel\components\net\netdev\src\netdev_ipaddr.o
CC build\kernel\components\net\sal\dfs_net\dfs_net.o
CC build\kernel\components\net\sal\impl\af_inet_lwip.o
CC build\kernel\components\net\sal\socket\net_netdb.o
CC build\kernel\components\net\sal\socket\net_sockets.o
CC build\kernel\components\net\sal\src\sal_socket.o
CC build\kernel\components\utilities\utest\utest.o
CC build\kernel\libcpu\arm\arm926\cpuport.o
D:\Develop\Git_Project\rt-thread\libcpu\arm\arm926\cpuport.c:96:1: error: expected identifier or '(' before '{' token
   96 | {
      | ^
D:\Develop\Git_Project\rt-thread\libcpu\arm\arm926\cpuport.c:105:1: error: expected identifier or '(' before '{' token
  105 | {
      | ^
In file included from D:\Develop\Git_Project\rt-thread\libcpu\arm\arm926\cpuport.c:12:
D:\Develop\Git_Project\rt-thread\include/rthw.h:76:38: error: expected identifier or '(' before numeric constant
   76 | #define rt_hw_cpu_icache_status(...) 0
      |                                      ^
D:\Develop\Git_Project\rt-thread\libcpu\arm\arm926\cpuport.c:113:11: note: in expansion of macro 'rt_hw_cpu_icache_status'
  113 | rt_base_t rt_hw_cpu_icache_status()
      |           ^~~~~~~~~~~~~~~~~~~~~~~
D:\Develop\Git_Project\rt-thread\libcpu\arm\arm926\cpuport.c:123:1: error: expected identifier or '(' before '{' token
  123 | {
      | ^
D:\Develop\Git_Project\rt-thread\libcpu\arm\arm926\cpuport.c:132:1: error: expected identifier or '(' before '{' token
  132 | {
      | ^
In file included from D:\Develop\Git_Project\rt-thread\libcpu\arm\arm926\cpuport.c:12:
D:\Develop\Git_Project\rt-thread\include/rthw.h:77:38: error: expected identifier or '(' before numeric constant
   77 | #define rt_hw_cpu_dcache_status(...) 0
      |                                      ^
D:\Develop\Git_Project\rt-thread\libcpu\arm\arm926\cpuport.c:140:11: note: in expansion of macro 'rt_hw_cpu_dcache_status'
  140 | rt_base_t rt_hw_cpu_dcache_status()
      |           ^~~~~~~~~~~~~~~~~~~~~~~
scons: *** [build\kernel\libcpu\arm\arm926\cpuport.o] Error 1
scons: building terminated because of errors.

**Comment by kylongmu** [comment]
能加一个nuvoton bsp的action吗？

**Comment by wosayttn** [comment]
Fixed in #6793. FYI. Thanks.
