### ISSUE TITLE
同步rt-smart后的提交，simulator编译报错

### ISSUE THREAD

**Issue by BreederBai** [RT-Thread/rt-thread#6696]
![image](https://user-images.githubusercontent.com/27894314/205829495-f484fbd5-c8ed-477d-a417-a1aa90e6299b.png)

**Comment by BernardXiong** [comment]
在调整中，还有提交PR修复，或者等我们后续进行修复，建议多探索前者 :smile:

**Comment by BreederBai** [comment]
截图中的报错似乎把...删除就行，但之后还有一个报错，好像和头文件重复有关，不知道怎么改，，，
