### ISSUE TITLE
目前RT-Thread对lm3s9b92的支持怎么样？

### ISSUE THREAD

**Issue by wutianba** [RT-Thread/rt-thread#670]
我在制作一个lm3s9b92的模拟器。希望使用RT-Thread作为标准进行测试。目前RT-Thread对lm3s9b92的支持怎么样？有没有什么需要注意的地方。

**Comment by BernardXiong** [comment]
bsp在这里：
https://github.com/RT-Thread/rt-thread/tree/master/bsp/lm3s9b9x

具体情况请仔细测试。
