### ISSUE TITLE
ulog flush函数理解疑问

### ISSUE THREAD

**Issue by i-jaffer** [RT-Thread/rt-thread#6720]
关于ulog中的 `ulog_flush()` 函数，如果在开启异步输出的情况下，ulog_async_output()函数已将缓冲区内的数据读取出来并output到后端模块或控制台了，后面再调用`backend->flush(backend);` 感觉是不是有点重复？
```c
/**
 * flush all backends's log
 */
void ulog_flush(void)
{
    rt_slist_t *node;
    ulog_backend_t backend;

    if (!ulog.init_ok)
        return;

#ifdef ULOG_USING_ASYNC_OUTPUT
    ulog_async_output();
#endif

    /* flush all backends */
    for (node = rt_slist_first(&ulog.backend_list); node; node = rt_slist_next(node))
    {
        backend = rt_slist_entry(node, struct ulog_backend, list);
        if (backend->flush)
        {
            backend->flush(backend);
        }
    }
}

```

![image](https://user-images.githubusercontent.com/73985820/206717694-d62e6968-153f-43b8-9270-f6716c2a4954.png)

**Comment by a1012112796** [comment]
> backend->flush(backend); 

有些后端设备需要flush 来保证数据写入(可能也是异步或者带缓存的, 例如文件系统)

**Comment by wdfk-prog** [comment]
> Contributor

也就是说ulog_async_output();只是将ULOG的缓冲区输出了.

而后端设备有些还自带了缓冲区,这些缓冲就需要用backend->flush(backend);输出到后端是吗?
