### ISSUE TITLE
Manual in english

### ISSUE THREAD

**Issue by eskomj** [RT-Thread/rt-thread#673]
Hello,

There is manual in english in github, but could somebody make english version available? It could help understanding of rt-thread a lot.

Esko Jaakkola
Finland

**Comment by BernardXiong** [comment]
Normally, you can use Google to translate RT-Thread programming guide. Moreover, the API manual of RT-Thread is in English.

**Comment by wzyy2** [comment]
I think RT-Thread should have a wiki for manual or guide.
It will help a lot.

**Comment by BernardXiong** [comment]
Yes, and the wiki can be placed on github.

**Comment by eskomj** [comment]
I found typo in my original message. Of course I meant that there is chinese version available. It really could help, if someone who manage chinese and english could do translation. Wiki would be best solution.

**Comment by mysterywolf** [comment]
https://www.rt-thread.io/document/site/
