### ISSUE TITLE
touch框架多了个touch.h

### ISSUE THREAD

**Issue by ccx-lan** [RT-Thread/rt-thread#6760]
在touch文件夹多了个touch.h,历史遗留问题？

**Comment by mysterywolf** [comment]
是的 是历史问题 应该放在rtdevice.h中

**Comment by ccx-lan** [comment]
嗯，touch文件夹的脚本的头文件路径也要改一下

**Comment by yangjie11** [comment]
确实存在两个touch.h
一个位于：\components\drivers\include\drivers\touch.h
另一个：components\drivers\touch\touch.h  【删掉】
