### ISSUE TITLE
master分支工程stm32分支修改了对keil的版本要求，提示不兼容

### ISSUE THREAD

**Issue by i-jaffer** [RT-Thread/rt-thread#6782]
目录位置：rt-thread\bsp\stm32\stm32f103-fire-arbitrary

master分支， 在ENV里面采用scons生成keil5工程，提示版本不兼容，如下图所示（当前电脑keil5版本为5.25）

![image](https://user-images.githubusercontent.com/73985820/209563025-e08fcdd9-cc33-4cc0-8fff-f864250049d3.png)

而在此问题在 lts-v3.1.x 分支内生成工程正常

**Comment by mysterywolf** [comment]
这个是正常的 就是打印了个你目前的Keil版本，工程已经正确生成了
