### ISSUE TITLE
fal read flash is decrypt？ fal read命令读取数据是明文吗？

### ISSUE THREAD

**Issue by chenjianquan7** [RT-Thread/rt-thread#6786]
i use fal read flash about i.mx rt2021 exitern flash, it has usb HAB and XIB encrypted ，so do the  fal read data is decrypted ?

我用fal read命令读取 i.mx rt2021的片外flash，这个是经过加密的，我的疑问是他读出来的数据是解密的吗？谢谢

**Comment by i-jaffer** [comment]
fal read底层起始就是掉对应的flash驱动里面的read，这与flash驱动内的read实现有关，此类疑问可在论坛上发帖
