### ISSUE TITLE
编译报错[simulator]：dfs_fd中没有path成员

### ISSUE THREAD

**Issue by BreederBai** [RT-Thread/rt-thread#6794]
![image](https://user-images.githubusercontent.com/27894314/209905836-44d46ee7-b3d8-42d0-a2a5-200579af19dd.png)

**Comment by mysterywolf** [comment]
@Guozhanxin 郭老师 smart并进来之后 simulator就寄了

**Comment by BreederBai** [comment]
@mysterywolf  刚我试着修复了下，看着应该是能用了，我提个pr。

**Comment by mysterywolf** [comment]
感谢提交PR!
