### ISSUE TITLE
[CH32V307 Arduino]编译出错

### ISSUE THREAD

**Issue by kylongmu** [RT-Thread/rt-thread#6810]
拉取最新rt-thread，在bsp下按readme_zh.md操作，仅打开CONFIG_PKG_USING_RTDUINO=y开关，之后执行以下操作，编译出错！
[config.zip](https://github.com/RT-Thread/rt-thread/files/10336980/config.zip)
> pkgs --update
[Use Gitee server]
Cloning into 'D:\Develop\Git_Project\rt-thread\bsp\wch\risc-v\ch32v307v-r1\packages\RTduino-latest'...
remote: Enumerating objects: 2235, done.
Receiving objects:  97% (2168/2235), 7.26 MiB | 1.04 MiB/sed 0 (delta 0), pack-reused 2235
Receiving objects: 100% (2235/2235), 7.79 MiB | 711.00 KiB/s, done.
Resolving deltas: 100% (1320/1320), done.
==============================>  RTDUINO latest is downloaded successfully.

==============================>  RTduino update done

Operation completed successfully.

THINKPAD@NOTEBOOK-P52 D:\Develop\Git_Project\rt-thread\bsp\wch\risc-v\ch32v307v-r1
> scons --exec-path=D:\Develop\sdk-toolchain-RISC-V-GCC-WCH-1.0.0\bin
scons: Reading SConscript files ...
Newlib version: 3.0.0
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build
CXX build\applications\arduino_main.o
In file included from applications\arduino_main.cpp:11:
packages\RTduino-latest\core/Arduino.h:117:2: warning: #warning "Please define interrupts for this architecture in Arduino.h" [-Wcpp]
 #warning "Please define interrupts for this architecture in Arduino.h"
  ^~~~~~~
CC build\applications\arduino_pinout\pins_arduino.o
In file included from applications\arduino_pinout\pins_arduino.c:11:
packages\RTduino-latest\core/Arduino.h:117:2: warning: #warning "Please define interrupts for this architecture in Arduino.h" [-Wcpp]
 #warning "Please define interrupts for this architecture in Arduino.h"
  ^~~~~~~

In file included from D:\Develop\Git_Project\rt-thread\bsp\wch\risc-v\Libraries\ch32v30x_libraries\ch32v307_hal\include/ch32v30x.h:182,
                 from board/board.h:16,
                 from packages\RTduino-latest\core/Arduino.h:42,
                 from applications\arduino_pinout\pins_arduino.c:11:
D:\Develop\Git_Project\rt-thread\bsp\wch\risc-v\Libraries\ch32v30x_libraries\bmsis\include/core_riscv.h: In function '__WFI':
D:\Develop\Git_Project\rt-thread\bsp\wch\risc-v\Libraries\ch32v30x_libraries\bmsis\include/core_riscv.h:279:3: error: 'asm' undeclared (first use in this function)
   asm volatile ("wfi");
   ^~~
D:\Develop\Git_Project\rt-thread\bsp\wch\risc-v\Libraries\ch32v30x_libraries\bmsis\include/core_riscv.h:279:3: note: each undeclared identifier is reported only once for each function it appears in
D:\Develop\Git_Project\rt-thread\bsp\wch\risc-v\Libraries\ch32v30x_libraries\bmsis\include/core_riscv.h:279:6: error: expected ';' before 'volatile'
   asm volatile ("wfi");
      ^~~~~~~~~
      ;
In file included from D:\Develop\Git_Project\rt-thread\bsp\wch\risc-v\Libraries\ch32v30x_libraries\ch32v307_hal\include/ch32v30x.h:182,
                 from board/board.h:16,
                 from packages\RTduino-latest\core/Arduino.h:42,
                 from applications\arduino_pinout\pins_arduino.c:11:
D:\Develop\Git_Project\rt-thread\bsp\wch\risc-v\Libraries\ch32v30x_libraries\bmsis\include/core_riscv.h: In function '__WFE':
D:\Develop\Git_Project\rt-thread\bsp\wch\risc-v\Libraries\ch32v30x_libraries\bmsis\include/core_riscv.h:296:3: error: 'asm' undeclared (first use in this function)
   asm volatile ("wfi");
   ^~~
D:\Develop\Git_Project\rt-thread\bsp\wch\risc-v\Libraries\ch32v30x_libraries\bmsis\include/core_riscv.h:296:6: error: expected ';' before 'volatile'
   asm volatile ("wfi");
      ^~~~~~~~~
      ;
D:\Develop\Git_Project\rt-thread\bsp\wch\risc-v\Libraries\ch32v30x_libraries\bmsis\include/core_riscv.h:297:6: error: expected ';' before 'volatile'
   asm volatile ("wfi");
      ^~~~~~~~~
      ;
scons: *** [build\applications\arduino_pinout\pins_arduino.o] Error 1
scons: building terminated because of errors.

**Comment by mysterywolf** [comment]
感谢反馈 问题已经修复 明天这个时候估计就可以用了 ，国内镜像源需要一天时间同步https://github.com/RTduino/RTduino/commit/3e0dcc3a7f62e6d6c945f71b738245ac0ddcc29d
