### ISSUE TITLE
新唐nk-rtu980用iperf测试以太网，nk-rtu980作为服务端速率只能测到几百K

### ISSUE THREAD

**Issue by lfkabc** [RT-Thread/rt-thread#6815]
详细截图与log见https://club.rt-thread.org/ask/question/be3978bc89c31b70.html。

**Comment by BernardXiong** [comment]
这个得找新唐官方支持才行，这个bsp是由新唐工程师维护的。

**Comment by wosayttn** [comment]
Hi,

The EMAC driver implemented zero-copy and NAPI-like method to improve the RX throughput.
Maybe you have a testing using lwiperf on RTU980.

See the description to bring up lwiperf utility. Thanks.
https://github.com/RT-Thread/rt-thread/blob/master/bsp/nuvoton/libraries/nuc980/rtt_port/drv_emac.c#L667

**Comment by tomyqg** [comment]
[
![iperf](https://user-images.githubusercontent.com/9368645/211228642-df931f78-c2bf-419e-8adc-8b324d6fb004.png)
](url)

**Comment by wosayttn** [comment]
Thanks Tomyqg.

Try to adjust optimization level to O2 by disabling DEBUG in rtconfig.py.
See here, https://github.com/RT-Thread/rt-thread/blob/master/bsp/nuvoton/nk-rtu980/rtconfig.py#L27 

Also see my testing after disabling debug mode.
![image](https://user-images.githubusercontent.com/15135795/211231886-53c9d09c-c05a-4280-ae6b-a49065ae0149.png)

**Comment by tomyqg** [comment]
用lwiperf可以测到一样的带宽，但是rtt自带的iperf(基于socket api)测速如何提高？

**Comment by tomyqg** [comment]
[drv_emac.txt](https://github.com/RT-Thread/rt-thread/files/10378370/drv_emac.txt)
这些优化效果甚微，最新这个emac驱动用socket [api测速还是很慢，但是之前这个驱动 开O2优化，rtt iperf 测速还可以[](url)](![iperf](https://user-images.githubusercontent.com/9368645/211446547-abcb9ada-7d71-4f5e-9e5d-c7ecc6b0745a.png))

**Comment by tomyqg** [comment]
最新的emac驱动，通过调整lwip配置，主要是下面几项，iper测速带宽有所提升,但是和老版驱动还是有较大差距
 #define RT_LWIP_TCP_SEG_NUM 256
#define RT_LWIP_TCP_SND_BUF 32768
#define RT_LWIP_TCP_WND 10240

![iperf](https://user-images.githubusercontent.com/9368645/211477127-7983366f-c8fc-4326-a387-247a816f75bc.png)

**Comment by wosayttn** [comment]
Hi, @tomyqg 

Latest version applied zero-copy RX in EMAC driver. It is better that previous memcpy version for saving bandwidth.
We also updated new default setting for the iperf issue. The score is up to 60Mbps in my testing.

**Comment by lfkabc** [comment]
最新代码OK。
