### ISSUE TITLE
不便利：logtrace必须要注册session

### ISSUE THREAD

**Issue by BernardXiong** [RT-Thread/rt-thread#683]
不能达到随手就使用的目的。必须要注册一个session，否则会出现诡异的
[0000...][]
的空中括号。

**Comment by armink** [comment]
老大要不是试试 EasyLogger：https://github.com/armink/EasyLogger ，一次初始化，“终身”使用。支持按照模块、级别、关键词过滤日志，也可以像 Logtrace 一样，把日志放在 idel 线程里异步非阻塞输出。

**Comment by HubertXie** [comment]
EasyLogger不错，用起来比较爽
我在想，能否将console定向到网络端
方便远程调试

**Comment by armink** [comment]
@HubertXie 可以试试 RT-Thread 的 WebTerminal 包：https://github.com/armink-rtt-pkgs/WebTerminal
