### ISSUE TITLE
air32f103工程使用scons --dist生成的独立功能无法使用MDK编译

### ISSUE THREAD

**Issue by 30toB** [RT-Thread/rt-thread#6879]
air32f103工程使用scons --dist生成的独立功能无法使用MDK编译

**Comment by mysterywolf** [comment]
1. 这个bsp是否支持keil5
2. 是否menuconfig 并使用scons --target=mdk5生成了keil5工程？

**Comment by zhkag** [comment]
> air32f103工程使用scons --dist生成的独立功能无法使用MDK编译

由于打包出来的文件是直接使用当前工程的配置，所以会导致一些相对路径无法找到

scons --dist 打包后的工程，您可以重新使用 scons --target=mdk5 生成 keil5 工程，即可正常编译

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/7073
