### ISSUE TITLE
stm32f7-disco工程打开后为空

### ISSUE THREAD

**Issue by yunjie167** [RT-Thread/rt-thread#688]
请问下为什么这个工程打开后没有包含任何文件呢?

**Comment by armink** [comment]
要用 SCons 工具来生成的。

**Comment by BernardXiong** [comment]
请用scons生成相关的工程文件。

**Comment by yunjie167** [comment]
费了好大劲把编译出来,却发现main.c是空的,为啥不写个简单的小demo呢,咳咳,可能我比较懒,实际可能我也是刚接触rt-thread,还有m7的开发板我也是第一次接触,所以....

**Comment by BernardXiong** [comment]
你可以写个 printf("hello world!\n"); 的，然后，欢迎提交、贡献你的代码

**Comment by yunjie167** [comment]
乐意效劳,我也不知道是自己理解错了还是你们的开发板和我的不一样,里面还是有许多东西要修改,等有空把工程跑起来再来分享下.
