### ISSUE TITLE
关于components\utilities\libadt\SConscript文件能否更改一下?

### ISSUE THREAD

**Issue by wdfk-prog** [RT-Thread/rt-thread#6890]
#关于components\utilities\libadt\SConscript文件能否更改一下?
单独一个目录放一个文件,看着难受
![image](https://user-images.githubusercontent.com/66928464/215764211-002f0c5f-0001-4369-a071-4b3c1c443ce1.png)
- 能否跟Utilities目录放在一起?
- 或者能否增加使用选项?我在STM32H750上查看并没有使用这个avl.c

**Comment by BernardXiong** [comment]
确实，这部分处理得有些不太对，后续调整下

**Comment by mysterywolf** [comment]
俺也一样

**Comment by BernardXiong** [comment]
正在改，还会和MM_MMU那边有关联，几个BSP得折腾下。

**Comment by BernardXiong** [comment]
Fixed with #6901
