### ISSUE TITLE
请求添加 STM32F429-Nucleo 的 BSP 支持~

### ISSUE THREAD

**Issue by Eplankton** [RT-Thread/rt-thread#6902]
新手入门，跟着文档里面怎么配也配不好。。。

**Comment by Eplankton** [comment]
> https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/docs/STM32%E7%B3%BB%E5%88%97BSP%E5%88%B6%E4%BD%9C%E6%95%99%E7%A8%8B.md 按照这个一步一步来。遇到哪里过不去了，可以提问。

全部按照这个来的，烧录也成功了，但是led没有亮。。

**Comment by supperthomas** [comment]
> > https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/docs/STM32%E7%B3%BB%E5%88%97BSP%E5%88%B6%E4%BD%9C%E6%95%99%E7%A8%8B.md 按照这个一步一步来。遇到哪里过不去了，可以提问。
> 
> 全部按照这个来的，烧录也成功了，但是led没有亮。。

debug  keil看一下，停在哪里了

**Comment by Eplankton** [comment]
> 

rt-thread init
