### ISSUE TITLE
RT-Thread Studio编译psoc6-cy8cproto-062S3-4343W bsp报错error: unknown type name 'clock_t'

### ISSUE THREAD

**Issue by dalen0822** [RT-Thread/rt-thread#6953]
使用最新的rt-thread master分支代码，根据官方的指导文档操作编译Infineon PSoc6系统的BSP代码编译不通过。
操作如下：
在bsp/Infineon/psoc6-cy8cproto-062S3-4343W 目录下执行 scons --dist 生成目标代码，使用RT-Thread Studio 导入后，执行编译会出现如下错误，请问如何解决。
`
17:13:01 **** Build of configuration Debug for project project ****
make -j8 all 
arm-none-eabi-gcc "../rt-thread/src/clock.c"
arm-none-eabi-gcc "../rt-thread/src/components.c"
arm-none-eabi-gcc "../rt-thread/src/device.c"
arm-none-eabi-gcc "../rt-thread/src/idle.c"
arm-none-eabi-gcc "../rt-thread/src/ipc.c"
arm-none-eabi-gcc "../rt-thread/src/irq.c"
arm-none-eabi-gcc "../rt-thread/src/kservice.c"
arm-none-eabi-gcc "../rt-thread/src/mem.c"
arm-none-eabi-gcc "../rt-thread/src/mempool.c"
arm-none-eabi-gcc "../rt-thread/src/object.c"
arm-none-eabi-gcc "../rt-thread/src/scheduler.c"
arm-none-eabi-gcc "../rt-thread/src/thread.c"
arm-none-eabi-gcc "../rt-thread/src/timer.c"
arm-none-eabi-gcc "../rt-thread/libcpu/arm/cortex-m4/context_gcc.S"
arm-none-eabi-gcc "../rt-thread/libcpu/arm/cortex-m4/cpuport.c"
arm-none-eabi-gcc "../rt-thread/libcpu/arm/common/div0.c"
arm-none-eabi-gcc "../rt-thread/libcpu/arm/common/showmem.c"
arm-none-eabi-gcc "../rt-thread/components/utilities/libadt/avl.c"
arm-none-eabi-gcc "../rt-thread/components/libc/compilers/newlib/syscalls.c"
arm-none-eabi-gcc "../rt-thread/components/libc/compilers/common/cctype.c"
arm-none-eabi-gcc "../rt-thread/components/libc/compilers/common/cstdio.c"
arm-none-eabi-gcc "../rt-thread/components/libc/compilers/common/cstdlib.c"
arm-none-eabi-gcc "../rt-thread/components/libc/compilers/common/cstring.c"
arm-none-eabi-gcc "../rt-thread/components/libc/compilers/common/ctime.c"
arm-none-eabi-gcc "../rt-thread/components/libc/compilers/common/cwchar.c"
arm-none-eabi-gcc "../rt-thread/components/finsh/cmd.c"
arm-none-eabi-gcc "../rt-thread/components/finsh/msh.c"
In file included from C:\RT-ThreadStudio\workspace\project\rt-thread\components\libc\compilers\common\include/sys/time.h:18:0,
                 from C:\RT-ThreadStudio\workspace\project\rt-thread\components\libc\compilers\common\include/sys/select.h:17,
                 from c:\rt-threadstudio\repo\extract\toolchain_support_packages\arm\gnu_tools_for_arm_embedded_processors\5.4.1\arm-none-eabi\include\sys\types.h:68,
                 from c:\rt-threadstudio\repo\extract\toolchain_support_packages\arm\gnu_tools_for_arm_embedded_processors\5.4.1\arm-none-eabi\include\stdio.h:61,
                 from C:\RT-ThreadStudio\workspace\project\rt-thread\components\libc\compilers\common\include/posix/stdio.h:18,
                 from ../rt-thread/components/libc/compilers/common/cstdio.c:11:
c:\rt-threadstudio\repo\extract\toolchain_support_packages\arm\gnu_tools_for_arm_embedded_processors\5.4.1\arm-none-eabi\include\time.h:56:1: error: unknown type name 'clock_t'
 clock_t    _EXFUN(clock,    (void));
 ^
In file included from C:\RT-ThreadStudio\workspace\project\rt-thread\components\libc\compilers\common\include/sys/select.h:17:0,
                 from c:\rt-threadstudio\repo\extract\toolchain_support_packages\arm\gnu_tools_for_arm_embedded_processors\5.4.1\arm-none-eabi\include\sys\types.h:68,
                 from c:\rt-threadstudio\repo\extract\toolchain_support_packages\arm\gnu_tools_for_arm_embedded_processors\5.4.1\arm-none-eabi\include\stdio.h:61,
                 from C:\RT-ThreadStudio\workspace\project\rt-thread\components\libc\compilers\common\include/posix/stdio.h:18,
                 from ../rt-thread/components/libc/compilers/common/cstdio.c:11:
C:\RT-ThreadStudio\workspace\project\rt-thread\components\libc\compilers\common\include/sys/time.h:56:5: error: unknown type name 'suseconds_t'
     suseconds_t tv_usec;    /* and microseconds */
     ^
In file included from C:\RT-ThreadStudio\workspace\project\rt-thread\components\libc\compilers\common\include/sys/time.h:18:0,
                 from C:\RT-ThreadStudio\workspace\project\rt-thread\components\libc\compilers\common\include/sys/select.h:17,
                 from c:\rt-threadstudio\repo\extract\toolchain_support_packages\arm\gnu_tools_for_arm_embedded_processors\5.4.1\arm-none-eabi\include\sys\types.h:68,
                 from c:\rt-threadstudio\repo\extract\toolchain_support_packages\arm\gnu_tools_for_arm_embedded_processors\5.4.1\arm-none-eabi\include\stdio.h:61,
                 from ../rt-thread/components/libc/compilers/newlib/syscalls.c:16:
c:\rt-threadstudio\repo\extract\toolchain_support_packages\arm\gnu_tools_for_arm_embedded_processors\5.4.1\arm-none-eabi\include\time.h:56:1: error: unknown type name 'clock_t'
 clock_t    _EXFUN(clock,    (void));
 ^
In file included from C:\RT-ThreadStudio\workspace\project\rt-thread\components\libc\compilers\common\include/sys/select.h:17:0,
                 from c:\rt-threadstudio\repo\extract\toolchain_support_packages\arm\gnu_tools_for_arm_embedded_processors\5.4.1\arm-none-eabi\include\sys\types.h:68,
                 from c:\rt-threadstudio\repo\extract\toolchain_support_packages\arm\gnu_tools_for_arm_embedded_processors\5.4.1\arm-none-eabi\include\stdio.h:61,
                 from ../rt-thread/components/libc/compilers/newlib/syscalls.c:16:
C:\RT-ThreadStudio\workspace\project\rt-thread\components\libc\compilers\common\include/sys/time.h:56:5: error: unknown type name 'suseconds_t'
     suseconds_t tv_usec;    /* and microseconds */
     ^
arm-none-eabi-gcc "../rt-thread/components/finsh/msh_parse.c"
make: *** [rt-thread/components/libc/compilers/common/subdir.mk:33: rt-thread/components/libc/compilers/common/cstdio.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [rt-thread/components/libc/compilers/newlib/subdir.mk:18: rt-thread/components/libc/compilers/newlib/syscalls.o] Error 1
"make -j8 all" terminated with exit code 2. Build might be incomplete.

17:13:05 Build Failed. 7 errors, 0 warnings. (took 3s.737ms)

`

**Comment by zhkag** [comment]
![image](https://user-images.githubusercontent.com/62738223/220576412-24531107-a73c-4355-b7bb-c65536760a2c.png)

试试用这个功能导入到 stdio

**Comment by dalen0822** [comment]
> ![image](https://user-images.githubusercontent.com/62738223/220576412-24531107-a73c-4355-b7bb-c65536760a2c.png)
> 
> 试试用这个功能导入到 stdio

仍然有同样的问题。
在linux下使用scons 编译就不会出现上述的报错。

**Comment by zhkag** [comment]
> > ![image](https://user-images.githubusercontent.com/62738223/220576412-24531107-a73c-4355-b7bb-c65536760a2c.png)
> > 试试用这个功能导入到 stdio
> 
> 仍然有同样的问题。 在linux下使用scons 编译就不会出现上述的报错。

您需要 dist 生成的目录下重新使用 scons --target=eclipse 生成工程后然后再导入到 stdio 中

**Comment by dalen0822** [comment]
> > > ![image](https://user-images.githubusercontent.com/62738223/220576412-24531107-a73c-4355-b7bb-c65536760a2c.png)
> > > 试试用这个功能导入到 stdio
> > 
> > 
> > 仍然有同样的问题。 在linux下使用scons 编译就不会出现上述的报错。
> 
> 您需要 dist 生成的目录下重新使用 scons --target=eclipse 生成工程后然后再导入到 stdio 中

非常感谢，问题解决了。

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/7073
