### ISSUE TITLE
在使用 scons --dist 之后，需要实现自动生成工程的功能，否则将有可能出现导入项目后编译失败

### ISSUE THREAD

**Issue by zhkag** [RT-Thread/rt-thread#6955]
https://github.com/RT-Thread/rt-thread/issues/6953
https://github.com/RT-Thread/rt-thread/issues/6879

**Comment by mysterywolf** [comment]
这个之前有这个功能，但是有一个问题是，自动生成不知道要生成什么工程，所以后来就移除掉了。因为用户如果使用发布版本，bsp实际上都已经帮忙刷好了，这个问题是由于用户使用开发版导致的，开发版用户需要自己刷工程。

**Comment by mysterywolf** [comment]
scons --dist 只提供打包服务，至于工程刷新，若使用开发版本，用户要么在dist之前刷好，要么dist之后再刷工程。

**Comment by zhkag** [comment]
> scons --dist 只提供打包服务，至于工程刷新，若使用开发版本，用户要么在dist之前刷好，要么dist之后再刷工程。

对于 mdk 和 stdio 来说（其他的暂时不知道），就算 dist 之前刷好之后然后再 dist 也是会有路径问题的，也就是说就算使用的是发布版本，只要牵扯到路径 copy 也是有可能会出现编译不正常的现象的

**Comment by mysterywolf** [comment]
那这是两个不同的问题。你给出的两个issue链接都是没有刷工程导致的。
你提到的copy问题 这是另一个问题，有些bsp根本不支持dist，copy逻辑有问题。

**Comment by mysterywolf** [comment]
这么改可行否：
scons --dist=mdk5 相当于scons --dist之后再执行scons --target=mdk5

**Comment by zhkag** [comment]
> 这么改可行否： scons --dist=mdk5 相当于scons --dist之后再执行scons --target=mdk5

可以的，如果没有等号的话给他们提示一下应该也是可行的

**Comment by mysterywolf** [comment]
solved in: https://github.com/RT-Thread/rt-thread/pull/7073
