### ISSUE TITLE
rt_spi_bus_attach_device_cspin中的cs_pin数据类型是否需要改动？

### ISSUE THREAD

**Issue by charlown** [RT-Thread/rt-thread#6993]
[pin][5.0.0] 修正pin框架数据类型使用不当 #6934 

在SPI中函数接口
rt_err_t rt_spi_bus_attach_device_cspin(struct rt_spi_device *device,
                                        const char           *name,
                                        const char           *bus_name,
                                        rt_base_t            cs_pin,
                                        void                 *user_data);
同样存在类似#6934 的问题

**Comment by mysterywolf** [comment]
这个接口使用的是base_t 没有问题呀
