### ISSUE TITLE
AT 命令 接收 "\0" 字符 造成无法正确识别之后字符并且接收之后字符会  recv_buff 数组越界

### ISSUE THREAD

**Issue by BeDay** [RT-Thread/rt-thread#7005]
文件 components/net/at/src/at_server.c
函数 static void server_parser(at_server_t server)
server_parser 函数未处理 “\0” 字符
下面代码匹配 “\r\n” 由于前面存入 “\0” 将永久匹配失败 并且不会清空 recv_buffer 造成数组越界
![image](https://user-images.githubusercontent.com/9448445/222361330-4930b19d-c3a1-4ba4-80b7-896edf6daebe.png)

**Comment by Guozhanxin** [comment]
有好的解决方法嘛？

**Comment by BeDay** [comment]
> 有好的解决方法嘛？

1.ch是 “\0” 跳过不存入 recv_buffer 
2.判断结束标识时 判断 recv_buffer 长度 并清空

 `
        result = server->get_char(server, &ch, RT_WAITING_FOREVER);
        // 判断字符读取是否成功
        if (result != RT_EOK){
            at_server_printfln("");
            at_server_printfln("get char error %d", result);
            continue;
        }

      if (ESC_KEY == ch)
        {
            break;
        }

        if ( RT_NULL == ch)
        {
            // 空字符 \0 不接收
            continue;
        }
      ...........
     
     // 判断不是 end_mark 同时判断 recv_buffer 满了 跳转清空
       if(!strstr(server->recv_buffer, server->end_mark))
        {
            if(server->cur_recv_len >= AT_SERVER_RECV_BUFF_LEN){
                at_server_printfln("");
                at_server_printfln("buff full eq %d clear buffer", AT_SERVER_RECV_BUFF_LEN);
                goto __retry;
            }
            continue;
        }


`

**Comment by mysterywolf** [comment]
此PR已经解决第一个问题，第二个问题可否提交一个PR？谢谢！

**Comment by armink** [comment]
既然是 AT 这种字符协议，就不应该会传入 `\0` ，楼主可否说下遇到问题的场景

**Comment by wenxingpt** [comment]
> 此PR #7370 已经解决第一个问题，第二个问题可否提交一个PR？谢谢！

If we ensure that there is no '\0' input, then no further changes will be necessary, maybe we can consider this thread completed~
