### ISSUE TITLE
目前的MSH和残留的finsh指令的问题

### ISSUE THREAD

**Issue by Yohozzy** [RT-Thread/rt-thread#7018]
finsh指令导出废弃了吗 
无论是bsp和components里面留下的finsh导出都失效了
像这些
FINSH_FUNCTION_EXPORT(list_tcps, list all of tcp connections);
FINSH_FUNCTION_EXPORT(list_udps, list all of udp connections);
是否有计划修复一下

**Comment by aozima** [comment]
netstat

**Comment by Yohozzy** [comment]
> netstat

明白了
