### ISSUE TITLE
v4.1.1 bsp-stm32 Keil Error: L6218E: Undefined symbol __builtin_return_address (referred from backtrace.o)

### ISSUE THREAD

**Issue by XS30** [RT-Thread/rt-thread#7026]
Vision: 4.1.1;
Error BSP Name: stm32f103-atk-nano 、stm32f103-blue-pill;
Keil Vision: 5.14;
Error Code: 
".\build\keil\Obj\rt-thread.axf: Error: L6218E: Undefined symbol __builtin_return_address (referred from backtrace.o).
Not enough information to list image symbols. "
使用Keil5 编译上述两个BSP时，首先出现backtrace.c无法打开错误提示，重新添加.c文件后，出现backtrace.h无法打开错误提示，于option中添加.h文件路径，最终出现上述错误代码提示，并且无法找到解决方法。
使用v4.1.0的bsp未出现上述问题。

**Comment by yangjie11** [comment]
master：
stm32f103-atk-nano：直接编译出错，需要重新生成mdk5工程后ok
stm32f103-blue-pill：直接编译出错，需要重新生成mdk5工程后ok
