### ISSUE TITLE
[HUST CSE]: Wrong order of judgment

### ISSUE THREAD

**Issue by lessone1** [RT-Thread/rt-thread#7248]
https://github.com/RT-Thread/rt-thread/blob/master/components/drivers/serial/serial_v2.c#L1319
https://github.com/RT-Thread/rt-thread/blob/master/components/drivers/serial/serial.c#L1207
两个文件中错误的判断顺序，导致：
当`cnt1 = _TIO_BUFLEN`时，在判断`_tio_buf[cnt1] != ';'`时会导致数组的下标越界
cnt2也同理做出修改

**Comment by mysterywolf** [comment]
感谢提交PR！
