### ISSUE TITLE
rtc driver and newlib not support timezone

### ISSUE THREAD

**Issue by xools** [RT-Thread/rt-thread#725]
Currently the RTC time is localtime, withou timezone translation.

**Comment by xools** [comment]
关于这个问题，是在rtc驱动层解决吗？
以及minilib的实现对timezone并没有处理，参考https://github.com/RT-Thread/rt-thread/blob/master/components/libc/minilibc/time.c#L73
我初步想法是在rtc驱动层存储utc/gmt时间，然后在minilibc层进行时区及Daylight Saving Time的转换。不知道其他libc会不会有问题？

**Comment by BernardXiong** [comment]
一般minilibc用得非常非常少的，基本上是当gcc下没有其他libc可用时才去使用。所以minilibc实际上是确实缺少非常多的东西。
