### ISSUE TITLE
[HUST CSE] bsp/stm32/stm32u575-st-nucleo中mdk5工程默认配置有问题，是否还存在其他的工程未使用env生成配置文件？

### ISSUE THREAD

**Issue by shandianchengzi** [RT-Thread/rt-thread#7259]
新增的开发板[stm32u575-st-nucleo](https://github.com/shandianchengzi/rt-thread/tree/master/bsp/stm32/stm32u575-st-nucleo)，MDK5打开并编译之后报了80个错：

![gByidGpwPJ](https://user-images.githubusercontent.com/58585665/232272067-fd38031d-b13a-42d2-8d1b-1dd6f21aa911.jpg)

报错说多个数据类型未定义，点开发现没定义的都是adc、i2c这种[README#进阶使用](https://github.com/shandianchengzi/rt-thread/blob/master/bsp/stm32/stm32u575-st-nucleo/README_zh.md#%E8%BF%9B%E9%98%B6%E4%BD%BF%E7%94%A8)里说默认不使用的外设。

![image](https://user-images.githubusercontent.com/58585665/232272828-3f4da268-051d-4927-bdaf-04b4d452bae1.png)

于是检查了menuconfig，是与[README](https://github.com/shandianchengzi/rt-thread/blob/master/bsp/stm32/stm32u575-st-nucleo/README_zh.md)相符合的，确实只开了GPIO和UART1。

![image](https://user-images.githubusercontent.com/58585665/232272938-d24737ad-8beb-4f9b-83fc-0d9e0c74e62d.png)

但工程配置项与menuconfig对不上，这导致使用者不得不用 env 工具重新生成工程配置，`scons --target=mdk5 -s`。看env工具是进阶使用，感觉如果为了使用者友好，在推送之前开发者应该重新生成一下的。

**那其他的开发板是否也没有用env重新生成配置文件，需不需要给它全部格式化一遍**？

**Comment by mysterywolf** [comment]
这个不需要的  master开发阶段出现这个问题很正常  因为代码在时刻变化，在发布之前我们会统一刷一遍工程的
