### ISSUE TITLE
[HUST CSE] README 里有许多文档对应的官网链接已经失效，需要替换

### ISSUE THREAD

**Issue by shandianchengzi** [RT-Thread/rt-thread#7270]
注意到曾经的文档链接格式是[https://www.rt-thread.org/document/site/xxxx]。比如[https://www.rt-thread.org/document/site/tutorial/beep-player/](https://www.rt-thread.org/document/site/tutorial/beep-player/)。

而现在链接格式基本上都变成了 [https://www.rt-thread.org/document/site/#/xxxxx]。
昨天查阅文档的时候发现总是跳转不到正确的地方。

经过观察发现官网的目录组织结构重构了。

因此我们尝试重新翻找网站手动替换的链接，
比如这个 PR，env工具的使用手册：https://github.com/RT-Thread/rt-thread/pull/7262

**Comment by aozima** [comment]
如PR所改的，部分文档名称没有变化的，转换为新的 锚点链接 就可以。
但文件名称有变动或删减的，就只能人工检查了。

**Comment by shandianchengzi** [comment]
> 如PR所改的，部分文档名称没有变化的，转换为新的 锚点链接 就可以。 但文件名称有变动或删减的，就只能人工检查了。

好的谢谢，hhh，那还挺难改的，我筛了蛮多发现都有变化。考虑让大家一起帮忙找一下
