### ISSUE TITLE
[HUST CSE] rt-thread/libcpu/mips/gs264/cache.c代码中有多处未给变量赋初值，是否需要完善？

### ISSUE THREAD

**Issue by liu-ziqin** [RT-Thread/rt-thread#7310]
我在看代码过程中发现rt-thread/libcpu/mips/gs264/cache.c文件中有变量未赋初值的情况，如rt_cpu_icache_line_size函数未对ctr赋初值，请问是否需要完善这个问题？
![issue](https://user-images.githubusercontent.com/131142442/232945613-b00952f4-1b74-4c7d-a17a-8b98a52d2893.png)

**Comment by mysterywolf** [comment]
是的 欢迎提交PR

**Comment by liu2guang** [comment]
mips 架构有其他的处理手段，这里的文件应该是没有意义的。对于 mips 架构上的虚拟地址有 kseg1 段（不带有 cache, 0xFFFF.FFFF.A000.0000 - 0xFFFF.FFFF.BFFF.FFFF）或者是 xkphys 段 Uncached 地址区域（0x9800.0000.0000.0000-0x9800.00FF.FFFF.FFFF）

**Comment by liu2guang** [comment]
操作外设地址直接使用宏将物理地址转换成 kseg1 段虚拟地址，直接进行访问即可
