### ISSUE TITLE
[HUST CSE] lpc2148 bsp 的驱动开发

### ISSUE THREAD

**Issue by SophieTwilight** [RT-Thread/rt-thread#7311]
lpc2148 bsp 的驱动现在的开发维护状态是什么？
该 bsp 中的以太网驱动 dm9000.c 与 sdcard 驱动 sd.c 中有大量未实现的函数，是否需要完善？

**Comment by mysterywolf** [comment]
看了一下这个bsp缺乏维护，上次有效提交内容是在2017年。如果愿意欢迎来维护~
