### ISSUE TITLE
drv_can里面有对空指针的操作

### ISSUE THREAD

**Issue by yyxssc** [RT-Thread/rt-thread#7327]
![image](https://user-images.githubusercontent.com/56120126/233267022-6b21e84f-806f-41a7-a5fc-17ad53bd62de.png)
注释掉的是原始的
后面是我新加的

**Comment by mysterywolf** [comment]
欢迎提交pr

**Comment by mysterywolf** [comment]
请问这是哪个bsp的驱动？

**Comment by yyxssc** [comment]
> 

我看到最新的版本里面已经修改掉了，可能我用的时候不是最新的

**Comment by mysterywolf** [comment]
好的
