### ISSUE TITLE
serial_v2.c中有错误

### ISSUE THREAD

**Issue by xzfallheart** [RT-Thread/rt-thread#7331]
uart设置为RT_DEVICE_FLAG_TX_BLOCKING时，程序会死循环。查看程序，按图把rt_memset()移上去，问题解除

![image](https://user-images.githubusercontent.com/18049869/233528967-d2c45d27-3fc4-4f4b-8732-da74d865479f.png)

**Comment by mysterywolf** [comment]
欢迎提交pr

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/7394
