### ISSUE TITLE
IAR __LDREX 和 __STREX 报 declared implicitly 警告问题

### ISSUE THREAD

**Issue by Zhyolo** [RT-Thread/rt-thread#7381]
rt-thread 版本：RT-Thread v5.0.0
芯片：HC32F4A0PITB
IDE：IAR 9.30.1.50054

报警告文件：rt-thread/libcpu/arm/common/atomic_arm.c
![image](https://user-images.githubusercontent.com/18344961/234501617-18d2924b-52e1-452b-be7f-03fe2cc4f9f0.png)

下面这儿多了个 volatile
![image](https://user-images.githubusercontent.com/18344961/234502424-3df3cc82-3819-4821-8d2d-ed7a2eafb2eb.png)

**Comment by BernardXiong** [comment]
volatile的问题，欢迎发PR。 IAR `__LDREX / __STREX` 不太了解，是否需要在IAR上有什么设置，或者不是这么写法的？

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/7393

**Comment by mysterywolf** [comment]
感谢提交PR！

**Comment by Zhyolo** [comment]
原子操作的问题 #7393 并没有解决， #7393 只解决了 volatile 多了一个的问题

**Comment by wenwen2101** [comment]
可以把__LDREXW的定义改成这样：
#elif defined (__IAR_SYSTEMS_ICC__)     /* for IAR Compiler */
#include "iccarm_builtin.h"
_Pragma("inline=forced") __intrinsic rt_atomic_t __LDREXW(volatile rt_atomic_t *ptr)
{
    return __iar_builtin_LDREX((volatile unsigned int *)ptr);
}
警告消失，并且确保使用iar的内置ldrex实现，在iar 9.30.1上编译通过

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/8060 解决
