### ISSUE TITLE
使用了fopen后未使用fclose

### ISSUE THREAD

**Issue by fly1ngpengu1ns** [RT-Thread/rt-thread#7386]
在https://github.com/RT-Thread/rt-thread/blob/master/examples/utest/testcases/posix/stdio_h/functions/perror_tc.c#L12 这个函数中，使用了fopen函数，却没有使用fclose函数
![image](https://user-images.githubusercontent.com/91705983/234558125-a4ab9235-56cc-4f82-aef8-7920de7b83c1.png)
另外，在接下来的第18行`uassert_int_equal(perror_entry(), 0);`语句中，将perror_entry函数的返回值与0进行比较。但问题在于此函数只有一个返回值0，并没有其它返回值，因此是否需要将perror_entry函数修改成如下的形式？
```
static int perror_entry(void)
{
    FILE *stream;
    stream = fopen( "nulltest.txt", "r" );
    if(stream == NULL)
    {
        printf("perror test:");
        perror("nulltest.txt");
        return -1;
    }
    fclose(stream);
    return 0;
}
```

**Comment by fly1ngpengu1ns** [comment]
> 嗯 确实有些问题 欢迎提交PR！

感谢您的支持，我们已经在 #7410 中修改了这个问题

**Comment by mysterywolf** [comment]
感谢提交PR  已经合并
