### ISSUE TITLE
返回了已经free掉的地址

### ISSUE THREAD

**Issue by fly1ngpengu1ns** [RT-Thread/rt-thread#7387]
在https://github.com/RT-Thread/rt-thread/blob/master/components/drivers/fdt/src/dtb_load.c#L64 这里
![image](https://user-images.githubusercontent.com/91705983/234559737-cc91c277-9976-4887-908f-ffe34032d230.png)
第54行使用了语句`free(fdt);`，但又在64行中将其作为返回值返回，造成了地址泄露。
这里应该是存在问题的，是否需要在54行之后增加`fdt=NULL;`这样的语句？即：
```
if (dtb_node_check(fdt) == RT_FALSE)
{
    free(fdt);
    fdt=NULL;
}
```

**Comment by fly1ngpengu1ns** [comment]
#7389

**Comment by mysterywolf** [comment]
感谢提交PR  正在review中
