### ISSUE TITLE
realloc之后没有重新定义

### ISSUE THREAD

**Issue by zouziyu2002** [RT-Thread/rt-thread#7388]
![image](https://user-images.githubusercontent.com/109213219/234566826-bca86063-573b-4de0-87f0-62e61477938e.png)
还有多处出现该类问题，是否需要一并提交一个pr？

**Comment by mysterywolf** [comment]
请问这个源码位置在哪里 麻烦发个链接呗

**Comment by zouziyu2002** [comment]
https://github.com/RT-Thread/rt-thread/blob/master/tools/kconfig-frontends/libs/parser/confdata.c#L204

**Comment by zouziyu2002** [comment]
忘记给链接了，sry

**Comment by mysterywolf** [comment]
emmm 这个不是RT-Thread的代码 郭老师你看一下此处是否需要修改？ @Guozhanxin

**Comment by zouziyu2002** [comment]
有些RT-Thread源码好像也有这个问题，比如这里：https://github.com/RT-Thread/rt-thread/blob/master/bsp/simulator/drivers/dfs_win32.c#L361

**Comment by mysterywolf** [comment]
欢迎提交PR修复~

**Comment by zouziyu2002** [comment]
好的
