### ISSUE TITLE
可能的空指针引用

### ISSUE THREAD

**Issue by zouziyu2002** [RT-Thread/rt-thread#7391]
![image](https://user-images.githubusercontent.com/109213219/234580149-58d474c9-6d91-4db8-b239-a18216e42055.png)

出现了声明后未赋值直接引用的情况？是之前有什么定义吗？

**Comment by mysterywolf** [comment]
请给一下源码的位置 谢谢

**Comment by zouziyu2002** [comment]
https://github.com/RT-Thread/rt-thread/blob/master/bsp/Infineon/libraries/HAL_Drivers/drv_i2c.c#L149-#L160

**Comment by mysterywolf** [comment]
@Rbb666 麻烦有时间看一下这个问题呗 谢谢

**Comment by Rbb666** [comment]
> ![image](https://user-images.githubusercontent.com/109213219/234580149-58d474c9-6d91-4db8-b239-a18216e42055.png)
> 
> 出现了声明后未赋值直接引用的情况？是之前有什么定义吗？

https://github.com/RT-Thread/rt-thread/pull/7396/files，在这个PR中修复了。

**Comment by zouziyu2002** [comment]
好的
