### ISSUE TITLE
可能的数组越界导致程序崩溃

### ISSUE THREAD

**Issue by zouziyu2002** [RT-Thread/rt-thread#7392]
rt-thread-master/rt-thread-master/bsp/Infineon/libraries/IFX_PSOC6_HAL/mtb-pdl-cat1/drivers/source/cy_sysclk_v2.c
其中定义
![image](https://user-images.githubusercontent.com/109213219/234585019-6e1e81f6-681d-4bf7-a14f-6ea6a273797d.png)
该值为33
但在下面的访问中
定义的数组为32位，并且存在越界访问的可能（未检查）
![image](https://user-images.githubusercontent.com/109213219/234585844-7747b73f-bced-47f2-9507-841f71be09dc.png)

**Comment by mysterywolf** [comment]
该源码非rt-thread源码 请向英飞凌上游官方报告其HAL有缺陷，我们这里即便改了，下次他们版本更新，你改的内容也会被覆盖掉。

**Comment by zouziyu2002** [comment]
好的
