### ISSUE TITLE
libcpu/aarch64/common/gicv3.c cpu_hw_base/redist_hw_base 与 RT_CPUS_NR 耦合问题

### ISSUE THREAD

**Issue by ssd4561** [RT-Thread/rt-thread#7440]
https://github.com/RT-Thread/rt-thread/blob/ca023c1b41e1f413b799e045524f02f572cc182a/libcpu/aarch64/common/gicv3.c#LL50C34-L50C34

此处gic v3 的Distributor 与 ReDistributor 与RT_CPUS_NR  存在耦合，如果CPU 0核为rt-thread 主核时，如此运行没有任何问题，但是如果非CPU0核为主核时，CPU id 与 gic 的绑定关系则被破坏，由此建议将此处解耦，让开发者自行决定gic控制器中存在多少个Distributor与Redistributor

**Comment by aozima** [comment]
学习了，之前还没遇到非CPU0核为主核的场景。
