### ISSUE TITLE
[CI][cppcheck] 需要根据ignore_format 过滤掉不需要扫描的文件夹

### ISSUE THREAD

**Issue by mysterywolf** [RT-Thread/rt-thread#7458]

**Comment by supperthomas** [comment]
https://github.com/RT-Thread/rt-thread/blob/master/.github/workflows/static_code_analysis.yml

添加路径检查

**Comment by supperthomas** [comment]
遍历一下ignore.yml文件找到所有需要忽略的文件夹，搞个大数组，然后过滤~

**Comment by supperthomas** [comment]
比如：
https://github.com/RT-Thread/rt-thread/blob/master/bsp/bouffalo_lab/libraries/bl_mcu_sdk/.ignore_format.yml

**Comment by supperthomas** [comment]
参考一下
https://github.com/RT-Thread/rt-thread/blob/master/tools/file_check.py
