### ISSUE TITLE
[ci] 增加对RT错误码返回值的检查

### ISSUE THREAD

**Issue by mysterywolf** [RT-Thread/rt-thread#7510]
RT_ERROR、RT_EINVEL等错误码在return时，必须返回负值，即 return -RT_ERROR  return -RT_EINVEL。RT_EOK除外，它可以直接 return RT_EOK.

需要新增一个ci检查项，来检查用户return错误码时，是否错误地直接return  RT_ERROR等错误码。

rt-thread错误码定义位于：https://github.com/RT-Thread/rt-thread/blob/master/include/rtdef.h#L358

之前曾经提交过一些PR来修正这个问题：https://github.com/RT-Thread/rt-thread/pull/7059 等

**Comment by a1012112796** [comment]
这个作为新手任务不太合适吧 [dog]

**Comment by supperthomas** [comment]
这个你要怎么 验证？

**Comment by mysterywolf** [comment]
rt-thread的错误码，在返回的时候 除了 return RT_EOK;之外，其他都应该是return -RT_Exxx，检查是否有负号

**Comment by mysterywolf** [comment]
这个问题提了好几个PR才修掉，很多bsp的提交者没有注意到这个问题 return的错误码是正值

**Comment by supperthomas** [comment]
> 这个问题提了好几个PR才修掉，很多bsp的提交者没有注意到这个问题 return的错误码是正值

太复杂了，没时间搞。

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/8341
