### ISSUE TITLE
How to get the tasks CPU utilization ?

### ISSUE THREAD

**Issue by Sfinx** [RT-Thread/rt-thread#7520]
Is there a way to get the tasks CPU utilization ? Something like vTaskGetRunTimeStats() from FreeRTOS ?

**Comment by supperthomas** [comment]
https://github.com/enkiller/cpu_usage

**Comment by supperthomas** [comment]
![图片](https://github.com/RT-Thread/rt-thread/assets/60349489/2b3e7c28-441f-440d-b460-e8621189a409)

**Comment by Sfinx** [comment]
Thanks !
