### ISSUE TITLE
[libc error]  编译错误PATH_MAX 未定义

### ISSUE THREAD

**Issue by supperthomas** [RT-Thread/rt-thread#7533]
任意STM32 bsp
stm32\stm32l496-st-nucleo
menuconfig选中mqueue.h
如下图
![图片](https://github.com/RT-Thread/rt-thread/assets/60349489/f643c705-9c9d-4973-9f5a-b034d77cc008)
之后执行`scons --target=mdk5`
会出现编译错误：
![图片](https://github.com/RT-Thread/rt-thread/assets/60349489/bce3d7e2-3ea5-40a7-9e4e-3ca1bac3e199)

**Comment by mysterywolf** [comment]
这块写的有问题，周一我看一下

**Comment by supperthomas** [comment]
@DylanLiuH2O

**Comment by mysterywolf** [comment]
涛哥 你这个先不用着急 可以直接把PATH_MAX这个判断去掉，这个判断的逻辑写的有问题，加>PATH_MAX这个判断完全没必要

**Comment by DylanLiuH2O** [comment]
> 涛哥 你这个先不用着急 可以直接把PATH_MAX这个判断去掉，这个判断的逻辑写的有问题，加>PATH_MAX这个判断完全没必要 我得联系谁写的这个，谁来改一下

原始作者的提交在这里#7395 ，`PATH_MAX`是一个平台相关的宏，而且并不是强制性的，因此可能会报未定义。
> Macro: int PATH_MAX
> The uniform system limit (if any) for the length of an entire file name (that is, the argument given to system calls such as open), including the terminating null character.
> **Portability Note: The GNU C Library does not enforce this limit even if PATH_MAX is defined.**

[Limits-for-Files](https://www.gnu.org/software/libc/manual/html_node/Limits-for-Files.html)

**Comment by mysterywolf** [comment]
fixed in here: https://github.com/RT-Thread/rt-thread/pull/7550
