### ISSUE TITLE
同时使用armlibc和dfs_elm, keil编译报错

### ISSUE THREAD

**Issue by JianRuiqian** [RT-Thread/rt-thread#756]
具体报错如下：
Error: L6915E: Library reports error: __use_no_semihosting_swi was requested, but time was referenced
定位到dfs_elm.c文件，发现get_fattime函数使用了now = time(RT_NULL);
请问有什么解决办法？是因为armlibc没有对time函数进行retarget吗？

**Comment by BernardXiong** [comment]
好像论坛上aozima给出回复了，如果确定是这样的，还请复制一份到这边来。另外，对于在RT-Thread github上有提交纪录的同学，可以联系我获得开发人员专用的QQ群。

**Comment by JianRuiqian** [comment]
谢谢！在rtc框架里有time函数的原型，添加后编译就能通过。请问是通过邮件联系您吗？
