### ISSUE TITLE
ulog_async_output_enabled(void) 函数功能无效

### ISSUE THREAD

**Issue by Harley-yang** [RT-Thread/rt-thread#7771]
版本：最新rtt代码
问题函数：
`/**
 * enable or disable asynchronous output mode
 * the log will be output directly when mode is disabled
 *
 * @param enabled RT_TRUE: enabled, RT_FALSE: disabled
 */
void ulog_async_output_enabled(rt_bool_t enabled)
{
    ulog.async_enabled = enabled;
}
`

问题描述：
当使能ULOG_USING_ASYNC_OUTPUT宏定义的时候，默认用户调用LOG_I（）等日志接口的时候，日志信息会通过异步线程的方式推迟打印出来；
但有时我们希望能够动态关闭log的异步输出，我看ulog子模块提供了ulog_async_output_enabled（RT_FALSE）这个接口给用户，注释里面也写了当传入RT_FALSE的时候，能够关闭异步功能，将日志直接打印出来。
但是实际调用该函数并参RT_FALSE的时候发现，日志还是异步输出的。
请帮忙解决这个问题。

**Comment by armink** [comment]
这个估计是当时实现时候漏实现了

你可以试试完善下 do_output 函数，增加关闭异步输出时，使用同步输出的能力
