### ISSUE TITLE
[SAL/SOCKET]关于重复释放 vnode 导致的断言问题

### ISSUE THREAD

**Issue by hg0720** [RT-Thread/rt-thread#7790]
在使用 socket 编程时开启 RT_DEBUG
在调用 closesocket() 接口时出现了断言问题：

(header_ptr->magic == (RT_MEMHEAP_MAGIC | RT_MEMHEAP_USED)) assertion failed at function:rt_memheap_free, line number:623

Debug 后发现 vnode 的地址被 free 了两次

![image](https://github.com/RT-Thread/rt-thread/assets/109518060/326e5391-63ed-4794-bafe-89344ec26233)
![image](https://github.com/RT-Thread/rt-thread/assets/109518060/ff562936-8de5-4c2e-bcc5-1318f01d17ac)

**Comment by mysterywolf** [comment]
欢迎提交PR！
