### ISSUE TITLE
rt-thread5.0+版本libcpu中risc-v代码是正在进行重新架构么?

### ISSUE THREAD

**Issue by charlown** [RT-Thread/rt-thread#7819]
手头上有ch32v103r-evt板子，rtt5.0+无法运行，回退到rtt4.1.1是可以的。看了一下libcpu/risc-v的改动历史，很多risc-v芯片移植代码移除了，这是在重新架构么？

**Comment by mysterywolf** [comment]
是的 已经重构完毕了，如果有问题的话看看可以重新对接一下

**Comment by charlown** [comment]
好的
