### ISSUE TITLE
ARM 32位打开 SMP 后有编译错误（qemu-vexpress-a9）

### ISSUE THREAD

**Issue by zhugengyu** [RT-Thread/rt-thread#7857]
RT_USING_SMP = on

![image](https://github.com/RT-Thread/rt-thread/assets/85654684/e19fb438-fec4-4e60-b174-5a6bdda65774)

- 初步看原因是头文件引用不当
```
rthw.h 引用 cpuport.h，cpuport.h 引用 rtthread.h，rtthread.h 引用 rtatomic.h，rtatomic.h 又引用回 rthw.h
```

- 临时解决办法就是在 rtatomic.h 不引用 rthw.h

![image](https://github.com/RT-Thread/rt-thread/assets/85654684/5f6f735f-d17f-4e57-9424-0f23ca41378d)

![image](https://github.com/RT-Thread/rt-thread/assets/85654684/2212b554-01f5-4600-9df3-a0b5fcf2378a)

**Comment by GuEe-GUI** [comment]
rtatomic.h 道理上是至少要引用一个 rtdef，但是后续的soft实现还是引入了 rthw.h
