### ISSUE TITLE
【内核/timer】rt_timer_start中这部分代码是否冗余

### ISSUE THREAD

**Issue by hg0720** [RT-Thread/rt-thread#7864]
在分析timer流程时，rt_timer_start函数中对于tick的排序算法中出现了冗余部分，具体如下：
![image](https://github.com/RT-Thread/rt-thread/assets/109518060/09029892-583b-4e47-a33f-d0bba4a0aa43)
不太清楚这部分判断的具体作用

**Comment by enkiller** [comment]
超时时间一致时，把节点插入到靠后的位置
