### ISSUE TITLE
keil 的 rt-thread 包官方不维护了吗？

### ISSUE THREAD

**Issue by ChowSings** [RT-Thread/rt-thread#7874]
keil 包停留在 3.1.5 版本 https://www.keil.arm.com/packs/rt-thread-realthread/versions/

**Comment by mysterywolf** [comment]
现在rt-thread nano最新就是3.1.5的

**Comment by ChowSings** [comment]
> 现在rt-thread nano最新就是3.1.5的

M4可以使用吗？

**Comment by mysterywolf** [comment]
rt-thread本身和平台无关，特定平台如果用nano需要适配

**Comment by ChowSings** [comment]
> rt-thread本身和平台无关，特定平台如果用nano需要适配

谢谢解答
