### ISSUE TITLE
Using STM32G0B1

### ISSUE THREAD

**Issue by updesh31** [RT-Thread/rt-thread#7877]
How can I use STM32G0B1CCT6 mcu with rt-thread?

**Comment by zhkag** [comment]
可以在 bsp 中找同系列的相似芯片 进行移植  如 https://github.com/RT-Thread/rt-thread/tree/master/bsp/stm32/stm32g070-st-nucleo

**Comment by updesh31** [comment]
Thanks

**Comment by updesh31** [comment]
I got it.
