### ISSUE TITLE
[RT_DEBUG_DEVICE]存在新的编译错误

### ISSUE THREAD

**Issue by kylongmu** [RT-Thread/rt-thread#7879]
D:\Develop\Git_Project\rt-thread\src\device.c: In function 'rt_device_init':
D:\Develop\Git_Project\rt-thread\src\device.c:181:17: warning: implicit declaration of function 'RT_DEBUG_LOG'; did you mean 'RT_EBUSY'? [-Wimplicit-function-declaration]
                 RT_DEBUG_LOG(RT_DEBUG_DEVICE, ("To initialize device:%s failed. The error code is %d\n",
                 ^~~~~~~~~~~~
                 RT_EBUSY
D:\Develop\Git_Project\rt-thread\src\device.c:181:30: error: 'RT_DEBUG_DEVICE' undeclared (first use in this function); did you mean 'RT_USING_DEVICE'?
                 RT_DEBUG_LOG(RT_DEBUG_DEVICE, ("To initialize device:%s failed. The error code is %d\n",
                              ^~~~~~~~~~~~~~~
                              RT_USING_DEVICE
D:\Develop\Git_Project\rt-thread\src\device.c:181:30: note: each undeclared identifier is reported only once for each function it appears in
D:\Develop\Git_Project\rt-thread\src\device.c: In function 'rt_device_open':
D:\Develop\Git_Project\rt-thread\src\device.c:219:30: error: 'RT_DEBUG_DEVICE' undeclared (first use in this function); did you mean 'RT_USING_DEVICE'?
                 RT_DEBUG_LOG(RT_DEBUG_DEVICE, ("To initialize device:%s failed. The error code is %d\n",
                              ^~~~~~~~~~~~~~~
                              RT_USING_DEVICE
scons: *** [build\kernel\src\device.o] Error 1
scons: building terminated because of errors.

例子里没有引用到D:\Develop\Git_Project\rt-thread\src\device.c这个文件，但是我的工程里用到了，所以我的工程编译还是出错。

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/7881/files 按照这个PR替换一下成LOG_D即可
