### ISSUE TITLE
[BSP] [STM32] drv_spi.c 疑似冗余代码

### ISSUE THREAD

**Issue by sp-cai** [RT-Thread/rt-thread#7909]
https://github.com/RT-Thread/rt-thread/blob/a6fcb4f8a13709e836b9133a08d573fc0dfd398a/bsp/stm32/libraries/HAL_Drivers/drv_spi.c#L111-L112
这两行代码没有找到用途，是否是冗余代码？

**Comment by mysterywolf** [comment]
感谢 https://github.com/RT-Thread/rt-thread/pull/7911

**Comment by sp-cai** [comment]
> 感谢 #7911

感谢确认
