### ISSUE TITLE
scons 4.5.2 build error in rt-thread4.1.1

### ISSUE THREAD

**Issue by Guozhanxin** [RT-Thread/rt-thread#7991]
新版本scons编译报错
![image](https://github.com/RT-Thread/rt-thread/assets/25633294/4f91281c-9d42-4f90-8891-1414cf3cc806)
注释掉下面这行代码可以正常使用
![image](https://github.com/RT-Thread/rt-thread/assets/25633294/c86a4047-106f-4554-bb1a-086d1e4dcee3)

**Comment by zhkag** [comment]
这就是原来 scons 固定到 4.4.0 的原因 后来熊大修了，高版本的 scons  2023-5-22 之前的版本都不好使的

**Comment by BernardXiong** [comment]
> 这就是原来 scons 固定到 4.4.0 的原因 后来熊大修了，高版本的 scons 2023-5-22 之前的版本都不好使的

这个是说修出问题了吗？

**Comment by zhkag** [comment]
感觉这个问题提到长期支持版中，重新释放一下版本吧，随着时间的推移肯定越来越多的人会更新到 4.4.0 之后的 scons 版本，到时候都会有这个问题的

**Comment by Guozhanxin** [comment]
> 感觉这个问题提到长期支持版中，重新释放一下版本吧，随着时间的推移肯定越来越多的人会更新到 4.4.0 之后的 scons 版本，到时候都会有这个问题的

哪一笔代码修复的啊

**Comment by zhkag** [comment]
> > 感觉这个问题提到长期支持版中，重新释放一下版本吧，随着时间的推移肯定越来越多的人会更新到 4.4.0 之后的 scons 版本，到时候都会有这个问题的
> 
> 哪一笔代码修复的啊

#7541
