### ISSUE TITLE
最新的env script  `pkgs --update` 有问题

### ISSUE THREAD

**Issue by supperthomas** [RT-Thread/rt-thread#8009]
```
 ~/work/rt-thread/rt-thread/bsp/nrf5x/nrf51822 ~/work/rt-thread/rt-thread
Traceback (most recent call last):
   File "/home/runner/.env/tools/scripts/env.py", line 34, in <module>
   from cmds import *
   File "/home/runner/.env/tools/scripts/cmds/cmd_menuconfig.py", line 31, in <module>
    import psutil
 ModuleNotFoundError: No module named 'psutil'
```

https://github.com/RT-Thread/rt-thread/actions/runs/6104398791

**Comment by mysterywolf** [comment]
昨天已经修复了 

https://github.com/RT-Thread/env-windows/commit/9ba1a1290a47e2a3c789a3ef0e5df49d78f5c07e

https://github.com/RT-Thread/env/commit/77ad79c582e0c0f3fa60eb5b4d4a7623ab642d84

**Comment by supperthomas** [comment]
> 昨天已经修复了
> 
> [RT-Thread/env-windows@9ba1a12](https://github.com/RT-Thread/env-windows/commit/9ba1a1290a47e2a3c789a3ef0e5df49d78f5c07e)
> 
> [RT-Thread/env@77ad79c](https://github.com/RT-Thread/env/commit/77ad79c582e0c0f3fa60eb5b4d4a7623ab642d84)

action 顺便修复一下?

**Comment by mysterywolf** [comment]
action 可否考虑用标准的env在ubuntu下的安装方式：
wget https://raw.githubusercontent.com/RT-Thread/env/master/install_ubuntu.sh
chmod 777 install_ubuntu.sh
./install_ubuntu.sh

这个脚本是env自带的 可以自动安装所有依赖并自动搭建环境

**Comment by supperthomas** [comment]
> action 可否考虑用标准的env在ubuntu下的安装方式： wget https://raw.githubusercontent.com/RT-Thread/env/master/install_ubuntu.sh chmod 777 install_ubuntu.sh ./install_ubuntu.sh
> 
> 这个脚本是env自带的 可以自动安装所有依赖并自动搭建环境
> 
> 这样action就不用有一套自己的安装环境的流程了

可以呀，可以试试。欢迎PR。

**Comment by mysterywolf** [comment]
哪个文件需要修改 涛哥可以提供一下嘛？ 我看看怎么改

**Comment by supperthomas** [comment]
https://github.com/RT-Thread/rt-thread/blob/master/.github/workflows/action.yml

**Comment by supperthomas** [comment]
https://github.com/RT-Thread/rt-thread/blob/5f948690c9b2190c8a237bdfc0e67f4d68f4efd6/.github/workflows/action.yml#L325

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/8010 涛哥你看一下

**Comment by supperthomas** [comment]
```
        run: |
          wget https://raw.githubusercontent.com/RT-Thread/env/master/install_ubuntu.sh
          chmod 777 install_ubuntu.sh
          ./install_ubuntu.sh
          git config --global http.postBuffer 524288000
          python -c "import tools.menuconfig; tools.menuconfig.touch_env()"
          echo "RTT_ROOT=${{ github.workspace }}" >> $GITHUB_ENV
```

**Comment by mysterywolf** [comment]
涛哥你来提个pr吧 action这块我不熟悉
