### ISSUE TITLE
[kernel] 内核依赖组件libc

### ISSUE THREAD

**Issue by yangjie11** [RT-Thread/rt-thread#8021]
如果更新nano就不太好用了

**Comment by BernardXiong** [comment]
可以贴贴，依赖了哪些libc部分，signal.h？

**Comment by siyun-chen** [comment]
> 可以贴贴，依赖了哪些libc部分，signal.h？

![image](https://github.com/RT-Thread/rt-thread/assets/50290239/bdeb386c-3c47-40cb-a5f4-53674d9db813)
在rtdef.h文件中，如果定义了RT_USING_LIBC则会包含sys/types.h，MDK中的AC5、AC6的Libc里面显然是没有包含的。不得不引用components\libc，这并不是一件麻烦事情，但是core依赖components总是有一种很别扭的感觉

**Comment by BernardXiong** [comment]
为什么需要包含`sys/types.h`？相同作用的，在AC6中是什么

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/8035 我提了一份草稿PR

**Comment by mysterywolf** [comment]
我建议打包nano的时候参照上面的PR 手动处理一下就可以了
