### ISSUE TITLE
The ls command caused the system to freeze

### ISSUE THREAD

**Issue by Johnxjj** [RT-Thread/rt-thread#8022]
I see that the vfs has changed a lot in the new version, I wonder where I can see the reason for this change, is there anything wrong with the earlier version?

**Comment by Johnxjj** [comment]
My rt-thread version number is v4.1.0

**Comment by BernardXiong** [comment]
There is a new version for dfs, as DFS v2.0, which fixes some legacy issues, such as dup, refcount etc. The DFS v2.0 only appears in version 5.0 for MPU.
