### ISSUE TITLE
STM32-L476RG 使用 v5.0.1 版本 RT-Thread 的代码编译出错  不识别的 RT_WEAK

### ISSUE THREAD

**Issue by alteracd** [RT-Thread/rt-thread#8097]
使用的开发板：STM32-L476RG-NUCLEO，直接在RTT Studio 中创建的工程。
![image](https://github.com/RT-Thread/rt-thread/assets/50413466/de741bf7-9158-44ed-abf5-175ebac1d5b6)
![image](https://github.com/RT-Thread/rt-thread/assets/50413466/c879494a-5f64-4cac-8e32-c3b5308b2dd4)

检查发现在最新版本的 RT-Thread (v5.0.1) 里 RT_WEAK 字段已经被 rt_weak 替换，手动替换之后可以正常编译使用。
是否应该按照版本更新一下这个地方？

**Comment by BernardXiong** [comment]
welcome PR, thanks.

**Comment by alteracd** [comment]
It has now been replaced to fix this issue
https://github.com/RT-Thread/rt-thread/blob/a39da9cb596b9dc0b0d0265fa67d5db8a2f66f09/bsp/stm32/libraries/HAL_Drivers/drv_common.c#L167
