### ISSUE TITLE
rt-tread4.1.1开启C++支持之后，全局对象的析构函数不会被调用

### ISSUE THREAD

**Issue by atwwww** [RT-Thread/rt-thread#8135]
### 环境：
windows 10
RT-Thread Studio 2.7.7
QEMU模拟

### 编译器：
arm-none-eabi-gcc 5.4.1
### 工程信息
![image](https://github.com/RT-Thread/rt-thread/assets/81611821/8aeed55b-9e15-4899-980e-21de93759100)

### 问题复现：
1. 打开C++支持
2. 在main函数外声明一个全局对象
3. 运行完毕之后发现，全局对象的构造函数被调用了，但**全局对象的析构函数没有被调用**。
代码
![48417f1d1bb156c264026ff91411a01c](https://github.com/RT-Thread/rt-thread/assets/81611821/5c75f4ab-5eff-489d-a451-abc9db370f87)
结果
![536128009a7f4a3b83f8f863552d5bfd](https://github.com/RT-Thread/rt-thread/assets/81611821/3f9a40b1-6f45-4985-b397-e5ec97c657b5)

### 目前已知：
1. RT-Thread全局对象的构造函数会在链接脚本机制下被收集放到.ctors段中，在函数cplusplus_system_init中被调用，以此来初始化。
2. RT-Thread链接脚本中似乎也有析构函数对应的段，但是似乎没有被使用。![image](https://github.com/RT-Thread/rt-thread/assets/81611821/8772c789-0db0-4fac-b69d-dfebc6fe619e)
3. 在Ubuntu20.04中，发现main函数结束后会跳入exit函数中，在此函数中，全局对象的析构函数被执行；但是RT-Thread中，main函数结束之后，直接跳到_thread_exit函数，将main线程detach。调度到idle线程时，清除main线程有关资源。
5. 全程没有调用到全局对象的析构函数。
6. 局部对象的构造函数和析构函数可以正常被调用。

### 想要了解
1. 什么原因导致的全局对象的析构函数没有被调用?
2. 怎样才能够补全这个全局对象的自动析构机制?

**Comment by JonasWen** [comment]
是不是作用域的问题。你把对象声明放到main里去就会调用析构函数了

**Comment by atwwww** [comment]
> 是不是作用域的问题。你把对象声明放到main里去就会调用析构函数了

放到main中确实可以，相当于是main的局部对象。编译器产生的汇编文件中是可以看到在函数结束前调用对象的析构函数的。
但是放到main外，作为一个真正的全局变量的时候似乎只能初始化，但是最后不会被调用析构函数。
我在问题中也说明了这种情况：
![42b4ff7f33e72c67dbae8b6561ce37e8](https://github.com/RT-Thread/rt-thread/assets/81611821/a75c6560-8d40-4d8b-9926-f6e32d832398)

**Comment by JonasWen** [comment]
你调用exit(0);试试看

**Comment by atwwww** [comment]
> 你调用exit(0);试试看

之前也试过手动调用exit(0)，然后又尝试了一次。
RT-THREAD实现了newlib中的exit的桩函数_exit，实现方式是将当前线程直接delete掉🤔
![ca41f14963d9f529139592e601462c67](https://github.com/RT-Thread/rt-thread/assets/81611821/bb0d1503-53a7-4740-b2d6-b229f4f7c906)

![e26854e84281864fdb24156131388a64](https://github.com/RT-Thread/rt-thread/assets/81611821/c4b8eb0c-6f19-4667-957f-e8f4a90597d6)

![a892d4010ed2b76c286409a84a407801](https://github.com/RT-Thread/rt-thread/assets/81611821/d14ea401-7a59-44a7-b9ce-f7f8c138fca7)

**Comment by JonasWen** [comment]
你有keil的环境吗，我用MDK5.38/ArmCompiler6.19编译后调用exit(0);会执行全局变量的析构函数。

**Comment by atwwww** [comment]
> 你有keil的环境吗，我用MDK5.38/ArmCompiler6.19编译后调用exit(0);会执行全局变量的析构函数。

我用的gnu的编译器，然后就用的RT-Thread Studio

**Comment by atwwww** [comment]
> 你有keil的环境吗，我用MDK5.38/ArmCompiler6.19编译后调用exit(0);会执行全局变量的析构函数。

我发现链接器配置参数，不要使用简化的newlib库就可以了。
![38b229fcd7d93aaf11a1c138f1d13552](https://github.com/RT-Thread/rt-thread/assets/81611821/a659aed6-4060-471e-86cb-346b484831a4)

![3900e3c11f1a55e3db51dab08507964b](https://github.com/RT-Thread/rt-thread/assets/81611821/737cf51e-beda-48ab-a682-16b4dbef3130)

**Comment by atwwww** [comment]
前段时间研究发现，nano-newlib中使用的应该是轻量级exit，轻量级退出程序在程序退出时不会清理全局变量。
在newlib的README中：
![874e77ddfade40f15774415d84315cbb](https://github.com/RT-Thread/rt-thread/assets/81611821/81b4a500-68a9-451f-a58a-948d273a2a22)

在newlib源码exit函数中：
![0ea7f5fa5f42b8e5f7f549964bbd554e](https://github.com/RT-Thread/rt-thread/assets/81611821/bf8edf01-be4f-4951-b46f-7a0343bd1e6b)

__atexit.c中关于lite_exit说明
![94e5baf7534f8781af21cd27b471e3c6](https://github.com/RT-Thread/rt-thread/assets/81611821/617b7b37-e3e6-48fe-ab74-d8fb12634fd9)
