### ISSUE TITLE
rt-thread/bsp/stm32f429-apollo工程可能存在因为C99导致的错误

### ISSUE THREAD

**Issue by yuan-fujie** [RT-Thread/rt-thread#814]
错误指向spi_flash_sfud.c文件里面某些地方， MDK 配置的 C++ —— misc controls 输入C99，就不会报错，不过有的电脑MDK配置不输入C99也可以编译通过

**Comment by armink** [comment]
使用 SFUD 要求了 C99 ，请看 SFUD 的说明文档。

**Comment by yuan-fujie** [comment]
嗯嗯，我没看，谢谢！

**Comment by BernardXiong** [comment]
需要修正为不使用C99代码啊
