### ISSUE TITLE
对于删除的宏，是否应该加一些提示信息

### ISSUE THREAD

**Issue by Guozhanxin** [RT-Thread/rt-thread#8149]
类似这种的
![image](https://github.com/RT-Thread/rt-thread/assets/25633294/8154012c-84be-4851-901d-c79cbe7c2021)

**Comment by zhkag** [comment]
感觉可以这样，不过过了一个大版本之后，也是要删除的

**Comment by mysterywolf** [comment]
5.1.0没有必要加了吧其他版本可以加一个？
