### ISSUE TITLE
[BSP] ci中bsp默认SDK软件包过大，导致不容易编译通过

### ISSUE THREAD

**Issue by supperthomas** [RT-Thread/rt-thread#8200]
目前已知BSP软件包过大，pkgs --update的时候需要下载submodule，这个会导致该bsp下载不完整，导致编译不过
- [ ] [ESP32_C3](https://github.com/RT-Thread/rt-thread/tree/master/bsp/ESP32_C3)
- [x] [raspberry-pico](https://github.com/RT-Thread/rt-thread/tree/master/bsp/raspberry-pico)

**Comment by mysterywolf** [comment]
应该把.submodule文件去掉 我们不需要依赖子仓的

**Comment by supperthomas** [comment]
https://github.com/RT-Thread-packages/raspberrypi-pico-sdk/pull/5

**Comment by supperthomas** [comment]
https://github.com/RT-Thread-packages/esp-idf/pull/12

**Comment by supperthomas** [comment]
https://github.com/RT-Thread-packages/esp-idf/pull/13

**Comment by supperthomas** [comment]
https://github.com/RT-Thread-packages/esp-idf/pull/14
