### ISSUE TITLE
对Tag v5.0.0 中的rt_schedule函数存在疑惑(或许是BUG)

### ISSUE THREAD

**Issue by Nohysiwe** [RT-Thread/rt-thread#8241]
在 Tag v5.0.0中, scheduler_mp.c 文件中 rt_schedule 函数, 有部分代码存在问题

```c
if (current_thread->scheduler_lock_nest == 1) /* whether lock scheduler */
```
如果我没理解错, schedule_lock_nest = 1时表示调度器被锁住，那么为何在此版本, 这个是在调度器锁住时才进行调度相关操作，这里是不是有bug,并且同一文件的 rt_critical_exit函数的末尾代码段 
```C
if (current_thread->scheduler_lock_nest <= 0)
    {
        current_thread->scheduler_lock_nest = 0;
        /* enable interrupt */
        rt_hw_local_irq_enable(level);

        rt_schedule();
    }    
```

在上述rt_schedule的函数下意味着未作任何操作，并且，这个没理解错的话，是不是想在出临界区时调度一下，可是这里显然不会执行任何操作。

**Comment by BernardXiong** [comment]
可以查看下最新版本情况。
