### ISSUE TITLE
关于提供内置hashmap结构的建议

### ISSUE THREAD

**Issue by musicwei** [RT-Thread/rt-thread#8276]
既然现在已经存在链表结构，是否有计划内置线程安全的hashmap结构？

**Comment by a1012112796** [comment]
这东西 rtt 本身用不上，内置的意义感觉不大。如果需要，可以考虑用 c++ stl 的， 线程安全加锁就可以了。

**Comment by xqyjlj** [comment]
等内核的futex支持后，会加上的。

**Comment by BernardXiong** [comment]
> https://github.com/RT-Thread/rt-thread/blob/master/components/utilities/libadt/hashmap/hashmap.h
