### ISSUE TITLE
【BSP 编译报错】更新了 MPU 组件后，用到m33和m7的BSP编译均报错找不到 <rtconfig.h>

### ISSUE THREAD

**Issue by hg0720** [RT-Thread/rt-thread#8284]
在编译 art_pi 时发现，由于在 context_gcc.S 中加入了 ``#include <rtconfig.h>`` 导致 BSP 编译错误
![image](https://github.com/RT-Thread/rt-thread/assets/109518060/9429db20-6139-4a9b-8ad9-0ccf57609a46)

**Comment by BernardXiong** [comment]
需要在SConstruct中调整汇编的编译参数

**Comment by mysterywolf** [comment]
sovled : https://github.com/RT-Thread/rt-thread/pull/8436
