### ISSUE TITLE
[ci] 继续完善编译strict mode

### ISSUE THREAD

**Issue by mysterywolf** [RT-Thread/rt-thread#8427]
配合attachconfig文件对指定bsp进行严格编译

计划支持 scons 命令，例如：
``` shell
scons --strict="-Werror -Wunsed -Wextra"
```

.attach在附加宏之前可以标定本次编译的严格程度
```
# strict: -Werror -Wunsed -Wextra
CONFIG_BSP_USING_LVGL=y
```

也可以创建一个没有附加宏的空.attach文件，来让BSP默认配置以严格编译模式编译
```
# strict: -Werror -Wunsed -Wextra
```

当识别到.attach的`# strict`关键字之后，就会将其后面的内容以scons --strict="-Werror -Wunsed -Wextra" 来执行编译

方案二：
 

为了方便识别，格式也可以是 **（个人倾向于这种方案）**：
```
# scons: --strict="-Werror -Wunsed -Wextra"
```

或

```
# --strict="-Werror -Wunsed -Wextra"
```

**Comment by mysterywolf** [comment]
attachconfig 文件夹支持递归扫描子文件夹下的attach文件

**Comment by vacabun** [comment]
我个人也比较倾向于方案二，在每个.attach文件的开头添加：
`# scons: --strict="-Werror -Wunsed -Wextra"`
或
`# --strict="-Werror -Wunsed -Wextra"`

**Comment by mysterywolf** [comment]
经过思考，不同的组采用不同的严格程度是更符合rt-thread实际情况的，scons --strict保持现状，无需增加--strict=“”方式，具体参数添加有Group确定 详见：https://github.com/RT-Thread/rt-thread/pull/8454

.attach文件仅需完成如下解析即可

```
# scons: --strict
```

如果侦测到scons关键字，则编译时，补充使用冒号后面的参数

**Comment by vacabun** [comment]
https://github.com/RT-Thread/rt-thread/pull/8464

检测到`# scons: [scons_args]`，编译时会补充使用冒号后面的参数，即添加到`scons -C bsp/{bsp} -j{nproc} {scons_args}`。

`.attach`文件内可以有多行`# scons: [scons_args]`，会自动以空格分开。
