### ISSUE TITLE
idle线程主动挂起行为是何用意呢？

### ISSUE THREAD

**Issue by daguobayern** [RT-Thread/rt-thread#8446]
最新master分支上的idle.c文件中的rt_defunct_execute函数，该函数中有如下代码
```c
        while (rt_atomic_load(&(thread->ref_count)))
        {
            rt_thread_delay(5);
        }
```

## 问题：
1，此处循环原子读ref_count是想达到什么目的呢，在idle线程初始化里面ref_count初始化为0，所以不会进入该循环，这里正确用法是什么呢，若此值非0，是不是在其他线程里面会一直减这个ref_count呢？
2，非0情况下，idle线程就主动sleep，这里不是就挂起idle线程了吗，idle是允许被挂起的吧

**Comment by FragrantRye** [comment]
看起来是想实现一个让权等待，但是本来都在idle线程里了，让给谁呢？

**Comment by BernardXiong** [comment]
哎，是有问题的，是bug

![image](https://github.com/RT-Thread/rt-thread/assets/1241087/bdab87db-7533-4f62-8b0c-40b28f725080)

**Comment by xqyjlj** [comment]
这是之前调试自旋锁的时候加的线程引用计数（防止释放线程的时候引用计数没释放干净），正常情况下线程ref进这里是0的。我下一个版本把线程引用计数删掉好了
