### ISSUE TITLE
rt-smart如何下载

### ISSUE THREAD

**Issue by LearnigF** [RT-Thread/rt-thread#8462]
hello 我发现之前的rt-smart分支被删除了，请问现在该如何下载rt-smart的源码，另外支持riscv qemu的工具链的下载链接也失效了，请问什么时候可以重新支持。非常感谢

**Comment by runsunlg** [comment]
我的理解:从5.0版本开始，smart已经合入主线了。下载最新代码通过配置就可以变成smart了。

**Comment by mysterywolf** [comment]
是的

> 我的理解:从5.0版本开始，smart已经合入主线了。下载最新代码通过配置就可以变成smart了。

**Comment by BernardXiong** [comment]
> 我的理解:从5.0版本开始，smart已经合入主线了。下载最新代码通过配置就可以变成smart了。

✔

**Comment by LearnigF** [comment]
非常感谢
