### ISSUE TITLE
问一下rt-thread商用问题

### ISSUE THREAD

**Issue by fghjhuang** [RT-Thread/rt-thread#855]
你好，我想问一下RT-thread是不是能免费使用到商业项目中去，需不需要想ucos那样进行收费的，虽然是开源；当然我指的是正常智能硬件IOT那些产品，不是什么违法硬件商品

**Comment by BernardXiong** [comment]
可以呀。

rt-thread的license接近于LGPL，对于rt-thread发布本身的修改需要开源出来。自己的代码不需要开源出来。相应的也没有费用。

当然，这样的许可方式rt-thread也不会为你的使用，产品承担任何的责任。

**Comment by fghjhuang** [comment]
就是我直接使用rt-thread来用到我的智能硬件项目的话，如果我没有修改rt-thread的源代码，只是使用它的功能，我是不需要开源自己的项目，然后直接使用到商业项目里面去就可以了，对吧？

**Comment by aric1987** [comment]
@BernardXiong 如果我自己编写的驱动是不是也需要开源呢？

**Comment by BernardXiong** [comment]
@aric1987 希望更多的人贡献出自己的代码出来，特别是和这类基础特性相关的。

当然，如果是你自己编写的驱动，而不是更改当前已有的驱动，是可以不开源出来。
