### ISSUE TITLE
关于在mpc5744上移植rtthread

### ISSUE THREAD

**Issue by wumingxu10** [RT-Thread/rt-thread#8552]
mpc5744 相关信息：https://www.nxp.com.cn/products/processors-and-microcontrollers/power-architecture/mpc5xxx-microcontrollers/ultra-reliable-mpc57xx-mcus/ultra-reliable-mpc574xp-mcu-for-automotive-and-industrial-safety-applications:MPC574xP
在rtthread libcpu中对于powerpc架构的支持内容较少，想问一下官方目前是否有这方面的开发安排？

**Comment by BernardXiong** [comment]
这个是面向车的芯片吧？目前从RT-Thread社区团队的角度来说，会更多考虑通用性芯片支持

欢迎有社区开发者或芯片厂商来贡献
