### ISSUE TITLE
[spi]spi总线挂载多个设备时可能通信失败

### ISSUE THREAD

**Issue by yangpengya** [RT-Thread/rt-thread#8556]
多个spi设备挂载在同一总线上并使用同一spi模式时，后续挂载的设备不能有效初始化cs_pin，导致通信可能失败。关联PR #6933 #6961 #7650

**Comment by mysterywolf** [comment]
欢迎提交PR~

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/9503
