### ISSUE TITLE
使用DUO开发板，编译RT-Thread大核时编译不过

### ISSUE THREAD

**Issue by Charles-De-Geulle-Goah** [RT-Thread/rt-thread#8732]
如图，进入cv18xx_risv目录下使用scons编译大核时编译报错，没有生成Image.gz,但是有Image生成
![微信图片_20240407104005](https://github.com/RT-Thread/rt-thread/assets/67092035/5b3cbd0b-477e-4a5e-bb80-b446fa1611c8)

![微信图片_20240407104013](https://github.com/RT-Thread/rt-thread/assets/67092035/3dd4d806-a9c0-4f49-bbd5-8fc4028f347f)

**Comment by flyingcys** [comment]
1、请根据对应bsp目录下的readme安装依赖
2、请提供操作系统版本

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/8734 再试试？
