### ISSUE TITLE
目前不使用设备树的aarch64 BSP不能使用PSCI方案管理CPU，能否针对这种情况做一下兼容呢？

### ISSUE THREAD

**Issue by liYony** [RT-Thread/rt-thread#8783]
目前aarch64的BSP在搞设备树来进行系统的初始化，但是目前仓库里面还有一些BSP并没有适配支持设备树，比如对于PSCI的使用，现在也只能在这些支持了设备树的BSP下使用，如果BSP没有支持设备树，将无法对PSCI进行相应的初始化(因为psci初始化的api是在设备树的probe函数中执行的)。

libcpu/aarch64/common/psci.c

```c
static rt_err_t psci_probe(struct rt_platform_device *pdev)
{
    rt_err_t err;

    err = psci_ofw_init(pdev);

    return err;
}

static const struct rt_ofw_node_id psci_ofw_ids[] =
{
    { .compatible = "arm,psci",     .data = psci_0_1_init },
    { .compatible = "arm,psci-0.2", .data = psci_0_2_init },
    { .compatible = "arm,psci-1.0", .data = psci_1_0_init },
    { /* sentinel */ }
};

static struct rt_platform_driver psci_driver =
{
    .name = "arm-psci",
    .ids = psci_ofw_ids,

    .probe = psci_probe,
};
```

甚至，如果没有打开RT_USING_OFW宏，PSCI相关的代码都不会被编译。

libcpu/aarch64/common/SConscript

```python
Import('rtconfig')

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp') + Glob('*.S')
CPPPATH = [cwd]

if GetDepend('RT_USING_OFW') == False:
    SrcRemove(src, ['setup.c', 'cpu_psci.c', 'psci.c'])

if GetDepend('RT_USING_PIC') == True:
    SrcRemove(src, ['gicv3.c', 'gic.c', 'gtimer.c', 'interrupt.c'])

group = DefineGroup('libcpu', src, depend = [''], CPPPATH = CPPPATH)
.....
```

**Comment by liYony** [comment]
> 后边应该还是慢慢往 OFW 的方向演化吧。
> 
> 如果为了兼容，建议是旧的 bsp 目录下自定义一个 psci 0.2 标准的初始化函数，不修改 ofw 吧。

主要是这个初始化函数跟psci.c文件中的变量相关，这个初始化函数可能需要留在psci.c这个文件中。我明天看看怎么搞一下，提个pr看一下。

**Comment by liYony** [comment]
我搞了一下，如果想要在原基础上修改psci.c文件来单独搞出来一个初始化函数的话必须要删除SConscript中的下面一段代码(确保psci.c可成功编译)：

libcpu/aarch64/common/SConscript

```python
# if GetDepend('RT_USING_OFW') == False:
#     SrcRemove(src, ['setup.c', 'cpu_psci.c', 'psci.c'])
```

这样子搞下去我感觉确实**不是很合理**。

> 后边应该还是慢慢往 OFW 的方向演化吧。
> 
> 如果为了兼容，建议是旧的 bsp 目录下自定义一个 psci 0.2 标准的初始化函数，不修改 ofw 吧。

你的这个建议，我认为还是会存在一些问题：

- psci的初始化函数本质上上是在给psci.c文件中的一些static变量赋值，所以在bsp目录下实现初始化函数貌似不可行。
- 并且在没有打开RT_USING_OFW宏的情况下，psci.c文件没有被编译，那里面的API是无法调用的。

就目前的情况，我这边还有一个思路：就是在libcpu/aarch64/common目录下新增一个类似psci_nodt.c这样的一个文件，专门服务于没有设备树的BSP，其文件里面的代码可参考psci.c进行实现。并且修改一下SConscript文件：

```python
if GetDepend('RT_USING_OFW') == False:
    SrcRemove(src, ['setup.c', 'cpu_psci.c', 'psci.c'])
else:                                 # new add
    SrcRemove(src, ['psci_nodt.c'])   # new add
```

这样做可能会导致libcpu/aarch64/common下代码冗余(psci.c和psci_nodt.c会异常相似)，但是我目前暂时想不到什么比较好的解决方案了。等集思广益！

**Comment by polarvid** [comment]
直接 cp 一份 psci.c 到 bsp 目录下面，再做一些修改应该是可以的吧？类似于这个模式 [`bsp/phytium/libraries/common/fpsci.c`](https://github.com/RT-Thread/rt-thread/blob/master/bsp/phytium/libraries/common/fpsci.c)

**Comment by GuEe-GUI** [comment]
平台是不支持设备树吗？为什么不能使用设备树呢？
