### ISSUE TITLE
duo : pinmux: 管脚复用的功能支持

### ISSUE THREAD

**Issue by unicornx** [RT-Thread/rt-thread#8934]
这是一个需求：

目前针对 duo 系列产品的管脚复用的 Kconfig 机制还不完善，希望能够优先支持。

- https://github.com/flyingcys/rt-thread/issues/14
- https://github.com/flyingcys/rt-thread/issues/17
- https://github.com/flyingcys/rt-thread/issues/18
- https://github.com/flyingcys/rt-thread/issues/19
- https://github.com/flyingcys/rt-thread/issues/27

**Comment by BernardXiong** [comment]
@liYony 目前设备树中是否包括了pinctrl的支持？未来duo上可以更多走设备树的方式？

**Comment by liYony** [comment]
> @liYony 目前设备树中是否包括了pinctrl的支持？未来duo上可以更多走设备树的方式？

关于这块明天社区会议可以讨论一下

**Comment by unicornx** [comment]
I2C part: https://github.com/flyingcys/rt-thread/issues/14

**Comment by unicornx** [comment]
All related stuff have been fixed with #9188 and #9196. Closed this issue.
