### ISSUE TITLE
不能同时使用两个i2c设备

### ISSUE THREAD

**Issue by JcZou** [RT-Thread/rt-thread#894]
如下，同时注册两个i2c设备，i2c1和i2c2.
device_i2c_init("i2c1");
device_i2c_init("i2c2");

如果同时注册两个i2c设备的话，先注册的设备将不能使用，比如上面这种情况，i2c1设备将因为i2c2设备的注册而无法使用。
而分别单独注册的话，则i2c设备功能正常。
请问是否在代码中有进行限定，同一时间只能使用一个总线设备？

**Comment by BernardXiong** [comment]
@aozima Please check this issue.

**Comment by JcZou** [comment]
感谢熊大 & aozima, 问题已经解决，是我自己代码的问题。
i2c_dev里面两个i2c总线设备share了一个stm32_i2c2_bit_ops导致的问题
