### ISSUE TITLE
..\..\..\components\drivers\ipc\completion.c文件缺失

### ISSUE THREAD

**Issue by nesa1978** [RT-Thread/rt-thread#8948]
在编译BSP中示例时报错"no source": Error:  #5: cannot open source input file "..\..\..\components\drivers\ipc\completion.c": No such file or directory，找到对应的路径下没有对应的文件
![image](https://github.com/RT-Thread/rt-thread/assets/133783979/5d8f14bb-7a29-48ca-978b-311f62b805eb)
![image](https://github.com/RT-Thread/rt-thread/assets/133783979/9552ff29-c0ce-41b7-be35-0ef2e8dc4be2)

**Comment by Yumbrella** [comment]
佬解决了吗

**Comment by nesa1978** [comment]
> 佬解决了吗
下载旧版本的Rtthread就行了5.0.1和5.0.2都可以

**Comment by BernardXiong** [comment]
改名调整了，需要重写刷新下工程文件吧

**Comment by guanjianhe** [comment]
1. 在工程删除 completion.c 文件
2. 添加 completion_comm.c completion_up.c condvar.c 3个文件
3. 添加cpu_up.c 文件 @nesa1978 @Yumbrella

**Comment by mysterywolf** [comment]
重新用env 用命令 scons --target=mdk5即可

**Comment by dujunqiu** [comment]
我还奇怪官方例程怎么缺少.c文件

**Comment by shandianchengzi** [comment]
> scons --target=mdk5

 scons --target=mdk5解决的

**Comment by dujunqiu** [comment]
这里有修改说明
https://blog.csdn.net/dujunqiu/article/details/139826672?spm=1001.2014.3001.5501

**Comment by Fcheng-1** [comment]
STM32L4系列的library库里面，都没有L4的HAL库，还得手动添加，建议代码，keil工程提交，先编译一下能否编过。
