### ISSUE TITLE
在rtthread studio建立v5.1.0的工程不能用

### ISSUE THREAD

**Issue by logeexpluoqi** [RT-Thread/rt-thread#8981]
用rttrhead studio建立v5.1.0工程出现了applications和drivers以及components、src下的文件以及文件夹没有添加构建的问题。
在手动添加构建后会出现很多编译报错，以及找不到ResetHandler的警告

![image](https://github.com/RT-Thread/rt-thread/assets/50949439/f3c033af-2b02-418d-bc58-a441dc3ca4af)
![image](https://github.com/RT-Thread/rt-thread/assets/50949439/154ba272-db86-47d7-bd1c-ba752b5d86a1)

**Comment by Rbb666** [comment]
https://github.com/RT-Thread-Studio/sdk-rt-thread-source-code/pull/15
