### ISSUE TITLE
qemu-vexpress-a9 中使用c++出错

### ISSUE THREAD

**Issue by messigogogo** [RT-Thread/rt-thread#8983]
我在使用qemu-vexpress-a9和qemu-virt64-aarch64编译c++文件后，启动时出现如下报错
使用的编译链分别是arm-linux-musleabi_for_x86_64-pc-linux-gnu / aarch64-linux-musleabi_for_x86_64-pc-linux-gnu

**Comment by messigogogo** [comment]
![ddd83843a7721e92545406dd72aba52](https://github.com/RT-Thread/rt-thread/assets/103986797/9fc9fd11-8187-478d-8795-1a629a58be73)

![4b7e390daa94aeb029960e64379d4e0](https://github.com/RT-Thread/rt-thread/assets/103986797/778069c7-603b-46c7-bbd6-d9f4c0f1902b)

![ac63b4863cf2e7f89f5a69f4868d3e2](https://github.com/RT-Thread/rt-thread/assets/103986797/a0387330-48af-4739-aa2a-bc3ed71525ff)

![e2684d9276fc6055bd6ec2f7e19d302](https://github.com/RT-Thread/rt-thread/assets/103986797/0ee1c521-fa38-4e1b-9bd7-d73cd07ff1c8)

aarch64在开启C++后需要修改link.lds.S 中的__ctors_start   ->  __ctors_start__    ;   __ctors_end ->__ctors_end__
该编译链在pthread上定义有冲突，暂时删去了RT_USING_PTHREADS配置保证可以编译过。现象如上图所示

**Comment by BernardXiong** [comment]
是不是也和工具链版本相关？另外，arm-linux-musleabi_for_x86_64-pc-linux-gnu 更多是和smart相关。可以多试试aarch64-none-elf工具链

**Comment by messigogogo** [comment]
> 是不是也和工具链版本相关？另外，arm-linux-musleabi_for_x86_64-pc-linux-gnu 更多是和smart相关。可以多试试aarch64-none-elf工具链

您好，我刚才在64位试了一下aarch64-none-elf，没有发生以上问题，可以正常启动。
1.这个工具链是不支持C++11吗？开启C++11编译不过？如果要使用C++11,需要使用什么工具链？
2.rt-smat是否支持C++，使用aarch64-none-elf编译不过rt-smart。

**Comment by messigogogo** [comment]
@BernardXiong
