### ISSUE TITLE
[Bug]  bsp/cvitek, adc driver is not completed

### ISSUE THREAD

**Issue by unicornx** [RT-Thread/rt-thread#9025]
### RT-Thread Version

master

### Hardware Type/Architectures

bsp/cvitek

### Develop Toolchain

GCC

### Describe the bug

Reading the code `bsp/cvitek/drivers/drv_adc.c`, currently only adc1 is supported, but in fact the chip supports 2 controllers and up to 6 adc inputs.

**Comment by unicornx** [comment]
已经 reasign 给 Z8MAN8

**Comment by unicornx** [comment]
请注意另一个 pr：#9191. 这个 issue 的改动需要基于它。

**Comment by Z8MAN8** [comment]
我可以负责推进
