### ISSUE TITLE
官方ART-Pi media io不工作

### ISSUE THREAD

**Issue by nicholas-zww** [RT-Thread/rt-thread#9081]
### RT-Thread Version

5.1.0

### Hardware Type/Architectures

STM32H750

### Develop Toolchain

GCC

### Describe the bug

下载rt-thread 5.1.0， 去到bsp下stm32h750-artpi，menuconfig打开media io跟lvgl 8.3.0。编译下载到板子，什么也没有，屏幕黑黑，调试串口也没任何输出

**Comment by Rbb666** [comment]
谢谢反馈，等我测试下，再反馈给你

**Comment by Rbb666** [comment]
https://github.com/RT-Thread/rt-thread/pull/9130
