### ISSUE TITLE
[Feature] 内核中是否可以去掉结构体typedef定义的可行性

### ISSUE THREAD

**Issue by youzuwei** [RT-Thread/rt-thread#9180]
### Describe problem solved by the proposed feature

在内核中的结构体是否可以去掉typedef定义，因为现在结构体的typedef定义一致型不是很好，有些重新定义为了指针，有些只是重新命名，这对使用造成了一些困扰，也对代码的可读性和可维护型不是很友好；并且linux内核也是不推荐使用typedef。

**Comment by BernardXiong** [comment]
有一定的历史性，完全移除typedef可行性不大呢。

目前的方式是，内核部分延续之前的方式，一些内核对象typedef后是指针；内核以外的组件，尽可能不使用typedef的方式。
