### ISSUE TITLE
[Bug] cvitek adc spi wdt 驱动中，局部函数收敛

### ISSUE THREAD

**Issue by Z8MAN8** [RT-Thread/rt-thread#9198]
### RT-Thread Version

master

### Hardware Type/Architectures

bsp/cvitek

### Develop Toolchain

GCC

### Describe the bug

`bsp/cvitek/drivers/drv_adc.h drv_spi.h drv_wdt.h` 中外设的相关局部函数不会被外部调用，应该把 static 函数从头文件移到对应的源文件中

**Comment by Z8MAN8** [comment]
@unicornx

**Comment by unicornx** [comment]
"收敛" 这个词太抽象了，直接说“ 把 static 函数从头文件移到源文件” 即可
