### ISSUE TITLE
[Feature] PR #9194 存在问题 | Unresolved thread on PR #9194

### ISSUE THREAD

**Issue by polarvid** [RT-Thread/rt-thread#9210]
### Describe problem solved by the proposed feature

存在未消解的 Change Request。需要给出合理拒绝理由，或进行正确修改。

https://github.com/RT-Thread/rt-thread/pull/9194

另外，强烈质疑维护者不解决问题的作风。我是不是可以认为主线上 PR 的 review 过程本质是可有可无的。
同理可得，以后我们提交 PR 也不需要关心 Review 。毕竟合并就是这样随心所欲的行为。

**Comment by unicornx** [comment]
以后 PR 上 reviewer 提出的问题，建议 PR 的 author 都必须给予答复，accept OR reject，没有答复就开始重新提交是一种不礼貌的行为。

**Comment by BernardXiong** [comment]
这块存在问题的，都有change req的标记了，还合并了？

**Comment by BernardXiong** [comment]
> 以后 PR 上 reviewer 提出的问题，建议 PR 的 author 都必须给予答复，accept OR reject，没有答复就开始重新提交是一种不礼貌的行为。

感觉这类都不是礼貌不礼貌的问题了，而是是否是合规性行为。
