### ISSUE TITLE
[Bug] USB UAC1 is not working with smartphone.

### ISSUE THREAD

**Issue by barfiii** [RT-Thread/rt-thread#9214]
### RT-Thread Version

3.1.3

### Hardware Type/Architectures

Rockchip

### Develop Toolchain

GCC

### Describe the bug

The USB UAC1 device is not functioning properly with Smartphones, while it is working as expected with a PC. The USB UAC1 device is not being detected as earphones after connecting it to a mobile device. However, if you manually restart the smartphone after connecting it to the device, it starts working. What could be the problem?

**Comment by BernardXiong** [comment]
There is no RK bsp on RTT 3.1.x series.

**Comment by SKrishna004** [comment]
> There is no RK bsp on RTT 3.1.x series.
> 

I'm talking about this **bsp/rockchip/rk2108**

**Comment by barfiii** [comment]
I'm talking about **bsp/rockchip/rk2108**

**Comment by BernardXiong** [comment]
Hi Barfiii,
There is no usb driver under rockchip bsp. Therefore, this issue is closed.
