### ISSUE TITLE
[Bug] bsp/qemu-virt64-riscv/SConstruct 中的 stack_size 问题

### ISSUE THREAD

**Issue by unicornx** [RT-Thread/rt-thread#9232]
### RT-Thread Version

master

### Hardware Type/Architectures

bsp/qemu-virt64-riscv

### Develop Toolchain

GCC

### Describe the bug

`bsp/qemu-virt64-riscv/SConstruct`

```python
stack_lds = open('link_stacksize.lds', 'w')
if GetDepend('__STACKSIZE__'): stack_size = GetDepend('__STACKSIZE__')
stack_lds.write('__STACKSIZE__ = %d;\n' % stack_size)
stack_lds.close()
```   

这里  `stack_size = GetDepend('__STACKSIZE__')` 是有何用意？GetDepend 返回值是 False

不过看上去 `GetDepend('__STACKSIZE__')` 一直返回的是 False，倒也没做什么。但是这个引入一个问题就是 `__STACKSIZE__` 的配置修改在 `bsp/qemu-virt64-riscv/link_stacksize.lds` 中不会起作用。

这个类似问题在很多 risv64 的项目中都存在，估计是抄过去的。

```shell
$ find -name "SConstruct" | xargs grep -wn "GetDepend('__STACKSIZE__')"
./allwinner/d1/SConstruct:58:if GetDepend('__STACKSIZE__'): stack_size = GetDepend('__STACKSIZE__')
./allwinner/d1s/SConstruct:96:if GetDepend('__STACKSIZE__'): stack_size = GetDepend('__STACKSIZE__')
./k210/SConstruct:31:if GetDepend('__STACKSIZE__'): stack_size = GetDepend('__STACKSIZE__')
./qemu-virt64-riscv/SConstruct:37:if GetDepend('__STACKSIZE__'): stack_size = GetDepend('__STACKSIZE__')
./bouffalo_lab/bl808/d0/SConstruct:47:if GetDepend('__STACKSIZE__'): stack_size = GetDepend('__STACKSIZE__')
./cvitek/cv18xx_risc-v/SConstruct:30:if GetDepend('__STACKSIZE__'): stack_size = GetDepend('__STACKSIZE__')
./juicevm/SConstruct:31:if GetDepend('__STACKSIZE__'): stack_size = GetDepend('__STACKSIZE__')
```

**Comment by polarvid** [comment]
`__STACKSIZE__` 是 bsp 下面的 Kconfig 里面定义的配置项目。这里就是尝试读取这个配置，然后写入链接脚本里面。

![image](https://github.com/user-attachments/assets/426da946-c325-4b89-b517-877c3841b3ed)

**Comment by unicornx** [comment]
> `__STACKSIZE__` 是 bsp 下面的 Kconfig 里面定义的配置项目。这里就是尝试读取这个配置，然后写入链接脚本里面。
> 
> ![image](https://private-user-images.githubusercontent.com/65584760/350871391-426da946-c325-4b89-b517-877c3841b3ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzY2NzgsIm5iZiI6MTcyMTYzNjM3OCwicGF0aCI6Ii82NTU4NDc2MC8zNTA4NzEzOTEtNDI2ZGE5NDYtYzMyNS00Yjg5LWI1MTctODc3YzM4NDFiM2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA4MTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMGFlMmIwZTM5ZGQzNDQ2YmQ5Y2I3MjM1NjdmYmNmMzRlOTFlZjk3N2Y4NTUyYzQ4MThhOTE1NDUwMjYwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VkwDBGzzhL3MfL08dXvbs1W2lQH6w_YBStKxDL9q_XQ)
> 
> ![image](https://private-user-images.githubusercontent.com/65584760/350872832-6aba450b-7830-4862-935d-4e2aabe243f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzY2NzgsIm5iZiI6MTcyMTYzNjM3OCwicGF0aCI6Ii82NTU4NDc2MC8zNTA4NzI4MzItNmFiYTQ1MGItNzgzMC00ODYyLTkzNWQtNGUyYWFiZTI0M2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA4MTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhN2IxZTExZDZhYThkZTAwMmQwYjNkM2QzNmNlYjU1NDA2YTJhNzVjNTlmNjliMjQ4NzRlODhiMDNiMDk4YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FdKPksEWPKBMOo_xTM_jYngq-plUzW55tCMsT1e5fCQ)

代码能看明白，但是逻辑我觉得是写错了。

**Comment by polarvid** [comment]
> 代码能看明白，但是逻辑我觉得是写错了。

我本地上看是没什么问题的。验证如下。

1. 修改配置 stack size 为 32KB

![image](https://github.com/user-attachments/assets/52431eed-3620-4902-b38a-45759b0fd12e)

2. 查看读取的配置 size

![image](https://github.com/user-attachments/assets/6cd03cac-1215-4d7c-b78f-d34ff0f91f01)

3. 验证链接脚本的 stack size

![image](https://github.com/user-attachments/assets/d947a12d-4040-4787-bd63-121a2214bf85)

**Comment by unicornx** [comment]
sorry，我发现描述错误，这个问题只存在于 bsp/cvitek/cv18xx_riscv 中。已经另外提了一个 issue #9237 来跟踪。

关闭此 issue。
