### ISSUE TITLE
[Bug] bsp/cvitek: 某些 配置宏名称不符合规范，需要改进

### ISSUE THREAD

**Issue by unicornx** [RT-Thread/rt-thread#9239]
### RT-Thread Version

master

### Hardware Type/Architectures

bsp/cvitek/

### Develop Toolchain

GCC

### Describe the bug

参考 https://github.com/RT-Thread/rt-thread/pull/9222#discussion_r1685431577

**Comment by Z8MAN8** [comment]
我可以负责推进

**Comment by unicornx** [comment]
> 我可以负责推进

Thanks, re-assigned to you.
