### ISSUE TITLE
[Bug] bsp/cvitek cv18xx_risc-v IRQ_MAX_NR num error

### ISSUE THREAD

**Issue by Z8MAN8** [RT-Thread/rt-thread#9259]
### RT-Thread Version

master

### Hardware Type/Architectures

bsp/cvitek

### Develop Toolchain

GCC

### Describe the bug

cv18xx_risc-v 的 IRQ_MAX_NR 值错误，当前配置为 64，datasheet 中的正确值为 101，错误的IRQ_MAX_NR会导致大于其值的中断号注册失败

**Comment by Z8MAN8** [comment]
@unicornx

**Comment by unicornx** [comment]
assigned to you @Z8MAN8 , thanks

**Comment by unicornx** [comment]
我发现对于小核 C906L，IRQ_MAX_NR 的值也不正常。而且小核的 `bsp/cvitek/c906_little/board/interrupt.h` 中也定义了一个同名的 IRQ_MAX_NR，貌似是重名了？

可以一个 PR 改掉，但需要两个 commit，一个 for c906B, 一个 for c906L, 这样分开会比较清楚。
