### ISSUE TITLE
[Bug] FAL头文件可能会污染ulog

### ISSUE THREAD

**Issue by kaidegit** [RT-Thread/rt-thread#9279]
### RT-Thread Version

master

### Hardware Type/Architectures

h750

### Develop Toolchain

GCC

### Describe the bug

引入或间接引入会导致log_d等api受到污染

在程序中定义LOG_TAG后引入ulog后再引入fal，或是先引入fal再定义LOG_TAG引入ulog，均会导致log_d等小写api使用FAL的log

![image](https://github.com/user-attachments/assets/378b32dc-4137-457c-a595-5f8dd75a54c1)
![image](https://github.com/user-attachments/assets/6f8abbcb-350d-43be-b362-444de86b9b3b)
![image](https://github.com/user-attachments/assets/d37b68f9-a7e1-493c-b1ba-87bea4b61495)

**Comment by wdfk-prog** [comment]
调换一下顺序,这一块放到最后
```c
#define LOG_TAG              "example"
#define LOG_LVL              LOG_LVL_DBG
#include <ulog.h>
```

**Comment by kaidegit** [comment]
唔似乎要求在包含fal之前的头文件都没有包含过ulog，否则最下面的包含ulog直接就被忽略了，也不是很友好

**Comment by BernardXiong** [comment]
或者这类是否有好的解决办法，大家可以多想想

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/9690
