### ISSUE TITLE
[Bug] rt_thread_mdelay 不是延时的ms，是systick的时钟周期的和rt_thread_delay函数没区别

### ISSUE THREAD

**Issue by UFO281** [RT-Thread/rt-thread#9300]
### RT-Thread Version

V4.02

### Hardware Type/Architectures

STM32F103

### Develop Toolchain

RT-Thread Studio

### Describe the bug

[Bug] rt_thread_mdelay 不是延时的ms，是systick的时钟周期的和rt_thread_delay函数没区别

### Other additional context

/**
 * This function will let current thread delay for some milliseconds.
 *
 * @param tick the delay time
 *
 * @return RT_EOK
 */
rt_err_t rt_thread_mdelay(rt_int32_t ms)
{
    rt_tick_t tick;

    tick = rt_tick_from_millisecond(ms);

    return rt_thread_sleep(tick);
}

**Comment by mysterywolf** [comment]
为什么呢 中间有rt_tick_from_millisecond换算的

**Comment by ComerLater** [comment]
会将ms转为tick，最终延时是tick
