### ISSUE TITLE
[Feature] [AT32] 希望 AT32 的以太网驱动能支持 LAN8720A

### ISSUE THREAD

**Issue by dongly** [RT-Thread/rt-thread#9309]
### Describe problem solved by the proposed feature

希望 AT32 的以太网驱动能支持 LAN8720A,之前曾经自己移植过, 但不能通信, 希望官方能支持一下. 谢谢! 
@sheltonyu

**Comment by sheltonyu** [comment]
可以，等有空了来适配一下。
谢谢反馈

**Comment by dongly** [comment]
谢谢发自我的荣耀手机-------- 原始邮件 --------发件人： sheltonyu ***@***.***>日期： 2024年8月15日周四 16:55收件人： RT-Thread/rt-thread ***@***.***>抄送： dongly ***@***.***>, Author ***@***.***>主    题： Re: [RT-Thread/rt-thread] [Feature] [AT32] 希望 AT32 的以太网驱动能支持 LAN8720A (Issue #9309)
可以，等有空了来适配一下。
谢谢反馈

**Comment by dongly** [comment]
#9376
