### ISSUE TITLE
[Bug] Useless assignment operation in bsp/cvitek/cv18xx_risc-v/SConstruct

### ISSUE THREAD

**Issue by unicornx** [RT-Thread/rt-thread#9349]
### RT-Thread Version

master

### Hardware Type/Architectures

bsp/cvitek/cv18xx_risc-v/

### Develop Toolchain

GCC

### Describe the bug

`bsp/cvitek/cv18xx_risc-v/SConstruct` 中以下赋值操作看上去是没有用的，反而容易引起混淆

```python
rtconfig.CPU='virt64'
rtconfig.ARCH='risc-v'
```

`bsp/cvitek/cv18xx_risc-v/rtconfig.py`  中已经设置了 ARCH 和 CPU 如下：
```python
ARCH        ='risc-v'
VENDOR      ='t-head'
CPU         ='c906'
CROSS_TOOL  ='gcc'
```

**Comment by heyuanjie87** [comment]
估计是从virt那边复制过来的

**Comment by unicornx** [comment]
> 估计是从virt那边复制过来的

我猜是，后面我找个时间提个 PR 给它删掉

**Comment by BernardXiong** [comment]
支持！把一切不合理的东西给整理清楚掉！
