### ISSUE TITLE
[Bug] Uninit issue

### ISSUE THREAD

**Issue by SoftSec-Tech** [RT-Thread/rt-thread#9398]
### RT-Thread Version

187e69a698712c443c32f384d39f09ad191f5866

### Hardware Type/Architectures

stm32

### Develop Toolchain

GCC

### Describe the bug

1. Uninit issue in line 440 https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/libraries/HAL_Drivers/drivers/drv_gpio.c 
2. Detected by Static Analysis tool - StatiCode,
![rt-thready-defect1](https://github.com/user-attachments/assets/99413ec2-6808-47c5-91f9-d3f97f1ceae0)
As in the screen shot, since there is the possibility that in step 7 - switch goes into default, so the GPIO_InitStruct.Mode is uninited, but it is used in the HAL_GPIO_INIT, thus caused an Uninit issue.

**Comment by mysterywolf** [comment]
Thanks  merged in https://github.com/RT-Thread/rt-thread/pull/9532
