### ISSUE TITLE
[Feature] Sensor types 增加 RT_SENSOR_CLASS_POWER类型

### ISSUE THREAD

**Issue by CYFS3** [RT-Thread/rt-thread#9399]
### Describe problem solved by the proposed feature

我在修复软件包`ina226`时候发现他在使用设备框架注册的类型是`RT_SENSOR_CLASS_POWER`，但是`Sensor types`中并没有这个类型，是不是在什么版本抛弃了这个定义。

### Describe your preferred solution

* `Sensor types`中增加`RT_SENSOR_CLASS_POWER`
* `Sensor unit types `中添加`RT_SENSOR_UNIT_MA`

### Describe possible alternatives

或者修改软件包`ina226`的设备类型为`RT_SENSOR_CLASS_NONE`

**Comment by kurisaW** [comment]
先确定他用的是哪个sensor版本，sensor.h或者sensor_v2.h中都找下看看有没有这个定义

**Comment by CYFS3** [comment]
> 先确定他用的是哪个sensor版本，sensor.h或者sensor_v2.h中都找下看看有没有这个定义

v2的命名应该是 RT_SENSOR_TYPE*来命名的，所以使用的一个是sensor
