### ISSUE TITLE
[Bug] cortex a7 soc 串口无法正常使用

### ISSUE THREAD

**Issue by baidxi** [RT-Thread/rt-thread#9476]
### RT-Thread Version

v5.1.x - last

### Hardware Type/Architectures

全志t113-s3

### Develop Toolchain

GCC

### Describe the bug

使用lts v4.1.x串口正常（在SPL中已初始化完成），在rt_hw_uart_init中将串口添加进系统，能正常使用。
使用v5.1.x之后的版本，串口无法正常工作 。使用trace32看了相关的时钟和配置都没有问题。
表现为发送fifo一直处于busy状态，手动重置了fifo时钟，fifo还一直是busy状态，不能发送数据。

**Comment by BernardXiong** [comment]
并没有T113的BSP啊

**Comment by baidxi** [comment]
> 并没有T113的BSP啊

我自己添加的，把相同的代码放到lts-v4.1.x上面正常，v5之后串口无法正常使用。
