### ISSUE TITLE
[Bug] [ymodem] last frame's data_sz issue. (soh, stx)

### ISSUE THREAD

**Issue by sulfurandcu** [RT-Thread/rt-thread#9479]
### RT-Thread Version

trunk

### Hardware Type/Architectures

all

### Develop Toolchain

Microsoft VScode

### Describe the bug

when ymodem receiving last frame in function _rym_do_fin(), 
in my opinion:
- if code is SOH, it should receive another `_RYM_SOH_PKG_SZ-1` long data,
- if code is STX, it should receive another `_RYM_STX_PKG_SZ-1` long data,

but now it will receive `_RYM_SOH_PKG_SZ-1` no matter what code is.
is there a bug or is the design like this?

![图片](https://github.com/user-attachments/assets/e5d4c934-e3d7-4d16-813b-e4502239d535)

**Comment by mysterywolf** [comment]
Could you submit a PR please?

**Comment by sulfurandcu** [comment]
> Could you submit a PR please?

see #9510
