### ISSUE TITLE
[Feature] 后期是不是可以考虑将bsp独立出来，使用一个单独的仓库管理，当前仓库仅保留内核和组件。

### ISSUE THREAD

**Issue by sulfurandcu** [RT-Thread/rt-thread#9519]
### Describe problem solved by the proposed feature

当前仓库过于庞大

### Describe your preferred solution

- rt-thread repo
- bsp repo
  - stm32
  - gd32
  - ...
  - linkto → rt-thread

例如这个仓库：https://github.com/sisong/HPatchLite/tree/main

**Comment by heyuanjie87** [comment]
支持

**Comment by mysterywolf** [comment]
我们会逐步将HAL库独立出来 但是BSP不会独立出去。
