### ISSUE TITLE
[Bug] at框架获取信号量超时错误判断

### ISSUE THREAD

**Issue by Bluebear233** [RT-Thread/rt-thread#9572]
### RT-Thread Version

5.2

### Hardware Type/Architectures

stm32f407-atk-explorer

### Develop Toolchain

GCC

### Describe the bug

测试环境说明：使用AT组件&ESP8266软件包&RTT_OTA下载

MSH执行http_ota时候，msh线程跑在at_socket.c的at_recvfrom函数下等待sock->recv_notice信号量
![1](https://github.com/user-attachments/assets/cbae0e05-38ed-4c3d-965d-d0dda0e6d878)

同时client_parser线程接收到数据就重置sock->recv_notice信号量
![2](https://github.com/user-attachments/assets/4f5a9945-9316-4780-b2ef-c0eeb957efe5)

导致等待信号量直接回!RT_EOK，最终数据接收超时，建议返回值改成-RT_ETIMEOUT
![3](https://github.com/user-attachments/assets/986e50fd-1dc2-4603-8e20-66de6b417792)

**Comment by kurisaW** [comment]
@Bluebear233 欢迎贡献PR！

**Comment by mysterywolf** [comment]
fixed：https://github.com/RT-Thread/rt-thread/pull/9615
