### ISSUE TITLE
[Bug] duo256m: RTT-Smart would raise `Load Page Fault` on boot

### ISSUE THREAD

**Issue by wychlw** [RT-Thread/rt-thread#9608]
### RT-Thread Version

7bf8589fad1c0406ed993025c9e7055ee6725619

### Hardware Type/Architectures

milkv-duo256m-sd (SOC SG2002)

### Develop Toolchain

GCC

### Describe the bug

The RTT-Smart with default config (change the addr to assert requirement, ofcourse) would get a Load Page Fault on boot. See screen record: [![asciicast](https://asciinema.org/a/2ezotkV7V7ukYTWLC3siS2LmX.svg)](https://asciinema.org/a/2ezotkV7V7ukYTWLC3siS2LmX)

After some digging, seems is commit 148e577 cause this problem. After revert it, all things works again: screen record [![asciicast](https://asciinema.org/a/lYWKFvJXL5Qp4xpomw2mtDHuw.svg)](https://asciinema.org/a/lYWKFvJXL5Qp4xpomw2mtDHuw)

### Other additional context

I've tried different vaddr, none of them work

**Comment by heyuanjie87** [comment]
参考我的bsp设置vaddr, https://github.com/heyuanjie87/bsp-MilkvDuo-xx

**Comment by wychlw** [comment]
> 参考我的bsp设置vaddr, https://github.com/heyuanjie87/bsp-MilkvDuo-xx

感谢！您的的确可以在duos和duo256m上工作。但是，master依然不行…（之前设置的实际上就是 `0xFFFFFFC000200000` ）

看起来问题更复杂了…

**Comment by heyuanjie87** [comment]
master上的duo riscv的驱动应该是还没支持smart的

**Comment by wychlw** [comment]
嗷！原来如此。谢谢您！

**Comment by shunyao666** [comment]
> master上的duo riscv的驱动应该是还没支持smart的
请问现在哪个分支已经支持了smart呢

**Comment by heyuanjie87** [comment]
https://github.com/heyuanjie87/bsp-MilkvDuo-xx
https://github.com/heyuanjie87/bsp-k230
这两个仓库都可以，还有master里的qemu bsp也可以

**Comment by unicornx** [comment]
#9657 已经 merge 了，请确认一下。如果没有问题请 close 这个 issue。

**Comment by wychlw** [comment]
> #9657 已经 merge 了，请确认一下。如果没有问题请 close 这个 issue。

DuoS 测试无问题，手上的Duo256暂时出问题了，等待别人测试中

**Comment by wychlw** [comment]
test pass, closing this issue
