### ISSUE TITLE
[Feature] RT-smart 支持 duo 系列

### ISSUE THREAD

**Issue by unicornx** [RT-Thread/rt-thread#9622]
### Describe problem solved by the proposed feature

目前 master 上的 duo 产品还不能跑 RT-smart，需要支持。

相关 issue 见 #9608。

**Comment by Guohezu001** [comment]
![image](https://github.com/user-attachments/assets/d91cb2e0-eeb9-4fa5-8bb0-fbb1ad2a4317)
刚刚测了一下，duo板子可以跑RT-smart

**Comment by unicornx** [comment]
> ![image](https://private-user-images.githubusercontent.com/157772539/386432010-d91cb2e0-eeb9-4fa5-8bb0-fbb1ad2a4317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NDAxMDAsIm5iZiI6MTczMTYzOTgwMCwicGF0aCI6Ii8xNTc3NzI1MzkvMzg2NDMyMDEwLWQ5MWNiMmUwLWVlYjktNGZhNS04YmIwLWZiYjFhZDJhNDMxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwMzAzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDZiMzgwZTM4OGY2MjY4YmEyM2IzMTA2NzRlNjQ3MDc1ZmQzNTU0MzBhZGU2MmUzMGYyYjQ5YTM4MTRkZGM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lsoBMeWBtPptJsMoQWb289RgAggYfnRK5Kx-bvJ_l5k) 刚刚测了一下，duo板子可以跑RT-smart

这不是 RT-smart，这是 标准版 RTT

RT-smart 启动的 logo 上有 Smart 字样如下：

![image](https://github.com/user-attachments/assets/c6cc9c26-7e96-4476-8e48-9078f45b14aa)

**Comment by unicornx** [comment]
> 这个 issue 可以由我来推进

#9657 已经 merge，目前 duo-S 还不支持，其他测试都正常。

**Comment by unicornx** [comment]
Verified duo/duo256m/duoS with commit c1166e0bf1.

Closed this issue.

Thanks all for your excellent contribution!
