### ISSUE TITLE
[Bug] print format looks werid when RT_DEBUGING_AUTO_INIT is open

### ISSUE THREAD

**Issue by unicornx** [RT-Thread/rt-thread#9671]
### RT-Thread Version

master

### Hardware Type/Architectures

bsp/cvitek/cv18xx_risc-v/

### Develop Toolchain

Other

### Describe the bug

enable RT_DEBUGING_AUTO_INIT 后，控制台上打印的格式比较混乱，建议改进：

![image](https://github.com/user-attachments/assets/8fed5d43-a488-4377-9a23-e56ae1d10613)

正常情况下，如果 init 函数中没有打印输出时，规整的输出是如下格式，例如：

```
initialize rti_board_end:0 done
```
但是一旦 init 函数中有打印输出，log 就比较混乱。譬如：
```
initialize mnt_initfile system initialization done!
:0 done
```
函数名 `mnt_init` 和打印 `file system initialization done!` 连在一起了，很容易搞混。

建议对打印统一在输出函数名后强制回车，然后另起一行打印输出结果。譬如：

```
initialize rti_board_end:
0 done
```
或者
```
initialize mnt_init
file system initialization done!
:0 done
```

这样看上去规整一些。

**Comment by BernardXiong** [comment]
这块似乎没什么好办法吧，或者有什么好的方法吗？

**Comment by unicornx** [comment]
> 这块似乎没什么好办法吧，或者有什么好的方法吗？

就是把打印格式改一下，看得规整点，现在内核中下面代码中的打印和 init 函数中中的打印连在一起了，加换行后至少可以分开

![image](https://github.com/user-attachments/assets/c72fee00-773f-4081-ac73-ee9fbdaba3f5)
