### ISSUE TITLE
[Feature] duo 支持在 RT-smart 上启动后自动挂载 rootfs（fat 格式）到 “/” 上

### ISSUE THREAD

**Issue by unicornx** [RT-Thread/rt-thread#9681]
### Describe problem solved by the proposed feature

在 #9622  的基础上实现 duo 支持启动后自动挂载 rootfs 到 “/” 上。

类似 linux，duo 采用 sd-card 驱动时，sd-card 的第二个分区一般用来存放 rootfs。

由于目前 userapps 只支持制作 fat 格式的，所以我们第一期也先支持 fat，等 ext4 就绪了我们再支持挂载 ext4.

**Comment by unicornx** [comment]
补充一些 backgroud info：

`bsp/cvitek/drivers/port/mnt_romfs.c` 这个文件是从 `bsp/bouffalo_lab/libraries/rt_drivers/port/mnt.c` 移植过来的。需要做进一步的清理，譬如 BSP_USING_ON_CHIP_FLASH 和 BSP_USING_ON_CHIP_FLASH_FS 相关的代码感觉都没有用的，可以删掉

原来你把 sd0 挂到 `/sdcard` 上感觉也没有必要。

**Comment by BernardXiong** [comment]
这样后续会越来越客制化了的，可以考虑把设备树用起来，先不考虑太多外设的情况，而是先把cpu，memory，console，rootfs 等配置参数通过设备树传递给内核

**Comment by unicornx** [comment]
> 这样后续会越来越客制化了的，可以考虑把设备树用起来，先不考虑太多外设的情况，而是先把cpu，memory，console，rootfs 等配置参数通过设备树传递给内核

好的，已建立长期 tracking issue #9707
