### ISSUE TITLE
[Bug] bsp/cvitek/cv18xx_aarch64 需要维护

### ISSUE THREAD

**Issue by unicornx** [RT-Thread/rt-thread#9694]
### RT-Thread Version

master

### Hardware Type/Architectures

bsp/cvitek/cv18xx_aarch64

### Develop Toolchain

GCC

### Describe the bug

bsp/cvitek 下的  cv18xx_aarch64 了？目前年久失修，如果没有人维护，我打算先将其标注为 unsupported, 如果再过段时间还是没有人出来认领的话，我就打算清理掉了

文档最好更新一下，确保使用者可以找到正确的 gcc，现在文档里没写清楚。另外 标准版和 smart 版既然都说支持了所以都需要提供一下

**Comment by Z8MAN8** [comment]
我可以认领

**Comment by liYony** [comment]
我这边认领

**Comment by liYony** [comment]
https://github.com/RT-Thread/rt-thread/pull/9749 已在此 pr 处理

**Comment by unicornx** [comment]
> #9749 已在此 pr 处理

这个 issue 涉及两个 PR：
- #9749 
- #9771

**Comment by liYony** [comment]
https://github.com/RT-Thread/rt-thread/pull/9835#issuecomment-2561683801

**Comment by unicornx** [comment]
> > #9749 已在此 pr 处理
> 
> 这个 issue 涉及两个 PR：
> 
> * [[bsp][cvitek] update the arm core project #9749](https://github.com/RT-Thread/rt-thread/pull/9749)
> * [rt_hw_spinlock_t cannot be found on single core include smp_call.h #9771](https://github.com/RT-Thread/rt-thread/pull/9771)

我已经 take over 这个 issue 并且在 #9835 中解决了，所以关闭了这两个 pr。
