### ISSUE TITLE
[Bug] [bsp][cvitek] 无法读取duo s的小核串口信息。

### ISSUE THREAD

**Issue by jiuyueshenhua** [RT-Thread/rt-thread#9698]
### RT-Thread Version

master

### Hardware Type/Architectures

duo s

### Develop Toolchain

Microsoft VScode

### Describe the bug

1. 使用scons --menuconfig选择duo s。

2. 烧录后读写到sd card。

3. 串口转USB连接 duo s的uart1

4. 执行sudo screen /dev/ttyUSB0 115200

上电后看不到任何字符。但同样的操作均能接受到大核串口传来的字符。

**Comment by flyingcys** [comment]
1. duos小核串口在uboot中重新pinmux为普通gpio了，处理方法：删除已经下载的cvitek_bootloader，重新编译小核后会自动下载最新版本的
2. 修改小核UART1_TX为JTAG_CPU_TMS，修改UART1_RX为JTAG_CPU_TCK
3. 重新编译运行即可正常显示小核串口日志，输入/输出均正常

**Comment by unicornx** [comment]
@jiuyueshenhua 请按照 issue 上的描述测试一下，如果可以 work ，我建议提个 pr 相应修改一下 readme，对 duoS 的小核 build 增加一个描述，这个 issue 就可以 close 了。

**Comment by jiuyueshenhua** [comment]
![image](https://github.com/user-attachments/assets/94bad732-d30a-46b6-94d6-dc55acb65f1d)
谢谢燕哥的努力，小核输出没问题了。

**Comment by unicornx** [comment]
> @jiuyueshenhua 请按照 issue 上的描述测试一下，如果可以 work ，我建议提个 pr 相应修改一下 readme，对 duoS 的小核 build 增加一个描述，这个 issue 就可以 close 了。

PR #9728 
已经提交对 readme 进行修改

**Comment by unicornx** [comment]
先不关闭，等 #9728 merge 后再关闭。
