### ISSUE TITLE
[Feature] 统一 riscv64 的 libcpu

### ISSUE THREAD

**Issue by unicornx** [RT-Thread/rt-thread#9743]
### Describe problem solved by the proposed feature

统一 riscv64 的 libcpu，把virt，c906等的都统一起来

该需求来源：https://github.com/RT-Thread/rt-thread/issues/8358#issue-2034418487

**Comment by polarvid** [comment]
我这边已经完成的里程碑如下：https://github.com/RT-Thread/rt-thread/issues/9151 。后面还有一些由其它开发者推进的 PR，目前来说基本已经完成和收尾了。
