### ISSUE TITLE
[Feature] Copyright Time Revision

### ISSUE THREAD

**Issue by RiceChen0** [RT-Thread/rt-thread#9765]
### Describe problem solved by the proposed feature

<img width="260" alt="d48e02c5be5abedbc28bac47de5af4f" src="https://github.com/user-attachments/assets/91a6411a-10c5-4742-9012-5ea8ebdf95fe">

这个版权时间是否需要修订

**Comment by supperthomas** [comment]
https://github.com/RT-Thread/rt-thread/blob/master/src/kservice.c

这个看上去已修改

**Comment by RiceChen0** [comment]
> https://github.com/RT-Thread/rt-thread/blob/master/src/kservice.c
> 
> 这个看上去已修改

关于这个问题，应该每次发版本的时候都要注意的，虽然最终修改了。准备2025年了。
