### ISSUE TITLE
[Bug] components\libc\compilers\common\include\dirent.h头文件中，libc_dirent结构体报错BUG

### ISSUE THREAD

**Issue by godmial** [RT-Thread/rt-thread#9833]
### RT-Thread Version

master

### Hardware Type/Architectures

gd32470z-lckfb

### Develop Toolchain

GCC

### Describe the bug

未对BSP做任何修改的前提下，使用scons命令生成的keil工程编译报错
![image](https://github.com/user-attachments/assets/3e14b923-33d1-43ea-b09e-0e6ce20bb40a)

报错定位
![image](https://github.com/user-attachments/assets/45d7739f-ee00-42d1-8bcf-c3d2eb10f26b)

屏蔽这个结构体成员之后编译可以通过
![image](https://github.com/user-attachments/assets/980da58b-13c9-49fe-9b3e-63b6a4b3ea45)
#9834

**Comment by godmial** [comment]
![image](https://github.com/user-attachments/assets/e8271219-598a-47f4-bcf3-0dc71c0a41ec)

已提交PR

**Comment by unicornx** [comment]
请把 issue 的 title 补充完整

**Comment by Rbb666** [comment]
> 
> ![image](https://github.com/user-attachments/assets/e8271219-598a-47f4-bcf3-0dc71c0a41ec)
> 
> 已提交PR

请在此issue或pr中互相关联下

**Comment by godmial** [comment]
#9834
