### ISSUE TITLE
stm32f10x_HAL uart3 的问题

### ISSUE THREAD

**Issue by joyhope** [RT-Thread/rt-thread#994]
bsp:  stm32f10x , console 在 uart1~ uart3 都正常的。
bsp:  stm32f10x_hal, console 在uart1, uart2 是正常的， 在uart3 上没有正常工作。 （没找到原因。）

**Comment by joyhope** [comment]
找到了， 

在 void rt_hw_usart_init(void) 里面，增加
	__HAL_RCC_GPIOB_CLK_ENABLE();

uart3 用了portB

**Comment by uestczyh222** [comment]
已pr修复

**Comment by uestczyh222** [comment]
这个issues close了吧？嗯？ 题主
